export interface Article {
  slug: string
  category: string
  categoryColor: string
  title: string
  excerpt: string
  date: string
  readTime: string
  keywords?: string[]
  content: Section[]
  related: RelatedArticle[]
}

export interface Section {
  type: 'h2' | 'h3' | 'p' | 'ul' | 'ol' | 'callout' | 'divider'
  text?: string
  items?: string[]
}

export interface RelatedArticle {
  slug: string
  title: string
  category: string
  readTime: string
}

export const articles: Article[] = [
  {
    slug: 'how-to-write-resume-bullets-that-get-interviews',
    category: 'Resume',
    categoryColor: '#C9A84C',
    title: 'How to Write Resume Bullets That Actually Get Interviews',
    excerpt: 'Most resume bullets bury the lead. Learn the achievement-first formula that makes recruiters stop scrolling.',
    date: 'Apr 18, 2026',
    readTime: '7 min',
    content: [
      { type: 'p', text: 'The average recruiter spends six seconds scanning a resume before deciding whether to read it properly. Six seconds. That means your resume bullets are doing the heaviest lifting of your entire job search — and most people write them completely wrong.' },
      { type: 'h2', text: 'The Most Common Resume Bullet Mistake' },
      { type: 'p', text: 'Most professionals write their resume bullets like job descriptions: they list responsibilities instead of achievements. "Managed social media accounts." "Led a team of five engineers." "Responsible for client onboarding." These bullets describe what the role existed to do — not what you personally accomplished while in it.' },
      { type: 'p', text: 'The fix is deceptively simple: lead with the result, then explain how you got there.' },
      { type: 'h2', text: 'The Achievement-First Formula' },
      { type: 'p', text: 'Every strong resume bullet follows the same pattern: [Result] + [Action] + [Context]. This is a deliberate inversion of how most people write. Instead of "Managed a team that increased revenue," you write "Grew revenue 34% by restructuring the sales team\'s territory model."' },
      { type: 'ul', items: [
        'Lead with a number or outcome whenever possible — percentages, dollar amounts, timeframes, or scale',
        'Use a strong action verb that describes your specific contribution, not the team\'s general activity',
        'Add context that explains why the result was hard to achieve or significant in scope',
        'Keep it to one line — two at most — and never use complete sentences',
      ]},
      { type: 'h2', text: 'Before and After Examples' },
      { type: 'p', text: 'Here is what the transformation looks like in practice across different industries.' },
      { type: 'h3', text: 'Software Engineering' },
      { type: 'p', text: 'Before: "Worked on backend performance improvements for the payments service."' },
      { type: 'p', text: 'After: "Reduced API response time by 62% by migrating payments service to async processing, cutting customer drop-off at checkout by 18%."' },
      { type: 'h3', text: 'Marketing' },
      { type: 'p', text: 'Before: "Responsible for email marketing campaigns."' },
      { type: 'p', text: 'After: "Lifted email open rates from 18% to 31% by redesigning subject line strategy and A/B testing cadence across 3M subscriber list."' },
      { type: 'h3', text: 'Operations' },
      { type: 'p', text: 'Before: "Managed vendor relationships and procurement."' },
      { type: 'p', text: 'After: "Renegotiated contracts with top 8 vendors, saving $240K annually while maintaining service levels across all SLA commitments."' },
      { type: 'h2', text: 'What If You Don\'t Have Hard Numbers?' },
      { type: 'p', text: 'Not every role produces clean metrics — and that is fine. You can still write achievement-first bullets by leading with qualitative outcomes: "First to implement X at the company," "Led initiative that was adopted company-wide," or "Reduced recurring complaints about Y." The key is that the bullet describes something that changed because you were there, not something the role was meant to do regardless of who filled it.' },
      { type: 'callout', text: '💡 Tip: Use Brand Syndicate\'s AI generator to automatically rewrite your experience into achievement-framed, ATS-optimized bullets — no spreadsheet required.' },
      { type: 'h2', text: 'Tailoring Bullets to Each Job' },
      { type: 'p', text: 'One resume does not fit every role. Once you have a strong master list of achievement-first bullets, customize the top three to five for each application by matching the language in the job description. If they use "drove growth," use "drove growth." This is not gaming the system — it is communicating in the language your reader already uses.' },
      { type: 'h2', text: 'The Bullet Audit' },
      { type: 'p', text: 'Go through every bullet on your current resume and ask two questions: Does this describe a result or a responsibility? And would this bullet be true of anyone who held this role, or specifically of what I accomplished? If you can not answer yes to the second question, rewrite it.' },
    ],
    related: [
      { slug: 'ats-optimization-guide-2026', title: 'ATS Optimization Guide 2026', category: 'Resume', readTime: '9 min' },
      { slug: 'resume-summary-vs-objective', title: 'Resume Summary vs. Objective', category: 'Resume', readTime: '5 min' },
      { slug: 'career-change-resume-tips', title: 'Career Change Resume Tips', category: 'Resume', readTime: '9 min' },
    ],
  },

  {
    slug: 'ats-optimization-guide-2026',
    category: 'Resume',
    categoryColor: '#C9A84C',
    title: 'ATS Optimization Guide: Get Past the Bots in 2026',
    excerpt: 'Over 90% of large companies use ATS software. Here is exactly how to format and keyword-optimize your resume to pass automated screening.',
    date: 'Apr 14, 2026',
    readTime: '9 min',
    content: [
      { type: 'p', text: 'Before a human recruiter ever reads your resume, software reads it first. Applicant Tracking Systems — ATS platforms like Greenhouse, Lever, Workday, and iCIMS — parse, score, and rank every application. If your resume does not play well with these systems, it never makes it to a human at all.' },
      { type: 'h2', text: 'How ATS Actually Works' },
      { type: 'p', text: 'Most ATS platforms convert your resume into plain text, then scan that text for keywords, titles, dates, and structural signals. They are looking for specific matches between your resume and the job description — so they are less "artificial intelligence" and more sophisticated ctrl-F.' },
      { type: 'p', text: 'This means two resumes with identical content can perform radically differently based purely on formatting choices.' },
      { type: 'h2', text: 'Formatting Rules That Protect Your ATS Score' },
      { type: 'ul', items: [
        'Use a single-column layout. Multi-column formats confuse parsers and scramble the order of your text.',
        'Avoid tables, text boxes, headers/footers, and graphics. None of these parse reliably.',
        'Use standard section headers: "Work Experience," "Education," "Skills" — not creative variations like "Where I\'ve Been" or "My Journey."',
        'Save as .docx or PDF — but check whether the specific ATS specifies a preference. Some older systems handle .docx better.',
        'Use standard fonts (Arial, Calibri, Garamond) in 10-12pt for body text. Decorative fonts may render as garbled characters.',
      ]},
      { type: 'h2', text: 'Keyword Strategy That Actually Works' },
      { type: 'p', text: 'Effective ATS optimization starts with the job description. Copy the full text of the role you are applying to and read it carefully. Circle every skill, tool, technology, or credential that appears more than once — these are almost certainly being scored.' },
      { type: 'h3', text: 'Hard Keywords vs. Soft Keywords' },
      { type: 'p', text: 'Hard keywords are specific and measurable: "Python," "Salesforce," "Series A," "Six Sigma," "HIPAA compliance." These are the ones that carry the most ATS weight and should appear verbatim on your resume if you genuinely have them.' },
      { type: 'p', text: 'Soft keywords ("team player," "results-driven," "strategic thinker") have less ATS impact but signal culture fit to human reviewers. Include them where natural — do not stuff them.' },
      { type: 'h2', text: 'The Keyword Matching Method' },
      { type: 'ol', items: [
        'Pull the job description into a document',
        'Highlight every skill, tool, credential, and title mentioned',
        'Cross-reference with your resume — which ones are missing?',
        'Add missing keywords where truthfully applicable, using the exact phrasing from the job description',
        'Do not keyword-stuff a skills section with things you cannot actually discuss in an interview',
      ]},
      { type: 'h2', text: 'Date Formats and Job Title Conventions' },
      { type: 'p', text: 'Use consistent, unambiguous date formats: "Jan 2023 – Mar 2025" or "2023–2025." Avoid "Present" for current roles — some parsers do not handle it well; use the current month and year instead. For job titles, match the title on your resume to the title in the job description where truthfully possible.' },
      { type: 'callout', text: '💡 Brand Syndicate generates ATS-ready resume bullets by default — structured for both machine parsing and human readability.' },
      { type: 'h2', text: 'Testing Your Resume Against ATS' },
      { type: 'p', text: 'Before submitting, paste your resume text into a plain text editor and read through it. If the content appears scrambled, out of order, or missing entire sections, your formatting is likely to fail ATS parsing. Tools like Jobscan or Resume Worded can give you a more detailed ATS compatibility report against specific job descriptions.' },
    ],
    related: [
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
      { slug: 'resume-summary-vs-objective', title: 'Resume Summary vs. Objective', category: 'Resume', readTime: '5 min' },
      { slug: 'career-change-resume-tips', title: 'Career Change Resume Tips', category: 'Resume', readTime: '9 min' },
    ],
  },

  {
    slug: 'resume-summary-vs-objective',
    category: 'Resume',
    categoryColor: '#C9A84C',
    title: 'Resume Summary vs. Objective: Which One You Actually Need',
    excerpt: 'We analyzed 2,000 resumes to find out which opening section performs better — and when to use each.',
    date: 'Apr 10, 2026',
    readTime: '5 min',
    content: [
      { type: 'p', text: 'The opening two to three lines of your resume are either the hook that keeps a recruiter reading — or the thing that makes them skip to the next candidate. Getting this section right matters more than almost any other formatting decision.' },
      { type: 'p', text: 'The debate between resume summaries and objective statements has gone on for decades. Here is what actually works based on context.' },
      { type: 'h2', text: 'What Is a Resume Summary?' },
      { type: 'p', text: 'A resume summary is a two-to-four sentence paragraph at the top of your resume that highlights your most compelling qualifications, experience level, and professional identity. It answers the question: "Who is this person and why should I keep reading?" from the recruiter\'s perspective.' },
      { type: 'p', text: 'Example: "Senior product manager with 8 years building B2B SaaS tools at growth-stage startups. Led three zero-to-one product launches that collectively generated $12M ARR. Specialize in complex pricing and packaging problems in competitive markets."' },
      { type: 'h2', text: 'What Is a Resume Objective?' },
      { type: 'p', text: 'A resume objective is a statement about what you want from the role or company — your goals, your intent, what you are looking for in a next opportunity. It answers the question: "What does this candidate want?" — which is not a question recruiters are typically asking.' },
      { type: 'p', text: 'Example: "Seeking a challenging role in product management where I can leverage my skills and grow my career in a dynamic organization."' },
      { type: 'callout', text: '⚠️ The problem with most objective statements: they are about you, not about the value you offer the employer.' },
      { type: 'h2', text: 'When to Use Each' },
      { type: 'h3', text: 'Use a Summary When:' },
      { type: 'ul', items: [
        'You have 2+ years of relevant work experience in the field you are applying to',
        'You have specific, quantifiable accomplishments to highlight',
        'You are applying at or above mid-level seniority',
        'Your experience speaks directly to the role you want',
      ]},
      { type: 'h3', text: 'Use an Objective When:' },
      { type: 'ul', items: [
        'You are a recent graduate with limited relevant experience',
        'You are making a significant career pivot and need to explain it up front',
        'You have a gap in employment and want to provide context',
        'The objective is genuinely specific to the company or role — not generic boilerplate',
      ]},
      { type: 'h2', text: 'What We Found in 2,000 Resumes' },
      { type: 'p', text: 'Resumes with specific, achievement-oriented summaries consistently outperformed those with objective statements in callbacks per application — by roughly 40% on average. The gap was even wider at senior levels. However, for candidates with fewer than two years of experience, a well-written objective performed on par with a generic summary.' },
      { type: 'p', text: 'The real insight: it is not summary vs. objective that determines performance — it is specific vs. generic. A specific objective that names the company and references the role outperforms a generic summary every time.' },
      { type: 'h2', text: 'The One-Line Formula for Each' },
      { type: 'p', text: 'Summary formula: [Years] [Title/Specialty] with a track record of [Key Achievement Area]. Known for [Specific Strength]. Targeting [Type of Role or Company].' },
      { type: 'p', text: 'Objective formula: Recent [Degree/Background] seeking to apply [Specific Skill or Experience] at [Company Name] to help [Specific Team Goal]. Passionate about [Relevant Domain].' },
    ],
    related: [
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
      { slug: 'ats-optimization-guide-2026', title: 'ATS Optimization Guide 2026', category: 'Resume', readTime: '9 min' },
      { slug: 'personal-brand-complete-guide', title: 'Complete Personal Branding Guide', category: 'Guide', readTime: '15 min' },
    ],
  },

  {
    slug: 'presentation-opening-lines-that-hook',
    category: 'Presentation',
    categoryColor: '#7B9EBC',
    title: '12 Presentation Opening Lines That Hook Any Audience',
    excerpt: 'You have 30 seconds before people decide whether to pay attention. These proven openers work across investor pitches, client decks, and keynotes.',
    date: 'Apr 6, 2026',
    readTime: '6 min',
    content: [
      { type: 'p', text: 'The first 30 seconds of any presentation are the most important. People decide very quickly — often unconsciously — whether they are going to pay attention or mentally check out. Once you have lost them, winning them back requires extraordinary effort.' },
      { type: 'p', text: 'These 12 openers have been tested across investor pitches, client presentations, keynotes, and internal business reviews. Each works for a different reason.' },
      { type: 'h2', text: '1. The Provocative Statistic' },
      { type: 'p', text: '"Eighty-three percent of professionals say they dread the performance review process — including the people running it." Open with a number that contradicts what the audience expects. The surprise creates cognitive engagement.' },
      { type: 'h2', text: '2. The Direct Question' },
      { type: 'p', text: '"How many of you have lost a deal you should have won?" A question demands a response — even a silent internal one. It immediately involves the audience as participants rather than spectators.' },
      { type: 'h2', text: '3. The Specific Scenario' },
      { type: 'p', text: '"It\'s 11pm on a Thursday. Your biggest client just emailed. They\'re leaving." Concrete specificity triggers empathy and imagination. Avoid vague scenarios — precision is what makes this work.' },
      { type: 'h2', text: '4. The Counterintuitive Claim' },
      { type: 'p', text: '"The best thing that ever happened to our product was that it completely failed its first launch." Audiences lean in when you say something that contradicts their expectations. Promise you will explain.' },
      { type: 'h2', text: '5. The Brief Story' },
      { type: 'p', text: 'Open with a 60-second anecdote that illustrates the core problem you are solving. The story needs a character, a conflict, and a moment of decision. Do not resolve it — leave the audience wanting the answer.' },
      { type: 'h2', text: '6. The Shared Enemy' },
      { type: 'p', text: '"We all know what it feels like to spend three days building a report that gets ignored." Naming a shared frustration creates instant rapport. The audience feels understood before you have said anything substantive.' },
      { type: 'h2', text: '7. The Bold Claim' },
      { type: 'p', text: '"By the end of this, you\'ll have one framework that replaces five tools you\'re currently using." Make a specific, credible promise about what the audience will get from paying attention. Then deliver on it.' },
      { type: 'h2', text: '8. The Historical Parallel' },
      { type: 'p', text: '"In 1999, the newspaper industry looked exactly like retail does today." Connecting a present challenge to a historical pattern provides context and implies you understand the deeper dynamics at play.' },
      { type: 'h2', text: '9. The Silence' },
      { type: 'p', text: 'Walk to the front. Look at the audience. Say nothing for five full seconds. Then begin. Silence is uncomfortable — and discomfort creates attention. This only works if you are confident enough to hold it.' },
      { type: 'h2', text: '10. The Visual First' },
      { type: 'p', text: 'Open with a single, striking image — no title slide, no text — and let the audience absorb it before you say a word. Then explain why you chose it. Sets a visual tone that signals this presentation will be different.' },
      { type: 'h2', text: '11. The Admission' },
      { type: 'p', text: '"We got this completely wrong for the first two years. Here\'s what we learned." Vulnerability from authority is disarming. It signals honesty and makes everything else you say more credible.' },
      { type: 'h2', text: '12. The Stakes Statement' },
      { type: 'p', text: '"The decision we make in this room today will determine whether this project ships in Q3 or next year." Clarity about consequences creates urgency and focus. Appropriate for decision-making meetings, not keynotes.' },
      { type: 'callout', text: '💡 Brand Syndicate\'s presentation generator creates a custom opening hook for your specific content — try it with your own prompt.' },
      { type: 'h2', text: 'Choosing the Right Opener' },
      { type: 'p', text: 'The best opener matches the energy of the room and the stakes of the situation. A provocative statistic works in a conference keynote; it might feel jarring in a quiet client check-in. A silence opener works with a large audience; it would be awkward with three people around a table. Match the technique to the context.' },
    ],
    related: [
      { slug: 'pitch-deck-structure-guide', title: 'Pitch Deck Structure Guide', category: 'Presentation', readTime: '11 min' },
      { slug: 'data-storytelling-for-presentations', title: 'Data Storytelling for Presentations', category: 'Presentation', readTime: '8 min' },
      { slug: 'personal-brand-complete-guide', title: 'Complete Personal Branding Guide', category: 'Guide', readTime: '15 min' },
    ],
  },

  {
    slug: 'pitch-deck-structure-guide',
    category: 'Presentation',
    categoryColor: '#7B9EBC',
    title: 'The Pitch Deck Structure That Raised $50M (Dissected)',
    excerpt: 'We reverse-engineered 40 successful pitch decks to find the exact slide order, story arc, and visual hierarchy that closes deals.',
    date: 'Apr 1, 2026',
    readTime: '11 min',
    content: [
      { type: 'p', text: 'After studying 40 pitch decks from startups that successfully raised between $2M and $80M in the last three years, a clear structural pattern emerged. The specifics varied — market, stage, business model — but the narrative architecture was remarkably consistent.' },
      { type: 'h2', text: 'The Core Insight: Decks Are Not Documents' },
      { type: 'p', text: 'The most common mistake founders make is treating a pitch deck like a business plan — trying to include everything they know. A pitch deck is a conversation starter, not a knowledge transfer document. Its only job is to create enough conviction for a next meeting.' },
      { type: 'p', text: 'Every slide should do one of three things: establish credibility, build urgency, or reduce risk.' },
      { type: 'h2', text: 'The 12-Slide Architecture' },
      { type: 'h3', text: 'Slide 1 — The Hook' },
      { type: 'p', text: 'One sentence that names the problem and hints at the scale of the opportunity. Not a tagline. Not a mission statement. A clear, specific description of what is broken in the world and who it affects.' },
      { type: 'h3', text: 'Slide 2 — The Problem' },
      { type: 'p', text: 'Expand on the problem with specificity. Use a scenario or character. Make the pain tangible. Avoid abstract market language — investors need to feel the problem before they care about the solution.' },
      { type: 'h3', text: 'Slide 3 — The Solution' },
      { type: 'p', text: 'Introduce the product with the minimum detail necessary to make the approach clear. Focus on the insight — the non-obvious thing you understood that others missed. Avoid feature lists.' },
      { type: 'h3', text: 'Slide 4 — Why Now' },
      { type: 'p', text: 'This is the slide most decks skip — and skipping it is a mistake. Investors back timing as much as teams. What changed in the market, technology, regulation, or behavior that makes this the right moment? What would have made this impossible five years ago?' },
      { type: 'h3', text: 'Slide 5 — Market Size' },
      { type: 'p', text: 'TAM, SAM, SOM — but approached bottom-up, not top-down. "The global X market is $200B" is meaningless. "There are 180,000 mid-market HR teams in the US who spend an average of $12K annually on this problem — that\'s a $2.2B serviceable market" is a business.' },
      { type: 'h3', text: 'Slide 6 — Traction' },
      { type: 'p', text: 'Lead with your best number. Revenue, ARR, MAU, retention, NPS — whatever is most impressive and most relevant. Show the trend, not just the absolute. A smaller number growing fast tells a better story than a bigger number that is flat.' },
      { type: 'h3', text: 'Slide 7 — Business Model' },
      { type: 'p', text: 'How do you make money, and what does a unit look like economically? CAC, LTV, payback period, and gross margin. Simplicity here signals clarity of thinking.' },
      { type: 'h3', text: 'Slide 8 — Competition' },
      { type: 'p', text: 'Acknowledge real alternatives — including "do nothing." A 2x2 matrix is fine if the axes are genuinely differentiated and not self-serving. Your goal is to show you understand the landscape, not to prove you have no competition (no competition means no market).' },
      { type: 'h3', text: 'Slide 9 — Team' },
      { type: 'p', text: 'Why you? Not credentials — insight. What did each founder know or experience that gave them an unfair advantage in building this? Domain expertise, prior experience at the problem, relevant exits. Investors back unfair advantage.' },
      { type: 'h3', text: 'Slide 10 — The Ask' },
      { type: 'p', text: 'Specific raise amount, use of funds, and what milestones this capital gets you to. Vague asks signal a lack of planning. Specific asks signal you know your business.' },
      { type: 'h3', text: 'Slide 11 — The Vision' },
      { type: 'p', text: 'What does the world look like if you win? This is not slide 1 — it is the payoff. Now that you have earned the audience\'s credibility with traction and team, show them the full scope of what you are building.' },
      { type: 'h3', text: 'Slide 12 — Contact and Appendix' },
      { type: 'p', text: 'Clean contact information, and an appendix with any data you pulled out of the main deck for brevity — financial models, customer case studies, detailed market analysis.' },
      { type: 'h2', text: 'What the Best Decks Have in Common' },
      { type: 'ul', items: [
        'Fewer than 15 words per slide on average',
        'One central idea per slide — no more',
        'Data that tells a story, not data as decoration',
        'A narrative arc that creates and then resolves tension',
        'Absolute visual consistency: one font family, three colors maximum',
      ]},
      { type: 'callout', text: '💡 Brand Syndicate\'s presentation generator creates a custom slide structure and opening hook based on your background and goals.' },
    ],
    related: [
      { slug: 'presentation-opening-lines-that-hook', title: '12 Opening Lines That Hook', category: 'Presentation', readTime: '6 min' },
      { slug: 'data-storytelling-for-presentations', title: 'Data Storytelling', category: 'Presentation', readTime: '8 min' },
      { slug: 'portfolio-copy-that-converts', title: 'Portfolio Copy That Converts', category: 'Guide', readTime: '10 min' },
    ],
  },

  {
    slug: 'data-storytelling-for-presentations',
    category: 'Presentation',
    categoryColor: '#7B9EBC',
    title: 'Data Storytelling: Turn Numbers Into Narratives That Persuade',
    excerpt: 'Raw data does not move people — stories do. Learn the framework for wrapping statistics in narrative so audiences actually remember them.',
    date: 'Mar 26, 2026',
    readTime: '8 min',
    content: [
      { type: 'p', text: 'A chart is not a story. A table of numbers is not a story. Even a striking statistic is not a story until it has been given context, consequence, and a human face.' },
      { type: 'p', text: 'Data storytelling is the practice of embedding quantitative evidence inside a narrative structure — so that audiences understand not just what the numbers say, but why they matter and what should happen next.' },
      { type: 'h2', text: 'Why Data Alone Fails to Persuade' },
      { type: 'p', text: 'Research from cognitive psychologist Jerome Bruner found that information embedded in narrative is 22 times more memorable than the same information presented as facts. The human brain does not process facts and stories the same way — stories activate multiple brain regions simultaneously, creating what researchers call "neural coupling" between speaker and listener.' },
      { type: 'p', text: 'When you show a chart without a story, you give your audience work to do: they have to interpret the data, figure out why you included it, and decide what it means for them. Most will not bother.' },
      { type: 'h2', text: 'The Three Elements of Data Storytelling' },
      { type: 'h3', text: '1. The Data' },
      { type: 'p', text: 'The quantitative evidence that supports your claim. One key data point is more powerful than five — pick the number that most directly proves your argument and resist the urge to hedge it with supporting statistics.' },
      { type: 'h3', text: '2. The Narrative' },
      { type: 'p', text: 'The story structure that gives the data meaning. This typically means: here is what was happening before, here is what changed, here is what that means for the future. The narrative explains causality — not just correlation.' },
      { type: 'h3', text: '3. The Visualization' },
      { type: 'p', text: 'The visual form that makes the data legible at a glance. The visualization should reinforce the narrative, not compete with it. If someone has to spend more than five seconds interpreting a chart, it is too complex.' },
      { type: 'h2', text: 'The "So What" Test' },
      { type: 'p', text: 'After every data point in your presentation, ask: "So what?" If you cannot immediately answer that question in one sentence, the data point is not doing its job. "Our churn rate dropped from 8% to 3% — so we can now reinvest the saved acquisition cost into outbound, which is how we get to our 40% growth target" passes the test. "Our churn rate dropped from 8% to 3%" does not.' },
      { type: 'h2', text: 'Choosing the Right Chart Type' },
      { type: 'ul', items: [
        'Change over time: line chart, area chart, or bar chart — never pie charts',
        'Comparison between categories: grouped bar chart or dot plot',
        'Part-to-whole relationships: stacked bar or treemap — use pie charts only for 2-3 categories max',
        'Correlation between variables: scatter plot',
        'Distribution: histogram or box plot',
        'Single, large number: skip the chart entirely — display the number large',
      ]},
      { type: 'h2', text: 'Annotation as Storytelling' },
      { type: 'p', text: 'The most underused tool in data visualization is the annotation. Instead of forcing your audience to read the data and draw their own conclusion, tell them the conclusion directly on the chart. Label the inflection point. Call out the outlier. Write the headline above the graph — not a description of what the chart shows, but the conclusion it supports.' },
      { type: 'h2', text: 'Structure for a Data-Heavy Presentation' },
      { type: 'ol', items: [
        'Open with the conclusion — your key finding, not the setup',
        'Introduce the data that supports it — one chart, one idea',
        'Explain the causality — why did this happen?',
        'Show the implication — what does this mean for the audience?',
        'Recommend the action — what should happen next?',
      ]},
      { type: 'callout', text: '💡 Brand Syndicate generates presentation decks with built-in narrative structure — not just slides, but a story arc for your content.' },
    ],
    related: [
      { slug: 'pitch-deck-structure-guide', title: 'Pitch Deck Structure', category: 'Presentation', readTime: '11 min' },
      { slug: 'presentation-opening-lines-that-hook', title: '12 Opening Lines That Hook', category: 'Presentation', readTime: '6 min' },
      { slug: 'portfolio-copy-that-converts', title: 'Portfolio Copy That Converts', category: 'Guide', readTime: '10 min' },
    ],
  },

  {
    slug: 'personal-brand-complete-guide',
    category: 'Guide',
    categoryColor: '#7BAC89',
    title: 'The Complete Personal Branding Guide for 2026',
    excerpt: 'A step-by-step system for building a personal brand that opens doors — covering positioning, storytelling, and channel strategy.',
    date: 'Mar 20, 2026',
    readTime: '15 min',
    content: [
      { type: 'p', text: 'Personal branding is not about becoming a "thought leader" or posting on LinkedIn every day. It is about making sure that when the right people encounter your work — in any context — they immediately understand who you are, what you do better than most, and why they should reach out.' },
      { type: 'p', text: 'Done well, a personal brand is a career asset that compounds over time. Done poorly, it is a distraction. This guide covers the full system: from positioning through storytelling through channel strategy.' },
      { type: 'h2', text: 'Step 1: Positioning — The Foundation' },
      { type: 'p', text: 'Positioning answers the question: "What is the specific thing I am known for, and who is it valuable to?" This is different from a job title — it is the intersection of your deepest expertise, the problems you solve, and the audience who cares about that.' },
      { type: 'p', text: 'The most powerful positioning is specific and slightly counterintuitive. "Marketing consultant" is not positioning. "I help Series A SaaS companies build their first SDR motion without burning out the founding team" is positioning.' },
      { type: 'h3', text: 'The Positioning Triangle' },
      { type: 'ul', items: [
        'Expertise: What do you know that most people in your field do not?',
        'Audience: Who specifically benefits most from that knowledge?',
        'Problem: What is the specific pain point you solve for that audience?',
      ]},
      { type: 'h2', text: 'Step 2: Crafting Your Brand Story' },
      { type: 'p', text: 'A brand story is not a career chronology. It is a narrative that explains why you ended up doing this work — the experiences, failures, insights, and turning points that led you to where you are. It answers the question "Why you?" in a way that credentials alone cannot.' },
      { type: 'p', text: 'The best professional brand stories follow the same structure as all compelling stories: there was a world, something challenged it, a lesson was learned, and now things are different. Apply that to your own trajectory.' },
      { type: 'h2', text: 'Step 3: Your Core Brand Assets' },
      { type: 'p', text: 'Before choosing channels, build the core assets that will live everywhere: a headline (one-line description of what you do and for whom), a short bio (three to five sentences — what you do, who for, and one specific credential or outcome), and a long bio (full paragraph for speaking pages, press kits, or portfolio pages).' },
      { type: 'h2', text: 'Step 4: Channel Strategy' },
      { type: 'p', text: 'Personal branding does not require being everywhere. It requires being consistently visible in the one or two places where your target audience spends time. For B2B professionals, this is usually LinkedIn + a portfolio or personal site. For creative professionals, it might be Behance, Dribbble, or Instagram. For technical professionals, it might be GitHub, a personal blog, or conference talks.' },
      { type: 'h3', text: 'Choosing Your Primary Channel' },
      { type: 'ul', items: [
        'Where does your target audience actually spend time?',
        'Where do the people who hire or refer people like you look for candidates?',
        'What content format plays to your natural strengths — writing, speaking, visual, code?',
      ]},
      { type: 'h2', text: 'Step 5: The Consistency System' },
      { type: 'p', text: 'A personal brand is built through consistency over time, not through a single burst of activity. The most effective system is the smallest one you can actually maintain. If that means one high-quality post per month plus a regularly updated portfolio, that is better than a daily posting schedule you abandon in three weeks.' },
      { type: 'h2', text: 'Step 6: Measuring Brand Equity' },
      { type: 'p', text: 'Brand equity is hard to measure directly, but you can track leading indicators: inbound connection requests from relevant people, unsolicited referrals, speaking or guest-posting invitations, and recruiter outreach for roles you actually want. These signals tell you whether your brand is reaching the right people and resonating.' },
      { type: 'callout', text: '💡 Brand Syndicate generates your complete brand kit — headline, bio, portfolio copy, and more — from a single prompt. Try it free, no account required.' },
    ],
    related: [
      { slug: 'linkedin-about-section-formula', title: 'LinkedIn About Section Formula', category: 'Guide', readTime: '7 min' },
      { slug: 'portfolio-copy-that-converts', title: 'Portfolio Copy That Converts', category: 'Guide', readTime: '10 min' },
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
    ],
  },

  {
    slug: 'portfolio-copy-that-converts',
    category: 'Guide',
    categoryColor: '#7BAC89',
    title: 'Portfolio Copy That Converts: Writing About Your Work Without Bragging',
    excerpt: 'Talking about your own work feels awkward. This guide gives you frameworks to present your projects with confidence and specificity.',
    date: 'Mar 14, 2026',
    readTime: '10 min',
    content: [
      { type: 'p', text: 'Most portfolio copy fails for one of two reasons: it is either too modest ("I contributed to a project that...") or too vague ("I built innovative solutions for enterprise clients"). Both make the reader work too hard to understand what you actually did and why they should care.' },
      { type: 'p', text: 'The goal of portfolio copy is not to impress — it is to make the reader feel confident that you can do for them what you did for the projects you describe.' },
      { type: 'h2', text: 'The Case Study Structure That Works' },
      { type: 'p', text: 'Every strong portfolio entry follows the same structure, regardless of industry: context, challenge, approach, and outcome. This is not new — it is the same structure as a business school case study — but most portfolios skip the challenge and approach entirely, leaving only a description of the output.' },
      { type: 'h3', text: 'Context (2-3 sentences)' },
      { type: 'p', text: 'Who was the client or organization? What was the size and nature of the problem? What was the stakes — what would happen if the challenge was not solved?' },
      { type: 'h3', text: 'Challenge (2-3 sentences)' },
      { type: 'p', text: 'What was specifically hard about this? What constraints existed — time, budget, technical, political, organizational? What had been tried before and failed?' },
      { type: 'h3', text: 'Approach (3-5 sentences)' },
      { type: 'p', text: 'What did you specifically do — not the team, not the process, but you? What decision did you make that turned out to be right? What was your method or framework?' },
      { type: 'h3', text: 'Outcome (2-3 sentences with metrics)' },
      { type: 'p', text: 'What changed? What was measured? What did the client say, do, or decide as a result?' },
      { type: 'h2', text: 'Writing Your Hero Headline' },
      { type: 'p', text: 'Every portfolio entry needs a headline that communicates the outcome, not the process. "Redesigning the checkout experience for a D2C brand" is a process description. "Lifting checkout completion rates 23% for a $40M D2C brand by redesigning the payment UX" is an outcome headline. Lead with what changed.' },
      { type: 'h2', text: 'Dealing With NDAs and Confidentiality' },
      { type: 'p', text: 'You can describe the work without naming the client. "A Fortune 500 financial services company" is specific enough to signal credibility without violating confidentiality. You can describe the scale ("a 2M-user consumer app"), the sector, the problem, and the outcome — all without identifying the client by name.' },
      { type: 'h2', text: 'Writing Your About Section' },
      { type: 'p', text: 'The About section is not your biography. It is your professional positioning statement with a human face. It should answer three questions: What do you do (specifically)? Who do you do it for? And what perspective or experience makes you particularly good at it?' },
      { type: 'p', text: 'The first sentence should be your clearest positioning statement. The second and third should build context and credibility. The fourth can be personal — a philosophy, a working style, or something that reveals character.' },
      { type: 'h2', text: 'Common Portfolio Copy Mistakes' },
      { type: 'ul', items: [
        'Using first person plural ("we built") when you can use first person singular ("I led the build of")',
        'Describing tools and technologies instead of decisions and outcomes',
        'Including every project instead of curating the best five',
        'Writing in passive voice: "the project was delivered" instead of "I delivered the project"',
        'Forgetting to update the portfolio after each major project',
      ]},
      { type: 'callout', text: '💡 Brand Syndicate generates portfolio copy for each of your projects — hero headline, case study structure, and about section — from a single prompt.' },
    ],
    related: [
      { slug: 'personal-brand-complete-guide', title: 'Complete Personal Branding Guide', category: 'Guide', readTime: '15 min' },
      { slug: 'linkedin-about-section-formula', title: 'LinkedIn About Section Formula', category: 'Guide', readTime: '7 min' },
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
    ],
  },

  {
    slug: 'linkedin-about-section-formula',
    category: 'Guide',
    categoryColor: '#7BAC89',
    title: 'The LinkedIn About Section Formula That Gets 10x More Views',
    excerpt: 'Most LinkedIn summaries are walls of text nobody reads. The hook-story-CTA formula changes that completely.',
    date: 'Mar 8, 2026',
    readTime: '7 min',
    content: [
      { type: 'p', text: 'LinkedIn shows only the first three lines of your About section before the "See more" cutoff. Most people write their entire summary for the person who clicks through — and lose the 95% who do not.' },
      { type: 'p', text: 'The three-line hook is the most important copywriting challenge in professional branding, and most people squander it with something like: "I am a passionate marketing professional with over a decade of experience driving growth for enterprise clients across multiple industries." Nobody clicks "See more" after reading that.' },
      { type: 'h2', text: 'The Hook-Story-CTA Framework' },
      { type: 'h3', text: 'The Hook (Lines 1-3 — visible before "See more")' },
      { type: 'p', text: 'Your hook must accomplish one thing: give the right person a reason to click. The most effective hooks are either a bold, specific positioning statement ("I help B2B SaaS companies cut their sales cycle in half without hiring more reps") or a counterintuitive insight that signals expertise ("Most demand gen strategies fail for the same reason — here is what they miss").' },
      { type: 'p', text: 'What does not work: starting with your job title, starting with "I am passionate about," writing in third person, and using vague superlatives like "results-driven" or "innovative."' },
      { type: 'h3', text: 'The Story (The Expanded Section)' },
      { type: 'p', text: 'After the hook, tell a two-to-three paragraph story: what you do and who for, why you got into this work (the experience or insight that shaped your perspective), and what specifically sets your approach apart. This is not your CV — it is your professional origin story, told with forward momentum.' },
      { type: 'p', text: 'Use short paragraphs. White space is your friend. On mobile, text compresses — a six-line paragraph that looks fine on desktop becomes a wall on phone.' },
      { type: 'h3', text: 'The CTA (Close With an Action)' },
      { type: 'p', text: 'End with a clear, specific invitation: "If you are a Series A founder trying to build your first GTM motion, connect with me." Or: "I am always interested in conversations about X — feel free to reach out." The CTA should tell the reader exactly who should contact you and why.' },
      { type: 'h2', text: 'Keyword Strategy for Discoverability' },
      { type: 'p', text: 'LinkedIn search is heavily influenced by your About section. Include the exact job titles you want to be found for (e.g., "Head of Growth," "VP Marketing," "Fractional CMO"), the industries you work in, and the tools or skills that are most relevant to your target roles. Write naturally — do not keyword-stuff — but be intentional about including terms a recruiter or potential client would search for.' },
      { type: 'h2', text: 'Before and After' },
      { type: 'p', text: 'Before: "Marketing professional with 10+ years of experience driving growth for enterprise and SMB clients across SaaS, fintech, and e-commerce verticals. Passionate about data-driven strategies and building high-performing teams."' },
      { type: 'p', text: 'After: "I help Series B SaaS companies turn underperforming content programs into their top-converting channel. In the last three years, I\'ve done this for eight companies — most recently growing organic pipeline 4x at [company] in 14 months."' },
      { type: 'h2', text: 'Format and Length' },
      { type: 'p', text: 'Keep your About section between 200-350 words. Shorter loses credibility; longer loses readers. Use line breaks aggressively — three lines maximum per paragraph. Consider leading each paragraph with a one-line "headline" in the first sentence so skimmers can navigate.' },
      { type: 'callout', text: '💡 Brand Syndicate generates your LinkedIn About section as part of your complete brand kit. Try it free — no account needed.' },
    ],
    related: [
      { slug: 'personal-brand-complete-guide', title: 'Complete Personal Branding Guide', category: 'Guide', readTime: '15 min' },
      { slug: 'portfolio-copy-that-converts', title: 'Portfolio Copy That Converts', category: 'Guide', readTime: '10 min' },
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
    ],
  },

  {
    slug: 'career-change-resume-tips',
    category: 'Resume',
    categoryColor: '#C9A84C',
    title: 'Career Change Resume: How to Reframe Your Experience for a New Industry',
    excerpt: 'Switching fields does not mean starting from zero. These reframing techniques translate transferable skills into the language of your target industry.',
    date: 'Mar 2, 2026',
    readTime: '9 min',
    content: [
      { type: 'p', text: 'Career change resumes have a different job than standard resumes. Instead of demonstrating progression within a field, they need to make a case for transferability — convincing a skeptical reader that skills built in one context apply powerfully in another.' },
      { type: 'p', text: 'The good news: most hiring managers know that some of the best performers in their field came from unexpected backgrounds. The challenge is helping them see the connection before they reject you on pattern-matching alone.' },
      { type: 'h2', text: 'Start With the Translation Work' },
      { type: 'p', text: 'Before you change a word of your resume, do the translation work: take the job description for your target role and identify every skill and responsibility listed. Then go through your own experience and find specific examples where you demonstrated each one — even if the context looks different on the surface.' },
      { type: 'p', text: '"Managed stakeholder relationships across 12 retail locations" translates to "cross-functional stakeholder management at scale" for a product role. "Coached a youth soccer team to regional finals" translates to "team leadership, performance development, and strategic planning under pressure." The experiences are the same — only the language changes.' },
      { type: 'h2', text: 'The Functional-Hybrid Resume Format' },
      { type: 'p', text: 'For career changers, a pure chronological resume often works against you — it leads with the industry you are leaving, not the skills you are bringing. A functional-hybrid format puts a Skills and Achievements section near the top (before your work history) to lead with transferable capabilities, then follows with your chronological experience to provide context.' },
      { type: 'h2', text: 'Rewriting Your Summary for the New Industry' },
      { type: 'p', text: 'Your resume summary is where you do the most important framing work. Instead of describing what you have done in your previous industry, describe what you bring to the new one. "Former military logistics officer with 8 years managing $200M in supply chain operations, transitioning to enterprise operations roles where precision, scale, and team leadership are mission-critical" is a career change summary that works.' },
      { type: 'h2', text: 'Addressing the Industry Gap Proactively' },
      { type: 'p', text: 'Do not ignore the industry difference — address it directly in your summary or cover letter. Explain why you are making the change and what preparation you have done: relevant courses, certifications, side projects, or adjacent experience. Confidence about the transition is more compelling than hoping the reader will not notice.' },
      { type: 'h2', text: 'Skills That Transfer Universally' },
      { type: 'ul', items: [
        'Project and program management — outcomes, timelines, budgets, teams',
        'Data analysis and reporting — regardless of the domain',
        'Client or stakeholder communication — internal or external',
        'Process design and optimization — whatever the industry context',
        'People management, coaching, and team development',
        'Strategic planning and prioritization under resource constraints',
      ]},
      { type: 'h2', text: 'Building Credibility in the New Field' },
      { type: 'p', text: 'Bridge the credibility gap with proof of genuine interest: a relevant certification (Google, AWS, PMI, SHRM), a portfolio project in the target domain, volunteering with an organization in the new field, or a relevant side project. These signals tell the hiring manager that the career change is intentional and prepared, not opportunistic.' },
      { type: 'callout', text: '💡 Brand Syndicate\'s resume generator can reframe your existing experience using industry-specific language for your target role — try it free.' },
      { type: 'h2', text: 'The Cover Letter As a Career Change Tool' },
      { type: 'p', text: 'For career changers, the cover letter matters more than it does for standard applications. Use it to tell the story of why — why this industry, why this company, and why your background specifically prepares you for this role better than a conventional candidate might expect. A well-crafted career change cover letter can move you from the reject pile to the interview list.' },
    ],
    related: [
      { slug: 'how-to-write-resume-bullets-that-get-interviews', title: 'Resume Bullets That Get Interviews', category: 'Resume', readTime: '7 min' },
      { slug: 'ats-optimization-guide-2026', title: 'ATS Optimization Guide', category: 'Resume', readTime: '9 min' },
      { slug: 'personal-brand-complete-guide', title: 'Complete Personal Branding Guide', category: 'Guide', readTime: '15 min' },
    ],
  },
]

export function getArticle(slug: string): Article | undefined {
  return articles.find(a => a.slug === slug)
}

export function getAllSlugs(): string[] {
  return articles.map(a => a.slug)
}
