import type { BrandOutput } from '@/lib/ai/generate'

function buildPortfolioHtml(data: BrandOutput, userName: string, accentColor = '#C9A84C'): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#09090A;color:#F0EAE0;font-family:'DM Sans',sans-serif;-webkit-font-smoothing:antialiased;min-height:100vh}
.nav{padding:20px 40px;border-bottom:1px solid rgba(255,255,255,0.06);display:flex;justify-content:space-between;align-items:center}
.logo{font-family:'Playfair Display',serif;font-size:16px;letter-spacing:0.2em;color:#F8F4EE;text-transform:uppercase}
.logo span{color:${accentColor}}
.hero{padding:60px 40px 40px}
.eyebrow{font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:${accentColor};margin-bottom:16px;display:flex;align-items:center;gap:10px;font-family:'DM Mono',monospace}
.eyebrow::before{content:'';display:block;width:20px;height:1px;background:${accentColor}}
h1{font-family:'Playfair Display',serif;font-size:48px;color:#F8F4EE;line-height:1.1;margin-bottom:16px;font-weight:400}
h1 em{color:${accentColor};font-style:italic}
.bio{font-size:14px;color:#A09890;line-height:1.8;max-width:480px;font-weight:300;margin-bottom:32px}
.cta{background:${accentColor};color:#000;border:none;padding:12px 24px;font-size:11px;letter-spacing:0.14em;text-transform:uppercase;font-weight:500;font-family:'DM Sans',sans-serif;cursor:pointer}
.skills{display:flex;flex-wrap:wrap;gap:8px;margin-top:28px}
.skill{padding:5px 12px;border:1px solid rgba(255,255,255,0.08);font-size:10px;letter-spacing:0.06em;text-transform:uppercase;color:#A09890;font-family:'DM Mono',monospace}
.section{padding:40px;border-top:1px solid rgba(255,255,255,0.06)}
.sec-label{font-size:9px;letter-spacing:0.2em;text-transform:uppercase;color:${accentColor};font-family:'DM Mono',monospace;margin-bottom:20px}
.work-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
.work-card{background:#131313;border:1px solid rgba(255,255,255,0.06);padding:20px}
.work-title{font-family:'Playfair Display',serif;font-size:16px;color:#F0EAE0;margin-bottom:6px}
.work-body{font-size:12px;color:#A09890;line-height:1.7;margin-bottom:10px;font-weight:300}
.work-highlight{font-size:10px;color:${accentColor};letter-spacing:0.06em;font-family:'DM Mono',monospace}
.footer{padding:24px 40px;border-top:1px solid rgba(255,255,255,0.06);display:flex;justify-content:space-between;align-items:center}
.footer-text{font-size:10px;color:#706860;letter-spacing:0.1em;font-family:'DM Mono',monospace}
</style>
</head>
<body>
<nav class="nav">
  <div class="logo">${userName} <span>·</span> Portfolio</div>
  <div style="font-size:10px;color:#A09890;letter-spacing:0.1em;font-family:'DM Mono',monospace">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' })}</div>
</nav>
<div class="hero">
  <div class="eyebrow">Personal Brand Portfolio</div>
  <h1>${data.headline.split(' ').map((w, i) => i === Math.floor(data.headline.split(' ').length / 2) ? `<em>${w}</em>` : w).join(' ')}</h1>
  <p class="bio">${data.bio}</p>
  <button class="cta">${data.cta}</button>
  <div class="skills">${data.skills.map(s => `<span class="skill">${s}</span>`).join('')}</div>
</div>
${data.portfolioSections.map(s => `
<div class="section">
  <div class="sec-label">${s.title}</div>
  <div class="work-grid">
    <div class="work-card">
      <div class="work-title">${s.title}</div>
      <div class="work-body">${s.body}</div>
      <div class="work-highlight">${s.highlight}</div>
    </div>
  </div>
</div>`).join('')}
<footer class="footer">
  <div class="footer-text">Generated by Brand Syndicate</div>
  <div class="footer-text">${data.tagline}</div>
</footer>
</body>
</html>`
}

function buildResumeHtml(data: BrandOutput, userName: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#F8F6F2;color:#1A1A1A;font-family:'DM Sans',sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact;padding:48px}
.header{margin-bottom:28px;border-bottom:1px solid #E0D8CE;padding-bottom:24px}
h1{font-family:'Playfair Display',serif;font-size:32px;color:#0A0A0A;margin-bottom:4px}
.role{font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:#888;font-family:'DM Mono',monospace;margin-bottom:12px}
.contact{display:flex;gap:20px;flex-wrap:wrap}
.contact span{font-size:10px;color:#888;font-family:'DM Mono',monospace}
.section{margin-bottom:24px}
.sec-title{font-size:9px;letter-spacing:0.2em;text-transform:uppercase;color:#C9A84C;font-family:'DM Mono',monospace;margin-bottom:10px;border-bottom:1px solid #E0D8CE;padding-bottom:6px}
.bio-text{font-size:12px;color:#555;line-height:1.8;font-weight:300}
.bullet{font-size:12px;color:#555;line-height:1.8;font-weight:300;padding-left:16px;margin-bottom:6px}
.skills{display:flex;flex-wrap:wrap;gap:6px}
.skill{padding:3px 10px;border:1px solid #E0D8CE;font-size:9px;letter-spacing:0.06em;text-transform:uppercase;color:#888}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #E0D8CE;font-size:9px;color:#bbb;font-family:'DM Mono',monospace;letter-spacing:0.06em}
</style>
</head>
<body>
<div class="header">
  <h1>${data.cardName || userName}</h1>
  <div class="role">${data.cardTitle}</div>
  <div class="contact">
    <span>${userName.toLowerCase().replace(' ', '.')}</span>
    <span>${data.tagline}</span>
  </div>
</div>
<div class="section">
  <div class="sec-title">Profile</div>
  <p class="bio-text">${data.bio}</p>
</div>
<div class="section">
  <div class="sec-title">Experience & Achievements</div>
  ${data.resumeBullets.map(b => `<div class="bullet">${b}</div>`).join('')}
</div>
<div class="section">
  <div class="sec-title">Core Skills</div>
  <div class="skills">${data.skills.map(s => `<span class="skill">${s}</span>`).join('')}</div>
</div>
<div class="footer">Generated by Brand Syndicate · ${new Date().toLocaleDateString()}</div>
</body>
</html>`
}

export async function generatePDF(
  data: BrandOutput,
  format: 'portfolio' | 'resume' | 'card',
  userName: string,
  accentColor: string,
  watermark = false
): Promise<Buffer> {
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let chromium: any = null
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let puppeteer: any = null

  try {
    chromium = (await import('@sparticuz/chromium')).default
    puppeteer = (await import('puppeteer-core')).default
  } catch {
    // Fallback for dev — return empty buffer
    return Buffer.from('')
  }

  const html = format === 'resume'
    ? buildResumeHtml(data, userName)
    : buildPortfolioHtml(data, userName, accentColor)

  const browser = await puppeteer!.launch({
    args: chromium!.args,
    defaultViewport: chromium!.defaultViewport,
    executablePath: await chromium!.executablePath(),
    headless: chromium!.headless,
  })

  const page = await browser.newPage()
  await page.setContent(html, { waitUntil: 'networkidle0' })

  if (watermark) {
    await page.evaluate(() => {
      const el = document.createElement('div')
      el.style.cssText = 'position:fixed;bottom:20px;right:20px;opacity:0.15;font-size:10px;font-family:monospace;letter-spacing:0.1em;text-transform:uppercase;color:#C9A84C;z-index:9999'
      el.textContent = 'FREE PLAN — brandsyndicate.co'
      document.body.appendChild(el)
    })
  }

  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: { top: '0', right: '0', bottom: '0', left: '0' },
  })

  await browser.close()
  return Buffer.from(pdfBuffer)
}
