// src/app/w/[slug]/route.ts
// Route Handler — returns raw HTML for a published user website.
// Injects: height-sync (iframe resize), analytics tracker, bs-backend (forms + blog).

import { NextResponse } from 'next/server'
import { db } from '@/lib/db'

export const dynamic = 'force-dynamic'

const NOT_FOUND_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Website Not Found</title>
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100dvh;
      display: flex; align-items: center; justify-content: center;
      font-family: 'DM Mono', 'Courier New', monospace;
      background: #09090a; color: #888;
      flex-direction: column; gap: 16px;
    }
    a { color: #C9A84C; text-decoration: none; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; }
  </style>
</head>
<body>
  <div style="font-size:32px;opacity:0.3">⊘</div>
  <div style="font-size:13px;letter-spacing:0.06em">Website not found.</div>
  <a href="/">← Brand Syndicate</a>
</body>
</html>`

const NOT_PUBLISHED_HTML = (name: string) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${name} – Not Published</title>
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100dvh;
      display: flex; align-items: center; justify-content: center;
      font-family: 'DM Mono', 'Courier New', monospace;
      background: #09090a; color: #888;
      flex-direction: column; gap: 16px;
    }
    a { color: #C9A84C; text-decoration: none; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; }
  </style>
</head>
<body>
  <div style="font-size:32px;opacity:0.3">⊘</div>
  <div style="font-size:13px;letter-spacing:0.06em">This website is not yet published.</div>
  <a href="/">← Brand Syndicate</a>
</body>
</html>`

// ── EMPTY BODY: shown when stored HTML has a <head> but no real body content ──
// Caused by max_tokens truncation during generation on older sites.
// The user needs to regenerate — the content was simply never written.
const TRUNCATED_HTML = (slug: string) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Website Incomplete</title>
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100dvh;
      display: flex; align-items: center; justify-content: center;
      font-family: 'DM Mono', 'Courier New', monospace;
      background: #09090a; color: #888;
      flex-direction: column; gap: 20px; padding: 40px; text-align: center;
    }
    .icon { font-size: 36px; opacity: 0.3; }
    .title { font-size: 13px; letter-spacing: 0.06em; color: rgba(255,255,255,0.6); }
    .sub { font-size: 11px; letter-spacing: 0.05em; line-height: 1.8; max-width: 360px; }
    .hint {
      margin-top: 8px; padding: 10px 20px;
      border: 1px solid rgba(201,168,76,0.35); border-radius: 4px;
      color: #C9A84C; font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase;
    }
    a { color: #C9A84C; text-decoration: none; font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; opacity: 0.6; }
    a:hover { opacity: 1; }
  </style>
</head>
<body>
  <div class="icon">⟳</div>
  <div class="title">Website Content Incomplete</div>
  <div class="sub">
    This website's content was cut short during generation.<br>
    Open it in your dashboard and click <strong style="color:#C9A84C">Regenerate</strong> to rebuild it.
  </div>
  <div class="hint">Regenerate required</div>
  <a href="/">← Brand Syndicate</a>
</body>
</html>`

// ── VISIBILITY FIX: injected into every site, new and existing ───────────────
// Overrides IntersectionObserver-based scroll-reveal patterns that were
// generated by older prompts. Elements with opacity:0 / visibility:hidden
// base styles from .reveal / .in-view class patterns are force-shown.
// Also neutralises any pending IntersectionObserver observe() calls so they
// don't fight the override after the fact.
const VISIBILITY_FIX_STYLE = `
<style id="bs-visibility-fix">
/* Force all scroll-reveal hidden elements to be visible */
[class*="reveal"],[class*="hidden"],[class*="fade-in"],[class*="fadeIn"],
[class*="slide-in"],[class*="slideIn"],[class*="animate"],[class*="in-view"],
[class*="is-visible"],[data-reveal],[data-animate],[data-aos] {
  opacity: 1 !important;
  transform: none !important;
  visibility: visible !important;
  transition: none !important;
}
</style>
<script>
/* Neutralise IntersectionObserver-based scroll reveals before they fire */
(function(){
  try {
    var _NIO = window.IntersectionObserver;
    window.IntersectionObserver = function(cb, opts) {
      var io = new _NIO(cb, opts);
      var _obs = io.observe.bind(io);
      io.observe = function(el) {
        /* Force element visible immediately then call original observe */
        if (el && el.style) {
          el.style.opacity = '';
          el.style.transform = '';
          el.style.visibility = '';
        }
        if (el && el.classList) {
          el.classList.add('visible');
          el.classList.add('in-view');
          el.classList.add('is-visible');
          el.classList.add('revealed');
        }
        return _obs(el);
      };
      return io;
    };
    window.IntersectionObserver.prototype = _NIO.prototype;
  } catch(e) {}
})();
</script>`



const EXISTING_WEBSITE_SPACE_FIX_STYLE = `
<style id="bs-existing-section-spacing-fix">
/* Existing saved website smoothness layer: section spacing, mobile text flow, non-cutoff media. */
html{scroll-behavior:smooth!important;}
body{line-height:1.55!important;text-rendering:optimizeLegibility!important;}
body *{min-width:0;}
h1,h2,h3,h4,h5,h6,p,li,a,button,span,small,strong,em{max-width:100%;overflow-wrap:break-word;word-break:normal;}
p,li{line-height:1.65!important;}
a,button,.btn,[class*="btn"],[class*="button"],[class*="cta"]{white-space:normal!important;min-height:44px;align-items:center;justify-content:center;text-align:center;}
section,.section,[class*="section"],main>div,footer{position:relative;max-width:100%;overflow:visible;}
section,.section,[class*="section"]{padding-block:clamp(48px,8vw,112px)!important;}
.container,.wrap,.wrapper,[class*="container"],[class*="wrap"],[class*="inner"]{width:min(100% - clamp(28px,6vw,96px),1200px)!important;margin-inline:auto!important;}
.grid,[class*="grid"],.cards,[class*="cards"],.row,[class*="row"],.features,[class*="features"],.services,[class*="services"],.pricing,[class*="pricing"],.testimonials,[class*="testimonials"],.gallery,[class*="gallery"]{gap:clamp(16px,3vw,40px)!important;}
.card,[class*="card"],.panel,[class*="panel"],.feature,[class*="feature"],.service,[class*="service"],.price,[class*="price"],.testimonial,[class*="testimonial"]{height:auto!important;min-height:0;overflow-wrap:break-word;}
img,picture,video,iframe{max-width:100%!important;}
img,video{height:auto;object-fit:cover;}
:not(body)[class*="hero"],.hero{isolation:isolate;}
:not(body)[class*="hero"]>*,.hero>*{max-width:100%;}
:not(body)[class*="hero"] p,.hero p{max-width:min(100%,68ch)!important;}
@media(max-width:1024px){
  [style*="grid-template-columns"],.grid,[class*="grid"],.cards,[class*="cards"],.features,[class*="features"],.services,[class*="services"],.pricing,[class*="pricing"],.testimonials,[class*="testimonials"],.gallery,[class*="gallery"],.split,[class*="split"]{grid-template-columns:1fr!important;}
  [style*="display:flex"],[style*="display: flex"],.row,[class*="row"],.columns,[class*="columns"]{flex-wrap:wrap!important;}
}
@media(max-width:768px){
  body{font-size:16px!important;}
  section,.section,[class*="section"]{padding-block:clamp(44px,14vw,84px)!important;padding-left:0!important;padding-right:0!important;overflow:visible!important;}
  .container,.wrap,.wrapper,[class*="container"],[class*="wrap"],[class*="inner"]{width:min(100% - 28px,100%)!important;}
  h1{font-size:clamp(32px,11vw,58px)!important;line-height:1.05!important;letter-spacing:max(-.06em,-2px)!important;}
  h2{font-size:clamp(26px,8vw,42px)!important;line-height:1.12!important;}
  h3{font-size:clamp(20px,6vw,30px)!important;line-height:1.18!important;}
  p,li{font-size:clamp(14px,4.2vw,17px)!important;line-height:1.65!important;}
  :not(body)[class*="hero"],.hero{height:auto!important;min-height:clamp(420px,92vw,720px)!important;padding-top:clamp(84px,20vw,128px)!important;padding-bottom:clamp(52px,16vw,92px)!important;display:flex!important;flex-direction:column!important;justify-content:center!important;overflow:hidden!important;}
  :not(body)[class*="hero"] .container,:not(body)[class*="hero"] .wrap,:not(body)[class*="hero"] [class*="inner"],.hero .container,.hero .wrap,.hero [class*="inner"]{display:block!important;}
  [class*="hero-bg"],[class*="hero-bg"] img,[class*="heroBg"],[class*="heroBg"] img,[class*="hero-image"],[class*="hero-image"] img,[class*="hero-visual"],[class*="hero-visual"] img,[class*="hero-media"],[class*="hero-media"] img,.hero-bg,.hero-bg img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;z-index:-1!important;}
  :not(body)[class*="hero"]::after,.hero::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.45),rgba(0,0,0,.78));z-index:-1;pointer-events:none;}
  .card,[class*="card"],.panel,[class*="panel"],.feature,[class*="feature"],.service,[class*="service"],.price,[class*="price"],.testimonial,[class*="testimonial"],form{padding:clamp(18px,5vw,28px)!important;max-width:100%!important;}
  img:not([class*="bg"]):not([style*="position:absolute"]):not([style*="position: absolute"]){max-height:72vh!important;}
}
@media(max-width:430px){
  .container,.wrap,.wrapper,[class*="container"],[class*="wrap"],[class*="inner"]{width:min(100% - 24px,100%)!important;}
  h1{font-size:clamp(30px,12vw,48px)!important;}
}
</style>
`

const MOBILE_ROOT_HERO_FIX_STYLE = `
<style id="bs-mobile-root-hero-fix-v7">
/* Final mobile correction: broad hero selectors used to catch body/header/hero-grid on phones. */
@media(max-width:980px){
  body[class*="bs-hero-v"]{display:block!important;position:static!important;padding:0!important;margin:0!important;min-height:100%!important;height:auto!important;overflow-x:hidden!important;}
  body[class*="bs-hero-v"]>nav,body[class*="bs-hero-v"]>.nav,body[class*="bs-hero-v"]>header{position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:10000!important;transform:none!important;}
  body[class*="bs-hero-v"] .hero,body[class*="bs-layout-"] .hero,body[class*="bs-seed-"] .hero,main.hero,section.hero{position:relative!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;justify-content:center!important;min-height:0!important;height:auto!important;}
  body[class*="bs-hero-v"] .hero-grid,body[class*="bs-layout-"] .hero-grid,body[class*="bs-seed-"] .hero-grid,body[class*="bs-hero-v"] .wrap.hero-grid,body[class*="bs-layout-"] .wrap.hero-grid,body[class*="bs-seed-"] .wrap.hero-grid,[class*="hero-grid"]{min-height:0!important;height:auto!important;padding-top:0!important;padding-bottom:0!important;display:grid!important;grid-template-columns:1fr!important;gap:24px!important;align-items:start!important;justify-content:initial!important;overflow:visible!important;width:min(100% - 28px,1180px)!important;margin-inline:auto!important;}
  .hero-bg,[class*="hero-bg"],.bs-hero-image-bg,[class*="hero-image"],[class*="hero-visual"],[class*="hero-media"]{padding:0!important;margin:0!important;min-height:0!important;}
  body[class*="bs-hero-v"] .hero-bg,body[class*="bs-layout-"] .hero-bg,body[class*="bs-seed-"] .hero-bg,body[class*="bs-hero-v"] .bs-hero-image-bg,body[class*="bs-layout-"] .bs-hero-image-bg,body[class*="bs-seed-"] .bs-hero-image-bg,.hero>.hero-bg,.hero>.bs-hero-image-bg,main.hero>.bs-hero-image-bg{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;z-index:0!important;pointer-events:none!important;overflow:hidden!important;}
  body[class*="bs-hero-v"] .hero-bg img,body[class*="bs-layout-"] .hero-bg img,body[class*="bs-seed-"] .hero-bg img,body[class*="bs-hero-v"] .bs-hero-image-bg img,body[class*="bs-layout-"] .bs-hero-image-bg img,body[class*="bs-seed-"] .bs-hero-image-bg img,.hero>.hero-bg img,.hero>.bs-hero-image-bg img,main.hero>.bs-hero-image-bg img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;display:block!important;}
  body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .hero-bg.hero-bg,body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .bs-hero-image-bg.bs-hero-image-bg{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;padding:0!important;margin:0!important;z-index:0!important;overflow:hidden!important;}
  body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .hero-bg.hero-bg img,body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .bs-hero-image-bg.bs-hero-image-bg img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;display:block!important;}
  .hero>div:not(.hero-bg):not(.bs-hero-image-bg),main.hero>div:not(.hero-bg):not(.bs-hero-image-bg),section.hero>div:not(.hero-bg):not(.bs-hero-image-bg),.hero>.wrap,main.hero>.wrap,section.hero>.wrap{position:relative!important;z-index:2!important;}
  .hero-actions,[class*="hero-actions"],.actions{min-height:0!important;padding-top:0!important;padding-bottom:0!important;display:flex!important;flex-wrap:wrap!important;gap:12px!important;}
  body[class*="bs-hero-v"] .showcase,body[class*="bs-layout-"] .showcase,body[class*="bs-seed-"] .showcase,.hero-card,[class*="hero-card"]{width:100%!important;max-width:100%!important;padding:0!important;display:block!important;overflow:hidden!important;}
}
@media(max-width:560px){
  .hero,.hero-section,main.hero,section.hero{padding-top:clamp(86px,20vw,112px)!important;padding-bottom:clamp(38px,10vw,64px)!important;min-height:0!important;height:auto!important;}
  body[class*="bs-hero-v"] .showcase{min-height:260px!important;}
  .hero-card,[class*="hero-card"]{min-height:220px!important;max-height:320px!important;}
  .hero-card>img,[class*="hero-card"]>img{min-height:220px!important;max-height:320px!important;}
}
</style>
`

const EXISTING_WEBSITE_LAYOUT_FIX_SCRIPT = `
<script id="bs-existing-layout-fix-script">
(function(){try{function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn();}
function fix(){var vw=document.documentElement.clientWidth||window.innerWidth;document.querySelectorAll('body *').forEach(function(el){try{var cs=getComputedStyle(el);if(cs.display==='none')return;var r=el.getBoundingClientRect();if((r.right>vw+2||el.scrollWidth>vw+2)&&!el.closest('.bs-mobile-drawer')){el.style.maxWidth='100%';el.style.minWidth='0';el.style.overflowWrap='break-word';if(cs.display.indexOf('grid')!==-1&&vw<1024)el.style.gridTemplateColumns='1fr';if(cs.display.indexOf('flex')!==-1&&vw<1024)el.style.flexWrap='wrap';}if(vw<768&&/H1|H2|H3|P|LI/.test(el.tagName)){el.style.maxWidth='100%';el.style.overflowWrap='break-word';}}catch(e){}});}ready(function(){fix();setTimeout(fix,350);setTimeout(fix,1200);});window.addEventListener('resize',function(){clearTimeout(window.__bsLayoutFixTimer);window.__bsLayoutFixTimer=setTimeout(fix,120);},{passive:true});}catch(e){}})();
</script>
`

// ── RESPONSIVE FIX: injected into every site, new and existing ───────────────
// Old sites generated before full responsive directives were in the prompt
// often have fixed-pixel widths, overflow issues, and no mobile breakpoints.
// This runtime CSS patch normalises the most common patterns without rewriting
// the stored HTML. It is injected into <head> alongside VISIBILITY_FIX_STYLE.
//
// Strategy:
//   1. Force box-sizing and overflow-x containment globally
//   2. Cap common fixed-width containers to 100vw
//   3. Make images fluid (max-width:100%)
//   4. Stack flex/grid rows on narrow screens
//   5. Ensure the viewport meta tag exists (some old sites omit it)
//   6. Clamp oversized font sizes on mobile
const RESPONSIVE_FIX_STYLE = `
<style id="bs-responsive-fix">
/* BrandSyndicate Responsive Compat Layer — applied to every public /w site */
*,*::before,*::after{box-sizing:border-box!important;}
html,body{width:100%!important;max-width:100%!important;overflow-x:hidden!important;-webkit-text-size-adjust:100%;}
body{min-width:0!important;}
section,main,footer,header,nav,.container,.wrap,.wrapper,[class*="container"],[class*="wrap"]{max-width:100%!important;min-width:0!important;}
img,video,iframe,canvas,svg{max-width:100%!important;}
img{display:block;object-position:center center;background:rgba(255,255,255,.06);}
img[src=""],img:not([src]){display:none!important;}
form,input,textarea,select,button{max-width:100%!important;}
input,textarea,select{min-height:44px!important;}
table{max-width:100%!important;}

/* Nav/logo hardening: fixes vertical stacked brand names like the screenshot */
nav,header,header nav,[class*="navbar"],[class*="nav-inner"],[class*="navInner"]{min-width:0!important;overflow:visible!important;}
nav>*,header>*,header nav>*{min-width:0!important;}
nav [class*="logo"],nav [class*="brand"],nav [class*="company"],header [class*="logo"],header [class*="brand"],header [class*="company"],nav a:first-child,header a:first-child{
  white-space:nowrap!important;word-break:keep-all!important;overflow-wrap:normal!important;writing-mode:horizontal-tb!important;text-orientation:mixed!important;line-height:1.12!important;display:inline-flex!important;align-items:center!important;gap:.35rem!important;max-width:calc(100% - 92px)!important;overflow:hidden!important;text-overflow:ellipsis!important;letter-spacing:.04em!important;
}
nav [class*="logo"] *,nav [class*="brand"] *,header [class*="logo"] *,header [class*="brand"] *{white-space:nowrap!important;word-break:keep-all!important;overflow-wrap:normal!important;}

.bs-mobile-menu-toggle{display:none;align-items:center;justify-content:center;flex-direction:column;gap:4px;width:42px;height:42px;border:1px solid rgba(255,255,255,.18);border-radius:999px;background:rgba(255,255,255,.08);color:inherit;cursor:pointer;z-index:10001;flex-shrink:0;}
.bs-mobile-menu-toggle span{display:block;width:18px;height:2px;background:currentColor;border-radius:2px;}
.bs-mobile-drawer{display:none;position:fixed;left:12px;right:12px;top:72px;z-index:10000;padding:14px;border:1px solid rgba(255,255,255,.16);border-radius:18px;background:rgba(10,10,10,.97);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);box-shadow:0 24px 60px rgba(0,0,0,.5);}
.bs-mobile-drawer.open{display:grid;gap:8px;}
.bs-mobile-drawer-link{display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;min-height:44px!important;padding:11px 14px!important;border-radius:12px!important;text-decoration:none!important;color:#fff!important;background:rgba(255,255,255,.07)!important;border:1px solid rgba(255,255,255,.08)!important;font-size:13px!important;letter-spacing:.08em!important;text-transform:uppercase!important;}

@media(max-width:768px){
  body{font-size:16px!important;}
  nav,header nav,[class*="navbar"],[class*="nav-inner"],[class*="navInner"]{display:flex!important;flex-wrap:nowrap!important;align-items:center!important;justify-content:space-between!important;gap:8px!important;width:100%!important;height:auto!important;min-height:0!important;padding-left:16px!important;padding-right:16px!important;overflow:visible!important;}
  nav [class*="logo"],nav [class*="brand"],header [class*="logo"],header [class*="brand"],nav a:first-child,header a:first-child{flex:1 1 auto!important;max-width:calc(100% - 88px)!important;font-size:clamp(14px,4.8vw,22px)!important;}
  nav > a[class*="cta"],nav > a[class*="btn"],nav > button[class*="cta"],nav > button[class*="btn"],nav [class*="nav-cta"],header [class*="nav-cta"]{display:none!important;}
  nav [class*="actions"],header [class*="actions"],nav [class*="desktop"],header [class*="desktop"],nav ul,header nav ul{display:none!important;}
  nav button[aria-label*="menu" i],header button[aria-label*="menu" i],nav [class*="hamb" i],header [class*="hamb" i],nav [class*="toggle" i],header [class*="toggle" i]{display:flex!important;flex:0 0 auto!important;}
  .bs-mobile-nav-ready .bs-mobile-menu-toggle{display:flex!important;margin-left:auto!important;flex:0 0 auto!important;}
  .bs-mobile-nav-ready [class*="links"],.bs-mobile-nav-ready [class*="nav-links"],.bs-mobile-nav-ready [class*="navLinks"],.bs-mobile-nav-ready [class*="menu"]:not(.bs-mobile-menu-toggle),.bs-mobile-nav-ready .bs-mobile-nav-original{display:none!important;}
  .bs-mobile-nav-ready .bs-mobile-drawer{display:none!important;}.bs-mobile-nav-ready .bs-mobile-drawer.open{display:grid!important;}

  [class*="hero-content"],[class*="hero-left"],[class*="hero-inner"],[class*="hero-copy"],[class*="hero-text"],[class*="showcase"],[class*="card"],[class*="content"],[class*="copy"],.panel,.quote,.price,.lead-form{min-width:0!important;max-width:100%!important;}
  section,.section,[class*="section"]{padding-left:clamp(16px,5vw,28px)!important;padding-right:clamp(16px,5vw,28px)!important;}
  [class*="metric"],[class*="stat"],[class*="service"],[class*="feature"],[class*="price"],[class*="testimonial"]{min-width:0!important;overflow-wrap:break-word!important;}
  h1{font-size:clamp(2rem,10vw,3.4rem)!important;line-height:1.05!important;max-width:100%!important;word-break:normal!important;overflow-wrap:break-word!important;}
  h2{font-size:clamp(1.55rem,7vw,2.4rem)!important;line-height:1.15!important;word-break:normal!important;overflow-wrap:break-word!important;}
  h3,p,li,a,button,span{word-break:normal!important;overflow-wrap:break-word!important;}
  .grid,[class*="grid"],[style*="grid-template-columns"],.features,.services,.pricing,.testimonials,.gallery,.metric-grid,.proof-wall,.contact,.split,.hero-grid{grid-template-columns:1fr!important;}
  [style*="display:flex"],[style*="display: flex"],.row,[class*="row"]{flex-wrap:wrap!important;}
  [style*="min-width"]{min-width:0!important;}
  table{display:block!important;width:100%!important;overflow-x:auto!important;}

  :not(body)[class*="hero"],.hero,section:first-of-type{height:auto!important;min-height:auto!important;padding-top:clamp(56px,14vw,96px)!important;padding-bottom:clamp(56px,14vw,96px)!important;}
  :not(body)[class*="hero"],.hero{position:relative!important;overflow:hidden!important;min-height:clamp(400px,90vw,700px)!important;display:flex!important;flex-direction:column!important;justify-content:center!important;}
  .hero-bg,.hero-bg img,[class*="hero-bg"],[class*="hero-bg"] img,[class*="heroBg"],[class*="heroBg"] img,[class*="hero-image"],[class*="hero-image"] img,[class*="hero-visual"],[class*="hero-visual"] img,[class*="hero-media"],[class*="hero-media"] img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;z-index:-1!important;display:block!important;}
  :not(body)[class*="hero"]>div,.hero>div,:not(body)[class*="hero"]>.wrap,.hero>.wrap{position:relative!important;z-index:2!important;}
  img:not(:not(body)[class*="hero"]):not([class*="bg"]):not([class*="cover"]):not([class*="fill"]):not([style*="position:absolute"]):not([style*="position: absolute"]){height:auto!important;max-height:70vh!important;}
}

@media(max-width:430px){
  nav,header nav,[class*="navbar"],[class*="nav-inner"]{padding-left:14px!important;padding-right:14px!important;}
  nav [class*="logo"],nav [class*="brand"],header [class*="logo"],header [class*="brand"],nav a:first-child,header a:first-child{max-width:calc(100% - 76px)!important;}
}
</style>
<script id="bs-responsive-viewport-script">
(function(){try{if(!document.querySelector('meta[name="viewport"]')){var m=document.createElement('meta');m.name='viewport';m.content='width=device-width, initial-scale=1';document.head.appendChild(m);}}catch(e){}})();
</script>`


function stripTemplateLanguage(html: string): string {
  const replacements: Array<[RegExp, string]> = [
    [/\btemplate\b/gi, 'website'],
    [/\btemplates\b/gi, 'websites'],
    [/this website is intentionally different from your current \d+ files:?/gi, ''],
    [/the structure is intentionally predictable:?/gi, ''],
    [/your backend can safely replace text while keeping the design intact\.?/gi, ''],
    [/new ID, new label, new section order, industry menu, copy pattern and layout treatment\.?/gi, ''],
    [/Claude JSON personalisation/gi, 'service and content clarity'],
    [/Claude JSON/gi, 'business content'],
    [/Brand Syndicate AI personalisation/gi, 'customer-ready presentation'],
    [/AI personalisation/gi, 'customer-ready presentation'],
    [/prompt-based industry matching/gi, 'category-specific messaging'],
    [/free AI preview/gi, 'business website'],
    [/AI preview/gi, 'business website'],
    [/Live Preview/gi, 'Project Snapshot'],
    [/Preview Quality/gi, 'Website Quality'],
    [/Every section is structured so your AI generator can replace copy, colours and business details without breaking the design\.?/gi, 'Every section explains the offer clearly, builds trust and guides visitors toward enquiry.'],
    [/your backend can safely replace text while keeping the design intact\.?/gi, 'the page stays readable as business details expand.'],
    [/Claude can add these as complete websites, not empty design shells\.?/gi, 'the page feels complete, credible and ready for enquiries.'],
    [/Connect this form to your existing generation history, admin panel, WhatsApp follow-up or CRM\. The layout stays readable even when Claude inserts longer AI content\.?/gi, 'Connect this form to WhatsApp, CRM or direct follow-up. The layout stays readable even with longer customer requirements.'],
    [/generation history, admin panel, WhatsApp follow-up or CRM/gi, 'WhatsApp, CRM or direct follow-up'],
    [/even when Claude inserts longer AI content/gi, 'even with longer customer requirements'],
    [/inside Brand Syndicate\.?/gi, ''],
  ]
  return html.split(/(<[^>]+>)/g).map(part => {
    if (part.startsWith('<')) return part
    let clean = part
    for (const [pattern, replacement] of replacements) clean = clean.replace(pattern, replacement)
    return clean.replace(/\s{2,}/g, ' ')
  }).join('')
}

// Height-sync: lets the generate-page iframe auto-resize
const HEIGHT_SYNC_SCRIPT = `
<script>
(function(){
  try {
    if(window.parent !== window){
      function rh(){ window.parent.postMessage({ type:'bs-height', height:document.body.scrollHeight },'*'); }
      rh();
      window.addEventListener('resize', rh);
      new MutationObserver(rh).observe(document.body,{ childList:true, subtree:true });
    }
  } catch(e){}
})();
</script>`



const MOBILE_NAV_SCRIPT = `
<script id="bs-mobile-nav-script">
(function(){
  try{
    function ready(fn){ if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',fn); else fn(); }
    ready(function(){
      (document.querySelectorAll('nav').length ? document.querySelectorAll('nav') : document.querySelectorAll('header')).forEach(function(nav){
        if(nav.querySelector('.bs-mobile-menu-toggle')) return;
        // Skip if template already has its own hamburger/toggle button
        var existingToggle = Array.prototype.slice.call(nav.querySelectorAll('button,div[role="button"]')).filter(function(el){
          var cls = (el.className||'').toLowerCase();
          var hasHamburgerClass = /toggle|burger|hamburger|menu-btn|mob|drawer|open/.test(cls);
          var hasOnlySpans = el.children.length >= 2 && Array.prototype.every.call(el.children, function(c){ return c.tagName === 'SPAN'; });
          return hasHamburgerClass || hasOnlySpans;
        });
        if(existingToggle.length > 0) {
          nav.classList.add('bs-mobile-nav-ready');
          Array.prototype.slice.call(nav.querySelectorAll('a,button')).forEach(function(el){
            if(existingToggle.indexOf(el) !== -1) return;
            var txt=(el.textContent||'').trim().toLowerCase();
            var cls=((el.className||'')+'').toLowerCase();
            var looksLikeBrand=/brand|logo|company/.test(cls) && txt.length < 34;
            var looksLikeNavAction=/schedule|consult|collection|service|about|contact|shop|book|pricing|generate|get started|start|portfolio/.test(txt) || /links|actions|cta|btn|menu/.test(cls);
            if(!looksLikeBrand && looksLikeNavAction) el.classList.add('bs-mobile-nav-original');
          });
          return;
        }
        var links = Array.prototype.slice.call(nav.querySelectorAll('a,button')).filter(function(el, i){
          var txt=(el.textContent||'').trim();
          if(!txt) return false;
          if(i===0 && txt.length < 34) return false;
          if(el.classList && (el.classList.contains('bs-mobile-menu-toggle') || el.classList.contains('bs-mobile-drawer-link'))) return false;
          return true;
        });
        if(links.length < 2) return;
        links.forEach(function(el){
          var parent = el.parentElement;
          if(parent && parent !== nav && parent.children.length <= Math.max(links.length + 1, 3)) parent.classList.add('bs-mobile-nav-original');
          else el.classList.add('bs-mobile-nav-original');
        });
        var btn=document.createElement('button');
        btn.type='button';
        btn.className='bs-mobile-menu-toggle';
        btn.setAttribute('aria-label','Open menu');
        btn.setAttribute('aria-expanded','false');
        btn.innerHTML='<span></span><span></span><span></span>';
        var drawer=document.createElement('div');
        drawer.className='bs-mobile-drawer';
        links.forEach(function(el){
          var clone=el.cloneNode(true);
          clone.classList.add('bs-mobile-drawer-link');
          clone.removeAttribute('style');
          clone.addEventListener('click',function(){drawer.classList.remove('open');btn.setAttribute('aria-expanded','false');});
          drawer.appendChild(clone);
        });
        function positionDrawer(){
          var r=nav.getBoundingClientRect();
          drawer.style.top=(r.bottom+window.scrollY+6)+'px';
        }
        btn.addEventListener('click',function(){
          positionDrawer();
          var isOpen=drawer.classList.toggle('open');
          btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        });
        document.addEventListener('click',function(e){
          if(!nav.contains(e.target)&&!drawer.contains(e.target)){drawer.classList.remove('open');btn.setAttribute('aria-expanded','false');}
        });
        window.addEventListener('scroll',function(){if(drawer.classList.contains('open'))positionDrawer();},{passive:true});
        nav.appendChild(btn);
        document.body.appendChild(drawer);
        nav.classList.add('bs-mobile-nav-ready');
      });
    });
  }catch(e){}
})();
</script>`

// Image hardening: prevents lazy images from staying blank in previews/mobile and
// adds a graceful fallback box for broken remote images.
const IMAGE_FIX_SCRIPT = `
<script id="bs-image-fallback-script">
(function(){
  try{
    function applyFallback(img){
      if(!img || img.dataset.bsFallbackApplied==='true') return;
      img.dataset.bsFallbackApplied='true';
      img.onerror=null;
      img.alt=img.alt||'Image unavailable';
      img.style.background='linear-gradient(135deg,#16110B,#3A2A16)';
      img.style.minHeight=img.style.minHeight||'180px';
      img.style.objectFit=img.style.objectFit||'cover';
      img.style.opacity='1';
      var label=(img.alt||'Image unavailable').replace(/[<>&"]/g,' ').slice(0,80);
      var svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#16110B"/><stop offset="1" stop-color="#6A4A25"/></linearGradient></defs><rect width="1200" height="800" fill="url(#g)"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#F5E8D0" font-family="Georgia,serif" font-size="44" letter-spacing="4">'+label+'</text></svg>';
      img.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);
    }
    function fix(){
      document.querySelectorAll('img').forEach(function(img){
        img.loading='eager';
        img.decoding='async';
        if(!img.getAttribute('referrerpolicy')) img.setAttribute('referrerpolicy','no-referrer');
        img.onerror=function(){ applyFallback(this); };
        if(img.complete && img.naturalWidth===0) applyFallback(img);
      });
    }
    if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',fix); else fix();
    window.addEventListener('load',fix);
  }catch(e){}
})();
</script>`

// Analytics tracker: fires on page load, sends duration on exit.
// Uses sendBeacon so exit events survive mobile tab switches.
// No cookies, no external calls — fully first-party.
function bsTrackerScript(siteId: string): string {
  return `<script>
(function(){
  try{
    var sid=sessionStorage.getItem('_bss')||(Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2));
    sessionStorage.setItem('_bss',sid);
    var ep='/api/website/${siteId}/track';
    var t0=Date.now();
    function send(dur){
      var b=JSON.stringify({sessionId:sid,durationMs:dur||undefined});
      if(navigator.sendBeacon){navigator.sendBeacon(ep,new Blob([b],{type:'application/json'}));}
      else{var x=new XMLHttpRequest();x.open('POST',ep,false);x.setRequestHeader('Content-Type','application/json');try{x.send(b);}catch(e){}}
    }
    send(null);
    var sent=false;
    function onExit(){if(sent)return;sent=true;send(Date.now()-t0);}
    document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')onExit();});
    window.addEventListener('pagehide',onExit);
  }catch(e){}
})();
</script>`
}

// bs-backend: wires contact/booking forms + blog to this site's API namespace
function bsBackendScript(siteId: string): string {
  return `<script src="/embed/bs-backend.js" data-site-id="${siteId}" defer></script>`
}



function stableGeneratedImageForQuery(query: string): string {
  const hay = decodeURIComponent(String(query || '')).replace(/[,+]/g, ' ')
  const options: Array<[RegExp, string]> = [
    [/furniture|sofa|interior|decor|wood|carpenter|kitchen/i, 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=75&auto=format&fit=crop'],
    [/school|college|academy|coaching|learning|education|training|student|course/i, 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=75&auto=format&fit=crop'],
    [/clinic|hospital|doctor|medical|dental|ayurveda|wellness|spa|health/i, 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&q=75&auto=format&fit=crop'],
    [/restaurant|cafe|bakery|food|cloud-kitchen|bar|lounge|chef|chocolate/i, 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=75&auto=format&fit=crop'],
    [/fashion|boutique|clothing|apparel|beauty|cosmetic|salon/i, 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1200&q=75&auto=format&fit=crop'],
    [/jewel|diamond|luxury|adore/i, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&q=75&auto=format&fit=crop'],
    [/real-estate|property|villa|architect|architecture|construction/i, 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=75&auto=format&fit=crop'],
    [/auto|car|bike|vehicle|automobile|mobility|showroom/i, 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=75&auto=format&fit=crop'],
    [/sports|fitness|gym|marathon|bat|cricket|club/i, 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&q=75&auto=format&fit=crop'],
    [/farm|agri|crop|organic|dairy|rural/i, 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=75&auto=format&fit=crop'],
    [/finance|accounting|fintech|bank|tax|loan|wealth/i, 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=75&auto=format&fit=crop'],
    [/logistics|warehouse|courier|shipping|transport/i, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=75&auto=format&fit=crop'],
    [/solar|energy|power/i, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=75&auto=format&fit=crop'],
    [/travel|tour|hotel|resort|stay/i, 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=75&auto=format&fit=crop'],
    [/law|legal|advocate/i, 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=75&auto=format&fit=crop'],
    [/tech|saas|software|ai|automation|cyber|blockchain|app|cloud/i, 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=75&auto=format&fit=crop'],
  ]
  for (const [pattern, url] of options) if (pattern.test(hay)) return url
  return 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=75&auto=format&fit=crop'
}

function replaceDeprecatedGeneratedImages(html: string): string {
  return html.replace(/https:\/\/source\.unsplash\.com\/featured\/(?:\d+x\d+\/)?\?([^"'\s<)]+)/gi, (_match, query: string) => stableGeneratedImageForQuery(query))
}

function repairCommonGeneratedHtmlIssues(html: string): string {
  return replaceDeprecatedGeneratedImages(html)
    .replace(/<img([^>]*?)\/\s+(loading|decoding|style|class|alt|src)=/gi, '<img$1 $2=')
    .replace(/<img([^>]*?)\/\s*>/gi, '<img$1>')
    .replace(/width:\s*100vw/gi, 'width:100%')
    .replace(/min-width:\s*100vw/gi, 'min-width:100%')
}

// Guard: returns true only if the body has real page content (>100 chars after stripping scripts).
// Catches the old max_tokens truncation bug where Claude wrote <head> meta but never reached <body>.
function hasBodyContent(html: string): boolean {
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  if (!bodyMatch) return false
  const bodyText = bodyMatch[1]
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .trim()
  return bodyText.length > 100
}

export async function GET(
  _req: Request,
  { params }: { params: { slug: string } }
) {
  const site = await db.userWebsite.findUnique({
    where: { slug: params.slug },
    select: { id: true, htmlContent: true, isPublished: true, name: true, slug: true },
  }).catch(() => null)

  if (!site) {
    return new Response(NOT_FOUND_HTML, {
      status: 404,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  if (!site.isPublished) {
    return new Response(NOT_PUBLISHED_HTML(site.name ?? 'Website'), {
      status: 200,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  const rawHtml = site.htmlContent?.trim() ?? ''

  // ── Guard: empty body → show regenerate prompt instead of blank page ────────
  // This catches sites where Claude was cut off mid-generation (max_tokens) before
  // writing any <body> content. The stored HTML has a <head> with meta tags but
  // nothing visible. Serving it would show a blank white/dark page with no indication
  // of what went wrong. We show a clear "regenerate" message instead.
  if (!rawHtml || !hasBodyContent(rawHtml)) {
    console.warn(`[w/${params.slug}] Site ${site.id} has empty body content — serving truncation page`)
    return new Response(TRUNCATED_HTML(site.slug ?? params.slug), {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    })
  }

  // Inject all scripts before </body>:
  // 0. VISIBILITY_FIX_STYLE  — fixes legacy opacity:0/IntersectionObserver hidden content
  // 0b. RESPONSIVE_FIX_STYLE — runtime responsive compat for old fixed-width sites
  // 1. HEIGHT_SYNC_SCRIPT    — iframe resize for the generate page preview
  // 2. bsTrackerScript       — first-party analytics (no cookies, no external requests)
  // 3. bsBackendScript       — form capture + blog rendering
  const inject = `${MOBILE_NAV_SCRIPT}${IMAGE_FIX_SCRIPT}${bsTrackerScript(site.id)}${bsBackendScript(site.id)}`

  // Inject visibility fix + responsive compat into <head> and other scripts before </body>
  let html = repairCommonGeneratedHtmlIssues(stripTemplateLanguage(rawHtml))
    .replace(/<style[^>]+id=["']bs-mobile-root-hero-fix-v[67]["'][\s\S]*?<\/style>/gi, '')
  if (html.includes('</head>')) {
    html = html.replace('</head>', VISIBILITY_FIX_STYLE + RESPONSIVE_FIX_STYLE + EXISTING_WEBSITE_SPACE_FIX_STYLE + MOBILE_ROOT_HERO_FIX_STYLE + EXISTING_WEBSITE_LAYOUT_FIX_SCRIPT + '\n</head>')
  } else {
    // No head tag — prepend at top
    html = VISIBILITY_FIX_STYLE + RESPONSIVE_FIX_STYLE + EXISTING_WEBSITE_SPACE_FIX_STYLE + MOBILE_ROOT_HERO_FIX_STYLE + EXISTING_WEBSITE_LAYOUT_FIX_SCRIPT + '\n' + html
  }
  html = html.replace(/<\/body>/i, `${inject}</body>`)

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type':  'text/html; charset=utf-8',
      'X-Frame-Options': 'SAMEORIGIN',
      'Cache-Control': 'no-store',
    },
  })
}
