// Auto-split chunk 4 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_04: WebsiteTemplate[] = [
  {
    id: 'bsx-corporate-wellness-platform-commerce',
    label: 'Corporate Wellness Platform — Commerce Edition',
    category: 'HealthTech',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform commerce', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'commerce', 'commerce edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-booking',
    label: 'Corporate Wellness Platform — Booking Edition',
    category: 'HealthTech',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform booking', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'booking', 'booking edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-trust',
    label: 'Corporate Wellness Platform — Trust Edition',
    category: 'HealthTech',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform trust', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'trust', 'trust edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-magazine',
    label: 'Corporate Wellness Platform — Magazine Edition',
    category: 'HealthTech',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform magazine', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'magazine', 'magazine edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-enterprise',
    label: 'Corporate Wellness Platform — Enterprise Edition',
    category: 'HealthTech',
    color: '#118AB2',
    bg: '#120817',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform enterprise', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'enterprise', 'enterprise edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-signal',
    label: 'Interior Material Library — Signal Edition',
    category: 'Design',
    color: '#118AB2',
    bg: '#120817',
    industries: ['design', 'interior material library', 'interior material library signal', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'signal', 'signal edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-atelier',
    label: 'Interior Material Library — Atelier Edition',
    category: 'Design',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['design', 'interior material library', 'interior material library atelier', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'atelier', 'atelier edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-local',
    label: 'Interior Material Library — Local Growth Edition',
    category: 'Design',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['design', 'interior material library', 'interior material library local', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'local', 'local growth edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-commerce',
    label: 'Interior Material Library — Commerce Edition',
    category: 'Design',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['design', 'interior material library', 'interior material library commerce', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'commerce', 'commerce edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-booking',
    label: 'Interior Material Library — Booking Edition',
    category: 'Design',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['design', 'interior material library', 'interior material library booking', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'booking', 'booking edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-trust',
    label: 'Interior Material Library — Trust Edition',
    category: 'Design',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['design', 'interior material library', 'interior material library trust', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'trust', 'trust edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-magazine',
    label: 'Interior Material Library — Magazine Edition',
    category: 'Design',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['design', 'interior material library', 'interior material library magazine', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'magazine', 'magazine edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-interior-material-library-enterprise',
    label: 'Interior Material Library — Enterprise Edition',
    category: 'Design',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['design', 'interior material library', 'interior material library enterprise', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk'],
    keywords: ['design', 'interior material library', 'enterprise', 'enterprise edition', 'materials', 'moodboards', 'vendors', 'samples', 'visit', 'surface samples', 'moodboard kits', 'vendor pricing', 'designer desk', 'project rooms'],
    description: 'Standalone unique Design website template for Interior Material Library, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-signal',
    label: 'Hyperlocal Grocery App — Signal Edition',
    category: 'Commerce',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app signal', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'signal', 'signal edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-atelier',
    label: 'Hyperlocal Grocery App — Atelier Edition',
    category: 'Commerce',
    color: '#EF4444',
    bg: '#100808',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app atelier', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'atelier', 'atelier edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-local',
    label: 'Hyperlocal Grocery App — Local Growth Edition',
    category: 'Commerce',
    color: '#10B981',
    bg: '#080501',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app local', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'local', 'local growth edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-commerce',
    label: 'Hyperlocal Grocery App — Commerce Edition',
    category: 'Commerce',
    color: '#F472B6',
    bg: '#031316',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app commerce', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'commerce edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-booking',
    label: 'Hyperlocal Grocery App — Booking Edition',
    category: 'Commerce',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app booking', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'booking', 'booking edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-trust',
    label: 'Hyperlocal Grocery App — Trust Edition',
    category: 'Commerce',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app trust', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'trust', 'trust edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-magazine',
    label: 'Hyperlocal Grocery App — Magazine Edition',
    category: 'Commerce',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app magazine', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'magazine', 'magazine edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-grocery-app-enterprise',
    label: 'Hyperlocal Grocery App — Enterprise Edition',
    category: 'Commerce',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['commerce', 'hyperlocal grocery app', 'hyperlocal grocery app enterprise', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners'],
    keywords: ['commerce', 'hyperlocal grocery app', 'enterprise', 'enterprise edition', 'categories', 'delivery', 'offers', 'partners', 'download', 'fresh produce', 'slot delivery', 'wallet offers', 'store partners', 'order tracking'],
    description: 'Standalone unique Commerce website template for Hyperlocal Grocery App, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-signal',
    label: 'Pet Grooming Spa — Signal Edition',
    category: 'Pets',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa signal', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'signal', 'signal edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-atelier',
    label: 'Pet Grooming Spa — Atelier Edition',
    category: 'Pets',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa atelier', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'atelier', 'atelier edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-local',
    label: 'Pet Grooming Spa — Local Growth Edition',
    category: 'Pets',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa local', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'local', 'local growth edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-commerce',
    label: 'Pet Grooming Spa — Commerce Edition',
    category: 'Pets',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa commerce', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'commerce', 'commerce edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-booking',
    label: 'Pet Grooming Spa — Booking Edition',
    category: 'Pets',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa booking', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'booking', 'booking edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-trust',
    label: 'Pet Grooming Spa — Trust Edition',
    category: 'Pets',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa trust', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'trust', 'trust edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-magazine',
    label: 'Pet Grooming Spa — Magazine Edition',
    category: 'Pets',
    color: '#118AB2',
    bg: '#060606',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa magazine', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'magazine', 'magazine edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pet-grooming-spa-enterprise',
    label: 'Pet Grooming Spa — Enterprise Edition',
    category: 'Pets',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['pets', 'pet grooming spa', 'pet grooming spa enterprise', 'spa bath', 'coat trimming', 'tick care', 'pet pickup'],
    keywords: ['pets', 'pet grooming spa', 'enterprise', 'enterprise edition', 'services', 'stylists', 'safety', 'membership', 'book', 'spa bath', 'coat trimming', 'tick care', 'pet pickup', 'grooming records'],
    description: 'Standalone unique Pets website template for Pet Grooming Spa, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-signal',
    label: 'Event Ticketing Platform — Signal Edition',
    category: 'Events',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['events', 'event ticketing platform', 'event ticketing platform signal', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'signal', 'signal edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-atelier',
    label: 'Event Ticketing Platform — Atelier Edition',
    category: 'Events',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['events', 'event ticketing platform', 'event ticketing platform atelier', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'atelier', 'atelier edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-local',
    label: 'Event Ticketing Platform — Local Growth Edition',
    category: 'Events',
    color: '#F97316',
    bg: '#100A04',
    industries: ['events', 'event ticketing platform', 'event ticketing platform local', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'local', 'local growth edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-commerce',
    label: 'Event Ticketing Platform — Commerce Edition',
    category: 'Events',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['events', 'event ticketing platform', 'event ticketing platform commerce', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'commerce', 'commerce edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-booking',
    label: 'Event Ticketing Platform — Booking Edition',
    category: 'Events',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['events', 'event ticketing platform', 'event ticketing platform booking', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'booking', 'booking edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-trust',
    label: 'Event Ticketing Platform — Trust Edition',
    category: 'Events',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['events', 'event ticketing platform', 'event ticketing platform trust', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'trust', 'trust edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-magazine',
    label: 'Event Ticketing Platform — Magazine Edition',
    category: 'Events',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['events', 'event ticketing platform', 'event ticketing platform magazine', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'magazine', 'magazine edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-event-ticketing-platform-enterprise',
    label: 'Event Ticketing Platform — Enterprise Edition',
    category: 'Events',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['events', 'event ticketing platform', 'event ticketing platform enterprise', 'seat maps', 'qr entry', 'promoter tools', 'refund rules'],
    keywords: ['events', 'event ticketing platform', 'enterprise', 'enterprise edition', 'venues', 'tickets', 'promoters', 'list event', 'seat maps', 'QR entry', 'promoter tools', 'refund rules', 'sales analytics'],
    description: 'Standalone unique Events website template for Event Ticketing Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-signal',
    label: 'Art Investment Gallery — Signal Edition',
    category: 'Art',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['art', 'art investment gallery', 'art investment gallery signal', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'signal', 'signal edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-atelier',
    label: 'Art Investment Gallery — Atelier Edition',
    category: 'Art',
    color: '#10B981',
    bg: '#010A05',
    industries: ['art', 'art investment gallery', 'art investment gallery atelier', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'atelier', 'atelier edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-local',
    label: 'Art Investment Gallery — Local Growth Edition',
    category: 'Art',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['art', 'art investment gallery', 'art investment gallery local', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'local', 'local growth edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-commerce',
    label: 'Art Investment Gallery — Commerce Edition',
    category: 'Art',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['art', 'art investment gallery', 'art investment gallery commerce', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'commerce', 'commerce edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-booking',
    label: 'Art Investment Gallery — Booking Edition',
    category: 'Art',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['art', 'art investment gallery', 'art investment gallery booking', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'booking', 'booking edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-trust',
    label: 'Art Investment Gallery — Trust Edition',
    category: 'Art',
    color: '#A3E635',
    bg: '#050313',
    industries: ['art', 'art investment gallery', 'art investment gallery trust', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'trust', 'trust edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-magazine',
    label: 'Art Investment Gallery — Magazine Edition',
    category: 'Art',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['art', 'art investment gallery', 'art investment gallery magazine', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'magazine', 'magazine edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-art-investment-gallery-enterprise',
    label: 'Art Investment Gallery — Enterprise Edition',
    category: 'Art',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['art', 'art investment gallery', 'art investment gallery enterprise', 'curated works', 'provenance notes', 'collector advisory', 'private viewings'],
    keywords: ['art', 'art investment gallery', 'enterprise', 'enterprise edition', 'artists', 'collections', 'advisory', 'exhibitions', 'acquire', 'curated works', 'provenance notes', 'collector advisory', 'private viewings', 'shipping support'],
    description: 'Standalone unique Art website template for Art Investment Gallery, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-signal',
    label: 'Premium Coworking Club — Signal Edition',
    category: 'Real Estate',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['real estate', 'premium coworking club', 'premium coworking club signal', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'signal', 'signal edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-atelier',
    label: 'Premium Coworking Club — Atelier Edition',
    category: 'Real Estate',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['real estate', 'premium coworking club', 'premium coworking club atelier', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'atelier', 'atelier edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-local',
    label: 'Premium Coworking Club — Local Growth Edition',
    category: 'Real Estate',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['real estate', 'premium coworking club', 'premium coworking club local', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'local', 'local growth edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-commerce',
    label: 'Premium Coworking Club — Commerce Edition',
    category: 'Real Estate',
    color: '#FFD166',
    bg: '#101112',
    industries: ['real estate', 'premium coworking club', 'premium coworking club commerce', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'commerce', 'commerce edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-booking',
    label: 'Premium Coworking Club — Booking Edition',
    category: 'Real Estate',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['real estate', 'premium coworking club', 'premium coworking club booking', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'booking', 'booking edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-trust',
    label: 'Premium Coworking Club — Trust Edition',
    category: 'Real Estate',
    color: '#118AB2',
    bg: '#100808',
    industries: ['real estate', 'premium coworking club', 'premium coworking club trust', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'trust', 'trust edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-magazine',
    label: 'Premium Coworking Club — Magazine Edition',
    category: 'Real Estate',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['real estate', 'premium coworking club', 'premium coworking club magazine', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'magazine', 'magazine edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-coworking-club-enterprise',
    label: 'Premium Coworking Club — Enterprise Edition',
    category: 'Real Estate',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['real estate', 'premium coworking club', 'premium coworking club enterprise', 'day passes', 'meeting rooms', 'founder events', 'mail handling'],
    keywords: ['real estate', 'premium coworking club', 'enterprise', 'enterprise edition', 'spaces', 'amenities', 'community', 'plans', 'tour', 'day passes', 'meeting rooms', 'founder events', 'mail handling', 'member app'],
    description: 'Standalone unique Real Estate website template for Premium Coworking Club, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-signal',
    label: 'AI Customer Support Suite — Signal Edition',
    category: 'SaaS',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite signal', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'signal', 'signal edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-atelier',
    label: 'AI Customer Support Suite — Atelier Edition',
    category: 'SaaS',
    color: '#F97316',
    bg: '#09111f',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite atelier', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'atelier', 'atelier edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-local',
    label: 'AI Customer Support Suite — Local Growth Edition',
    category: 'SaaS',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite local', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'local', 'local growth edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-commerce',
    label: 'AI Customer Support Suite — Commerce Edition',
    category: 'SaaS',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite commerce', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'commerce', 'commerce edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-booking',
    label: 'AI Customer Support Suite — Booking Edition',
    category: 'SaaS',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite booking', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'booking', 'booking edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-trust',
    label: 'AI Customer Support Suite — Trust Edition',
    category: 'SaaS',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite trust', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'trust', 'trust edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-magazine',
    label: 'AI Customer Support Suite — Magazine Edition',
    category: 'SaaS',
    color: '#EF4444',
    bg: '#120817',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite magazine', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'magazine', 'magazine edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-customer-support-suite-enterprise',
    label: 'AI Customer Support Suite — Enterprise Edition',
    category: 'SaaS',
    color: '#10B981',
    bg: '#050313',
    industries: ['saas', 'ai customer support suite', 'ai customer support suite enterprise', 'ai replies', 'ticket routing', 'knowledge base', 'sla reports'],
    keywords: ['saas', 'ai customer support suite', 'enterprise', 'enterprise edition', 'inbox', 'agents', 'integrations', 'analytics', 'demo', 'AI replies', 'ticket routing', 'knowledge base', 'SLA reports', 'human handoff'],
    description: 'Standalone unique SaaS website template for AI Customer Support Suite, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-signal',
    label: 'Clinic Appointment SaaS — Signal Edition',
    category: 'SaaS',
    color: '#10B981',
    bg: '#050313',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas signal', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'signal', 'signal edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-atelier',
    label: 'Clinic Appointment SaaS — Atelier Edition',
    category: 'SaaS',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas atelier', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'atelier', 'atelier edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-local',
    label: 'Clinic Appointment SaaS — Local Growth Edition',
    category: 'SaaS',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas local', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'local', 'local growth edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-commerce',
    label: 'Clinic Appointment SaaS — Commerce Edition',
    category: 'SaaS',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas commerce', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'commerce', 'commerce edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-booking',
    label: 'Clinic Appointment SaaS — Booking Edition',
    category: 'SaaS',
    color: '#A3E635',
    bg: '#111827',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas booking', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'booking', 'booking edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-trust',
    label: 'Clinic Appointment SaaS — Trust Edition',
    category: 'SaaS',
    color: '#FB7185',
    bg: '#101112',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas trust', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'trust', 'trust edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-magazine',
    label: 'Clinic Appointment SaaS — Magazine Edition',
    category: 'SaaS',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas magazine', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'magazine', 'magazine edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-clinic-appointment-saas-enterprise',
    label: 'Clinic Appointment SaaS — Enterprise Edition',
    category: 'SaaS',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['saas', 'clinic appointment saas', 'clinic appointment saas enterprise', 'doctor slots', 'patient reminders', 'digital forms', 'payment links'],
    keywords: ['saas', 'clinic appointment saas', 'enterprise', 'enterprise edition', 'calendar', 'patients', 'payments', 'reports', 'demo', 'doctor slots', 'patient reminders', 'digital forms', 'payment links', 'clinic reports'],
    description: 'Standalone unique SaaS website template for Clinic Appointment SaaS, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-signal',
    label: 'Restaurant Franchise System — Signal Edition',
    category: 'Business',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system signal', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'signal', 'signal edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-atelier',
    label: 'Restaurant Franchise System — Atelier Edition',
    category: 'Business',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system atelier', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'atelier', 'atelier edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-local',
    label: 'Restaurant Franchise System — Local Growth Edition',
    category: 'Business',
    color: '#FFD166',
    bg: '#031316',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system local', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'local', 'local growth edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-commerce',
    label: 'Restaurant Franchise System — Commerce Edition',
    category: 'Business',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system commerce', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'commerce', 'commerce edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-booking',
    label: 'Restaurant Franchise System — Booking Edition',
    category: 'Business',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system booking', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'booking', 'booking edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-trust',
    label: 'Restaurant Franchise System — Trust Edition',
    category: 'Business',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system trust', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'trust', 'trust edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-magazine',
    label: 'Restaurant Franchise System — Magazine Edition',
    category: 'Business',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system magazine', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'magazine', 'magazine edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-restaurant-franchise-system-enterprise',
    label: 'Restaurant Franchise System — Enterprise Edition',
    category: 'Business',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['business', 'restaurant franchise system', 'restaurant franchise system enterprise', 'franchise kit', 'central kitchen', 'staff training', 'brand audits'],
    keywords: ['business', 'restaurant franchise system', 'enterprise', 'enterprise edition', 'model', 'menu', 'training', 'locations', 'apply', 'franchise kit', 'central kitchen', 'staff training', 'brand audits', 'location support'],
    description: 'Standalone unique Business website template for Restaurant Franchise System, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-signal',
    label: 'Textile Export House — Signal Edition',
    category: 'Manufacturing',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['manufacturing', 'textile export house', 'textile export house signal', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'signal', 'signal edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-atelier',
    label: 'Textile Export House — Atelier Edition',
    category: 'Manufacturing',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['manufacturing', 'textile export house', 'textile export house atelier', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'atelier', 'atelier edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-local',
    label: 'Textile Export House — Local Growth Edition',
    category: 'Manufacturing',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['manufacturing', 'textile export house', 'textile export house local', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'local', 'local growth edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-commerce',
    label: 'Textile Export House — Commerce Edition',
    category: 'Manufacturing',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['manufacturing', 'textile export house', 'textile export house commerce', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'commerce', 'commerce edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-booking',
    label: 'Textile Export House — Booking Edition',
    category: 'Manufacturing',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['manufacturing', 'textile export house', 'textile export house booking', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'booking', 'booking edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-trust',
    label: 'Textile Export House — Trust Edition',
    category: 'Manufacturing',
    color: '#EF4444',
    bg: '#060606',
    industries: ['manufacturing', 'textile export house', 'textile export house trust', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'trust', 'trust edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-magazine',
    label: 'Textile Export House — Magazine Edition',
    category: 'Manufacturing',
    color: '#10B981',
    bg: '#111827',
    industries: ['manufacturing', 'textile export house', 'textile export house magazine', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'magazine', 'magazine edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-textile-export-house-enterprise',
    label: 'Textile Export House — Enterprise Edition',
    category: 'Manufacturing',
    color: '#F472B6',
    bg: '#101112',
    industries: ['manufacturing', 'textile export house', 'textile export house enterprise', 'fabric library', 'dyeing units', 'moq planning', 'quality checks'],
    keywords: ['manufacturing', 'textile export house', 'enterprise', 'enterprise edition', 'fabrics', 'factory', 'quality', 'exports', 'quote', 'fabric library', 'dyeing units', 'MOQ planning', 'quality checks', 'shipping docs'],
    description: 'Standalone unique Manufacturing website template for Textile Export House, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-signal',
    label: 'CNC Prototype Factory — Signal Edition',
    category: 'Manufacturing',
    color: '#F472B6',
    bg: '#101112',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory signal', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'signal', 'signal edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-atelier',
    label: 'CNC Prototype Factory — Atelier Edition',
    category: 'Manufacturing',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory atelier', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'atelier', 'atelier edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-local',
    label: 'CNC Prototype Factory — Local Growth Edition',
    category: 'Manufacturing',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory local', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'local', 'local growth edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-commerce',
    label: 'CNC Prototype Factory — Commerce Edition',
    category: 'Manufacturing',
    color: '#A3E635',
    bg: '#080501',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory commerce', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'commerce', 'commerce edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-booking',
    label: 'CNC Prototype Factory — Booking Edition',
    category: 'Manufacturing',
    color: '#FB7185',
    bg: '#031316',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory booking', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'booking', 'booking edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-trust',
    label: 'CNC Prototype Factory — Trust Edition',
    category: 'Manufacturing',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory trust', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'trust', 'trust edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-magazine',
    label: 'CNC Prototype Factory — Magazine Edition',
    category: 'Manufacturing',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory magazine', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'magazine', 'magazine edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cnc-prototype-factory-enterprise',
    label: 'CNC Prototype Factory — Enterprise Edition',
    category: 'Manufacturing',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['manufacturing', 'cnc prototype factory', 'cnc prototype factory enterprise', 'cnc milling', 'turning jobs', 'aluminium parts', 'inspection reports'],
    keywords: ['manufacturing', 'cnc prototype factory', 'enterprise', 'enterprise edition', 'capabilities', 'materials', 'tolerance', 'projects', 'quote', 'CNC milling', 'turning jobs', 'aluminium parts', 'inspection reports', 'rapid quotes'],
    description: 'Standalone unique Manufacturing website template for CNC Prototype Factory, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-signal',
    label: 'Premium Gym Chain — Signal Edition',
    category: 'Fitness',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['fitness', 'premium gym chain', 'premium gym chain signal', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'signal', 'signal edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-atelier',
    label: 'Premium Gym Chain — Atelier Edition',
    category: 'Fitness',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['fitness', 'premium gym chain', 'premium gym chain atelier', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'atelier', 'atelier edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-local',
    label: 'Premium Gym Chain — Local Growth Edition',
    category: 'Fitness',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['fitness', 'premium gym chain', 'premium gym chain local', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'local', 'local growth edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-commerce',
    label: 'Premium Gym Chain — Commerce Edition',
    category: 'Fitness',
    color: '#118AB2',
    bg: '#120817',
    industries: ['fitness', 'premium gym chain', 'premium gym chain commerce', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'commerce', 'commerce edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-booking',
    label: 'Premium Gym Chain — Booking Edition',
    category: 'Fitness',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['fitness', 'premium gym chain', 'premium gym chain booking', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'booking', 'booking edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-trust',
    label: 'Premium Gym Chain — Trust Edition',
    category: 'Fitness',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['fitness', 'premium gym chain', 'premium gym chain trust', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'trust', 'trust edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-magazine',
    label: 'Premium Gym Chain — Magazine Edition',
    category: 'Fitness',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['fitness', 'premium gym chain', 'premium gym chain magazine', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'magazine', 'magazine edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-gym-chain-enterprise',
    label: 'Premium Gym Chain — Enterprise Edition',
    category: 'Fitness',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['fitness', 'premium gym chain', 'premium gym chain enterprise', 'strength zones', 'personal trainers', 'body scans', 'group classes'],
    keywords: ['fitness', 'premium gym chain', 'enterprise', 'enterprise edition', 'programs', 'trainers', 'clubs', 'plans', 'join', 'strength zones', 'personal trainers', 'body scans', 'group classes', 'member app'],
    description: 'Standalone unique Fitness website template for Premium Gym Chain, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-signal',
    label: 'Soundproof Podcast Studio — Signal Edition',
    category: 'Media',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio signal', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'signal', 'signal edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-atelier',
    label: 'Soundproof Podcast Studio — Atelier Edition',
    category: 'Media',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio atelier', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'atelier', 'atelier edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-local',
    label: 'Soundproof Podcast Studio — Local Growth Edition',
    category: 'Media',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio local', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'local', 'local growth edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-commerce',
    label: 'Soundproof Podcast Studio — Commerce Edition',
    category: 'Media',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio commerce', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'commerce', 'commerce edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-booking',
    label: 'Soundproof Podcast Studio — Booking Edition',
    category: 'Media',
    color: '#EF4444',
    bg: '#100808',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio booking', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'booking', 'booking edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-trust',
    label: 'Soundproof Podcast Studio — Trust Edition',
    category: 'Media',
    color: '#10B981',
    bg: '#080501',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio trust', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'trust', 'trust edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-magazine',
    label: 'Soundproof Podcast Studio — Magazine Edition',
    category: 'Media',
    color: '#F472B6',
    bg: '#031316',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio magazine', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'magazine', 'magazine edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-soundproof-podcast-studio-enterprise',
    label: 'Soundproof Podcast Studio — Enterprise Edition',
    category: 'Media',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['media', 'soundproof podcast studio', 'soundproof podcast studio enterprise', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes'],
    keywords: ['media', 'soundproof podcast studio', 'enterprise', 'enterprise edition', 'rooms', 'gear', 'packages', 'shows', 'book', 'acoustic rooms', 'multi-cam setup', 'editing desk', 'show notes', 'publishing support'],
    description: 'Standalone unique Media website template for Soundproof Podcast Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-signal',
    label: 'School Transport Tracking — Signal Edition',
    category: 'SafetyTech',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking signal', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'signal', 'signal edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-atelier',
    label: 'School Transport Tracking — Atelier Edition',
    category: 'SafetyTech',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking atelier', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'atelier', 'atelier edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-local',
    label: 'School Transport Tracking — Local Growth Edition',
    category: 'SafetyTech',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking local', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'local', 'local growth edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-commerce',
    label: 'School Transport Tracking — Commerce Edition',
    category: 'SafetyTech',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking commerce', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'commerce', 'commerce edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-booking',
    label: 'School Transport Tracking — Booking Edition',
    category: 'SafetyTech',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking booking', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'booking', 'booking edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-trust',
    label: 'School Transport Tracking — Trust Edition',
    category: 'SafetyTech',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking trust', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'trust', 'trust edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
