// Auto-split chunk 6 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_06: WebsiteTemplate[] = [
  {
    id: 'bsx-warehouse-automation-saas-atelier',
    label: 'Warehouse Automation SaaS — Atelier Edition',
    category: 'SaaS',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas atelier', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'atelier', 'atelier edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-local',
    label: 'Warehouse Automation SaaS — Local Growth Edition',
    category: 'SaaS',
    color: '#FFD166',
    bg: '#101112',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas local', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'local', 'local growth edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-commerce',
    label: 'Warehouse Automation SaaS — Commerce Edition',
    category: 'SaaS',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas commerce', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'commerce', 'commerce edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-booking',
    label: 'Warehouse Automation SaaS — Booking Edition',
    category: 'SaaS',
    color: '#118AB2',
    bg: '#100808',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas booking', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'booking', 'booking edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-trust',
    label: 'Warehouse Automation SaaS — Trust Edition',
    category: 'SaaS',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas trust', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'trust', 'trust edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-magazine',
    label: 'Warehouse Automation SaaS — Magazine Edition',
    category: 'SaaS',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas magazine', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'magazine', 'magazine edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-enterprise',
    label: 'Warehouse Automation SaaS — Enterprise Edition',
    category: 'SaaS',
    color: '#F97316',
    bg: '#09111f',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas enterprise', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'enterprise', 'enterprise edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-signal',
    label: 'Private Tutoring Collective — Signal Edition',
    category: 'Education',
    color: '#F97316',
    bg: '#09111f',
    industries: ['education', 'private tutoring collective', 'private tutoring collective signal', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'signal', 'signal edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-atelier',
    label: 'Private Tutoring Collective — Atelier Edition',
    category: 'Education',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['education', 'private tutoring collective', 'private tutoring collective atelier', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'atelier', 'atelier edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-local',
    label: 'Private Tutoring Collective — Local Growth Edition',
    category: 'Education',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['education', 'private tutoring collective', 'private tutoring collective local', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'local', 'local growth edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-commerce',
    label: 'Private Tutoring Collective — Commerce Edition',
    category: 'Education',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['education', 'private tutoring collective', 'private tutoring collective commerce', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'commerce', 'commerce edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-booking',
    label: 'Private Tutoring Collective — Booking Edition',
    category: 'Education',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['education', 'private tutoring collective', 'private tutoring collective booking', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'booking', 'booking edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-trust',
    label: 'Private Tutoring Collective — Trust Edition',
    category: 'Education',
    color: '#EF4444',
    bg: '#120817',
    industries: ['education', 'private tutoring collective', 'private tutoring collective trust', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'trust', 'trust edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-magazine',
    label: 'Private Tutoring Collective — Magazine Edition',
    category: 'Education',
    color: '#10B981',
    bg: '#050313',
    industries: ['education', 'private tutoring collective', 'private tutoring collective magazine', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'magazine', 'magazine edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-tutoring-collective-enterprise',
    label: 'Private Tutoring Collective — Enterprise Edition',
    category: 'Education',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['education', 'private tutoring collective', 'private tutoring collective enterprise', 'verified tutors', 'student plans', 'parent reports', 'exam prep'],
    keywords: ['education', 'private tutoring collective', 'enterprise', 'enterprise edition', 'subjects', 'tutors', 'results', 'parents', 'demo class', 'verified tutors', 'student plans', 'parent reports', 'exam prep', 'demo classes'],
    description: 'Standalone unique Education website template for Private Tutoring Collective, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-signal',
    label: 'Senior Living Community — Signal Edition',
    category: 'Care',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['care', 'senior living community', 'senior living community signal', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'signal', 'signal edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-atelier',
    label: 'Senior Living Community — Atelier Edition',
    category: 'Care',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['care', 'senior living community', 'senior living community atelier', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'atelier', 'atelier edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-local',
    label: 'Senior Living Community — Local Growth Edition',
    category: 'Care',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['care', 'senior living community', 'senior living community local', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'local', 'local growth edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-commerce',
    label: 'Senior Living Community — Commerce Edition',
    category: 'Care',
    color: '#A3E635',
    bg: '#111827',
    industries: ['care', 'senior living community', 'senior living community commerce', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'commerce', 'commerce edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-booking',
    label: 'Senior Living Community — Booking Edition',
    category: 'Care',
    color: '#FB7185',
    bg: '#101112',
    industries: ['care', 'senior living community', 'senior living community booking', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'booking', 'booking edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-trust',
    label: 'Senior Living Community — Trust Edition',
    category: 'Care',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['care', 'senior living community', 'senior living community trust', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'trust', 'trust edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-magazine',
    label: 'Senior Living Community — Magazine Edition',
    category: 'Care',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['care', 'senior living community', 'senior living community magazine', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'magazine', 'magazine edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-senior-living-community-enterprise',
    label: 'Senior Living Community — Enterprise Edition',
    category: 'Care',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['care', 'senior living community', 'senior living community enterprise', 'assisted living', 'medical desk', 'activity clubs', 'family updates'],
    keywords: ['care', 'senior living community', 'enterprise', 'enterprise edition', 'residences', 'activities', 'dining', 'visit', 'assisted living', 'medical desk', 'activity clubs', 'family updates', 'secure campus'],
    description: 'Standalone unique Care website template for Senior Living Community, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-signal',
    label: 'Sports Injury Rehab — Signal Edition',
    category: 'Healthcare',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab signal', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'signal', 'signal edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-atelier',
    label: 'Sports Injury Rehab — Atelier Edition',
    category: 'Healthcare',
    color: '#FFD166',
    bg: '#031316',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab atelier', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'atelier', 'atelier edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-local',
    label: 'Sports Injury Rehab — Local Growth Edition',
    category: 'Healthcare',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab local', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'local', 'local growth edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-commerce',
    label: 'Sports Injury Rehab — Commerce Edition',
    category: 'Healthcare',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab commerce', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'commerce', 'commerce edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-booking',
    label: 'Sports Injury Rehab — Booking Edition',
    category: 'Healthcare',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab booking', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'booking', 'booking edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-trust',
    label: 'Sports Injury Rehab — Trust Edition',
    category: 'Healthcare',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab trust', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'trust', 'trust edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-magazine',
    label: 'Sports Injury Rehab — Magazine Edition',
    category: 'Healthcare',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab magazine', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'magazine', 'magazine edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-sports-injury-rehab-enterprise',
    label: 'Sports Injury Rehab — Enterprise Edition',
    category: 'Healthcare',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['healthcare', 'sports injury rehab', 'sports injury rehab enterprise', 'physio plans', 'return to sport', 'movement screening', 'rehab reports'],
    keywords: ['healthcare', 'sports injury rehab', 'enterprise', 'enterprise edition', 'treatments', 'therapists', 'recovery', 'athletes', 'book', 'physio plans', 'return to sport', 'movement screening', 'rehab reports', 'sports doctors'],
    description: 'Standalone unique Healthcare website template for Sports Injury Rehab, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-signal',
    label: 'Microfinance Branchless — Signal Edition',
    category: 'Finance',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless signal', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'signal', 'signal edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-atelier',
    label: 'Microfinance Branchless — Atelier Edition',
    category: 'Finance',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless atelier', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'atelier', 'atelier edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-local',
    label: 'Microfinance Branchless — Local Growth Edition',
    category: 'Finance',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless local', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'local', 'local growth edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-commerce',
    label: 'Microfinance Branchless — Commerce Edition',
    category: 'Finance',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless commerce', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'commerce', 'commerce edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-booking',
    label: 'Microfinance Branchless — Booking Edition',
    category: 'Finance',
    color: '#EF4444',
    bg: '#060606',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless booking', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'booking', 'booking edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-trust',
    label: 'Microfinance Branchless — Trust Edition',
    category: 'Finance',
    color: '#10B981',
    bg: '#111827',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless trust', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'trust', 'trust edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-magazine',
    label: 'Microfinance Branchless — Magazine Edition',
    category: 'Finance',
    color: '#F472B6',
    bg: '#101112',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless magazine', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'magazine', 'magazine edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microfinance-branchless-enterprise',
    label: 'Microfinance Branchless — Enterprise Edition',
    category: 'Finance',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['finance', 'microfinance branchless', 'microfinance branchless enterprise', 'field agents', 'small loans', 'repayment reminders', 'village groups'],
    keywords: ['finance', 'microfinance branchless', 'enterprise', 'enterprise edition', 'loans', 'agents', 'repayments', 'impact', 'apply', 'field agents', 'small loans', 'repayment reminders', 'village groups', 'impact reports'],
    description: 'Standalone unique Finance website template for Microfinance Branchless, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-signal',
    label: 'Hotel Management College — Signal Edition',
    category: 'Education',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['education', 'hotel management college', 'hotel management college signal', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'signal', 'signal edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-atelier',
    label: 'Hotel Management College — Atelier Edition',
    category: 'Education',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['education', 'hotel management college', 'hotel management college atelier', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'atelier', 'atelier edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-local',
    label: 'Hotel Management College — Local Growth Edition',
    category: 'Education',
    color: '#A3E635',
    bg: '#080501',
    industries: ['education', 'hotel management college', 'hotel management college local', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'local', 'local growth edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-commerce',
    label: 'Hotel Management College — Commerce Edition',
    category: 'Education',
    color: '#FB7185',
    bg: '#031316',
    industries: ['education', 'hotel management college', 'hotel management college commerce', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'commerce', 'commerce edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-booking',
    label: 'Hotel Management College — Booking Edition',
    category: 'Education',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['education', 'hotel management college', 'hotel management college booking', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'booking', 'booking edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-trust',
    label: 'Hotel Management College — Trust Edition',
    category: 'Education',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['education', 'hotel management college', 'hotel management college trust', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'trust', 'trust edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-magazine',
    label: 'Hotel Management College — Magazine Edition',
    category: 'Education',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['education', 'hotel management college', 'hotel management college magazine', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'magazine', 'magazine edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hotel-management-college-enterprise',
    label: 'Hotel Management College — Enterprise Edition',
    category: 'Education',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['education', 'hotel management college', 'hotel management college enterprise', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk'],
    keywords: ['education', 'hotel management college', 'enterprise', 'enterprise edition', 'courses', 'kitchens', 'placements', 'campus', 'apply', 'training kitchens', 'hotel internships', 'placement cells', 'mock front desk', 'student events'],
    description: 'Standalone unique Education website template for Hotel Management College, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-signal',
    label: 'Virtual Interior Designer — Signal Edition',
    category: 'DesignTech',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer signal', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'signal', 'signal edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-atelier',
    label: 'Virtual Interior Designer — Atelier Edition',
    category: 'DesignTech',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer atelier', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'atelier', 'atelier edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-local',
    label: 'Virtual Interior Designer — Local Growth Edition',
    category: 'DesignTech',
    color: '#118AB2',
    bg: '#120817',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer local', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'local', 'local growth edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-commerce',
    label: 'Virtual Interior Designer — Commerce Edition',
    category: 'DesignTech',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer commerce', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'commerce', 'commerce edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-booking',
    label: 'Virtual Interior Designer — Booking Edition',
    category: 'DesignTech',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer booking', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'booking', 'booking edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-trust',
    label: 'Virtual Interior Designer — Trust Edition',
    category: 'DesignTech',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer trust', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'trust', 'trust edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-magazine',
    label: 'Virtual Interior Designer — Magazine Edition',
    category: 'DesignTech',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer magazine', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'magazine', 'magazine edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-virtual-interior-designer-enterprise',
    label: 'Virtual Interior Designer — Enterprise Edition',
    category: 'DesignTech',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['designtech', 'virtual interior designer', 'virtual interior designer enterprise', 'online consults', '3d room plans', 'shopping lists', 'vendor links'],
    keywords: ['designtech', 'virtual interior designer', 'enterprise', 'enterprise edition', 'rooms', 'packages', 'moodboards', 'vendors', 'start', 'online consults', '3D room plans', 'shopping lists', 'vendor links', 'revision rounds'],
    description: 'Standalone unique DesignTech website template for Virtual Interior Designer, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-signal',
    label: 'Smart Parking System — Signal Edition',
    category: 'Mobility',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['mobility', 'smart parking system', 'smart parking system signal', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'signal', 'signal edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-atelier',
    label: 'Smart Parking System — Atelier Edition',
    category: 'Mobility',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['mobility', 'smart parking system', 'smart parking system atelier', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'atelier', 'atelier edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-local',
    label: 'Smart Parking System — Local Growth Edition',
    category: 'Mobility',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['mobility', 'smart parking system', 'smart parking system local', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'local', 'local growth edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-commerce',
    label: 'Smart Parking System — Commerce Edition',
    category: 'Mobility',
    color: '#EF4444',
    bg: '#100808',
    industries: ['mobility', 'smart parking system', 'smart parking system commerce', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'commerce', 'commerce edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-booking',
    label: 'Smart Parking System — Booking Edition',
    category: 'Mobility',
    color: '#10B981',
    bg: '#080501',
    industries: ['mobility', 'smart parking system', 'smart parking system booking', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'booking', 'booking edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-trust',
    label: 'Smart Parking System — Trust Edition',
    category: 'Mobility',
    color: '#F472B6',
    bg: '#031316',
    industries: ['mobility', 'smart parking system', 'smart parking system trust', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'trust', 'trust edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-magazine',
    label: 'Smart Parking System — Magazine Edition',
    category: 'Mobility',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['mobility', 'smart parking system', 'smart parking system magazine', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'magazine', 'magazine edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-parking-system-enterprise',
    label: 'Smart Parking System — Enterprise Edition',
    category: 'Mobility',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['mobility', 'smart parking system', 'smart parking system enterprise', 'slot sensors', 'anpr gates', 'parking app', 'wallet payments'],
    keywords: ['mobility', 'smart parking system', 'enterprise', 'enterprise edition', 'lots', 'sensors', 'payments', 'reports', 'demo', 'slot sensors', 'ANPR gates', 'parking app', 'wallet payments', 'operator reports'],
    description: 'Standalone unique Mobility website template for Smart Parking System, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-signal',
    label: 'Local Dairy Delivery — Signal Edition',
    category: 'Food',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['food', 'local dairy delivery', 'local dairy delivery signal', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'signal', 'signal edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-atelier',
    label: 'Local Dairy Delivery — Atelier Edition',
    category: 'Food',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['food', 'local dairy delivery', 'local dairy delivery atelier', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'atelier', 'atelier edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-local',
    label: 'Local Dairy Delivery — Local Growth Edition',
    category: 'Food',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['food', 'local dairy delivery', 'local dairy delivery local', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'local', 'local growth edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-commerce',
    label: 'Local Dairy Delivery — Commerce Edition',
    category: 'Food',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['food', 'local dairy delivery', 'local dairy delivery commerce', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'commerce', 'commerce edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-booking',
    label: 'Local Dairy Delivery — Booking Edition',
    category: 'Food',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['food', 'local dairy delivery', 'local dairy delivery booking', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'booking', 'booking edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-trust',
    label: 'Local Dairy Delivery — Trust Edition',
    category: 'Food',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['food', 'local dairy delivery', 'local dairy delivery trust', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'trust', 'trust edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-magazine',
    label: 'Local Dairy Delivery — Magazine Edition',
    category: 'Food',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['food', 'local dairy delivery', 'local dairy delivery magazine', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'magazine', 'magazine edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-local-dairy-delivery-enterprise',
    label: 'Local Dairy Delivery — Enterprise Edition',
    category: 'Food',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['food', 'local dairy delivery', 'local dairy delivery enterprise', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing'],
    keywords: ['food', 'local dairy delivery', 'enterprise', 'enterprise edition', 'products', 'farm', 'subscription', 'quality', 'subscribe', 'milk delivery', 'farm sourcing', 'subscription plans', 'quality testing', 'morning routes'],
    description: 'Standalone unique Food website template for Local Dairy Delivery, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-signal',
    label: 'Bespoke Tailoring House — Signal Edition',
    category: 'Fashion',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house signal', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'signal', 'signal edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-atelier',
    label: 'Bespoke Tailoring House — Atelier Edition',
    category: 'Fashion',
    color: '#118AB2',
    bg: '#060606',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house atelier', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'atelier', 'atelier edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-local',
    label: 'Bespoke Tailoring House — Local Growth Edition',
    category: 'Fashion',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house local', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'local', 'local growth edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-commerce',
    label: 'Bespoke Tailoring House — Commerce Edition',
    category: 'Fashion',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house commerce', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'commerce', 'commerce edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-booking',
    label: 'Bespoke Tailoring House — Booking Edition',
    category: 'Fashion',
    color: '#F97316',
    bg: '#100A04',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house booking', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'booking', 'booking edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-trust',
    label: 'Bespoke Tailoring House — Trust Edition',
    category: 'Fashion',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house trust', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'trust', 'trust edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-magazine',
    label: 'Bespoke Tailoring House — Magazine Edition',
    category: 'Fashion',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house magazine', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'magazine', 'magazine edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bespoke-tailoring-house-enterprise',
    label: 'Bespoke Tailoring House — Enterprise Edition',
    category: 'Fashion',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['fashion', 'bespoke tailoring house', 'bespoke tailoring house enterprise', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds'],
    keywords: ['fashion', 'bespoke tailoring house', 'enterprise', 'enterprise edition', 'suits', 'measurements', 'fabrics', 'appointments', 'book', 'custom suits', 'measurement profiles', 'fabric swatches', 'fitting rounds', 'occasion styling'],
    description: 'Standalone unique Fashion website template for Bespoke Tailoring House, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-signal',
    label: 'Green Building Consultants — Signal Edition',
    category: 'Sustainability',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['sustainability', 'green building consultants', 'green building consultants signal', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'signal', 'signal edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-atelier',
    label: 'Green Building Consultants — Atelier Edition',
    category: 'Sustainability',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['sustainability', 'green building consultants', 'green building consultants atelier', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'atelier', 'atelier edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-local',
    label: 'Green Building Consultants — Local Growth Edition',
    category: 'Sustainability',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['sustainability', 'green building consultants', 'green building consultants local', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'local', 'local growth edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-commerce',
    label: 'Green Building Consultants — Commerce Edition',
    category: 'Sustainability',
    color: '#10B981',
    bg: '#010A05',
    industries: ['sustainability', 'green building consultants', 'green building consultants commerce', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'commerce', 'commerce edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-booking',
    label: 'Green Building Consultants — Booking Edition',
    category: 'Sustainability',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['sustainability', 'green building consultants', 'green building consultants booking', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'booking', 'booking edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-trust',
    label: 'Green Building Consultants — Trust Edition',
    category: 'Sustainability',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['sustainability', 'green building consultants', 'green building consultants trust', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'trust', 'trust edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-magazine',
    label: 'Green Building Consultants — Magazine Edition',
    category: 'Sustainability',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['sustainability', 'green building consultants', 'green building consultants magazine', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'magazine', 'magazine edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-green-building-consultants-enterprise',
    label: 'Green Building Consultants — Enterprise Edition',
    category: 'Sustainability',
    color: '#A3E635',
    bg: '#050313',
    industries: ['sustainability', 'green building consultants', 'green building consultants enterprise', 'energy audits', 'leed support', 'water strategy', 'materials review'],
    keywords: ['sustainability', 'green building consultants', 'enterprise', 'enterprise edition', 'audits', 'design', 'certification', 'projects', 'consult', 'energy audits', 'LEED support', 'water strategy', 'materials review', 'carbon reports'],
    description: 'Standalone unique Sustainability website template for Green Building Consultants, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-signal',
    label: 'AI Video Ad Maker — Signal Edition',
    category: 'AI Creative',
    color: '#A3E635',
    bg: '#050313',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker signal', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'signal', 'signal edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-atelier',
    label: 'AI Video Ad Maker — Atelier Edition',
    category: 'AI Creative',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker atelier', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'atelier', 'atelier edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-local',
    label: 'AI Video Ad Maker — Local Growth Edition',
    category: 'AI Creative',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker local', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'local', 'local growth edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-commerce',
    label: 'AI Video Ad Maker — Commerce Edition',
    category: 'AI Creative',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker commerce', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'commerce', 'commerce edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-booking',
    label: 'AI Video Ad Maker — Booking Edition',
    category: 'AI Creative',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker booking', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'booking', 'booking edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-trust',
    label: 'AI Video Ad Maker — Trust Edition',
    category: 'AI Creative',
    color: '#FFD166',
    bg: '#101112',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker trust', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'trust', 'trust edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-magazine',
    label: 'AI Video Ad Maker — Magazine Edition',
    category: 'AI Creative',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker magazine', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'magazine', 'magazine edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-video-ad-maker-enterprise',
    label: 'AI Video Ad Maker — Enterprise Edition',
    category: 'AI Creative',
    color: '#118AB2',
    bg: '#100808',
    industries: ['ai creative', 'ai video ad maker', 'ai video ad maker enterprise', 'storyboards', 'asset search', 'motion templates', 'render queue'],
    keywords: ['ai creative', 'ai video ad maker', 'enterprise', 'enterprise edition', 'scripts', 'assets', 'templates', 'rendering', 'generate', 'storyboards', 'asset search', 'motion templates', 'render queue', 'cost tracking'],
    description: 'Standalone unique AI Creative website template for AI Video Ad Maker, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-signal',
    label: 'DevOps Monitoring Platform — Signal Edition',
    category: 'SaaS',
    color: '#118AB2',
    bg: '#100808',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform signal', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'signal', 'signal edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-atelier',
    label: 'DevOps Monitoring Platform — Atelier Edition',
    category: 'SaaS',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform atelier', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'atelier', 'atelier edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-local',
    label: 'DevOps Monitoring Platform — Local Growth Edition',
    category: 'SaaS',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform local', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'local', 'local growth edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-commerce',
    label: 'DevOps Monitoring Platform — Commerce Edition',
    category: 'SaaS',
    color: '#F97316',
    bg: '#09111f',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform commerce', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'commerce', 'commerce edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-booking',
    label: 'DevOps Monitoring Platform — Booking Edition',
    category: 'SaaS',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform booking', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'booking', 'booking edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-trust',
    label: 'DevOps Monitoring Platform — Trust Edition',
    category: 'SaaS',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform trust', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'trust', 'trust edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-magazine',
    label: 'DevOps Monitoring Platform — Magazine Edition',
    category: 'SaaS',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform magazine', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'magazine', 'magazine edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-devops-monitoring-platform-enterprise',
    label: 'DevOps Monitoring Platform — Enterprise Edition',
    category: 'SaaS',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['saas', 'devops monitoring platform', 'devops monitoring platform enterprise', 'uptime checks', 'log search', 'incident rooms', 'team alerts'],
    keywords: ['saas', 'devops monitoring platform', 'enterprise', 'enterprise edition', 'metrics', 'alerts', 'incidents', 'integrations', 'demo', 'uptime checks', 'log search', 'incident rooms', 'team alerts', 'status pages'],
    description: 'Standalone unique SaaS website template for DevOps Monitoring Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-signal',
    label: 'WhatsApp CRM Platform — Signal Edition',
    category: 'SaaS',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform signal', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'signal', 'signal edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-atelier',
    label: 'WhatsApp CRM Platform — Atelier Edition',
    category: 'SaaS',
    color: '#EF4444',
    bg: '#120817',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform atelier', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'atelier', 'atelier edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-local',
    label: 'WhatsApp CRM Platform — Local Growth Edition',
    category: 'SaaS',
    color: '#10B981',
    bg: '#050313',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform local', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'local', 'local growth edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-commerce',
    label: 'WhatsApp CRM Platform — Commerce Edition',
    category: 'SaaS',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform commerce', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'commerce', 'commerce edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-booking',
    label: 'WhatsApp CRM Platform — Booking Edition',
    category: 'SaaS',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform booking', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'booking', 'booking edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-trust',
    label: 'WhatsApp CRM Platform — Trust Edition',
    category: 'SaaS',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform trust', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'trust', 'trust edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-magazine',
    label: 'WhatsApp CRM Platform — Magazine Edition',
    category: 'SaaS',
    color: '#A3E635',
    bg: '#111827',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform magazine', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'magazine', 'magazine edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-whatsapp-crm-platform-enterprise',
    label: 'WhatsApp CRM Platform — Enterprise Edition',
    category: 'SaaS',
    color: '#FB7185',
    bg: '#101112',
    industries: ['saas', 'whatsapp crm platform', 'whatsapp crm platform enterprise', 'shared inbox', 'approved templates', 'lead tags', 'agent routing'],
    keywords: ['saas', 'whatsapp crm platform', 'enterprise', 'enterprise edition', 'inbox', 'broadcasts', 'templates', 'reports', 'demo', 'shared inbox', 'approved templates', 'lead tags', 'agent routing', 'campaign reports'],
    description: 'Standalone unique SaaS website template for WhatsApp CRM Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-signal',
    label: 'Pharma Cold Storage — Signal Edition',
    category: 'Logistics',
    color: '#FB7185',
    bg: '#101112',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage signal', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'signal', 'signal edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-atelier',
    label: 'Pharma Cold Storage — Atelier Edition',
    category: 'Logistics',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage atelier', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'atelier', 'atelier edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-local',
    label: 'Pharma Cold Storage — Local Growth Edition',
    category: 'Logistics',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage local', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'local', 'local growth edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-commerce',
    label: 'Pharma Cold Storage — Commerce Edition',
    category: 'Logistics',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage commerce', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'commerce', 'commerce edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
