// Auto-split chunk 8 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_08: WebsiteTemplate[] = [
  {
    id: 'bsx-rera-real-estate-advisory-enterprise',
    label: 'RERA Real Estate Advisory — Enterprise Edition',
    category: 'Real Estate',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory enterprise', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'enterprise', 'enterprise edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-signal',
    label: 'Adaptive Learning SaaS — Signal Edition',
    category: 'EdTech',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas signal', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'signal', 'signal edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-atelier',
    label: 'Adaptive Learning SaaS — Atelier Edition',
    category: 'EdTech',
    color: '#118AB2',
    bg: '#120817',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas atelier', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'atelier', 'atelier edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-local',
    label: 'Adaptive Learning SaaS — Local Growth Edition',
    category: 'EdTech',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas local', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'local', 'local growth edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-commerce',
    label: 'Adaptive Learning SaaS — Commerce Edition',
    category: 'EdTech',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas commerce', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'commerce', 'commerce edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-booking',
    label: 'Adaptive Learning SaaS — Booking Edition',
    category: 'EdTech',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas booking', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'booking', 'booking edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-trust',
    label: 'Adaptive Learning SaaS — Trust Edition',
    category: 'EdTech',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas trust', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'trust', 'trust edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-magazine',
    label: 'Adaptive Learning SaaS — Magazine Edition',
    category: 'EdTech',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas magazine', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'magazine', 'magazine edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-adaptive-learning-saas-enterprise',
    label: 'Adaptive Learning SaaS — Enterprise Edition',
    category: 'EdTech',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['edtech', 'adaptive learning saas', 'adaptive learning saas enterprise', 'personalised paths', 'ai tutor', 'teacher dashboard', 'parent insights'],
    keywords: ['edtech', 'adaptive learning saas', 'enterprise', 'enterprise edition', 'lessons', 'ai tutor', 'progress', 'schools', 'demo', 'personalised paths', 'AI tutor', 'teacher dashboard', 'parent insights', 'school rollout'],
    description: 'Standalone unique EdTech website template for Adaptive Learning SaaS, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-signal',
    label: 'Home Health Nursing — Signal Edition',
    category: 'Care',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['care', 'home health nursing', 'home health nursing signal', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'signal', 'signal edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-atelier',
    label: 'Home Health Nursing — Atelier Edition',
    category: 'Care',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['care', 'home health nursing', 'home health nursing atelier', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'atelier', 'atelier edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-local',
    label: 'Home Health Nursing — Local Growth Edition',
    category: 'Care',
    color: '#EF4444',
    bg: '#100808',
    industries: ['care', 'home health nursing', 'home health nursing local', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'local', 'local growth edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-commerce',
    label: 'Home Health Nursing — Commerce Edition',
    category: 'Care',
    color: '#10B981',
    bg: '#080501',
    industries: ['care', 'home health nursing', 'home health nursing commerce', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'commerce', 'commerce edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-booking',
    label: 'Home Health Nursing — Booking Edition',
    category: 'Care',
    color: '#F472B6',
    bg: '#031316',
    industries: ['care', 'home health nursing', 'home health nursing booking', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'booking', 'booking edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-trust',
    label: 'Home Health Nursing — Trust Edition',
    category: 'Care',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['care', 'home health nursing', 'home health nursing trust', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'trust', 'trust edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-magazine',
    label: 'Home Health Nursing — Magazine Edition',
    category: 'Care',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['care', 'home health nursing', 'home health nursing magazine', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'magazine', 'magazine edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-home-health-nursing-enterprise',
    label: 'Home Health Nursing — Enterprise Edition',
    category: 'Care',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['care', 'home health nursing', 'home health nursing enterprise', 'trained nurses', 'care schedules', 'medical equipment', 'family reports'],
    keywords: ['care', 'home health nursing', 'enterprise', 'enterprise edition', 'care plans', 'nurses', 'equipment', 'family updates', 'book', 'trained nurses', 'care schedules', 'medical equipment', 'family reports', 'emergency support'],
    description: 'Standalone unique Care website template for Home Health Nursing, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-signal',
    label: 'Luxury Car Detailing Studio — Signal Edition',
    category: 'Auto',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio signal', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'signal', 'signal edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-atelier',
    label: 'Luxury Car Detailing Studio — Atelier Edition',
    category: 'Auto',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio atelier', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'atelier', 'atelier edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-local',
    label: 'Luxury Car Detailing Studio — Local Growth Edition',
    category: 'Auto',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio local', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'local', 'local growth edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-commerce',
    label: 'Luxury Car Detailing Studio — Commerce Edition',
    category: 'Auto',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio commerce', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'commerce', 'commerce edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-booking',
    label: 'Luxury Car Detailing Studio — Booking Edition',
    category: 'Auto',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio booking', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'booking', 'booking edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-trust',
    label: 'Luxury Car Detailing Studio — Trust Edition',
    category: 'Auto',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio trust', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'trust', 'trust edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-magazine',
    label: 'Luxury Car Detailing Studio — Magazine Edition',
    category: 'Auto',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio magazine', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'magazine', 'magazine edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-car-detailing-enterprise',
    label: 'Luxury Car Detailing Studio — Enterprise Edition',
    category: 'Auto',
    color: '#118AB2',
    bg: '#060606',
    industries: ['auto', 'luxury car detailing studio', 'luxury car detailing studio enterprise', 'ceramic coating', 'paint correction', 'ppf film', 'studio lighting'],
    keywords: ['auto', 'luxury car detailing studio', 'enterprise', 'enterprise edition', 'services', 'coatings', 'studio', 'results', 'book', 'ceramic coating', 'paint correction', 'PPF film', 'studio lighting', 'maintenance plans'],
    description: 'Standalone unique Auto website template for Luxury Car Detailing Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-signal',
    label: 'Community Sports Club — Signal Edition',
    category: 'Sports',
    color: '#118AB2',
    bg: '#060606',
    industries: ['sports', 'community sports club', 'community sports club signal', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'signal', 'signal edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-atelier',
    label: 'Community Sports Club — Atelier Edition',
    category: 'Sports',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['sports', 'community sports club', 'community sports club atelier', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'atelier', 'atelier edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-local',
    label: 'Community Sports Club — Local Growth Edition',
    category: 'Sports',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['sports', 'community sports club', 'community sports club local', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'local', 'local growth edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-commerce',
    label: 'Community Sports Club — Commerce Edition',
    category: 'Sports',
    color: '#F97316',
    bg: '#100A04',
    industries: ['sports', 'community sports club', 'community sports club commerce', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'commerce', 'commerce edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-booking',
    label: 'Community Sports Club — Booking Edition',
    category: 'Sports',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['sports', 'community sports club', 'community sports club booking', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'booking', 'booking edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-trust',
    label: 'Community Sports Club — Trust Edition',
    category: 'Sports',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['sports', 'community sports club', 'community sports club trust', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'trust', 'trust edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-magazine',
    label: 'Community Sports Club — Magazine Edition',
    category: 'Sports',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['sports', 'community sports club', 'community sports club magazine', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'magazine', 'magazine edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-community-sports-club-enterprise',
    label: 'Community Sports Club — Enterprise Edition',
    category: 'Sports',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['sports', 'community sports club', 'community sports club enterprise', 'multi-sport courts', 'coach sessions', 'league tables', 'member app'],
    keywords: ['sports', 'community sports club', 'enterprise', 'enterprise edition', 'facilities', 'coaches', 'leagues', 'membership', 'join', 'multi-sport courts', 'coach sessions', 'league tables', 'member app', 'tournament calendar'],
    description: 'Standalone unique Sports website template for Community Sports Club, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-signal',
    label: 'Bamboo Home Products — Signal Edition',
    category: 'Sustainable Retail',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products signal', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'signal', 'signal edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-atelier',
    label: 'Bamboo Home Products — Atelier Edition',
    category: 'Sustainable Retail',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products atelier', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'atelier', 'atelier edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-local',
    label: 'Bamboo Home Products — Local Growth Edition',
    category: 'Sustainable Retail',
    color: '#10B981',
    bg: '#010A05',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products local', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'local', 'local growth edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-commerce',
    label: 'Bamboo Home Products — Commerce Edition',
    category: 'Sustainable Retail',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products commerce', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'commerce', 'commerce edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-booking',
    label: 'Bamboo Home Products — Booking Edition',
    category: 'Sustainable Retail',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products booking', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'booking', 'booking edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-trust',
    label: 'Bamboo Home Products — Trust Edition',
    category: 'Sustainable Retail',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products trust', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'trust', 'trust edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-magazine',
    label: 'Bamboo Home Products — Magazine Edition',
    category: 'Sustainable Retail',
    color: '#A3E635',
    bg: '#050313',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products magazine', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'magazine', 'magazine edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-bamboo-home-products-enterprise',
    label: 'Bamboo Home Products — Enterprise Edition',
    category: 'Sustainable Retail',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['sustainable retail', 'bamboo home products', 'bamboo home products enterprise', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges'],
    keywords: ['sustainable retail', 'bamboo home products', 'enterprise', 'enterprise edition', 'products', 'materials', 'impact', 'wholesale', 'shop', 'bamboo fibre', 'home essentials', 'eco packaging', 'impact badges', 'wholesale orders'],
    description: 'Standalone unique Sustainable Retail website template for Bamboo Home Products, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-signal',
    label: 'Founder PR Advisory — Signal Edition',
    category: 'PR',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory signal', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'signal', 'signal edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-atelier',
    label: 'Founder PR Advisory — Atelier Edition',
    category: 'PR',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory atelier', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'atelier', 'atelier edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-local',
    label: 'Founder PR Advisory — Local Growth Edition',
    category: 'PR',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory local', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'local', 'local growth edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-commerce',
    label: 'Founder PR Advisory — Commerce Edition',
    category: 'PR',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory commerce', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'commerce', 'commerce edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-booking',
    label: 'Founder PR Advisory — Booking Edition',
    category: 'PR',
    color: '#FFD166',
    bg: '#101112',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory booking', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'booking', 'booking edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-trust',
    label: 'Founder PR Advisory — Trust Edition',
    category: 'PR',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory trust', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'trust', 'trust edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-magazine',
    label: 'Founder PR Advisory — Magazine Edition',
    category: 'PR',
    color: '#118AB2',
    bg: '#100808',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory magazine', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'magazine', 'magazine edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-founder-pr-advisory-enterprise',
    label: 'Founder PR Advisory — Enterprise Edition',
    category: 'PR',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['pr', 'founder pr advisory', 'founder pr advisory enterprise', 'founder narratives', 'media outreach', 'press kits', 'thought leadership'],
    keywords: ['pr', 'founder pr advisory', 'enterprise', 'enterprise edition', 'positioning', 'media', 'stories', 'proof', 'consult', 'founder narratives', 'media outreach', 'press kits', 'thought leadership', 'reputation tracking'],
    description: 'Standalone unique PR website template for Founder PR Advisory, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-signal',
    label: 'Industrial HVAC Company — Signal Edition',
    category: 'Building Services',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company signal', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'signal', 'signal edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-atelier',
    label: 'Industrial HVAC Company — Atelier Edition',
    category: 'Building Services',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company atelier', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'atelier', 'atelier edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-local',
    label: 'Industrial HVAC Company — Local Growth Edition',
    category: 'Building Services',
    color: '#F97316',
    bg: '#09111f',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company local', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'local', 'local growth edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-commerce',
    label: 'Industrial HVAC Company — Commerce Edition',
    category: 'Building Services',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company commerce', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'commerce', 'commerce edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-booking',
    label: 'Industrial HVAC Company — Booking Edition',
    category: 'Building Services',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company booking', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'booking', 'booking edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-trust',
    label: 'Industrial HVAC Company — Trust Edition',
    category: 'Building Services',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company trust', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'trust', 'trust edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-magazine',
    label: 'Industrial HVAC Company — Magazine Edition',
    category: 'Building Services',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company magazine', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'magazine', 'magazine edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-hvac-company-enterprise',
    label: 'Industrial HVAC Company — Enterprise Edition',
    category: 'Building Services',
    color: '#EF4444',
    bg: '#120817',
    industries: ['building services', 'industrial hvac company', 'industrial hvac company enterprise', 'chiller systems', 'duct design', 'amc teams', 'energy savings'],
    keywords: ['building services', 'industrial hvac company', 'enterprise', 'enterprise edition', 'solutions', 'projects', 'maintenance', 'energy', 'quote', 'chiller systems', 'duct design', 'AMC teams', 'energy savings', 'site audits'],
    description: 'Standalone unique Building Services website template for Industrial HVAC Company, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-signal',
    label: 'Telecom Tower Services — Signal Edition',
    category: 'Infrastructure',
    color: '#EF4444',
    bg: '#120817',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services signal', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'signal', 'signal edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-atelier',
    label: 'Telecom Tower Services — Atelier Edition',
    category: 'Infrastructure',
    color: '#10B981',
    bg: '#050313',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services atelier', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'atelier', 'atelier edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-local',
    label: 'Telecom Tower Services — Local Growth Edition',
    category: 'Infrastructure',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services local', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'local', 'local growth edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-commerce',
    label: 'Telecom Tower Services — Commerce Edition',
    category: 'Infrastructure',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services commerce', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'commerce', 'commerce edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-booking',
    label: 'Telecom Tower Services — Booking Edition',
    category: 'Infrastructure',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services booking', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'booking', 'booking edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-trust',
    label: 'Telecom Tower Services — Trust Edition',
    category: 'Infrastructure',
    color: '#A3E635',
    bg: '#111827',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services trust', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'trust', 'trust edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-magazine',
    label: 'Telecom Tower Services — Magazine Edition',
    category: 'Infrastructure',
    color: '#FB7185',
    bg: '#101112',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services magazine', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'magazine', 'magazine edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-telecom-tower-services-enterprise',
    label: 'Telecom Tower Services — Enterprise Edition',
    category: 'Infrastructure',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['infrastructure', 'telecom tower services', 'telecom tower services enterprise', 'tower erection', 'site maintenance', 'power backup', 'safety checks'],
    keywords: ['infrastructure', 'telecom tower services', 'enterprise', 'enterprise edition', 'sites', 'maintenance', 'safety', 'network', 'enquire', 'tower erection', 'site maintenance', 'power backup', 'safety checks', 'network reports'],
    description: 'Standalone unique Infrastructure website template for Telecom Tower Services, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-signal',
    label: 'Eco Tourism Camp — Signal Edition',
    category: 'Travel',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp signal', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'signal', 'signal edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-atelier',
    label: 'Eco Tourism Camp — Atelier Edition',
    category: 'Travel',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp atelier', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'atelier', 'atelier edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-local',
    label: 'Eco Tourism Camp — Local Growth Edition',
    category: 'Travel',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp local', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'local', 'local growth edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-commerce',
    label: 'Eco Tourism Camp — Commerce Edition',
    category: 'Travel',
    color: '#FFD166',
    bg: '#031316',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp commerce', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'commerce', 'commerce edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-booking',
    label: 'Eco Tourism Camp — Booking Edition',
    category: 'Travel',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp booking', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'booking', 'booking edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-trust',
    label: 'Eco Tourism Camp — Trust Edition',
    category: 'Travel',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp trust', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'trust', 'trust edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-magazine',
    label: 'Eco Tourism Camp — Magazine Edition',
    category: 'Travel',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp magazine', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'magazine', 'magazine edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-eco-tourism-camp-enterprise',
    label: 'Eco Tourism Camp — Enterprise Edition',
    category: 'Travel',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['travel', 'eco tourism camp', 'eco tourism camp enterprise', 'forest stays', 'guided trails', 'local food', 'eco rules'],
    keywords: ['travel', 'eco tourism camp', 'enterprise', 'enterprise edition', 'stays', 'trails', 'guides', 'impact', 'book', 'forest stays', 'guided trails', 'local food', 'eco rules', 'community impact'],
    description: 'Standalone unique Travel website template for Eco Tourism Camp, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-signal',
    label: 'AI Recruitment Screening — Signal Edition',
    category: 'HRTech',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening signal', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'signal', 'signal edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-atelier',
    label: 'AI Recruitment Screening — Atelier Edition',
    category: 'HRTech',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening atelier', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'atelier', 'atelier edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-local',
    label: 'AI Recruitment Screening — Local Growth Edition',
    category: 'HRTech',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening local', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'local', 'local growth edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-commerce',
    label: 'AI Recruitment Screening — Commerce Edition',
    category: 'HRTech',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening commerce', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'commerce', 'commerce edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-booking',
    label: 'AI Recruitment Screening — Booking Edition',
    category: 'HRTech',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening booking', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'booking', 'booking edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-trust',
    label: 'AI Recruitment Screening — Trust Edition',
    category: 'HRTech',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening trust', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'trust', 'trust edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-magazine',
    label: 'AI Recruitment Screening — Magazine Edition',
    category: 'HRTech',
    color: '#EF4444',
    bg: '#060606',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening magazine', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'magazine', 'magazine edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ai-recruitment-screening-enterprise',
    label: 'AI Recruitment Screening — Enterprise Edition',
    category: 'HRTech',
    color: '#10B981',
    bg: '#111827',
    industries: ['hrtech', 'ai recruitment screening', 'ai recruitment screening enterprise', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks'],
    keywords: ['hrtech', 'ai recruitment screening', 'enterprise', 'enterprise edition', 'screening', 'interviews', 'reports', 'bias controls', 'demo', 'resume scoring', 'interview kits', 'candidate reports', 'bias checks', 'ATS links'],
    description: 'Standalone unique HRTech website template for AI Recruitment Screening, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-signal',
    label: 'College Festival Portal — Signal Edition',
    category: 'Events',
    color: '#10B981',
    bg: '#111827',
    industries: ['events', 'college festival portal', 'college festival portal signal', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'signal', 'signal edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-atelier',
    label: 'College Festival Portal — Atelier Edition',
    category: 'Events',
    color: '#F472B6',
    bg: '#101112',
    industries: ['events', 'college festival portal', 'college festival portal atelier', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'atelier', 'atelier edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-local',
    label: 'College Festival Portal — Local Growth Edition',
    category: 'Events',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['events', 'college festival portal', 'college festival portal local', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'local', 'local growth edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-commerce',
    label: 'College Festival Portal — Commerce Edition',
    category: 'Events',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['events', 'college festival portal', 'college festival portal commerce', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'commerce', 'commerce edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-booking',
    label: 'College Festival Portal — Booking Edition',
    category: 'Events',
    color: '#A3E635',
    bg: '#080501',
    industries: ['events', 'college festival portal', 'college festival portal booking', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'booking', 'booking edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-trust',
    label: 'College Festival Portal — Trust Edition',
    category: 'Events',
    color: '#FB7185',
    bg: '#031316',
    industries: ['events', 'college festival portal', 'college festival portal trust', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'trust', 'trust edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-magazine',
    label: 'College Festival Portal — Magazine Edition',
    category: 'Events',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['events', 'college festival portal', 'college festival portal magazine', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'magazine', 'magazine edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-college-festival-portal-enterprise',
    label: 'College Festival Portal — Enterprise Edition',
    category: 'Events',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['events', 'college festival portal', 'college festival portal enterprise', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards'],
    keywords: ['events', 'college festival portal', 'enterprise', 'enterprise edition', 'competitions', 'sponsors', 'teams', 'register', 'competition pages', 'team entries', 'sponsor decks', 'leaderboards', 'event passes'],
    description: 'Standalone unique Events website template for College Festival Portal, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-signal',
    label: 'Premium Stationery Brand — Signal Edition',
    category: 'Retail',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand signal', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'signal', 'signal edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-atelier',
    label: 'Premium Stationery Brand — Atelier Edition',
    category: 'Retail',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand atelier', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'atelier', 'atelier edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-local',
    label: 'Premium Stationery Brand — Local Growth Edition',
    category: 'Retail',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand local', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'local', 'local growth edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-commerce',
    label: 'Premium Stationery Brand — Commerce Edition',
    category: 'Retail',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand commerce', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'commerce', 'commerce edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-booking',
    label: 'Premium Stationery Brand — Booking Edition',
    category: 'Retail',
    color: '#118AB2',
    bg: '#120817',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand booking', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'booking', 'booking edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-trust',
    label: 'Premium Stationery Brand — Trust Edition',
    category: 'Retail',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand trust', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'trust', 'trust edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-magazine',
    label: 'Premium Stationery Brand — Magazine Edition',
    category: 'Retail',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand magazine', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'magazine', 'magazine edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-stationery-brand-enterprise',
    label: 'Premium Stationery Brand — Enterprise Edition',
    category: 'Retail',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['retail', 'premium stationery brand', 'premium stationery brand enterprise', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs'],
    keywords: ['retail', 'premium stationery brand', 'enterprise', 'enterprise edition', 'products', 'design', 'bundles', 'corporate', 'shop', 'notebooks', 'desk sets', 'custom embossing', 'corporate packs', 'gift wrapping'],
    description: 'Standalone unique Retail website template for Premium Stationery Brand, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-signal',
    label: 'Medical Device Manufacturing — Signal Edition',
    category: 'Manufacturing',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing signal', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'signal', 'signal edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-atelier',
    label: 'Medical Device Manufacturing — Atelier Edition',
    category: 'Manufacturing',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing atelier', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'atelier', 'atelier edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-local',
    label: 'Medical Device Manufacturing — Local Growth Edition',
    category: 'Manufacturing',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing local', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'local', 'local growth edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-commerce',
    label: 'Medical Device Manufacturing — Commerce Edition',
    category: 'Manufacturing',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing commerce', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'commerce', 'commerce edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-booking',
    label: 'Medical Device Manufacturing — Booking Edition',
    category: 'Manufacturing',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing booking', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'booking', 'booking edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-trust',
    label: 'Medical Device Manufacturing — Trust Edition',
    category: 'Manufacturing',
    color: '#EF4444',
    bg: '#100808',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing trust', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'trust', 'trust edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-magazine',
    label: 'Medical Device Manufacturing — Magazine Edition',
    category: 'Manufacturing',
    color: '#10B981',
    bg: '#080501',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing magazine', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'magazine', 'magazine edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-medical-cannula-manufacturing-enterprise',
    label: 'Medical Device Manufacturing — Enterprise Edition',
    category: 'Manufacturing',
    color: '#F472B6',
    bg: '#031316',
    industries: ['manufacturing', 'medical device manufacturing', 'medical device manufacturing enterprise', 'medical devices', 'cleanroom units', 'sterility checks', 'iso records'],
    keywords: ['manufacturing', 'medical device manufacturing', 'enterprise', 'enterprise edition', 'products', 'cleanroom', 'quality', 'certifications', 'quote', 'medical devices', 'cleanroom units', 'sterility checks', 'ISO records', 'bulk supply'],
    description: 'Standalone unique Manufacturing website template for Medical Device Manufacturing, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-signal',
    label: 'Rainwater Project Company — Signal Edition',
    category: 'Sustainability',
    color: '#F472B6',
    bg: '#031316',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company signal', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'signal', 'signal edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-atelier',
    label: 'Rainwater Project Company — Atelier Edition',
    category: 'Sustainability',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company atelier', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'atelier', 'atelier edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-local',
    label: 'Rainwater Project Company — Local Growth Edition',
    category: 'Sustainability',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company local', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'local', 'local growth edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-commerce',
    label: 'Rainwater Project Company — Commerce Edition',
    category: 'Sustainability',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company commerce', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'commerce', 'commerce edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-booking',
    label: 'Rainwater Project Company — Booking Edition',
    category: 'Sustainability',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company booking', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'booking', 'booking edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-trust',
    label: 'Rainwater Project Company — Trust Edition',
    category: 'Sustainability',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company trust', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'trust', 'trust edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-magazine',
    label: 'Rainwater Project Company — Magazine Edition',
    category: 'Sustainability',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company magazine', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'magazine', 'magazine edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rainwater-project-company-enterprise',
    label: 'Rainwater Project Company — Enterprise Edition',
    category: 'Sustainability',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['sustainability', 'rainwater project company', 'rainwater project company enterprise', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan'],
    keywords: ['sustainability', 'rainwater project company', 'enterprise', 'enterprise edition', 'systems', 'projects', 'benefits', 'maintenance', 'estimate', 'collection systems', 'filtration tanks', 'site survey', 'maintenance plan', 'water savings'],
    description: 'Standalone unique Sustainability website template for Rainwater Project Company, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-signal',
    label: 'Private Detective Agency — Signal Edition',
    category: 'Investigation',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['investigation', 'private detective agency', 'private detective agency signal', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'signal', 'signal edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-atelier',
    label: 'Private Detective Agency — Atelier Edition',
    category: 'Investigation',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['investigation', 'private detective agency', 'private detective agency atelier', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'atelier', 'atelier edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
