// Auto-split chunk 2 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_02: WebsiteTemplate[] = [
  {
    id: 'property-management',
    label: 'Property Management',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["property management", "property management"],
    keywords: ["property", "management", "property management", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Property Management with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'real-estate-broker',
    label: 'Real Estate Broker',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["real estate broker", "estate broker"],
    keywords: ["real", "estate", "broker", "real estate broker", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Real Estate Broker with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'real-estate-premium',
    label: 'Real Estate Premium',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["real estate premium", "estate premium"],
    keywords: ["real", "estate", "premium", "real estate premium", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Real Estate Premium with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'recruitment-agency',
    label: 'Recruitment Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["recruitment agency", "recruitment agency"],
    keywords: ["recruitment", "agency", "recruitment agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Recruitment Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'repair-service',
    label: 'Repair Service',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["repair service", "repair service"],
    keywords: ["repair", "service", "repair service", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Repair Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'roofing-company',
    label: 'Roofing Company',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["roofing company", "roofing company"],
    keywords: ["roofing", "company", "roofing company", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Roofing Company with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'saree-store',
    label: 'Saree Store',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["saree store", "saree store"],
    keywords: ["saree", "store", "saree store", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Saree Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'school-website',
    label: 'School Website',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["school website", "school website"],
    keywords: ["school", "website", "school website", "education", "landing page", "business"],
    description: 'Responsive education website template for School Website with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'security-agency',
    label: 'Security Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["security agency", "security agency"],
    keywords: ["security", "agency", "security agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Security Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'seo-agency',
    label: 'SEO Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["seo agency", "seo agency"],
    keywords: ["seo", "agency", "seo agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for SEO Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'sneaker-store',
    label: 'Sneaker Store',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["sneaker store", "sneaker store"],
    keywords: ["sneaker", "store", "sneaker store", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Sneaker Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'social-media-agency',
    label: 'Social Media Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["social media agency", "media agency"],
    keywords: ["social", "media", "agency", "social media agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Social Media Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'software-company',
    label: 'Software Company',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["software company", "software company"],
    keywords: ["software", "company", "software company", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Software Company with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'sports-academy',
    label: 'Sports Academy',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["sports academy", "sports academy"],
    keywords: ["sports", "academy", "sports academy", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Sports Academy with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'sports-store',
    label: 'Sports Store',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["sports store", "sports store"],
    keywords: ["sports", "store", "sports store", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Sports Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'steel-supplier',
    label: 'Steel Supplier',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["steel supplier", "steel supplier"],
    keywords: ["steel", "supplier", "steel supplier", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Steel Supplier with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'stock-trading-coach',
    label: 'Stock Trading Coach',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["stock trading coach", "trading coach"],
    keywords: ["stock", "trading", "coach", "stock trading coach", "business", "website", "landing page"],
    description: 'Responsive business website template for Stock Trading Coach with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'streetwear-brand',
    label: 'Streetwear Brand',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["streetwear brand", "streetwear brand"],
    keywords: ["streetwear", "brand", "streetwear brand", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Streetwear Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'sweet-shop',
    label: 'Sweet Shop',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["sweet shop", "sweet shop"],
    keywords: ["sweet", "shop", "sweet shop", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Sweet Shop with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'tax-consultant',
    label: 'Tax Consultant',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["tax consultant", "tax consultant"],
    keywords: ["tax", "consultant", "tax consultant", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Tax Consultant with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'taxi-service',
    label: 'Taxi Service',
    category: 'Auto',
    color: '#FF4E00',
    bg: '#100402',
    industries: ["taxi service", "taxi service"],
    keywords: ["taxi", "service", "taxi service", "auto", "website", "landing page", "business"],
    description: 'Responsive auto website template for Taxi Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'tea-brand',
    label: 'Tea Brand',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["tea brand", "tea brand"],
    keywords: ["tea", "brand", "tea brand", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Tea Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'tent-house',
    label: 'Tent House',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["tent house", "tent house"],
    keywords: ["tent", "house", "tent house", "business", "website", "landing page"],
    description: 'Responsive business website template for Tent House with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'textile-manufacturer',
    label: 'Textile Manufacturer',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["textile manufacturer", "textile manufacturer"],
    keywords: ["textile", "manufacturer", "textile manufacturer", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Textile Manufacturer with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'theatre-group',
    label: 'Theatre Group',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["theatre group", "theatre group"],
    keywords: ["theatre", "group", "theatre group", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Theatre Group with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'tiles-showroom',
    label: 'Tiles Showroom',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["tiles showroom", "tiles showroom"],
    keywords: ["tiles", "showroom", "tiles showroom", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Tiles Showroom with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'toy-store',
    label: 'Toy Store',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["toy store", "toy store"],
    keywords: ["toy", "store", "toy store", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Toy Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'upsc-coaching',
    label: 'UPSC Coaching',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["upsc coaching", "upsc coaching"],
    keywords: ["upsc", "coaching", "upsc coaching", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for UPSC Coaching with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'vegan-cafe',
    label: 'Vegan Cafe',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["vegan cafe", "vegan cafe"],
    keywords: ["vegan", "cafe", "vegan cafe", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Vegan Cafe with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'veterinary-clinic',
    label: 'Veterinary Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["veterinary clinic", "veterinary clinic"],
    keywords: ["veterinary", "clinic", "veterinary clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Veterinary Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'video-production',
    label: 'Video Production',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["video production", "video production"],
    keywords: ["video", "production", "video production", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Video Production with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'warehouse-logistics',
    label: 'Warehouse Logistics',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["warehouse logistics", "warehouse logistics"],
    keywords: ["warehouse", "logistics", "warehouse logistics", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Warehouse Logistics with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'watch-brand',
    label: 'Watch Brand',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["watch brand", "watch brand"],
    keywords: ["watch", "brand", "watch brand", "business", "website", "landing page"],
    description: 'Responsive business website template for Watch Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'website-design-agency',
    label: 'Website Design Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["website design agency", "design agency"],
    keywords: ["website", "design", "agency", "website design agency", "landing page", "business"],
    description: 'Responsive agency website template for Website Design Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'wedding-planner-luxury',
    label: 'Wedding Planner Luxury',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["wedding planner luxury", "planner luxury"],
    keywords: ["wedding", "planner", "luxury", "wedding planner luxury", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Wedding Planner Luxury with conversion sections, visuals, service highlights and lead capture.',
  },
{
    id: 'bsx-neon-fintech-card-signal',
    label: 'Neon Fintech Card Platform — Signal Edition',
    category: 'FinTech',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform signal', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'signal', 'signal edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-atelier',
    label: 'Neon Fintech Card Platform — Atelier Edition',
    category: 'FinTech',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform atelier', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'atelier', 'atelier edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-local',
    label: 'Neon Fintech Card Platform — Local Growth Edition',
    category: 'FinTech',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform local', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'local', 'local growth edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-commerce',
    label: 'Neon Fintech Card Platform — Commerce Edition',
    category: 'FinTech',
    color: '#EF4444',
    bg: '#060606',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform commerce', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'commerce', 'commerce edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-booking',
    label: 'Neon Fintech Card Platform — Booking Edition',
    category: 'FinTech',
    color: '#10B981',
    bg: '#111827',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform booking', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'booking', 'booking edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-trust',
    label: 'Neon Fintech Card Platform — Trust Edition',
    category: 'FinTech',
    color: '#F472B6',
    bg: '#101112',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform trust', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'trust', 'trust edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-magazine',
    label: 'Neon Fintech Card Platform — Magazine Edition',
    category: 'FinTech',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform magazine', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'magazine', 'magazine edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-neon-fintech-card-enterprise',
    label: 'Neon Fintech Card Platform — Enterprise Edition',
    category: 'FinTech',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['fintech', 'neon fintech card platform', 'neon fintech card platform enterprise', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts'],
    keywords: ['fintech', 'neon fintech card platform', 'enterprise', 'enterprise edition', 'cards', 'limits', 'rewards', 'security', 'apply', 'virtual cards', 'spend controls', 'instant settlement', 'fraud alerts', 'merchant rewards'],
    description: 'Standalone unique FinTech website template for Neon Fintech Card Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-signal',
    label: 'Rural Clinic Network — Signal Edition',
    category: 'Healthcare',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network signal', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'signal', 'signal edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-atelier',
    label: 'Rural Clinic Network — Atelier Edition',
    category: 'Healthcare',
    color: '#A3E635',
    bg: '#080501',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network atelier', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'atelier', 'atelier edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-local',
    label: 'Rural Clinic Network — Local Growth Edition',
    category: 'Healthcare',
    color: '#FB7185',
    bg: '#031316',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network local', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'local', 'local growth edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-commerce',
    label: 'Rural Clinic Network — Commerce Edition',
    category: 'Healthcare',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network commerce', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'commerce', 'commerce edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-booking',
    label: 'Rural Clinic Network — Booking Edition',
    category: 'Healthcare',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network booking', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'booking', 'booking edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-trust',
    label: 'Rural Clinic Network — Trust Edition',
    category: 'Healthcare',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network trust', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'trust', 'trust edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-magazine',
    label: 'Rural Clinic Network — Magazine Edition',
    category: 'Healthcare',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network magazine', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'magazine', 'magazine edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rural-clinic-network-enterprise',
    label: 'Rural Clinic Network — Enterprise Edition',
    category: 'Healthcare',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['healthcare', 'rural clinic network', 'rural clinic network enterprise', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar'],
    keywords: ['healthcare', 'rural clinic network', 'enterprise', 'enterprise edition', 'clinics', 'doctors', 'camps', 'reports', 'book', 'teleconsult desks', 'medicine stock', 'lab pickup', 'health camp calendar', 'family records'],
    description: 'Standalone unique Healthcare website template for Rural Clinic Network, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-signal',
    label: 'Luxury Villa Rentals — Signal Edition',
    category: 'Travel',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals signal', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'signal', 'signal edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-atelier',
    label: 'Luxury Villa Rentals — Atelier Edition',
    category: 'Travel',
    color: '#118AB2',
    bg: '#120817',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals atelier', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'atelier', 'atelier edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-local',
    label: 'Luxury Villa Rentals — Local Growth Edition',
    category: 'Travel',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals local', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'local', 'local growth edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-commerce',
    label: 'Luxury Villa Rentals — Commerce Edition',
    category: 'Travel',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals commerce', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'commerce', 'commerce edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-booking',
    label: 'Luxury Villa Rentals — Booking Edition',
    category: 'Travel',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals booking', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'booking', 'booking edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-trust',
    label: 'Luxury Villa Rentals — Trust Edition',
    category: 'Travel',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals trust', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'trust', 'trust edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-magazine',
    label: 'Luxury Villa Rentals — Magazine Edition',
    category: 'Travel',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals magazine', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'magazine', 'magazine edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-villa-rentals-enterprise',
    label: 'Luxury Villa Rentals — Enterprise Edition',
    category: 'Travel',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['travel', 'luxury villa rentals', 'luxury villa rentals enterprise', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays'],
    keywords: ['travel', 'luxury villa rentals', 'enterprise', 'enterprise edition', 'villas', 'experiences', 'concierge', 'reviews', 'reserve', 'private pools', 'chef service', 'chauffeur pickup', 'curated stays', 'guest verification'],
    description: 'Standalone unique Travel website template for Luxury Villa Rentals, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-signal',
    label: 'Smart Farming IoT — Signal Edition',
    category: 'AgriTech',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['agritech', 'smart farming iot', 'smart farming iot signal', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'signal', 'signal edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-atelier',
    label: 'Smart Farming IoT — Atelier Edition',
    category: 'AgriTech',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['agritech', 'smart farming iot', 'smart farming iot atelier', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'atelier', 'atelier edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-local',
    label: 'Smart Farming IoT — Local Growth Edition',
    category: 'AgriTech',
    color: '#EF4444',
    bg: '#100808',
    industries: ['agritech', 'smart farming iot', 'smart farming iot local', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'local', 'local growth edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-commerce',
    label: 'Smart Farming IoT — Commerce Edition',
    category: 'AgriTech',
    color: '#10B981',
    bg: '#080501',
    industries: ['agritech', 'smart farming iot', 'smart farming iot commerce', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'commerce', 'commerce edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-booking',
    label: 'Smart Farming IoT — Booking Edition',
    category: 'AgriTech',
    color: '#F472B6',
    bg: '#031316',
    industries: ['agritech', 'smart farming iot', 'smart farming iot booking', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'booking', 'booking edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-trust',
    label: 'Smart Farming IoT — Trust Edition',
    category: 'AgriTech',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['agritech', 'smart farming iot', 'smart farming iot trust', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'trust', 'trust edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-magazine',
    label: 'Smart Farming IoT — Magazine Edition',
    category: 'AgriTech',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['agritech', 'smart farming iot', 'smart farming iot magazine', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'magazine', 'magazine edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-farming-iot-enterprise',
    label: 'Smart Farming IoT — Enterprise Edition',
    category: 'AgriTech',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['agritech', 'smart farming iot', 'smart farming iot enterprise', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control'],
    keywords: ['agritech', 'smart farming iot', 'enterprise', 'enterprise edition', 'sensors', 'crops', 'dashboard', 'impact', 'demo', 'soil sensors', 'weather alerts', 'crop analytics', 'irrigation control', 'yield reports'],
    description: 'Standalone unique AgriTech website template for Smart Farming IoT, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-signal',
    label: 'Marine Logistics Operator — Signal Edition',
    category: 'Logistics',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator signal', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'signal', 'signal edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-atelier',
    label: 'Marine Logistics Operator — Atelier Edition',
    category: 'Logistics',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator atelier', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'atelier', 'atelier edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-local',
    label: 'Marine Logistics Operator — Local Growth Edition',
    category: 'Logistics',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator local', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'local', 'local growth edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-commerce',
    label: 'Marine Logistics Operator — Commerce Edition',
    category: 'Logistics',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator commerce', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'commerce', 'commerce edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-booking',
    label: 'Marine Logistics Operator — Booking Edition',
    category: 'Logistics',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator booking', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'booking', 'booking edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-trust',
    label: 'Marine Logistics Operator — Trust Edition',
    category: 'Logistics',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator trust', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'trust', 'trust edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-magazine',
    label: 'Marine Logistics Operator — Magazine Edition',
    category: 'Logistics',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator magazine', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'magazine', 'magazine edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-marine-logistics-enterprise',
    label: 'Marine Logistics Operator — Enterprise Edition',
    category: 'Logistics',
    color: '#118AB2',
    bg: '#060606',
    industries: ['logistics', 'marine logistics operator', 'marine logistics operator enterprise', 'port schedules', 'container status', 'cold cargo', 'customs desk'],
    keywords: ['logistics', 'marine logistics operator', 'enterprise', 'enterprise edition', 'routes', 'fleet', 'tracking', 'customs', 'quote', 'port schedules', 'container status', 'cold cargo', 'customs desk', 'insurance support'],
    description: 'Standalone unique Logistics website template for Marine Logistics Operator, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-signal',
    label: 'Digital Law Chambers — Signal Edition',
    category: 'Legal',
    color: '#118AB2',
    bg: '#060606',
    industries: ['legal', 'digital law chambers', 'digital law chambers signal', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'signal', 'signal edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-atelier',
    label: 'Digital Law Chambers — Atelier Edition',
    category: 'Legal',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['legal', 'digital law chambers', 'digital law chambers atelier', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'atelier', 'atelier edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-local',
    label: 'Digital Law Chambers — Local Growth Edition',
    category: 'Legal',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['legal', 'digital law chambers', 'digital law chambers local', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'local', 'local growth edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-commerce',
    label: 'Digital Law Chambers — Commerce Edition',
    category: 'Legal',
    color: '#F97316',
    bg: '#100A04',
    industries: ['legal', 'digital law chambers', 'digital law chambers commerce', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'commerce', 'commerce edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-booking',
    label: 'Digital Law Chambers — Booking Edition',
    category: 'Legal',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['legal', 'digital law chambers', 'digital law chambers booking', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'booking', 'booking edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-trust',
    label: 'Digital Law Chambers — Trust Edition',
    category: 'Legal',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['legal', 'digital law chambers', 'digital law chambers trust', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'trust', 'trust edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-magazine',
    label: 'Digital Law Chambers — Magazine Edition',
    category: 'Legal',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['legal', 'digital law chambers', 'digital law chambers magazine', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'magazine', 'magazine edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-digital-law-chambers-enterprise',
    label: 'Digital Law Chambers — Enterprise Edition',
    category: 'Legal',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['legal', 'digital law chambers', 'digital law chambers enterprise', 'contract review', 'startup filings', 'ip protection', 'dispute notices'],
    keywords: ['legal', 'digital law chambers', 'enterprise', 'enterprise edition', 'practice', 'documents', 'cases', 'team', 'consult', 'contract review', 'startup filings', 'IP protection', 'dispute notices', 'compliance calendar'],
    description: 'Standalone unique Legal website template for Digital Law Chambers, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-signal',
    label: 'Premium Salon Suite — Signal Edition',
    category: 'Beauty',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['beauty', 'premium salon suite', 'premium salon suite signal', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'signal', 'signal edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-atelier',
    label: 'Premium Salon Suite — Atelier Edition',
    category: 'Beauty',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['beauty', 'premium salon suite', 'premium salon suite atelier', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'atelier', 'atelier edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-local',
    label: 'Premium Salon Suite — Local Growth Edition',
    category: 'Beauty',
    color: '#10B981',
    bg: '#010A05',
    industries: ['beauty', 'premium salon suite', 'premium salon suite local', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'local', 'local growth edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-commerce',
    label: 'Premium Salon Suite — Commerce Edition',
    category: 'Beauty',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['beauty', 'premium salon suite', 'premium salon suite commerce', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'commerce', 'commerce edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-booking',
    label: 'Premium Salon Suite — Booking Edition',
    category: 'Beauty',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['beauty', 'premium salon suite', 'premium salon suite booking', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'booking', 'booking edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-trust',
    label: 'Premium Salon Suite — Trust Edition',
    category: 'Beauty',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['beauty', 'premium salon suite', 'premium salon suite trust', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'trust', 'trust edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-magazine',
    label: 'Premium Salon Suite — Magazine Edition',
    category: 'Beauty',
    color: '#A3E635',
    bg: '#050313',
    industries: ['beauty', 'premium salon suite', 'premium salon suite magazine', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'magazine', 'magazine edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-salon-suite-enterprise',
    label: 'Premium Salon Suite — Enterprise Edition',
    category: 'Beauty',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['beauty', 'premium salon suite', 'premium salon suite enterprise', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans'],
    keywords: ['beauty', 'premium salon suite', 'enterprise', 'enterprise edition', 'looks', 'artists', 'packages', 'results', 'book', 'hair rituals', 'bridal looks', 'skin prep', 'membership plans', 'before after gallery'],
    description: 'Standalone unique Beauty website template for Premium Salon Suite, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-signal',
    label: 'Urban Rooftop Cafe — Signal Edition',
    category: 'Food',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe signal', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'signal', 'signal edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-atelier',
    label: 'Urban Rooftop Cafe — Atelier Edition',
    category: 'Food',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe atelier', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'atelier', 'atelier edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-local',
    label: 'Urban Rooftop Cafe — Local Growth Edition',
    category: 'Food',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe local', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'local', 'local growth edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-commerce',
    label: 'Urban Rooftop Cafe — Commerce Edition',
    category: 'Food',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe commerce', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'commerce', 'commerce edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-booking',
    label: 'Urban Rooftop Cafe — Booking Edition',
    category: 'Food',
    color: '#FFD166',
    bg: '#101112',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe booking', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'booking', 'booking edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-trust',
    label: 'Urban Rooftop Cafe — Trust Edition',
    category: 'Food',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe trust', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'trust', 'trust edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-magazine',
    label: 'Urban Rooftop Cafe — Magazine Edition',
    category: 'Food',
    color: '#118AB2',
    bg: '#100808',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe magazine', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'magazine', 'magazine edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-urban-rooftop-cafe-enterprise',
    label: 'Urban Rooftop Cafe — Enterprise Edition',
    category: 'Food',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['food', 'urban rooftop cafe', 'urban rooftop cafe enterprise', 'sunset seating', 'chef specials', 'live music', 'table booking'],
    keywords: ['food', 'urban rooftop cafe', 'enterprise', 'enterprise edition', 'menu', 'views', 'events', 'gallery', 'reserve', 'sunset seating', 'chef specials', 'live music', 'table booking', 'party packages'],
    description: 'Standalone unique Food website template for Urban Rooftop Cafe, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-signal',
    label: 'Boutique Publishing House — Signal Edition',
    category: 'Publishing',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house signal', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'signal', 'signal edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-atelier',
    label: 'Boutique Publishing House — Atelier Edition',
    category: 'Publishing',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house atelier', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'atelier', 'atelier edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-local',
    label: 'Boutique Publishing House — Local Growth Edition',
    category: 'Publishing',
    color: '#F97316',
    bg: '#09111f',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house local', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'local', 'local growth edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-commerce',
    label: 'Boutique Publishing House — Commerce Edition',
    category: 'Publishing',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house commerce', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'commerce', 'commerce edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-booking',
    label: 'Boutique Publishing House — Booking Edition',
    category: 'Publishing',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house booking', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'booking', 'booking edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-trust',
    label: 'Boutique Publishing House — Trust Edition',
    category: 'Publishing',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house trust', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'trust', 'trust edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-magazine',
    label: 'Boutique Publishing House — Magazine Edition',
    category: 'Publishing',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house magazine', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'magazine', 'magazine edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-boutique-publishing-house-enterprise',
    label: 'Boutique Publishing House — Enterprise Edition',
    category: 'Publishing',
    color: '#EF4444',
    bg: '#120817',
    industries: ['publishing', 'boutique publishing house', 'boutique publishing house enterprise', 'editorial desk', 'cover design', 'print runs', 'book launches'],
    keywords: ['publishing', 'boutique publishing house', 'enterprise', 'enterprise edition', 'books', 'authors', 'submissions', 'distribution', 'submit', 'editorial desk', 'cover design', 'print runs', 'book launches', 'author royalties'],
    description: 'Standalone unique Publishing website template for Boutique Publishing House, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-signal',
    label: 'EdTech Test Prep Portal — Signal Edition',
    category: 'Education',
    color: '#EF4444',
    bg: '#120817',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal signal', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'signal', 'signal edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-atelier',
    label: 'EdTech Test Prep Portal — Atelier Edition',
    category: 'Education',
    color: '#10B981',
    bg: '#050313',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal atelier', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'atelier', 'atelier edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-local',
    label: 'EdTech Test Prep Portal — Local Growth Edition',
    category: 'Education',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal local', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'local', 'local growth edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-commerce',
    label: 'EdTech Test Prep Portal — Commerce Edition',
    category: 'Education',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal commerce', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'commerce', 'commerce edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-booking',
    label: 'EdTech Test Prep Portal — Booking Edition',
    category: 'Education',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal booking', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'booking', 'booking edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-trust',
    label: 'EdTech Test Prep Portal — Trust Edition',
    category: 'Education',
    color: '#A3E635',
    bg: '#111827',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal trust', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'trust', 'trust edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-magazine',
    label: 'EdTech Test Prep Portal — Magazine Edition',
    category: 'Education',
    color: '#FB7185',
    bg: '#101112',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal magazine', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'magazine', 'magazine edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-edtech-test-prep-enterprise',
    label: 'EdTech Test Prep Portal — Enterprise Edition',
    category: 'Education',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['education', 'edtech test prep portal', 'edtech test prep portal enterprise', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans'],
    keywords: ['education', 'edtech test prep portal', 'enterprise', 'enterprise edition', 'courses', 'tests', 'mentors', 'results', 'enroll', 'mock tests', 'doubt rooms', 'rank analytics', 'study plans', 'scholarships'],
    description: 'Standalone unique Education website template for EdTech Test Prep Portal, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
