// Auto-split chunk 1 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_01: WebsiteTemplate[] = [
  {
    id: 'ai-automation-agency',
    label: 'AI Automation Agency',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["ai automation agency", "automation agency"],
    keywords: ["ai", "automation", "agency", "ai automation agency", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for AI Automation Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'ai-saas',
    label: 'AI SaaS',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["ai saas", "ai saas"],
    keywords: ["ai", "saas", "ai saas", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for AI SaaS with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'animation-studio',
    label: 'Animation Studio',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["animation studio", "animation studio"],
    keywords: ["animation", "studio", "animation studio", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Animation Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'architecture-minimal',
    label: 'Architecture Minimal',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["architecture minimal", "architecture minimal"],
    keywords: ["architecture", "minimal", "architecture minimal", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Architecture Minimal with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'artist-gallery',
    label: 'Artist Gallery',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["artist gallery", "artist gallery"],
    keywords: ["artist", "gallery", "artist gallery", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Artist Gallery with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'author-portfolio',
    label: 'Author Portfolio',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["author portfolio", "author portfolio"],
    keywords: ["author", "portfolio", "author portfolio", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Author Portfolio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'automobile-workshop',
    label: 'Automobile Workshop',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["automobile workshop", "automobile workshop"],
    keywords: ["automobile", "workshop", "automobile workshop", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Automobile Workshop with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'ayurvedic-clinic',
    label: 'Ayurvedic Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["ayurvedic clinic", "ayurvedic clinic"],
    keywords: ["ayurvedic", "clinic", "ayurvedic clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Ayurvedic Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'b2b-manufacturer',
    label: 'B2B Manufacturer',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["b2b manufacturer", "b2b manufacturer"],
    keywords: ["b2b", "manufacturer", "b2b manufacturer", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for B2B Manufacturer with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'banquet-hall',
    label: 'Banquet Hall',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["banquet hall", "banquet hall"],
    keywords: ["banquet", "hall", "banquet hall", "business", "website", "landing page"],
    description: 'Responsive business website template for Banquet Hall with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'bar-lounge',
    label: 'Bar Lounge',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["bar lounge", "bar lounge"],
    keywords: ["bar", "lounge", "bar lounge", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Bar Lounge with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'barber-shop',
    label: 'Barber Shop',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["barber shop", "barber shop"],
    keywords: ["barber", "shop", "barber shop", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Barber Shop with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'beauty-ecommerce',
    label: 'Beauty Ecommerce',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["beauty ecommerce", "beauty ecommerce"],
    keywords: ["beauty", "ecommerce", "beauty ecommerce", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Beauty Ecommerce with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'bike-showroom',
    label: 'Bike Showroom',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["bike showroom", "bike showroom"],
    keywords: ["bike", "showroom", "bike showroom", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Bike Showroom with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'birthday-planner',
    label: 'Birthday Planner',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["birthday planner", "birthday planner"],
    keywords: ["birthday", "planner", "birthday planner", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Birthday Planner with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'blockchain-startup',
    label: 'Blockchain Startup',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["blockchain startup", "blockchain startup"],
    keywords: ["blockchain", "startup", "blockchain startup", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Blockchain Startup with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'bookstore',
    label: 'Bookstore',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["bookstore"],
    keywords: ["bookstore", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Bookstore with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'branding-studio',
    label: 'Branding Studio',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["branding studio", "branding studio"],
    keywords: ["branding", "studio", "branding studio", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Branding Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'bridal-boutique',
    label: 'Bridal Boutique',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["bridal boutique", "bridal boutique"],
    keywords: ["bridal", "boutique", "bridal boutique", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Bridal Boutique with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'business-consultant',
    label: 'Business Consultant',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["business consultant", "business consultant"],
    keywords: ["business", "consultant", "business consultant", "agency", "website", "landing page"],
    description: 'Responsive agency website template for Business Consultant with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'ca-firm',
    label: 'CA Firm',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["ca firm", "ca firm"],
    keywords: ["ca", "firm", "ca firm", "business", "website", "landing page"],
    description: 'Responsive business website template for CA Firm with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'car-rental',
    label: 'Car Rental',
    category: 'Auto',
    color: '#FF4E00',
    bg: '#100402',
    industries: ["car rental", "car rental"],
    keywords: ["car", "rental", "car rental", "auto", "website", "landing page", "business"],
    description: 'Responsive auto website template for Car Rental with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'catering-service',
    label: 'Catering Service',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["catering service", "catering service"],
    keywords: ["catering", "service", "catering service", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Catering Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'chemical-supplier',
    label: 'Chemical Supplier',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["chemical supplier", "chemical supplier"],
    keywords: ["chemical", "supplier", "chemical supplier", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Chemical Supplier with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'civil-contractor',
    label: 'Civil Contractor',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["civil contractor", "civil contractor"],
    keywords: ["civil", "contractor", "civil contractor", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Civil Contractor with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'cleaning-service',
    label: 'Cleaning Service',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["cleaning service", "cleaning service"],
    keywords: ["cleaning", "service", "cleaning service", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Cleaning Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'cloud-services',
    label: 'Cloud Services',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["cloud services", "cloud services"],
    keywords: ["cloud", "services", "cloud services", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Cloud Services with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'coaching-institute',
    label: 'Coaching Institute',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["coaching institute", "coaching institute"],
    keywords: ["coaching", "institute", "coaching institute", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Coaching Institute with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'college-website',
    label: 'College Website',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["college website", "college website"],
    keywords: ["college", "website", "college website", "education", "landing page", "business"],
    description: 'Responsive education website template for College Website with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'construction-premium',
    label: 'Construction Premium',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["construction premium", "construction premium"],
    keywords: ["construction", "premium", "construction premium", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Construction Premium with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'corporate-events',
    label: 'Corporate Events',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["corporate events", "corporate events"],
    keywords: ["corporate", "events", "corporate events", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Corporate Events with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'courier-service',
    label: 'Courier Service',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["courier service", "courier service"],
    keywords: ["courier", "service", "courier service", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Courier Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'coworking-space',
    label: 'Coworking Space',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["coworking space", "coworking space"],
    keywords: ["coworking", "space", "coworking space", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Coworking Space with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'crm-software',
    label: 'CRM Software',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["crm software", "crm software"],
    keywords: ["crm", "software", "crm software", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for CRM Software with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'crypto-education',
    label: 'Crypto Education',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["crypto education", "crypto education"],
    keywords: ["crypto", "education", "crypto education", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Crypto Education with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'cybersecurity-saas',
    label: 'Cybersecurity SaaS',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["cybersecurity saas", "cybersecurity saas"],
    keywords: ["cybersecurity", "saas", "cybersecurity saas", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Cybersecurity SaaS with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'dance-academy',
    label: 'Dance Academy',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["dance academy", "dance academy"],
    keywords: ["dance", "academy", "dance academy", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Dance Academy with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'data-analytics',
    label: 'Data Analytics',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["data analytics", "data analytics"],
    keywords: ["data", "analytics", "data analytics", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Data Analytics with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'dermatology-clinic',
    label: 'Dermatology Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["dermatology clinic", "dermatology clinic"],
    keywords: ["dermatology", "clinic", "dermatology clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Dermatology Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'diagnostic-lab',
    label: 'Diagnostic Lab',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["diagnostic lab", "diagnostic lab"],
    keywords: ["diagnostic", "lab", "diagnostic lab", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Diagnostic Lab with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'diamond-jewellery',
    label: 'Diamond Jewellery',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["diamond jewellery", "diamond jewellery"],
    keywords: ["diamond", "jewellery", "diamond jewellery", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Diamond Jewellery with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'digital-marketing-agency',
    label: 'Digital Marketing Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["digital marketing agency", "marketing agency"],
    keywords: ["digital", "marketing", "agency", "digital marketing agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Digital Marketing Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'domain-provider',
    label: 'Domain Provider',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["domain provider", "domain provider"],
    keywords: ["domain", "provider", "domain provider", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Domain Provider with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'driving-school',
    label: 'Driving School',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["driving school", "driving school"],
    keywords: ["driving", "school", "driving school", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Driving School with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'edtech-platform',
    label: 'Edtech Platform',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["edtech platform", "edtech platform"],
    keywords: ["edtech", "platform", "edtech platform", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Edtech Platform with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'electrician-service',
    label: 'Electrician Service',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["electrician service", "electrician service"],
    keywords: ["electrician", "service", "electrician service", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Electrician Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'electronics-ecommerce',
    label: 'Electronics Ecommerce',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["electronics ecommerce", "electronics ecommerce"],
    keywords: ["electronics", "ecommerce", "electronics ecommerce", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Electronics Ecommerce with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'electronics-store',
    label: 'Electronics Store',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["electronics store", "electronics store"],
    keywords: ["electronics", "store", "electronics store", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Electronics Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'ev-showroom',
    label: 'EV Showroom',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["ev showroom", "ev showroom"],
    keywords: ["ev", "showroom", "ev showroom", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for EV Showroom with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'export-business',
    label: 'Export Business',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["export business", "export business"],
    keywords: ["export", "business", "export business", "agency", "website", "landing page"],
    description: 'Responsive agency website template for Export Business with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'export-logistics',
    label: 'Export Logistics',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["export logistics", "export logistics"],
    keywords: ["export", "logistics", "export logistics", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Export Logistics with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'eye-clinic',
    label: 'Eye Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["eye clinic", "eye clinic"],
    keywords: ["eye", "clinic", "eye clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Eye Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'fashion-ecommerce',
    label: 'Fashion Ecommerce',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["fashion ecommerce", "fashion ecommerce"],
    keywords: ["fashion", "ecommerce", "fashion ecommerce", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Fashion Ecommerce with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'fertility-clinic',
    label: 'Fertility Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["fertility clinic", "fertility clinic"],
    keywords: ["fertility", "clinic", "fertility clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Fertility Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'fintech-app',
    label: 'Fintech App',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["fintech app", "fintech app"],
    keywords: ["fintech", "app", "fintech app", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Fintech App with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'flower-shop',
    label: 'Flower Shop',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["flower shop", "flower shop"],
    keywords: ["flower", "shop", "flower shop", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Flower Shop with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'furniture-ecommerce',
    label: 'Furniture Ecommerce',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["furniture ecommerce", "furniture ecommerce"],
    keywords: ["furniture", "ecommerce", "furniture ecommerce", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Furniture Ecommerce with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'gaming-esports-team',
    label: 'Gaming Esports Team',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["gaming esports team", "esports team"],
    keywords: ["gaming", "esports", "team", "gaming esports team", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Gaming Esports Team with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'graphic-design-studio',
    label: 'Graphic Design Studio',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["graphic design studio", "design studio"],
    keywords: ["graphic", "design", "studio", "graphic design studio", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Graphic Design Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'grocery-delivery',
    label: 'Grocery Delivery',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["grocery delivery", "grocery delivery"],
    keywords: ["grocery", "delivery", "grocery delivery", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Grocery Delivery with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'home-decor-store',
    label: 'Home Decor Store',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["home decor store", "decor store"],
    keywords: ["home", "decor", "store", "home decor store", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Home Decor Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'homeopathy-clinic',
    label: 'Homeopathy Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["homeopathy clinic", "homeopathy clinic"],
    keywords: ["homeopathy", "clinic", "homeopathy clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Homeopathy Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'homestay',
    label: 'Homestay',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["homestay"],
    keywords: ["homestay", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Homestay with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'hostel',
    label: 'Hostel',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["hostel"],
    keywords: ["hostel", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Hostel with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'hosting-company',
    label: 'Hosting Company',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ["hosting company", "hosting company"],
    keywords: ["hosting", "company", "hosting company", "tech", "website", "landing page", "business"],
    description: 'Responsive tech website template for Hosting Company with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'hr-consultancy',
    label: 'Hr Consultancy',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["hr consultancy", "hr consultancy"],
    keywords: ["hr", "consultancy", "hr consultancy", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Hr Consultancy with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'ice-cream-parlour',
    label: 'Ice Cream Parlour',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["ice cream parlour", "cream parlour"],
    keywords: ["ice", "cream", "parlour", "ice cream parlour", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Ice Cream Parlour with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'immigration-consultant',
    label: 'Immigration Consultant',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["immigration consultant", "immigration consultant"],
    keywords: ["immigration", "consultant", "immigration consultant", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Immigration Consultant with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'influencer-marketing',
    label: 'Influencer Marketing',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["influencer marketing", "influencer marketing"],
    keywords: ["influencer", "marketing", "influencer marketing", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Influencer Marketing with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'influencer-portfolio',
    label: 'Influencer Portfolio',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["influencer portfolio", "influencer portfolio"],
    keywords: ["influencer", "portfolio", "influencer portfolio", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Influencer Portfolio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'insurance-agency',
    label: 'Insurance Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["insurance agency", "insurance agency"],
    keywords: ["insurance", "agency", "insurance agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Insurance Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'interior-luxury-studio',
    label: 'Interior Luxury Studio',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["interior luxury studio", "luxury studio"],
    keywords: ["interior", "luxury", "studio", "interior luxury studio", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Interior Luxury Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'it-support',
    label: 'IT Support',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["it support", "it support"],
    keywords: ["it", "support", "it support", "business", "website", "landing page"],
    description: 'Responsive business website template for IT Support with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'jewellery-bridal',
    label: 'Jewellery Bridal',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["jewellery bridal", "jewellery bridal"],
    keywords: ["jewellery", "bridal", "jewellery bridal", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Jewellery Bridal with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'jewellery-ecommerce',
    label: 'Jewellery Ecommerce',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["jewellery ecommerce", "jewellery ecommerce"],
    keywords: ["jewellery", "ecommerce", "jewellery ecommerce", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Jewellery Ecommerce with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'jewellery-minimal',
    label: 'Jewellery Minimal',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["jewellery minimal", "jewellery minimal"],
    keywords: ["jewellery", "minimal", "jewellery minimal", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Jewellery Minimal with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'juice-bar',
    label: 'Juice Bar',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["juice bar", "juice bar"],
    keywords: ["juice", "bar", "juice bar", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Juice Bar with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'kidswear-brand',
    label: 'Kidswear Brand',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["kidswear brand", "kidswear brand"],
    keywords: ["kidswear", "brand", "kidswear brand", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Kidswear Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'landscape-design',
    label: 'Landscape Design',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["landscape design", "landscape design"],
    keywords: ["landscape", "design", "landscape design", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Landscape Design with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'language-school',
    label: 'Language School',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["language school", "language school"],
    keywords: ["language", "school", "language school", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Language School with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'laundry-service',
    label: 'Laundry Service',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["laundry service", "laundry service"],
    keywords: ["laundry", "service", "laundry service", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Laundry Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'legal-consultant',
    label: 'Legal Consultant',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["legal consultant", "legal consultant"],
    keywords: ["legal", "consultant", "legal consultant", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Legal Consultant with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'lighting-store',
    label: 'Lighting Store',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["lighting store", "lighting store"],
    keywords: ["lighting", "store", "lighting store", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Lighting Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'loan-consultant',
    label: 'Loan Consultant',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["loan consultant", "loan consultant"],
    keywords: ["loan", "consultant", "loan consultant", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Loan Consultant with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'luxury-spa-resort',
    label: 'Luxury Spa Resort',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["luxury spa resort", "spa resort"],
    keywords: ["luxury", "spa", "resort", "luxury spa resort", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Luxury Spa Resort with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'luxury-villa-rental',
    label: 'Luxury Villa Rental',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["luxury villa rental", "villa rental"],
    keywords: ["luxury", "villa", "rental", "luxury villa rental", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for Luxury Villa Rental with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'makeup-artist',
    label: 'Makeup Artist',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["makeup artist", "makeup artist"],
    keywords: ["makeup", "artist", "makeup artist", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Makeup Artist with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'maternity-hospital',
    label: 'Maternity Hospital',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["maternity hospital", "maternity hospital"],
    keywords: ["maternity", "hospital", "maternity hospital", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Maternity Hospital with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'menswear-brand',
    label: 'Menswear Brand',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["menswear brand", "menswear brand"],
    keywords: ["menswear", "brand", "menswear brand", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Menswear Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'mental-wellness',
    label: 'Mental Wellness',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["mental wellness", "mental wellness"],
    keywords: ["mental", "wellness", "mental wellness", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Mental Wellness with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'mobile-store',
    label: 'Mobile Store',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["mobile store", "mobile store"],
    keywords: ["mobile", "store", "mobile store", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Mobile Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'modular-kitchen',
    label: 'Modular Kitchen',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["modular kitchen", "modular kitchen"],
    keywords: ["modular", "kitchen", "modular kitchen", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Modular Kitchen with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'moving-packers',
    label: 'Moving Packers',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["moving packers", "moving packers"],
    keywords: ["moving", "packers", "moving packers", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Moving Packers with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'music-school',
    label: 'Music School',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["music school", "music school"],
    keywords: ["music", "school", "music school", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Music School with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'nail-studio',
    label: 'Nail Studio',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["nail studio", "nail studio"],
    keywords: ["nail", "studio", "nail studio", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Nail Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'notary-service',
    label: 'Notary Service',
    category: 'Business',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["notary service", "notary service"],
    keywords: ["notary", "service", "notary service", "business", "website", "landing page"],
    description: 'Responsive business website template for Notary Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'nutritionist',
    label: 'Nutritionist',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["nutritionist"],
    keywords: ["nutritionist", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Nutritionist with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'online-course-creator',
    label: 'Online Course Creator',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["online course creator", "course creator"],
    keywords: ["online", "course", "creator", "online course creator", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Online Course Creator with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'optical-store',
    label: 'Optical Store',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["optical store", "optical store"],
    keywords: ["optical", "store", "optical store", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Optical Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'organic-food-store',
    label: 'Organic Food Store',
    category: 'Commerce',
    color: '#F0C060',
    bg: '#060606',
    industries: ["organic food store", "food store"],
    keywords: ["organic", "food", "store", "organic food store", "commerce", "website", "landing page", "business"],
    description: 'Responsive commerce website template for Organic Food Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'orthopedic-clinic',
    label: 'Orthopedic Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["orthopedic clinic", "orthopedic clinic"],
    keywords: ["orthopedic", "clinic", "orthopedic clinic", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Orthopedic Clinic with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'packaging-company',
    label: 'Packaging Company',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["packaging company", "packaging company"],
    keywords: ["packaging", "company", "packaging company", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Packaging Company with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'perfume-brand',
    label: 'Perfume Brand',
    category: 'Fashion',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ["perfume brand", "perfume brand"],
    keywords: ["perfume", "brand", "perfume brand", "fashion", "website", "landing page", "business"],
    description: 'Responsive fashion website template for Perfume Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'pest-control',
    label: 'Pest Control',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["pest control", "pest control"],
    keywords: ["pest", "control", "pest control", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Pest Control with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'pg-hostel',
    label: 'PG Hostel',
    category: 'Real Estate',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ["pg hostel", "pg hostel"],
    keywords: ["pg", "hostel", "pg hostel", "real estate", "website", "landing page", "business"],
    description: 'Responsive real estate website template for PG Hostel with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'pharmacy-store',
    label: 'Pharmacy Store',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["pharmacy store", "pharmacy store"],
    keywords: ["pharmacy", "store", "pharmacy store", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Pharmacy Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'photobooth-service',
    label: 'Photobooth Service',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["photobooth service", "photobooth service"],
    keywords: ["photobooth", "service", "photobooth service", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Photobooth Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'physiotherapy-centre',
    label: 'Physiotherapy Centre',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ["physiotherapy centre", "physiotherapy centre"],
    keywords: ["physiotherapy", "centre", "physiotherapy centre", "health", "website", "landing page", "business"],
    description: 'Responsive health website template for Physiotherapy Centre with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'pizza-brand',
    label: 'Pizza Brand',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ["pizza brand", "pizza brand"],
    keywords: ["pizza", "brand", "pizza brand", "food", "website", "landing page", "business"],
    description: 'Responsive food website template for Pizza Brand with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'plumbing-service',
    label: 'Plumbing Service',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ["plumbing service", "plumbing service"],
    keywords: ["plumbing", "service", "plumbing service", "industry", "website", "landing page", "business"],
    description: 'Responsive industry website template for Plumbing Service with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'podcast-studio',
    label: 'Podcast Studio',
    category: 'Creative',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ["podcast studio", "podcast studio"],
    keywords: ["podcast", "studio", "podcast studio", "creative", "website", "landing page", "business"],
    description: 'Responsive creative website template for Podcast Studio with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'pr-agency',
    label: 'Pr Agency',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["pr agency", "pr agency"],
    keywords: ["pr", "agency", "pr agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Pr Agency with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'premium-gift-store',
    label: 'Premium Gift Store',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["premium gift store", "gift store"],
    keywords: ["premium", "gift", "store", "premium gift store", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Premium Gift Store with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'preschool',
    label: 'Preschool',
    category: 'Education',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ["preschool"],
    keywords: ["preschool", "education", "website", "landing page", "business"],
    description: 'Responsive education website template for Preschool with conversion sections, visuals, service highlights and lead capture.',
  },
  {
    id: 'printing-press',
    label: 'Printing Press',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ["printing press", "printing press"],
    keywords: ["printing", "press", "printing press", "agency", "website", "landing page", "business"],
    description: 'Responsive agency website template for Printing Press with conversion sections, visuals, service highlights and lead capture.',
  },
]
