// Auto-split chunk 9 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_09: WebsiteTemplate[] = [
  {
    id: 'bsx-private-detective-agency-local',
    label: 'Private Detective Agency — Local Growth Edition',
    category: 'Investigation',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['investigation', 'private detective agency', 'private detective agency local', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'local', 'local growth edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-commerce',
    label: 'Private Detective Agency — Commerce Edition',
    category: 'Investigation',
    color: '#118AB2',
    bg: '#060606',
    industries: ['investigation', 'private detective agency', 'private detective agency commerce', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'commerce', 'commerce edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-booking',
    label: 'Private Detective Agency — Booking Edition',
    category: 'Investigation',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['investigation', 'private detective agency', 'private detective agency booking', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'booking', 'booking edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-trust',
    label: 'Private Detective Agency — Trust Edition',
    category: 'Investigation',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['investigation', 'private detective agency', 'private detective agency trust', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'trust', 'trust edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-magazine',
    label: 'Private Detective Agency — Magazine Edition',
    category: 'Investigation',
    color: '#F97316',
    bg: '#100A04',
    industries: ['investigation', 'private detective agency', 'private detective agency magazine', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'magazine', 'magazine edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-private-detective-agency-enterprise',
    label: 'Private Detective Agency — Enterprise Edition',
    category: 'Investigation',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['investigation', 'private detective agency', 'private detective agency enterprise', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols'],
    keywords: ['investigation', 'private detective agency', 'enterprise', 'enterprise edition', 'services', 'discretion', 'cases', 'process', 'consult', 'background checks', 'corporate investigations', 'evidence reports', 'privacy protocols', 'case managers'],
    description: 'Standalone unique Investigation website template for Private Detective Agency, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-signal',
    label: 'Language Translation Bureau — Signal Edition',
    category: 'Services',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['services', 'language translation bureau', 'language translation bureau signal', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'signal', 'signal edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-atelier',
    label: 'Language Translation Bureau — Atelier Edition',
    category: 'Services',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['services', 'language translation bureau', 'language translation bureau atelier', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'atelier', 'atelier edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-local',
    label: 'Language Translation Bureau — Local Growth Edition',
    category: 'Services',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['services', 'language translation bureau', 'language translation bureau local', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'local', 'local growth edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-commerce',
    label: 'Language Translation Bureau — Commerce Edition',
    category: 'Services',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['services', 'language translation bureau', 'language translation bureau commerce', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'commerce', 'commerce edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-booking',
    label: 'Language Translation Bureau — Booking Edition',
    category: 'Services',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['services', 'language translation bureau', 'language translation bureau booking', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'booking', 'booking edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-trust',
    label: 'Language Translation Bureau — Trust Edition',
    category: 'Services',
    color: '#10B981',
    bg: '#010A05',
    industries: ['services', 'language translation bureau', 'language translation bureau trust', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'trust', 'trust edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-magazine',
    label: 'Language Translation Bureau — Magazine Edition',
    category: 'Services',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['services', 'language translation bureau', 'language translation bureau magazine', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'magazine', 'magazine edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-language-translation-bureau-enterprise',
    label: 'Language Translation Bureau — Enterprise Edition',
    category: 'Services',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['services', 'language translation bureau', 'language translation bureau enterprise', 'certified translations', 'interpreter desk', 'document upload', 'quality review'],
    keywords: ['services', 'language translation bureau', 'enterprise', 'enterprise edition', 'languages', 'documents', 'interpreters', 'quality', 'order', 'certified translations', 'interpreter desk', 'document upload', 'quality review', 'delivery tracking'],
    description: 'Standalone unique Services website template for Language Translation Bureau, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-signal',
    label: 'Rapid Ambulance Network — Signal Edition',
    category: 'Emergency',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network signal', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'signal', 'signal edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-atelier',
    label: 'Rapid Ambulance Network — Atelier Edition',
    category: 'Emergency',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network atelier', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'atelier', 'atelier edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-local',
    label: 'Rapid Ambulance Network — Local Growth Edition',
    category: 'Emergency',
    color: '#A3E635',
    bg: '#050313',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network local', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'local', 'local growth edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-commerce',
    label: 'Rapid Ambulance Network — Commerce Edition',
    category: 'Emergency',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network commerce', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'commerce', 'commerce edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-booking',
    label: 'Rapid Ambulance Network — Booking Edition',
    category: 'Emergency',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network booking', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'booking', 'booking edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-trust',
    label: 'Rapid Ambulance Network — Trust Edition',
    category: 'Emergency',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network trust', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'trust', 'trust edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-magazine',
    label: 'Rapid Ambulance Network — Magazine Edition',
    category: 'Emergency',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network magazine', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'magazine', 'magazine edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rapid-ambulance-network-enterprise',
    label: 'Rapid Ambulance Network — Enterprise Edition',
    category: 'Emergency',
    color: '#FFD166',
    bg: '#101112',
    industries: ['emergency', 'rapid ambulance network', 'rapid ambulance network enterprise', 'icu ambulances', 'route tracking', 'hospital links', 'trained staff'],
    keywords: ['emergency', 'rapid ambulance network', 'enterprise', 'enterprise edition', 'ambulances', 'coverage', 'hospitals', 'tracking', 'call', 'ICU ambulances', 'route tracking', 'hospital links', 'trained staff', 'emergency hotline'],
    description: 'Standalone unique Emergency website template for Rapid Ambulance Network, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-signal',
    label: 'Startup Grant Advisory — Signal Edition',
    category: 'Consulting',
    color: '#FFD166',
    bg: '#101112',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory signal', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'signal', 'signal edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-atelier',
    label: 'Startup Grant Advisory — Atelier Edition',
    category: 'Consulting',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory atelier', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'atelier', 'atelier edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-local',
    label: 'Startup Grant Advisory — Local Growth Edition',
    category: 'Consulting',
    color: '#118AB2',
    bg: '#100808',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory local', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'local', 'local growth edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-commerce',
    label: 'Startup Grant Advisory — Commerce Edition',
    category: 'Consulting',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory commerce', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'commerce', 'commerce edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-booking',
    label: 'Startup Grant Advisory — Booking Edition',
    category: 'Consulting',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory booking', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'booking', 'booking edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-trust',
    label: 'Startup Grant Advisory — Trust Edition',
    category: 'Consulting',
    color: '#F97316',
    bg: '#09111f',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory trust', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'trust', 'trust edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-magazine',
    label: 'Startup Grant Advisory — Magazine Edition',
    category: 'Consulting',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory magazine', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'magazine', 'magazine edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-startup-grant-advisory-enterprise',
    label: 'Startup Grant Advisory — Enterprise Edition',
    category: 'Consulting',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['consulting', 'startup grant advisory', 'startup grant advisory enterprise', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar'],
    keywords: ['consulting', 'startup grant advisory', 'enterprise', 'enterprise edition', 'programs', 'eligibility', 'documents', 'results', 'apply', 'grant matching', 'eligibility checks', 'document prep', 'submission calendar', 'founder support'],
    description: 'Standalone unique Consulting website template for Startup Grant Advisory, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-signal',
    label: 'Smart Classroom Hardware — Signal Edition',
    category: 'EdTech Hardware',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware signal', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'signal', 'signal edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-atelier',
    label: 'Smart Classroom Hardware — Atelier Edition',
    category: 'EdTech Hardware',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware atelier', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'atelier', 'atelier edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-local',
    label: 'Smart Classroom Hardware — Local Growth Edition',
    category: 'EdTech Hardware',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware local', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'local', 'local growth edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-commerce',
    label: 'Smart Classroom Hardware — Commerce Edition',
    category: 'EdTech Hardware',
    color: '#EF4444',
    bg: '#120817',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware commerce', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'commerce', 'commerce edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-booking',
    label: 'Smart Classroom Hardware — Booking Edition',
    category: 'EdTech Hardware',
    color: '#10B981',
    bg: '#050313',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware booking', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'booking', 'booking edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-trust',
    label: 'Smart Classroom Hardware — Trust Edition',
    category: 'EdTech Hardware',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware trust', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'trust', 'trust edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-magazine',
    label: 'Smart Classroom Hardware — Magazine Edition',
    category: 'EdTech Hardware',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware magazine', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'magazine', 'magazine edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-smart-classroom-hardware-enterprise',
    label: 'Smart Classroom Hardware — Enterprise Edition',
    category: 'EdTech Hardware',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['edtech hardware', 'smart classroom hardware', 'smart classroom hardware enterprise', 'interactive boards', 'school rollout', 'teacher training', 'device service'],
    keywords: ['edtech hardware', 'smart classroom hardware', 'enterprise', 'enterprise edition', 'devices', 'schools', 'installation', 'training', 'quote', 'interactive boards', 'school rollout', 'teacher training', 'device service', 'content integration'],
    description: 'Standalone unique EdTech Hardware website template for Smart Classroom Hardware, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'app-development',
    label: 'App Dev Studio',
    category: 'Tech',
    color: '#00C2FF',
    bg: '#020B12',
    industries: ['app development', 'software', 'mobile apps', 'tech startup', 'SaaS', 'IT services'],
    keywords: ['app', 'mobile', 'software', 'development', 'flutter', 'ios', 'android', 'startup', 'tech', 'developer', 'code', 'programming'],
    description: 'Modern app development studio website for mobile and software companies.',
  },
  {
    id: 'architect',
    label: 'Architecture Firm',
    category: 'Design',
    color: '#D4C9A8',
    bg: '#0C0B09',
    industries: ['architecture', 'urban planning', 'structural design', 'interior architecture'],
    keywords: ['architect', 'architecture', 'firm', 'building', 'design', 'urban', 'structure', 'blueprint', 'construction design'],
    description: 'Premium architecture firm website with editorial aesthetic for design-led studios.',
  },
  {
    id: 'arka-automobile',
    label: 'Automobile Showroom',
    category: 'Auto',
    color: '#FF4E00',
    bg: '#100402',
    industries: ['automobile', 'car dealership', 'vehicle showroom', 'automotive'],
    keywords: ['car', 'automobile', 'auto', 'showroom', 'vehicle', 'dealership', 'bikes', 'motors', 'automotive'],
    description: 'High-energy automobile showroom and dealership website with bold visual identity.',
  },
  {
    id: 'bakery',
    label: 'Artisan Bakery',
    category: 'Food',
    color: '#E8B87A',
    bg: '#100A04',
    industries: ['bakery', 'patisserie', 'cafe', 'artisan food', 'confectionery'],
    keywords: ['bakery', 'bread', 'pastry', 'cake', 'artisan', 'bake', 'oven', 'croissant', 'confectionery', 'sweets', 'baked goods'],
    description: 'Warm, artisan bakery website with rich food photography and inviting copy.',
  },
  {
    id: 'blackapex',
    label: 'Black Apex Corp.',
    category: 'Agency',
    color: '#C0C0C0',
    bg: '#060606',
    industries: ['agency', 'corporate', 'consulting', 'enterprise', 'B2B services', 'professional services'],
    keywords: ['agency', 'corporate', 'enterprise', 'business', 'consulting', 'services', 'B2B', 'professional', 'solutions', 'company'],
    description: 'Dark, authoritative corporate and agency website for enterprise and B2B brands.',
  },
  {
    id: 'car-detailing',
    label: 'Car Detailing',
    category: 'Auto',
    color: '#C0392B',
    bg: '#0D0302',
    industries: ['car detailing', 'auto care', 'vehicle cleaning', 'ceramic coating'],
    keywords: ['detailing', 'car wash', 'ceramic', 'coating', 'polish', 'auto care', 'vehicle', 'wash', 'detailer'],
    description: 'Bold car detailing and auto care service website with premium finish.',
  },
  {
    id: 'cloud-kitchen',
    label: 'Cloud Kitchen',
    category: 'Food',
    color: '#FF6B35',
    bg: '#100502',
    industries: ['cloud kitchen', 'ghost kitchen', 'food delivery', 'restaurant delivery'],
    keywords: ['cloud kitchen', 'ghost kitchen', 'delivery', 'food', 'online order', 'tiffin', 'meals', 'kitchen'],
    description: 'Cloud kitchen and food delivery brand website optimised for online orders.',
  },
  {
    id: 'coffee-brand',
    label: 'Coffee Brand',
    category: 'Food',
    color: '#9C6E3C',
    bg: '#080501',
    industries: ['coffee', 'cafe', 'specialty coffee', 'roastery', 'beverage'],
    keywords: ['coffee', 'cafe', 'roastery', 'espresso', 'brew', 'barista', 'beans', 'specialty', 'latte'],
    description: 'Premium coffee brand and cafe website with rich, warm identity.',
  },
  {
    id: 'construction',
    label: 'Construction Co.',
    category: 'Industry',
    color: '#F4A000',
    bg: '#0A0600',
    industries: ['construction', 'civil engineering', 'infrastructure', 'builders', 'contractors'],
    keywords: ['construction', 'builders', 'contractor', 'civil', 'infrastructure', 'building', 'project', 'engineer', 'infra'],
    description: 'Strong, authoritative construction and infrastructure company website.',
  },
  {
    id: 'cosmetics',
    label: 'Cosmetics Brand',
    category: 'Beauty',
    color: '#E8A0C0',
    bg: '#100808',
    industries: ['cosmetics', 'beauty', 'skincare', 'makeup', 'personal care'],
    keywords: ['cosmetics', 'beauty', 'skincare', 'makeup', 'lipstick', 'foundation', 'cream', 'serum', 'glow', 'skin'],
    description: 'Elegant cosmetics and beauty brand website with luxurious visual language.',
  },
  {
    id: 'cybersecurity',
    label: 'Cybersecurity Firm',
    category: 'Tech',
    color: '#00FF94',
    bg: '#010A05',
    industries: ['cybersecurity', 'information security', 'IT security', 'data protection'],
    keywords: ['cyber', 'security', 'hacking', 'protection', 'firewall', 'data', 'threat', 'VAPT', 'penetration', 'compliance'],
    description: 'Technical cybersecurity firm website with dark, authoritative visual identity.',
  },
  {
    id: 'dental-clinic',
    label: 'Dental Clinic',
    category: 'Health',
    color: '#7EC8E3',
    bg: '#020C10',
    industries: ['dental', 'dentistry', 'oral care', 'orthodontics', 'dental clinic'],
    keywords: ['dental', 'dentist', 'clinic', 'teeth', 'oral', 'orthodontics', 'braces', 'implant', 'smile'],
    description: 'Clean, professional dental clinic website that builds patient trust.',
  },
  {
    id: 'education-academy',
    label: 'Education Academy',
    category: 'Edu',
    color: '#6A9FD8',
    bg: '#02060F',
    industries: ['education', 'coaching', 'academy', 'institute', 'school', 'tutoring', 'courses'],
    keywords: ['education', 'academy', 'classes', 'coaching', 'institute', 'school', 'tutor', 'course', 'learning', 'study', 'training'],
    description: 'Professional education and coaching academy website with clear enrollment CTA.',
  },
  {
    id: 'event-planner',
    label: 'Event Planner',
    category: 'Events',
    color: '#C77DFF',
    bg: '#07020F',
    industries: ['event planning', 'event management', 'weddings', 'corporate events', 'parties'],
    keywords: ['event', 'planner', 'wedding', 'party', 'conference', 'management', 'decor', 'celebration', 'organiser'],
    description: 'Vibrant event planning and management website for weddings and corporate events.',
  },
  {
    id: 'fashion-brand',
    label: 'Fashion Brand',
    category: 'Fashion',
    color: '#F0C060',
    bg: '#0A0700',
    industries: ['fashion', 'clothing', 'apparel', 'lifestyle', 'streetwear'],
    keywords: ['fashion', 'clothing', 'apparel', 'brand', 'wear', 'collection', 'outfit', 'style', 'trend', 'garment', 'boutique'],
    description: 'Editorial fashion brand website with bold typographic identity.',
  },
  {
    id: 'financial-advisor',
    label: 'Financial Advisor',
    category: 'Finance',
    color: '#4CAF82',
    bg: '#010A05',
    industries: ['financial advisory', 'wealth management', 'investments', 'insurance', 'tax consulting'],
    keywords: ['finance', 'financial', 'advisor', 'wealth', 'investment', 'money', 'insurance', 'tax', 'portfolio', 'returns', 'mutual fund'],
    description: 'Credible financial advisory and wealth management website.',
  },
  {
    id: 'fitness-coach',
    label: 'Fitness Coach',
    category: 'Health',
    color: '#FF5252',
    bg: '#0D0101',
    industries: ['fitness', 'personal training', 'gym', 'health coaching', 'sports'],
    keywords: ['fitness', 'coach', 'gym', 'workout', 'training', 'fat loss', 'muscle', 'health', 'nutrition', 'trainer', 'physique'],
    description: 'High-energy fitness coach and personal trainer website with results-focused copy.',
  },
  {
    id: 'flux-mobile',
    label: 'Mobile App Brand',
    category: 'Tech',
    color: '#9B59FF',
    bg: '#04010E',
    industries: ['mobile app', 'SaaS product', 'consumer tech', 'digital product'],
    keywords: ['mobile app', 'product', 'download', 'iOS', 'android', 'app store', 'SaaS', 'platform', 'digital'],
    description: 'Sleek mobile app or digital product landing page with app store CTAs.',
  },
  {
    id: 'furniture',
    label: 'Furniture Studio',
    category: 'Design',
    color: '#C8956A',
    bg: '#0A0604',
    industries: ['furniture', 'home decor', 'woodwork', 'interior furnishings'],
    keywords: ['furniture', 'wood', 'sofa', 'table', 'chair', 'decor', 'handmade', 'craftsmanship', 'home', 'bespoke'],
    description: 'Warm, artisan furniture studio and home decor website.',
  },
  {
    id: 'gaming-studio',
    label: 'Gaming Studio',
    category: 'Tech',
    color: '#39FF14',
    bg: '#010801',
    industries: ['gaming', 'game development', 'esports', 'game studio'],
    keywords: ['gaming', 'game', 'studio', 'esports', 'play', 'indie', 'developer', 'multiplayer', 'console'],
    description: 'Electrifying gaming studio and esports website with neon visual identity.',
  },
  {
    id: 'hotel-resort',
    label: 'Hotel & Resort',
    category: 'Hospitality',
    color: '#D4A86A',
    bg: '#090601',
    industries: ['hotel', 'resort', 'hospitality', 'accommodation', 'luxury stays'],
    keywords: ['hotel', 'resort', 'stay', 'rooms', 'booking', 'luxury', 'hospitality', 'accommodation', 'suite', 'check-in'],
    description: 'Luxurious hotel and resort website with atmospheric photography and booking CTA.',
  },
  {
    id: 'interior-design',
    label: 'Interior Design',
    category: 'Design',
    color: '#B8A99A',
    bg: '#080706',
    industries: ['interior design', 'home styling', 'space planning', 'decor consulting'],
    keywords: ['interior', 'design', 'decor', 'space', 'home', 'styling', 'renovation', 'furnish', 'room', 'architecture'],
    description: 'Premium interior design studio website with editorial portfolio layout.',
  },
  {
    id: 'jewellery',
    label: 'Fine Jewellery',
    category: 'Luxury',
    color: '#E8D5A3',
    bg: '#09080A',
    industries: ['jewellery', 'bridal jewellery', 'luxury retail', 'fashion', 'ornaments'],
    keywords: ['jewels', 'jewellery', 'jewelry', 'jewellers', 'bridal', 'rings', 'necklace', 'gold', 'diamond', 'ornaments', 'gems', 'bangle'],
    description: 'Premium luxury jewellery website for bridal, fashion and high-value retail brands.',
  },
  {
    id: 'law-firm',
    label: 'Law Firm',
    category: 'Legal',
    color: '#8B7355',
    bg: '#06050A',
    industries: ['law', 'legal services', 'advocates', 'solicitors', 'legal consulting'],
    keywords: ['law', 'legal', 'lawyer', 'advocate', 'solicitor', 'attorney', 'firm', 'court', 'compliance', 'litigation'],
    description: 'Authoritative law firm and legal services website that builds client trust.',
  },
  {
    id: 'logistics',
    label: 'Logistics Co.',
    category: 'Industry',
    color: '#4A90D9',
    bg: '#01060D',
    industries: ['logistics', 'supply chain', 'freight', 'shipping', 'transportation', 'warehousing'],
    keywords: ['logistics', 'shipping', 'freight', 'transport', 'supply chain', 'delivery', 'warehouse', 'cargo', 'fleet'],
    description: 'Reliable logistics and supply chain company website with tracking-focused copy.',
  },
  {
    id: 'lumiere-cosmetics',
    label: 'Lumière Cosmetics',
    category: 'Beauty',
    color: '#F5C2D0',
    bg: '#0D0408',
    industries: ['cosmetics', 'luxury beauty', 'skincare', 'fragrances', 'premium beauty'],
    keywords: ['lumiere', 'cosmetics', 'luxury beauty', 'serum', 'glow', 'skin', 'premium', 'fragrance', 'parfum', 'beauty brand'],
    description: 'Ultra-premium cosmetics and luxury beauty brand with Parisian editorial aesthetic.',
  },
  {
    id: 'luxury-restaurant',
    label: 'Luxury Restaurant',
    category: 'Food',
    color: '#C9A84C',
    bg: '#080600',
    industries: ['restaurant', 'cafe', 'fine dining', 'food', 'cloud kitchen', 'dhaba', 'eatery'],
    keywords: ['restaurant', 'cafe', 'kitchen', 'food', 'dining', 'menu', 'chef', 'dine', 'eatery', 'biryani', 'dhaba', 'thali'],
    description: 'Premium food and restaurant website with cinematic ambience and booking CTA.',
  },
  {
    id: 'marketing-agency',
    label: 'Marketing Agency',
    category: 'Agency',
    color: '#FF4081',
    bg: '#0D0104',
    industries: ['agency', 'marketing', 'branding', 'advertising', 'consulting', 'general business', 'digital marketing'],
    keywords: ['agency', 'marketing', 'branding', 'ads', 'growth', 'consulting', 'business', 'digital', 'media', 'promotion', 'strategy'],
    description: 'Versatile premium business website for agencies, consultants, startups and service businesses.',
  },
  {
    id: 'medical-spa',
    label: 'Medical Spa',
    category: 'Health',
    color: '#9EC8C0',
    bg: '#02080A',
    industries: ['medical spa', 'aesthetics', 'wellness clinic', 'skin clinic', 'anti-ageing'],
    keywords: ['medical', 'spa', 'aesthetic', 'skin', 'botox', 'treatment', 'wellness', 'laser', 'anti-ageing', 'clinic'],
    description: 'Elegant medical spa and aesthetic clinic website with calm, clinical premium feel.',
  },
  {
    id: 'meridian-hospital',
    label: 'Hospital & Clinic',
    category: 'Health',
    color: '#5B9BD5',
    bg: '#01060C',
    industries: ['hospital', 'clinic', 'healthcare', 'multispeciality', 'medical centre'],
    keywords: ['hospital', 'clinic', 'doctor', 'health', 'medical', 'care', 'patient', 'specialist', 'healthcare', 'surgery', 'nursing'],
    description: 'Professional hospital and multi-specialty clinic website with patient trust signals.',
  },
  {
    id: 'music-artist',
    label: 'Music Artist',
    category: 'Creative',
    color: '#FF6B6B',
    bg: '#0A0101',
    industries: ['music', 'artist', 'musician', 'band', 'entertainment'],
    keywords: ['music', 'artist', 'musician', 'band', 'song', 'album', 'concert', 'tour', 'DJ', 'rapper', 'singer', 'producer'],
    description: 'Cinematic music artist website with discography, bookings and press kit.',
  },
  {
    id: 'ngo',
    label: 'NGO / Nonprofit',
    category: 'Social',
    color: '#66BB6A',
    bg: '#020A02',
    industries: ['NGO', 'nonprofit', 'social enterprise', 'charity', 'foundation', 'CSR'],
    keywords: ['NGO', 'nonprofit', 'charity', 'social', 'foundation', 'mission', 'impact', 'donate', 'community', 'welfare'],
    description: 'Mission-driven NGO and nonprofit website with strong social impact narrative.',
  },
  {
    id: 'noir-clothing',
    label: 'Noir Clothing',
    category: 'Fashion',
    color: '#E0E0E0',
    bg: '#030303',
    industries: ['clothing', 'fashion brand', 'streetwear', 'luxury clothing', 'apparel'],
    keywords: ['noir', 'clothing', 'fashion', 'apparel', 'streetwear', 'luxury', 'wear', 'brand', 'collection', 'dark', 'minimal'],
    description: 'Dark luxury clothing brand website with minimal editorial aesthetic.',
  },
  {
    id: 'pet-care',
    label: 'Pet Care Clinic',
    category: 'Health',
    color: '#FFAB40',
    bg: '#0A0600',
    industries: ['pet care', 'veterinary', 'animal clinic', 'pet shop', 'grooming'],
    keywords: ['pet', 'dog', 'cat', 'veterinary', 'vet', 'animal', 'grooming', 'clinic', 'care', 'boarding'],
    description: 'Warm, friendly pet care and veterinary clinic website.',
  },
  {
    id: 'photographer',
    label: 'Photographer',
    category: 'Creative',
    color: '#E0E0E0',
    bg: '#040404',
    industries: ['photography', 'photo studio', 'videography', 'creative studio'],
    keywords: ['photographer', 'photography', 'photo', 'shoot', 'portrait', 'commercial', 'camera', 'studio', 'videography', 'images'],
    description: 'Stunning photographer portfolio website with full-bleed gallery and booking CTA.',
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    category: 'Property',
    color: '#87A878',
    bg: '#030804',
    industries: ['real estate', 'property', 'realty', 'builders', 'housing', 'land developers'],
    keywords: ['real estate', 'property', 'realty', 'homes', 'flat', 'apartment', 'plot', 'builders', 'housing', 'rent', 'buy', 'developer'],
    description: 'Premium real estate and property developer website with listing showcase.',
  },
  {
    id: 'saas-startup',
    label: 'SaaS Startup',
    category: 'Tech',
    color: '#4FC3F7',
    bg: '#010A10',
    industries: ['SaaS', 'software startup', 'B2B software', 'cloud software', 'tech product'],
    keywords: ['SaaS', 'software', 'cloud', 'subscription', 'dashboard', 'API', 'platform', 'B2B', 'startup', 'product', 'tool'],
    description: 'Modern SaaS startup website with product demo, pricing, and conversion focus.',
  },
  {
    id: 'salon',
    label: 'Beauty Salon',
    category: 'Beauty',
    color: '#F48FB1',
    bg: '#0D0306',
    industries: ['salon', 'beauty salon', 'hair salon', 'spa', 'beauty parlour'],
    keywords: ['salon', 'beauty', 'hair', 'spa', 'parlour', 'nails', 'threading', 'waxing', 'facial', 'bridal', 'makeover'],
    description: 'Elegant beauty salon and hair studio website with booking and services list.',
  },
  {
    id: 'solar-company',
    label: 'Solar Company',
    category: 'Industry',
    color: '#FFD54F',
    bg: '#0A0800',
    industries: ['solar energy', 'renewable energy', 'green energy', 'solar installation'],
    keywords: ['solar', 'energy', 'panel', 'renewable', 'green', 'photovoltaic', 'installation', 'EPC', 'power', 'sustainability'],
    description: 'Clean solar energy company website with ROI calculator and installation process.',
  },
  {
    id: 'travel-agency',
    label: 'Travel Agency',
    category: 'Travel',
    color: '#4DB6AC',
    bg: '#01080A',
    industries: ['travel', 'tourism', 'tour operator', 'travel agency', 'holiday packages'],
    keywords: ['travel', 'tour', 'trip', 'holiday', 'package', 'destination', 'tourism', 'hotel', 'flights', 'visa', 'adventure'],
    description: 'Immersive travel and tourism website with destination showcases and booking CTAs.',
  },
  {
    id: 'wedding-photography',
    label: 'Wedding Photography',
    category: 'Creative',
    color: '#F8BBD9',
    bg: '#0A0305',
    industries: ['wedding photography', 'wedding videography', 'bridal photography', 'event photography'],
    keywords: ['wedding', 'photography', 'bridal', 'couple', 'portrait', 'pre-wedding', 'cinematography', 'videography', 'album'],
    description: 'Romantic wedding photography and videography portfolio website.',
  },
  {
    id: 'yoga-studio',
    label: 'Yoga Studio',
    category: 'Health',
    color: '#CE93D8',
    bg: '#060208',
    industries: ['yoga', 'meditation', 'wellness', 'mindfulness', 'spiritual', 'holistic health'],
    keywords: ['yoga', 'meditation', 'wellness', 'mindfulness', 'class', 'studio', 'holistic', 'spiritual', 'breath', 'ayurveda'],
    description: 'Calming yoga studio and wellness website with class schedules and booking.',
  },
  {
    id: "ayurvedic-clinic",
    label: "Ayurvedic Clinic",
    category: "Health",
    color: "#8DBA63",
    bg: "#071006",
    industries: ["ayurveda", "clinic", "wellness", "healthcare"],
    keywords: ["ayurveda", "ayurvedic", "panchakarma", "herbal", "wellness", "clinic"],
    description: "Premium wellness website for ayurvedic clinics, doctors and natural healthcare brands.",
  },
  {
    id: "homeopathy-clinic",
    label: "Homeopathy Clinic",
    category: "Health",
    color: "#9ACBA5",
    bg: "#06110A",
    industries: ["homeopathy", "clinic", "doctor", "wellness"],
    keywords: ["homeopathy", "homeopathic", "doctor", "clinic", "natural", "medicine"],
    description: "Trust-focused website for homeopathy clinics and natural care practitioners.",
  },
  {
    id: "physiotherapy-centre",
    label: "Physiotherapy Centre",
    category: "Health",
    color: "#6BC7D9",
    bg: "#031016",
    industries: ["physiotherapy", "clinic", "rehab", "healthcare"],
    keywords: ["physio", "physiotherapy", "rehab", "pain", "sports injury", "therapy"],
    description: "Clean therapy website for physiotherapy centres, rehab clinics and injury recovery.",
  },
  {
    id: "diagnostic-lab",
    label: "Diagnostic Lab",
    category: "Health",
    color: "#55B7FF",
    bg: "#020B14",
    industries: ["diagnostics", "lab", "healthcare", "medical"],
    keywords: ["lab", "diagnostic", "blood test", "scan", "pathology", "report"],
    description: "Professional diagnostic lab website for tests, bookings and reports.",
  },
  {
    id: "eye-clinic",
    label: "Eye Clinic",
    category: "Health",
    color: "#7DD3FC",
    bg: "#031019",
    industries: ["eye clinic", "doctor", "healthcare", "optical"],
    keywords: ["eye", "clinic", "vision", "optical", "lasik", "doctor"],
    description: "Modern eye clinic website for ophthalmologists, optical stores and vision care.",
  },
  {
    id: "dermatology-clinic",
    label: "Dermatology Clinic",
    category: "Health",
    color: "#F3A8C8",
    bg: "#12070D",
    industries: ["dermatology", "skin clinic", "healthcare", "beauty"],
    keywords: ["skin", "derma", "dermatology", "acne", "laser", "clinic"],
    description: "Premium skin clinic website for dermatologists, laser treatments and aesthetics.",
  },
  {
    id: "fertility-clinic",
    label: "Fertility Clinic",
    category: "Health",
    color: "#E8B9C8",
    bg: "#10070B",
    industries: ["fertility", "clinic", "healthcare", "doctor"],
    keywords: ["fertility", "ivf", "clinic", "motherhood", "care", "doctor"],
    description: "Sensitive and trustworthy website for fertility clinics and IVF centres.",
  },
  {
    id: "mental-wellness",
    label: "Mental Wellness",
    category: "Health",
    color: "#B9A7FF",
    bg: "#080616",
    industries: ["therapy", "psychology", "mental wellness", "healthcare"],
    keywords: ["therapy", "psychology", "counselling", "mental health", "wellness"],
    description: "Calm wellness website for therapists, counsellors and mental health practices.",
  },
  {
    id: "nutritionist",
    label: "Nutritionist",
    category: "Health",
    color: "#A6D96A",
    bg: "#071005",
    industries: ["nutritionist", "dietitian", "health", "fitness"],
    keywords: ["nutrition", "diet", "dietitian", "weight loss", "health", "meal plan"],
    description: "Fresh website for nutritionists, diet coaches and healthy lifestyle consultants.",
  },
  {
    id: "pharmacy-store",
    label: "Pharmacy Store",
    category: "Health",
    color: "#4ADE80",
    bg: "#04100A",
    industries: ["pharmacy", "medical store", "healthcare", "retail"],
    keywords: ["pharmacy", "medicine", "medical store", "health", "drugstore"],
    description: "Reliable website for pharmacies, medical stores and healthcare retail.",
  },
  {
    id: "orthopedic-clinic",
    label: "Orthopedic Clinic",
    category: "Health",
    color: "#91B4FF",
    bg: "#050C18",
    industries: ["orthopedic", "clinic", "doctor", "healthcare"],
    keywords: ["orthopedic", "bone", "joint", "knee", "spine", "doctor"],
    description: "Professional orthopedic clinic website for bone, joint and spine care.",
  },
  {
    id: "maternity-hospital",
    label: "Maternity Hospital",
    category: "Health",
    color: "#F9A8D4",
    bg: "#150611",
    industries: ["maternity", "hospital", "clinic", "healthcare"],
    keywords: ["maternity", "mother", "baby", "hospital", "pregnancy", "care"],
    description: "Warm maternity hospital website for women and child care services.",
  },
  {
    id: "veterinary-clinic",
    label: "Veterinary Clinic",
    category: "Health",
    color: "#F59E0B",
    bg: "#100902",
    industries: ["veterinary", "pet care", "clinic", "animals"],
    keywords: ["vet", "veterinary", "pet", "dog", "cat", "animal clinic"],
    description: "Friendly veterinary website for animal hospitals and pet clinics.",
  },
  {
    id: "organic-food-store",
    label: "Organic Food Store",
    category: "Food",
    color: "#84CC16",
    bg: "#091203",
    industries: ["organic food", "grocery", "retail", "food"],
    keywords: ["organic", "grocery", "farm fresh", "vegetables", "healthy food"],
    description: "Fresh e-commerce style website for organic groceries and health food stores.",
  },
  {
    id: "sweet-shop",
    label: "Indian Sweet Shop",
    category: "Food",
    color: "#F59E0B",
    bg: "#120704",
    industries: ["sweet shop", "mithai", "food", "bakery"],
    keywords: ["mithai", "sweets", "laddu", "barfi", "dessert", "indian sweets"],
    description: "Festive Indian sweet shop website for mithai brands and dessert stores.",
  },
  {
    id: "ice-cream-parlour",
    label: "Ice Cream Parlour",
    category: "Food",
    color: "#F9A8D4",
    bg: "#140812",
    industries: ["ice cream", "dessert", "cafe", "food"],
    keywords: ["ice cream", "gelato", "dessert", "parlour", "scoop"],
    description: "Playful dessert website for ice cream parlours and gelato brands.",
  },
  {
    id: "juice-bar",
    label: "Juice Bar",
    category: "Food",
    color: "#22C55E",
    bg: "#041006",
    industries: ["juice bar", "beverage", "health food", "cafe"],
    keywords: ["juice", "smoothie", "shake", "healthy", "fresh", "bar"],
    description: "Fresh beverage website for juice bars, smoothie shops and healthy cafes.",
  },
  {
    id: "tea-brand",
    label: "Tea Brand",
    category: "Food",
    color: "#A3A15B",
    bg: "#0F0E04",
    industries: ["tea", "beverage", "cafe", "retail"],
    keywords: ["tea", "chai", "green tea", "beverage", "brew"],
    description: "Premium tea brand website for chai, tea estates and packaged beverage brands.",
  },
  {
    id: "catering-service",
    label: "Catering Service",
    category: "Food",
    color: "#F97316",
    bg: "#120604",
    industries: ["catering", "events", "food", "restaurant"],
    keywords: ["catering", "event food", "buffet", "wedding catering", "party"],
    description: "High-conversion catering website for events, weddings and corporate food services.",
  },
  {
    id: "pizza-brand",
    label: "Pizza Brand",
    category: "Food",
    color: "#EF4444",
    bg: "#120303",
    industries: ["pizza", "restaurant", "cloud kitchen", "food"],
    keywords: ["pizza", "pizzeria", "delivery", "cheese", "slice", "restaurant"],
    description: "Bold pizza brand website for pizzerias, delivery kitchens and fast food brands.",
  },
  {
    id: "vegan-cafe",
    label: "Vegan Café",
    category: "Food",
    color: "#65A30D",
    bg: "#081004",
    industries: ["vegan cafe", "restaurant", "healthy food", "cafe"],
    keywords: ["vegan", "plant based", "cafe", "healthy", "organic"],
    description: "Modern vegan café website for plant-based food businesses.",
  },
  {
    id: "bar-lounge",
    label: "Bar & Lounge",
    category: "Hospitality",
    color: "#A855F7",
    bg: "#090411",
    industries: ["bar", "lounge", "restaurant", "hospitality"],
    keywords: ["bar", "lounge", "cocktail", "nightlife", "club"],
    description: "Premium nightlife website for bars, lounges and evening venues.",
  },
  {
    id: "banquet-hall",
    label: "Banquet Hall",
    category: "Events",
    color: "#D4AF37",
    bg: "#100804",
    industries: ["banquet", "wedding venue", "events", "hospitality"],
    keywords: ["banquet", "venue", "wedding hall", "party hall", "events"],
    description: "Elegant venue website for banquet halls and wedding/event spaces.",
  },
  {
    id: "luxury-spa-resort",
    label: "Luxury Spa Resort",
    category: "Hospitality",
    color: "#C8A46A",
    bg: "#090705",
    industries: ["spa resort", "hotel", "hospitality", "wellness"],
    keywords: ["spa", "resort", "luxury stay", "wellness", "retreat"],
    description: "Luxury resort website for wellness stays, spa hotels and retreats.",
  },
  {
    id: "homestay",
    label: "Homestay",
    category: "Hospitality",
    color: "#8BB174",
    bg: "#071006",
    industries: ["homestay", "hotel", "travel", "hospitality"],
    keywords: ["homestay", "stay", "bnb", "rooms", "travel"],
    description: "Warm homestay website for boutique stays, rooms and local travel experiences.",
  },
  {
    id: "hostel",
    label: "Youth Hostel",
    category: "Hospitality",
    color: "#38BDF8",
    bg: "#03101A",
    industries: ["hostel", "travel", "hospitality", "student"],
    keywords: ["hostel", "backpacker", "stay", "dorm", "budget travel"],
    description: "Energetic hostel website for backpacker stays and student accommodation.",
  },
  {
    id: "coworking-space",
    label: "Coworking Space",
    category: "Property",
    color: "#7C3AED",
    bg: "#060412",
    industries: ["coworking", "office space", "startup", "property"],
    keywords: ["coworking", "office", "workspace", "startup", "desk", "meeting room"],
    description: "Modern coworking website for workspace rentals, startups and office communities.",
  },
  {
    id: "pg-hostel",
    label: "PG & Hostel",
    category: "Property",
    color: "#06B6D4",
    bg: "#041018",
    industries: ["pg", "hostel", "rental", "property"],
    keywords: ["pg", "hostel", "room", "rent", "student", "accommodation"],
    description: "Practical rental website for PGs, hostels and student housing.",
  },
  {
    id: "luxury-villa-rental",
    label: "Luxury Villa Rental",
    category: "Property",
    color: "#D4AF37",
    bg: "#090806",
    industries: ["villa rental", "real estate", "hospitality", "travel"],
    keywords: ["villa", "luxury stay", "rental", "pool villa", "vacation home"],
    description: "Premium website for villa rentals, luxury stays and vacation homes.",
  },
  {
    id: "interior-luxury-studio",
    label: "Luxury Interior Studio",
    category: "Design",
    color: "#C6A47E",
    bg: "#090705",
    industries: ["interior design", "luxury design", "home decor"],
    keywords: ["interior", "luxury", "villa", "decor", "renovation"],
    description: "High-end interior design website for luxury homes and design studios.",
  },
  {
    id: "modular-kitchen",
    label: "Modular Kitchen",
    category: "Design",
    color: "#F59E0B",
    bg: "#0F0802",
    industries: ["modular kitchen", "interior", "furniture", "home"],
    keywords: ["modular kitchen", "cabinet", "interior", "home", "renovation"],
    description: "Conversion-led modular kitchen website for home improvement brands.",
  },
  {
    id: "lighting-store",
    label: "Lighting Store",
    category: "Design",
    color: "#FDE68A",
    bg: "#100D03",
    industries: ["lighting", "home decor", "retail", "interior"],
    keywords: ["lighting", "lamp", "chandelier", "home decor", "led"],
    description: "Premium lighting store website for decor, lamps and architectural lighting brands.",
  },
  {
    id: "tiles-showroom",
    label: "Tiles Showroom",
    category: "Design",
    color: "#A8A29E",
    bg: "#0D0C0B",
    industries: ["tiles", "home decor", "construction", "retail"],
    keywords: ["tiles", "ceramic", "marble", "flooring", "showroom"],
    description: "Clean showroom website for tiles, marble and flooring retailers.",
  },
  {
    id: "home-decor-store",
    label: "Home Décor Store",
    category: "Design",
    color: "#C084FC",
    bg: "#0B0612",
    industries: ["home decor", "retail", "furniture", "interior"],
    keywords: ["decor", "home decor", "wall art", "vase", "furnishing"],
    description: "Stylish home decor website for furnishings, decor products and lifestyle retail.",
  },
  {
    id: "landscape-design",
    label: "Landscape Design",
    category: "Design",
    color: "#7BA05B",
    bg: "#061006",
    industries: ["landscaping", "garden", "design", "architecture"],
    keywords: ["landscape", "garden", "outdoor", "plants", "design"],
    description: "Natural design website for landscaping, garden and outdoor space businesses.",
  },
]
