// Auto-split chunk 5 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_05: WebsiteTemplate[] = [
  {
    id: 'bsx-school-transport-tracking-magazine',
    label: 'School Transport Tracking — Magazine Edition',
    category: 'SafetyTech',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking magazine', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'magazine', 'magazine edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-school-transport-tracking-enterprise',
    label: 'School Transport Tracking — Enterprise Edition',
    category: 'SafetyTech',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['safetytech', 'school transport tracking', 'school transport tracking enterprise', 'gps routes', 'parent app', 'attendance scan', 'speed alerts'],
    keywords: ['safetytech', 'school transport tracking', 'enterprise', 'enterprise edition', 'buses', 'parents', 'alerts', 'routes', 'demo', 'GPS routes', 'parent app', 'attendance scan', 'speed alerts', 'driver checks'],
    description: 'Standalone unique SafetyTech website template for School Transport Tracking, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-signal',
    label: 'Water Purification Company — Signal Edition',
    category: 'Utilities',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['utilities', 'water purification company', 'water purification company signal', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'signal', 'signal edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-atelier',
    label: 'Water Purification Company — Atelier Edition',
    category: 'Utilities',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['utilities', 'water purification company', 'water purification company atelier', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'atelier', 'atelier edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-local',
    label: 'Water Purification Company — Local Growth Edition',
    category: 'Utilities',
    color: '#118AB2',
    bg: '#060606',
    industries: ['utilities', 'water purification company', 'water purification company local', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'local', 'local growth edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-commerce',
    label: 'Water Purification Company — Commerce Edition',
    category: 'Utilities',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['utilities', 'water purification company', 'water purification company commerce', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'commerce', 'commerce edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-booking',
    label: 'Water Purification Company — Booking Edition',
    category: 'Utilities',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['utilities', 'water purification company', 'water purification company booking', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'booking', 'booking edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-trust',
    label: 'Water Purification Company — Trust Edition',
    category: 'Utilities',
    color: '#F97316',
    bg: '#100A04',
    industries: ['utilities', 'water purification company', 'water purification company trust', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'trust', 'trust edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-magazine',
    label: 'Water Purification Company — Magazine Edition',
    category: 'Utilities',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['utilities', 'water purification company', 'water purification company magazine', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'magazine', 'magazine edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-water-purification-company-enterprise',
    label: 'Water Purification Company — Enterprise Edition',
    category: 'Utilities',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['utilities', 'water purification company', 'water purification company enterprise', 'ro plants', 'water tests', 'amc service', 'industrial setup'],
    keywords: ['utilities', 'water purification company', 'enterprise', 'enterprise edition', 'systems', 'quality', 'service', 'projects', 'enquire', 'RO plants', 'water tests', 'AMC service', 'industrial setup', 'purity reports'],
    description: 'Standalone unique Utilities website template for Water Purification Company, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-signal',
    label: 'Regional News Network — Signal Edition',
    category: 'Media',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['media', 'regional news network', 'regional news network signal', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'signal', 'signal edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-atelier',
    label: 'Regional News Network — Atelier Edition',
    category: 'Media',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['media', 'regional news network', 'regional news network atelier', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'atelier', 'atelier edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-local',
    label: 'Regional News Network — Local Growth Edition',
    category: 'Media',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['media', 'regional news network', 'regional news network local', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'local', 'local growth edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-commerce',
    label: 'Regional News Network — Commerce Edition',
    category: 'Media',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['media', 'regional news network', 'regional news network commerce', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'commerce', 'commerce edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-booking',
    label: 'Regional News Network — Booking Edition',
    category: 'Media',
    color: '#10B981',
    bg: '#010A05',
    industries: ['media', 'regional news network', 'regional news network booking', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'booking', 'booking edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-trust',
    label: 'Regional News Network — Trust Edition',
    category: 'Media',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['media', 'regional news network', 'regional news network trust', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'trust', 'trust edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-magazine',
    label: 'Regional News Network — Magazine Edition',
    category: 'Media',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['media', 'regional news network', 'regional news network magazine', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'magazine', 'magazine edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-regional-news-network-enterprise',
    label: 'Regional News Network — Enterprise Edition',
    category: 'Media',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['media', 'regional news network', 'regional news network enterprise', 'district desks', 'video bulletins', 'ad slots', 'reader clubs'],
    keywords: ['media', 'regional news network', 'enterprise', 'enterprise edition', 'news', 'districts', 'video', 'advertise', 'subscribe', 'district desks', 'video bulletins', 'ad slots', 'reader clubs', 'breaking alerts'],
    description: 'Standalone unique Media website template for Regional News Network, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-signal',
    label: 'Premium Furniture Atelier — Signal Edition',
    category: 'Home',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier signal', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'signal', 'signal edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-atelier',
    label: 'Premium Furniture Atelier — Atelier Edition',
    category: 'Home',
    color: '#A3E635',
    bg: '#050313',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier atelier', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'atelier', 'atelier edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-local',
    label: 'Premium Furniture Atelier — Local Growth Edition',
    category: 'Home',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier local', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'local', 'local growth edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-commerce',
    label: 'Premium Furniture Atelier — Commerce Edition',
    category: 'Home',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier commerce', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'commerce', 'commerce edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-booking',
    label: 'Premium Furniture Atelier — Booking Edition',
    category: 'Home',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier booking', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'booking', 'booking edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-trust',
    label: 'Premium Furniture Atelier — Trust Edition',
    category: 'Home',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier trust', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'trust', 'trust edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-magazine',
    label: 'Premium Furniture Atelier — Magazine Edition',
    category: 'Home',
    color: '#FFD166',
    bg: '#101112',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier magazine', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'magazine', 'magazine edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-premium-furniture-atelier-enterprise',
    label: 'Premium Furniture Atelier — Enterprise Edition',
    category: 'Home',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['home', 'premium furniture atelier', 'premium furniture atelier enterprise', 'solid wood', 'custom sofas', 'fabric options', 'room styling'],
    keywords: ['home', 'premium furniture atelier', 'enterprise', 'enterprise edition', 'collections', 'craft', 'custom', 'projects', 'visit', 'solid wood', 'custom sofas', 'fabric options', 'room styling', 'delivery setup'],
    description: 'Standalone unique Home website template for Premium Furniture Atelier, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-signal',
    label: 'Spiritual Yoga Ashram — Signal Edition',
    category: 'Spiritual',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram signal', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'signal', 'signal edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-atelier',
    label: 'Spiritual Yoga Ashram — Atelier Edition',
    category: 'Spiritual',
    color: '#118AB2',
    bg: '#100808',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram atelier', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'atelier', 'atelier edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-local',
    label: 'Spiritual Yoga Ashram — Local Growth Edition',
    category: 'Spiritual',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram local', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'local', 'local growth edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-commerce',
    label: 'Spiritual Yoga Ashram — Commerce Edition',
    category: 'Spiritual',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram commerce', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'commerce', 'commerce edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-booking',
    label: 'Spiritual Yoga Ashram — Booking Edition',
    category: 'Spiritual',
    color: '#F97316',
    bg: '#09111f',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram booking', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'booking', 'booking edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-trust',
    label: 'Spiritual Yoga Ashram — Trust Edition',
    category: 'Spiritual',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram trust', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'trust', 'trust edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-magazine',
    label: 'Spiritual Yoga Ashram — Magazine Edition',
    category: 'Spiritual',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram magazine', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'magazine', 'magazine edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-spiritual-yoga-ashram-enterprise',
    label: 'Spiritual Yoga Ashram — Enterprise Edition',
    category: 'Spiritual',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['spiritual', 'spiritual yoga ashram', 'spiritual yoga ashram enterprise', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats'],
    keywords: ['spiritual', 'spiritual yoga ashram', 'enterprise', 'enterprise edition', 'practices', 'teachers', 'retreats', 'schedule', 'join', 'morning sadhana', 'meditation hall', 'teacher lineage', 'residential retreats', 'daily rituals'],
    description: 'Standalone unique Spiritual website template for Spiritual Yoga Ashram, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-signal',
    label: 'Creative Recruitment Agency — Signal Edition',
    category: 'HR',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency signal', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'signal', 'signal edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-atelier',
    label: 'Creative Recruitment Agency — Atelier Edition',
    category: 'HR',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency atelier', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'atelier', 'atelier edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-local',
    label: 'Creative Recruitment Agency — Local Growth Edition',
    category: 'HR',
    color: '#EF4444',
    bg: '#120817',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency local', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'local', 'local growth edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-commerce',
    label: 'Creative Recruitment Agency — Commerce Edition',
    category: 'HR',
    color: '#10B981',
    bg: '#050313',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency commerce', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'commerce', 'commerce edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-booking',
    label: 'Creative Recruitment Agency — Booking Edition',
    category: 'HR',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency booking', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'booking', 'booking edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-trust',
    label: 'Creative Recruitment Agency — Trust Edition',
    category: 'HR',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency trust', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'trust', 'trust edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-magazine',
    label: 'Creative Recruitment Agency — Magazine Edition',
    category: 'HR',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency magazine', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'magazine', 'magazine edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-creative-recruitment-agency-enterprise',
    label: 'Creative Recruitment Agency — Enterprise Edition',
    category: 'HR',
    color: '#A3E635',
    bg: '#111827',
    industries: ['hr', 'creative recruitment agency', 'creative recruitment agency enterprise', 'portfolio screening', 'role mapping', 'interview loops', 'offer support'],
    keywords: ['hr', 'creative recruitment agency', 'enterprise', 'enterprise edition', 'talent', 'roles', 'process', 'clients', 'hire', 'portfolio screening', 'role mapping', 'interview loops', 'offer support', 'talent pools'],
    description: 'Standalone unique HR website template for Creative Recruitment Agency, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-signal',
    label: 'Luxury Watch Resale — Signal Edition',
    category: 'Luxury Retail',
    color: '#A3E635',
    bg: '#111827',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale signal', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'signal', 'signal edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-atelier',
    label: 'Luxury Watch Resale — Atelier Edition',
    category: 'Luxury Retail',
    color: '#FB7185',
    bg: '#101112',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale atelier', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'atelier', 'atelier edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-local',
    label: 'Luxury Watch Resale — Local Growth Edition',
    category: 'Luxury Retail',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale local', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'local', 'local growth edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-commerce',
    label: 'Luxury Watch Resale — Commerce Edition',
    category: 'Luxury Retail',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale commerce', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'commerce', 'commerce edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-booking',
    label: 'Luxury Watch Resale — Booking Edition',
    category: 'Luxury Retail',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale booking', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'booking', 'booking edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-trust',
    label: 'Luxury Watch Resale — Trust Edition',
    category: 'Luxury Retail',
    color: '#FFD166',
    bg: '#031316',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale trust', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'trust', 'trust edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-magazine',
    label: 'Luxury Watch Resale — Magazine Edition',
    category: 'Luxury Retail',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale magazine', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'magazine', 'magazine edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-luxury-watch-resale-enterprise',
    label: 'Luxury Watch Resale — Enterprise Edition',
    category: 'Luxury Retail',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['luxury retail', 'luxury watch resale', 'luxury watch resale enterprise', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports'],
    keywords: ['luxury retail', 'luxury watch resale', 'enterprise', 'enterprise edition', 'watches', 'authentication', 'sell', 'stories', 'enquire', 'authentication lab', 'collector pieces', 'buyback support', 'condition reports', 'secure shipping'],
    description: 'Standalone unique Luxury Retail website template for Luxury Watch Resale, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-signal',
    label: 'Baking Masterclass Academy — Signal Edition',
    category: 'Education',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy signal', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'signal', 'signal edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-atelier',
    label: 'Baking Masterclass Academy — Atelier Edition',
    category: 'Education',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy atelier', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'atelier', 'atelier edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-local',
    label: 'Baking Masterclass Academy — Local Growth Edition',
    category: 'Education',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy local', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'local', 'local growth edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-commerce',
    label: 'Baking Masterclass Academy — Commerce Edition',
    category: 'Education',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy commerce', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'commerce', 'commerce edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-booking',
    label: 'Baking Masterclass Academy — Booking Edition',
    category: 'Education',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy booking', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'booking', 'booking edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-trust',
    label: 'Baking Masterclass Academy — Trust Edition',
    category: 'Education',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy trust', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'trust', 'trust edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-magazine',
    label: 'Baking Masterclass Academy — Magazine Edition',
    category: 'Education',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy magazine', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'magazine', 'magazine edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-baking-masterclass-academy-enterprise',
    label: 'Baking Masterclass Academy — Enterprise Edition',
    category: 'Education',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['education', 'baking masterclass academy', 'baking masterclass academy enterprise', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits'],
    keywords: ['education', 'baking masterclass academy', 'enterprise', 'enterprise edition', 'classes', 'chefs', 'recipes', 'kits', 'enroll', 'hands-on baking', 'chef mentors', 'recipe vault', 'ingredient kits', 'certificate classes'],
    description: 'Standalone unique Education website template for Baking Masterclass Academy, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-signal',
    label: 'Mobile Repair Lab — Signal Edition',
    category: 'Repair',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab signal', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'signal', 'signal edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-atelier',
    label: 'Mobile Repair Lab — Atelier Edition',
    category: 'Repair',
    color: '#EF4444',
    bg: '#060606',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab atelier', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'atelier', 'atelier edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-local',
    label: 'Mobile Repair Lab — Local Growth Edition',
    category: 'Repair',
    color: '#10B981',
    bg: '#111827',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab local', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'local', 'local growth edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-commerce',
    label: 'Mobile Repair Lab — Commerce Edition',
    category: 'Repair',
    color: '#F472B6',
    bg: '#101112',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab commerce', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'commerce', 'commerce edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-booking',
    label: 'Mobile Repair Lab — Booking Edition',
    category: 'Repair',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab booking', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'booking', 'booking edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-trust',
    label: 'Mobile Repair Lab — Trust Edition',
    category: 'Repair',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab trust', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'trust', 'trust edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-magazine',
    label: 'Mobile Repair Lab — Magazine Edition',
    category: 'Repair',
    color: '#A3E635',
    bg: '#080501',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab magazine', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'magazine', 'magazine edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-mobile-repair-lab-enterprise',
    label: 'Mobile Repair Lab — Enterprise Edition',
    category: 'Repair',
    color: '#FB7185',
    bg: '#031316',
    industries: ['repair', 'mobile repair lab', 'mobile repair lab enterprise', 'screen repair', 'battery replacement', 'data safety', 'job tracking'],
    keywords: ['repair', 'mobile repair lab', 'enterprise', 'enterprise edition', 'repairs', 'parts', 'warranty', 'tracking', 'book', 'screen repair', 'battery replacement', 'data safety', 'job tracking', 'pickup drop'],
    description: 'Standalone unique Repair website template for Mobile Repair Lab, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-signal',
    label: 'Indie Game Studio — Signal Edition',
    category: 'Gaming',
    color: '#FB7185',
    bg: '#031316',
    industries: ['gaming', 'indie game studio', 'indie game studio signal', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'signal', 'signal edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-atelier',
    label: 'Indie Game Studio — Atelier Edition',
    category: 'Gaming',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['gaming', 'indie game studio', 'indie game studio atelier', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'atelier', 'atelier edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-local',
    label: 'Indie Game Studio — Local Growth Edition',
    category: 'Gaming',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['gaming', 'indie game studio', 'indie game studio local', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'local', 'local growth edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-commerce',
    label: 'Indie Game Studio — Commerce Edition',
    category: 'Gaming',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['gaming', 'indie game studio', 'indie game studio commerce', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'commerce', 'commerce edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-booking',
    label: 'Indie Game Studio — Booking Edition',
    category: 'Gaming',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['gaming', 'indie game studio', 'indie game studio booking', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'booking', 'booking edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-trust',
    label: 'Indie Game Studio — Trust Edition',
    category: 'Gaming',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['gaming', 'indie game studio', 'indie game studio trust', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'trust', 'trust edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-magazine',
    label: 'Indie Game Studio — Magazine Edition',
    category: 'Gaming',
    color: '#118AB2',
    bg: '#120817',
    industries: ['gaming', 'indie game studio', 'indie game studio magazine', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'magazine', 'magazine edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-indie-game-studio-enterprise',
    label: 'Indie Game Studio — Enterprise Edition',
    category: 'Gaming',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['gaming', 'indie game studio', 'indie game studio enterprise', 'game trailers', 'world building', 'dev updates', 'community polls'],
    keywords: ['gaming', 'indie game studio', 'enterprise', 'enterprise edition', 'games', 'worlds', 'devlog', 'community', 'play', 'game trailers', 'world building', 'dev updates', 'community polls', 'early access'],
    description: 'Standalone unique Gaming website template for Indie Game Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-signal',
    label: 'Museum Learning Centre — Signal Edition',
    category: 'Culture',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['culture', 'museum learning centre', 'museum learning centre signal', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'signal', 'signal edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-atelier',
    label: 'Museum Learning Centre — Atelier Edition',
    category: 'Culture',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['culture', 'museum learning centre', 'museum learning centre atelier', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'atelier', 'atelier edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-local',
    label: 'Museum Learning Centre — Local Growth Edition',
    category: 'Culture',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['culture', 'museum learning centre', 'museum learning centre local', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'local', 'local growth edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-commerce',
    label: 'Museum Learning Centre — Commerce Edition',
    category: 'Culture',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['culture', 'museum learning centre', 'museum learning centre commerce', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'commerce', 'commerce edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-booking',
    label: 'Museum Learning Centre — Booking Edition',
    category: 'Culture',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['culture', 'museum learning centre', 'museum learning centre booking', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'booking', 'booking edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-trust',
    label: 'Museum Learning Centre — Trust Edition',
    category: 'Culture',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['culture', 'museum learning centre', 'museum learning centre trust', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'trust', 'trust edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-magazine',
    label: 'Museum Learning Centre — Magazine Edition',
    category: 'Culture',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['culture', 'museum learning centre', 'museum learning centre magazine', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'magazine', 'magazine edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-museum-learning-centre-enterprise',
    label: 'Museum Learning Centre — Enterprise Edition',
    category: 'Culture',
    color: '#EF4444',
    bg: '#100808',
    industries: ['culture', 'museum learning centre', 'museum learning centre enterprise', 'curated exhibits', 'school tours', 'audio guides', 'membership cards'],
    keywords: ['culture', 'museum learning centre', 'enterprise', 'enterprise edition', 'exhibits', 'programs', 'tickets', 'schools', 'visit', 'curated exhibits', 'school tours', 'audio guides', 'membership cards', 'event calendar'],
    description: 'Standalone unique Culture website template for Museum Learning Centre, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-signal',
    label: 'Perfume Discovery House — Signal Edition',
    category: 'Beauty',
    color: '#EF4444',
    bg: '#100808',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house signal', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'signal', 'signal edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-atelier',
    label: 'Perfume Discovery House — Atelier Edition',
    category: 'Beauty',
    color: '#10B981',
    bg: '#080501',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house atelier', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'atelier', 'atelier edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-local',
    label: 'Perfume Discovery House — Local Growth Edition',
    category: 'Beauty',
    color: '#F472B6',
    bg: '#031316',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house local', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'local', 'local growth edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-commerce',
    label: 'Perfume Discovery House — Commerce Edition',
    category: 'Beauty',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house commerce', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'commerce', 'commerce edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-booking',
    label: 'Perfume Discovery House — Booking Edition',
    category: 'Beauty',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house booking', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'booking', 'booking edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-trust',
    label: 'Perfume Discovery House — Trust Edition',
    category: 'Beauty',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house trust', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'trust', 'trust edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-magazine',
    label: 'Perfume Discovery House — Magazine Edition',
    category: 'Beauty',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house magazine', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'magazine', 'magazine edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-perfume-discovery-house-enterprise',
    label: 'Perfume Discovery House — Enterprise Edition',
    category: 'Beauty',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['beauty', 'perfume discovery house', 'perfume discovery house enterprise', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz'],
    keywords: ['beauty', 'perfume discovery house', 'enterprise', 'enterprise edition', 'scents', 'notes', 'rituals', 'gifts', 'shop', 'scent notes', 'discovery sets', 'gifting rituals', 'personal quiz', 'fragrance layering'],
    description: 'Standalone unique Beauty website template for Perfume Discovery House, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-signal',
    label: 'City Marathon Event — Signal Edition',
    category: 'Sports',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['sports', 'city marathon event', 'city marathon event signal', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'signal', 'signal edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-atelier',
    label: 'City Marathon Event — Atelier Edition',
    category: 'Sports',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['sports', 'city marathon event', 'city marathon event atelier', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'atelier', 'atelier edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-local',
    label: 'City Marathon Event — Local Growth Edition',
    category: 'Sports',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['sports', 'city marathon event', 'city marathon event local', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'local', 'local growth edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-commerce',
    label: 'City Marathon Event — Commerce Edition',
    category: 'Sports',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['sports', 'city marathon event', 'city marathon event commerce', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'commerce', 'commerce edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-booking',
    label: 'City Marathon Event — Booking Edition',
    category: 'Sports',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['sports', 'city marathon event', 'city marathon event booking', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'booking', 'booking edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-trust',
    label: 'City Marathon Event — Trust Edition',
    category: 'Sports',
    color: '#118AB2',
    bg: '#060606',
    industries: ['sports', 'city marathon event', 'city marathon event trust', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'trust', 'trust edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-magazine',
    label: 'City Marathon Event — Magazine Edition',
    category: 'Sports',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['sports', 'city marathon event', 'city marathon event magazine', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'magazine', 'magazine edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-city-marathon-event-enterprise',
    label: 'City Marathon Event — Enterprise Edition',
    category: 'Sports',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['sports', 'city marathon event', 'city marathon event enterprise', 'race routes', 'timing chips', 'training plans', 'sponsor blocks'],
    keywords: ['sports', 'city marathon event', 'enterprise', 'enterprise edition', 'race', 'routes', 'training', 'sponsors', 'register', 'race routes', 'timing chips', 'training plans', 'sponsor blocks', 'runner kits'],
    description: 'Standalone unique Sports website template for City Marathon Event, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-signal',
    label: 'Corporate Gifting Studio — Signal Edition',
    category: 'Gifting',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio signal', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'signal', 'signal edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-atelier',
    label: 'Corporate Gifting Studio — Atelier Edition',
    category: 'Gifting',
    color: '#F97316',
    bg: '#100A04',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio atelier', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'atelier', 'atelier edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-local',
    label: 'Corporate Gifting Studio — Local Growth Edition',
    category: 'Gifting',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio local', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'local', 'local growth edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-commerce',
    label: 'Corporate Gifting Studio — Commerce Edition',
    category: 'Gifting',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio commerce', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'commerce', 'commerce edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-booking',
    label: 'Corporate Gifting Studio — Booking Edition',
    category: 'Gifting',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio booking', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'booking', 'booking edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-trust',
    label: 'Corporate Gifting Studio — Trust Edition',
    category: 'Gifting',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio trust', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'trust', 'trust edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-magazine',
    label: 'Corporate Gifting Studio — Magazine Edition',
    category: 'Gifting',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio magazine', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'magazine', 'magazine edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-gifting-studio-enterprise',
    label: 'Corporate Gifting Studio — Enterprise Edition',
    category: 'Gifting',
    color: '#10B981',
    bg: '#010A05',
    industries: ['gifting', 'corporate gifting studio', 'corporate gifting studio enterprise', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking'],
    keywords: ['gifting', 'corporate gifting studio', 'enterprise', 'enterprise edition', 'catalogues', 'custom', 'bulk', 'delivery', 'quote', 'gift catalogues', 'logo branding', 'bulk packing', 'delivery tracking', 'festival kits'],
    description: 'Standalone unique Gifting website template for Corporate Gifting Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-signal',
    label: 'Organic Tea Estate — Signal Edition',
    category: 'Beverage',
    color: '#10B981',
    bg: '#010A05',
    industries: ['beverage', 'organic tea estate', 'organic tea estate signal', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'signal', 'signal edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-atelier',
    label: 'Organic Tea Estate — Atelier Edition',
    category: 'Beverage',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['beverage', 'organic tea estate', 'organic tea estate atelier', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'atelier', 'atelier edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-local',
    label: 'Organic Tea Estate — Local Growth Edition',
    category: 'Beverage',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['beverage', 'organic tea estate', 'organic tea estate local', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'local', 'local growth edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-commerce',
    label: 'Organic Tea Estate — Commerce Edition',
    category: 'Beverage',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['beverage', 'organic tea estate', 'organic tea estate commerce', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'commerce', 'commerce edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-booking',
    label: 'Organic Tea Estate — Booking Edition',
    category: 'Beverage',
    color: '#A3E635',
    bg: '#050313',
    industries: ['beverage', 'organic tea estate', 'organic tea estate booking', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'booking', 'booking edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-trust',
    label: 'Organic Tea Estate — Trust Edition',
    category: 'Beverage',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['beverage', 'organic tea estate', 'organic tea estate trust', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'trust', 'trust edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-magazine',
    label: 'Organic Tea Estate — Magazine Edition',
    category: 'Beverage',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['beverage', 'organic tea estate', 'organic tea estate magazine', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'magazine', 'magazine edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-organic-tea-estate-enterprise',
    label: 'Organic Tea Estate — Enterprise Edition',
    category: 'Beverage',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['beverage', 'organic tea estate', 'organic tea estate enterprise', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs'],
    keywords: ['beverage', 'organic tea estate', 'enterprise', 'enterprise edition', 'teas', 'estate', 'tastings', 'wholesale', 'shop', 'estate grown tea', 'tasting notes', 'tea subscriptions', 'wholesale packs', 'farm stories'],
    description: 'Standalone unique Beverage website template for Organic Tea Estate, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-warehouse-automation-saas-signal',
    label: 'Warehouse Automation SaaS — Signal Edition',
    category: 'SaaS',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['saas', 'warehouse automation saas', 'warehouse automation saas signal', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts'],
    keywords: ['saas', 'warehouse automation saas', 'signal', 'signal edition', 'inventory', 'scanning', 'robots', 'reports', 'demo', 'barcode flows', 'pick lists', 'robot zones', 'stock alerts', 'manager dashboard'],
    description: 'Standalone unique SaaS website template for Warehouse Automation SaaS, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
