// Auto-split chunk 3 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_03: WebsiteTemplate[] = [
  {
    id: 'bsx-ceramic-tableware-brand-signal',
    label: 'Ceramic Tableware Brand — Signal Edition',
    category: 'Retail',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand signal', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'signal', 'signal edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-atelier',
    label: 'Ceramic Tableware Brand — Atelier Edition',
    category: 'Retail',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand atelier', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'atelier', 'atelier edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-local',
    label: 'Ceramic Tableware Brand — Local Growth Edition',
    category: 'Retail',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand local', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'local', 'local growth edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-commerce',
    label: 'Ceramic Tableware Brand — Commerce Edition',
    category: 'Retail',
    color: '#FFD166',
    bg: '#031316',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand commerce', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'commerce', 'commerce edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-booking',
    label: 'Ceramic Tableware Brand — Booking Edition',
    category: 'Retail',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand booking', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'booking', 'booking edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-trust',
    label: 'Ceramic Tableware Brand — Trust Edition',
    category: 'Retail',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand trust', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'trust', 'trust edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-magazine',
    label: 'Ceramic Tableware Brand — Magazine Edition',
    category: 'Retail',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand magazine', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'magazine', 'magazine edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ceramic-tableware-brand-enterprise',
    label: 'Ceramic Tableware Brand — Enterprise Edition',
    category: 'Retail',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['retail', 'ceramic tableware brand', 'ceramic tableware brand enterprise', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes'],
    keywords: ['retail', 'ceramic tableware brand', 'enterprise', 'enterprise edition', 'collections', 'craft', 'sets', 'care', 'shop', 'handmade plates', 'dinner sets', 'glaze stories', 'gift boxes', 'studio visits'],
    description: 'Standalone unique Retail website template for Ceramic Tableware Brand, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-signal',
    label: 'Microbrewery Experience — Signal Edition',
    category: 'Hospitality',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience signal', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'signal', 'signal edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-atelier',
    label: 'Microbrewery Experience — Atelier Edition',
    category: 'Hospitality',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience atelier', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'atelier', 'atelier edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-local',
    label: 'Microbrewery Experience — Local Growth Edition',
    category: 'Hospitality',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience local', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'local', 'local growth edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-commerce',
    label: 'Microbrewery Experience — Commerce Edition',
    category: 'Hospitality',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience commerce', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'commerce', 'commerce edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-booking',
    label: 'Microbrewery Experience — Booking Edition',
    category: 'Hospitality',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience booking', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'booking', 'booking edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-trust',
    label: 'Microbrewery Experience — Trust Edition',
    category: 'Hospitality',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience trust', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'trust', 'trust edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-magazine',
    label: 'Microbrewery Experience — Magazine Edition',
    category: 'Hospitality',
    color: '#EF4444',
    bg: '#060606',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience magazine', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'magazine', 'magazine edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-microbrewery-experience-enterprise',
    label: 'Microbrewery Experience — Enterprise Edition',
    category: 'Hospitality',
    color: '#10B981',
    bg: '#111827',
    industries: ['hospitality', 'microbrewery experience', 'microbrewery experience enterprise', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours'],
    keywords: ['hospitality', 'microbrewery experience', 'enterprise', 'enterprise edition', 'brews', 'food', 'events', 'tours', 'visit', 'brew menu', 'tasting flights', 'taproom events', 'brewery tours', 'private tables'],
    description: 'Standalone unique Hospitality website template for Microbrewery Experience, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-signal',
    label: 'Kids Learning Lab — Signal Edition',
    category: 'Education',
    color: '#10B981',
    bg: '#111827',
    industries: ['education', 'kids learning lab', 'kids learning lab signal', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'signal', 'signal edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-atelier',
    label: 'Kids Learning Lab — Atelier Edition',
    category: 'Education',
    color: '#F472B6',
    bg: '#101112',
    industries: ['education', 'kids learning lab', 'kids learning lab atelier', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'atelier', 'atelier edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-local',
    label: 'Kids Learning Lab — Local Growth Edition',
    category: 'Education',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['education', 'kids learning lab', 'kids learning lab local', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'local', 'local growth edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-commerce',
    label: 'Kids Learning Lab — Commerce Edition',
    category: 'Education',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['education', 'kids learning lab', 'kids learning lab commerce', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'commerce', 'commerce edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-booking',
    label: 'Kids Learning Lab — Booking Edition',
    category: 'Education',
    color: '#A3E635',
    bg: '#080501',
    industries: ['education', 'kids learning lab', 'kids learning lab booking', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'booking', 'booking edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-trust',
    label: 'Kids Learning Lab — Trust Edition',
    category: 'Education',
    color: '#FB7185',
    bg: '#031316',
    industries: ['education', 'kids learning lab', 'kids learning lab trust', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'trust', 'trust edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-magazine',
    label: 'Kids Learning Lab — Magazine Edition',
    category: 'Education',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['education', 'kids learning lab', 'kids learning lab magazine', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'magazine', 'magazine edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-kids-learning-lab-enterprise',
    label: 'Kids Learning Lab — Enterprise Edition',
    category: 'Education',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['education', 'kids learning lab', 'kids learning lab enterprise', 'stem kits', 'story rooms', 'parent updates', 'activity calendar'],
    keywords: ['education', 'kids learning lab', 'enterprise', 'enterprise edition', 'programs', 'activities', 'mentors', 'safety', 'join', 'STEM kits', 'story rooms', 'parent updates', 'activity calendar', 'skill badges'],
    description: 'Standalone unique Education website template for Kids Learning Lab, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-signal',
    label: 'Film Color Grading Studio — Signal Edition',
    category: 'Media',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['media', 'film color grading studio', 'film color grading studio signal', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'signal', 'signal edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-atelier',
    label: 'Film Color Grading Studio — Atelier Edition',
    category: 'Media',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['media', 'film color grading studio', 'film color grading studio atelier', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'atelier', 'atelier edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-local',
    label: 'Film Color Grading Studio — Local Growth Edition',
    category: 'Media',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['media', 'film color grading studio', 'film color grading studio local', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'local', 'local growth edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-commerce',
    label: 'Film Color Grading Studio — Commerce Edition',
    category: 'Media',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['media', 'film color grading studio', 'film color grading studio commerce', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'commerce', 'commerce edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-booking',
    label: 'Film Color Grading Studio — Booking Edition',
    category: 'Media',
    color: '#118AB2',
    bg: '#120817',
    industries: ['media', 'film color grading studio', 'film color grading studio booking', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'booking', 'booking edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-trust',
    label: 'Film Color Grading Studio — Trust Edition',
    category: 'Media',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['media', 'film color grading studio', 'film color grading studio trust', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'trust', 'trust edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-magazine',
    label: 'Film Color Grading Studio — Magazine Edition',
    category: 'Media',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['media', 'film color grading studio', 'film color grading studio magazine', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'magazine', 'magazine edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-film-color-grading-studio-enterprise',
    label: 'Film Color Grading Studio — Enterprise Edition',
    category: 'Media',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['media', 'film color grading studio', 'film color grading studio enterprise', 'grading suites', 'hdr mastering', 'look development', 'director review'],
    keywords: ['media', 'film color grading studio', 'enterprise', 'enterprise edition', 'work', 'suites', 'process', 'reels', 'book', 'grading suites', 'HDR mastering', 'look development', 'director review', 'delivery formats'],
    description: 'Standalone unique Media website template for Film Color Grading Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-signal',
    label: 'Heritage Hotel Palace — Signal Edition',
    category: 'Hospitality',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace signal', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'signal', 'signal edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-atelier',
    label: 'Heritage Hotel Palace — Atelier Edition',
    category: 'Hospitality',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace atelier', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'atelier', 'atelier edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-local',
    label: 'Heritage Hotel Palace — Local Growth Edition',
    category: 'Hospitality',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace local', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'local', 'local growth edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-commerce',
    label: 'Heritage Hotel Palace — Commerce Edition',
    category: 'Hospitality',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace commerce', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'commerce', 'commerce edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-booking',
    label: 'Heritage Hotel Palace — Booking Edition',
    category: 'Hospitality',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace booking', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'booking', 'booking edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-trust',
    label: 'Heritage Hotel Palace — Trust Edition',
    category: 'Hospitality',
    color: '#EF4444',
    bg: '#100808',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace trust', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'trust', 'trust edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-magazine',
    label: 'Heritage Hotel Palace — Magazine Edition',
    category: 'Hospitality',
    color: '#10B981',
    bg: '#080501',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace magazine', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'magazine', 'magazine edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-heritage-hotel-palace-enterprise',
    label: 'Heritage Hotel Palace — Enterprise Edition',
    category: 'Hospitality',
    color: '#F472B6',
    bg: '#031316',
    industries: ['hospitality', 'heritage hotel palace', 'heritage hotel palace enterprise', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns'],
    keywords: ['hospitality', 'heritage hotel palace', 'enterprise', 'enterprise edition', 'suites', 'dining', 'history', 'weddings', 'reserve', 'royal suites', 'courtyard dining', 'heritage tours', 'wedding lawns', 'concierge service'],
    description: 'Standalone unique Hospitality website template for Heritage Hotel Palace, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-signal',
    label: 'B2B Spare Parts Market — Signal Edition',
    category: 'Marketplace',
    color: '#F472B6',
    bg: '#031316',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market signal', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'signal', 'signal edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-atelier',
    label: 'B2B Spare Parts Market — Atelier Edition',
    category: 'Marketplace',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market atelier', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'atelier', 'atelier edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-local',
    label: 'B2B Spare Parts Market — Local Growth Edition',
    category: 'Marketplace',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market local', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'local', 'local growth edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-commerce',
    label: 'B2B Spare Parts Market — Commerce Edition',
    category: 'Marketplace',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market commerce', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'commerce', 'commerce edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-booking',
    label: 'B2B Spare Parts Market — Booking Edition',
    category: 'Marketplace',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market booking', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'booking', 'booking edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-trust',
    label: 'B2B Spare Parts Market — Trust Edition',
    category: 'Marketplace',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market trust', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'trust', 'trust edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-magazine',
    label: 'B2B Spare Parts Market — Magazine Edition',
    category: 'Marketplace',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market magazine', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'magazine', 'magazine edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-b2b-spare-parts-market-enterprise',
    label: 'B2B Spare Parts Market — Enterprise Edition',
    category: 'Marketplace',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['marketplace', 'b2b spare parts market', 'b2b spare parts market enterprise', 'verified suppliers', 'bulk rfq', 'part matching', 'dispatch tracking'],
    keywords: ['marketplace', 'b2b spare parts market', 'enterprise', 'enterprise edition', 'parts', 'suppliers', 'rfq', 'logistics', 'start', 'verified suppliers', 'bulk RFQ', 'part matching', 'dispatch tracking', 'GST invoices'],
    description: 'Standalone unique Marketplace website template for B2B Spare Parts Market, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-signal',
    label: 'Lab Grown Diamond Store — Signal Edition',
    category: 'Jewellery',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store signal', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'signal', 'signal edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-atelier',
    label: 'Lab Grown Diamond Store — Atelier Edition',
    category: 'Jewellery',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store atelier', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'atelier', 'atelier edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-local',
    label: 'Lab Grown Diamond Store — Local Growth Edition',
    category: 'Jewellery',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store local', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'local', 'local growth edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-commerce',
    label: 'Lab Grown Diamond Store — Commerce Edition',
    category: 'Jewellery',
    color: '#118AB2',
    bg: '#060606',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store commerce', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'commerce', 'commerce edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-booking',
    label: 'Lab Grown Diamond Store — Booking Edition',
    category: 'Jewellery',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store booking', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'booking', 'booking edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-trust',
    label: 'Lab Grown Diamond Store — Trust Edition',
    category: 'Jewellery',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store trust', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'trust', 'trust edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-magazine',
    label: 'Lab Grown Diamond Store — Magazine Edition',
    category: 'Jewellery',
    color: '#F97316',
    bg: '#100A04',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store magazine', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'magazine', 'magazine edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-lab-grown-diamond-store-enterprise',
    label: 'Lab Grown Diamond Store — Enterprise Edition',
    category: 'Jewellery',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['jewellery', 'lab grown diamond store', 'lab grown diamond store enterprise', 'igi certificates', 'custom rings', 'ethical diamonds', 'try at home'],
    keywords: ['jewellery', 'lab grown diamond store', 'enterprise', 'enterprise edition', 'rings', 'certification', 'custom', 'stories', 'book', 'IGI certificates', 'custom rings', 'ethical diamonds', 'try at home', 'appointment booking'],
    description: 'Standalone unique Jewellery website template for Lab Grown Diamond Store, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-signal',
    label: 'Ayurveda Wellness Retreat — Signal Edition',
    category: 'Wellness',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat signal', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'signal', 'signal edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-atelier',
    label: 'Ayurveda Wellness Retreat — Atelier Edition',
    category: 'Wellness',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat atelier', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'atelier', 'atelier edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-local',
    label: 'Ayurveda Wellness Retreat — Local Growth Edition',
    category: 'Wellness',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat local', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'local', 'local growth edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-commerce',
    label: 'Ayurveda Wellness Retreat — Commerce Edition',
    category: 'Wellness',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat commerce', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'commerce', 'commerce edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-booking',
    label: 'Ayurveda Wellness Retreat — Booking Edition',
    category: 'Wellness',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat booking', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'booking', 'booking edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-trust',
    label: 'Ayurveda Wellness Retreat — Trust Edition',
    category: 'Wellness',
    color: '#10B981',
    bg: '#010A05',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat trust', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'trust', 'trust edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-magazine',
    label: 'Ayurveda Wellness Retreat — Magazine Edition',
    category: 'Wellness',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat magazine', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'magazine', 'magazine edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-ayurveda-wellness-retreat-enterprise',
    label: 'Ayurveda Wellness Retreat — Enterprise Edition',
    category: 'Wellness',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['wellness', 'ayurveda wellness retreat', 'ayurveda wellness retreat enterprise', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays'],
    keywords: ['wellness', 'ayurveda wellness retreat', 'enterprise', 'enterprise edition', 'therapies', 'doctors', 'retreats', 'herbs', 'book', 'dosha consults', 'therapy plans', 'herbal kitchen', 'retreat stays', 'progress tracking'],
    description: 'Standalone unique Wellness website template for Ayurveda Wellness Retreat, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-signal',
    label: 'Industrial Safety Training — Signal Edition',
    category: 'Training',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['training', 'industrial safety training', 'industrial safety training signal', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'signal', 'signal edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-atelier',
    label: 'Industrial Safety Training — Atelier Edition',
    category: 'Training',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['training', 'industrial safety training', 'industrial safety training atelier', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'atelier', 'atelier edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-local',
    label: 'Industrial Safety Training — Local Growth Edition',
    category: 'Training',
    color: '#A3E635',
    bg: '#050313',
    industries: ['training', 'industrial safety training', 'industrial safety training local', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'local', 'local growth edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-commerce',
    label: 'Industrial Safety Training — Commerce Edition',
    category: 'Training',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['training', 'industrial safety training', 'industrial safety training commerce', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'commerce', 'commerce edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-booking',
    label: 'Industrial Safety Training — Booking Edition',
    category: 'Training',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['training', 'industrial safety training', 'industrial safety training booking', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'booking', 'booking edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-trust',
    label: 'Industrial Safety Training — Trust Edition',
    category: 'Training',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['training', 'industrial safety training', 'industrial safety training trust', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'trust', 'trust edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-magazine',
    label: 'Industrial Safety Training — Magazine Edition',
    category: 'Training',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['training', 'industrial safety training', 'industrial safety training magazine', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'magazine', 'magazine edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-industrial-safety-training-enterprise',
    label: 'Industrial Safety Training — Enterprise Edition',
    category: 'Training',
    color: '#FFD166',
    bg: '#101112',
    industries: ['training', 'industrial safety training', 'industrial safety training enterprise', 'ppe modules', 'site drills', 'certificates', 'incident logs'],
    keywords: ['training', 'industrial safety training', 'enterprise', 'enterprise edition', 'programs', 'simulations', 'compliance', 'teams', 'enquire', 'PPE modules', 'site drills', 'certificates', 'incident logs', 'audit readiness'],
    description: 'Standalone unique Training website template for Industrial Safety Training, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-signal',
    label: 'Drone Wedding Films — Signal Edition',
    category: 'Media',
    color: '#FFD166',
    bg: '#101112',
    industries: ['media', 'drone wedding films', 'drone wedding films signal', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'signal', 'signal edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-atelier',
    label: 'Drone Wedding Films — Atelier Edition',
    category: 'Media',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['media', 'drone wedding films', 'drone wedding films atelier', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'atelier', 'atelier edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-local',
    label: 'Drone Wedding Films — Local Growth Edition',
    category: 'Media',
    color: '#118AB2',
    bg: '#100808',
    industries: ['media', 'drone wedding films', 'drone wedding films local', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'local', 'local growth edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-commerce',
    label: 'Drone Wedding Films — Commerce Edition',
    category: 'Media',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['media', 'drone wedding films', 'drone wedding films commerce', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'commerce', 'commerce edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-booking',
    label: 'Drone Wedding Films — Booking Edition',
    category: 'Media',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['media', 'drone wedding films', 'drone wedding films booking', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'booking', 'booking edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-trust',
    label: 'Drone Wedding Films — Trust Edition',
    category: 'Media',
    color: '#F97316',
    bg: '#09111f',
    industries: ['media', 'drone wedding films', 'drone wedding films trust', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'trust', 'trust edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-magazine',
    label: 'Drone Wedding Films — Magazine Edition',
    category: 'Media',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['media', 'drone wedding films', 'drone wedding films magazine', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'magazine', 'magazine edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-drone-wedding-films-enterprise',
    label: 'Drone Wedding Films — Enterprise Edition',
    category: 'Media',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['media', 'drone wedding films', 'drone wedding films enterprise', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots'],
    keywords: ['media', 'drone wedding films', 'enterprise', 'enterprise edition', 'films', 'packages', 'crew', 'gallery', 'book', 'aerial rituals', 'cinematic edits', 'same day teaser', 'licensed pilots', 'album delivery'],
    description: 'Standalone unique Media website template for Drone Wedding Films, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-signal',
    label: 'Solar Warehouse Power — Signal Edition',
    category: 'Energy',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power signal', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'signal', 'signal edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-atelier',
    label: 'Solar Warehouse Power — Atelier Edition',
    category: 'Energy',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power atelier', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'atelier', 'atelier edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-local',
    label: 'Solar Warehouse Power — Local Growth Edition',
    category: 'Energy',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power local', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'local', 'local growth edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-commerce',
    label: 'Solar Warehouse Power — Commerce Edition',
    category: 'Energy',
    color: '#EF4444',
    bg: '#120817',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power commerce', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'commerce', 'commerce edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-booking',
    label: 'Solar Warehouse Power — Booking Edition',
    category: 'Energy',
    color: '#10B981',
    bg: '#050313',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power booking', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'booking', 'booking edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-trust',
    label: 'Solar Warehouse Power — Trust Edition',
    category: 'Energy',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power trust', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'trust', 'trust edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-magazine',
    label: 'Solar Warehouse Power — Magazine Edition',
    category: 'Energy',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power magazine', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'magazine', 'magazine edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-solar-warehouse-power-enterprise',
    label: 'Solar Warehouse Power — Enterprise Edition',
    category: 'Energy',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['energy', 'solar warehouse power', 'solar warehouse power enterprise', 'rooftop layout', 'subsidy help', 'net metering', 'amc visits'],
    keywords: ['energy', 'solar warehouse power', 'enterprise', 'enterprise edition', 'savings', 'systems', 'projects', 'amc', 'estimate', 'rooftop layout', 'subsidy help', 'net metering', 'AMC visits', 'energy reports'],
    description: 'Standalone unique Energy website template for Solar Warehouse Power, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-signal',
    label: 'Electric Bike Showroom — Signal Edition',
    category: 'Mobility',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom signal', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'signal', 'signal edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-atelier',
    label: 'Electric Bike Showroom — Atelier Edition',
    category: 'Mobility',
    color: '#A3E635',
    bg: '#111827',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom atelier', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'atelier', 'atelier edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-local',
    label: 'Electric Bike Showroom — Local Growth Edition',
    category: 'Mobility',
    color: '#FB7185',
    bg: '#101112',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom local', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'local', 'local growth edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-commerce',
    label: 'Electric Bike Showroom — Commerce Edition',
    category: 'Mobility',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom commerce', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'commerce', 'commerce edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-booking',
    label: 'Electric Bike Showroom — Booking Edition',
    category: 'Mobility',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom booking', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'booking', 'booking edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-trust',
    label: 'Electric Bike Showroom — Trust Edition',
    category: 'Mobility',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom trust', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'trust', 'trust edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-magazine',
    label: 'Electric Bike Showroom — Magazine Edition',
    category: 'Mobility',
    color: '#FFD166',
    bg: '#031316',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom magazine', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'magazine', 'magazine edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electric-bike-showroom-enterprise',
    label: 'Electric Bike Showroom — Enterprise Edition',
    category: 'Mobility',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['mobility', 'electric bike showroom', 'electric bike showroom enterprise', 'battery warranty', 'test rides', 'emi plans', 'service bays'],
    keywords: ['mobility', 'electric bike showroom', 'enterprise', 'enterprise edition', 'models', 'range', 'finance', 'service', 'book ride', 'battery warranty', 'test rides', 'EMI plans', 'service bays', 'charging map'],
    description: 'Standalone unique Mobility website template for Electric Bike Showroom, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-signal',
    label: 'Cloud Accounting Desk — Signal Edition',
    category: 'Finance',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk signal', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'signal', 'signal edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-atelier',
    label: 'Cloud Accounting Desk — Atelier Edition',
    category: 'Finance',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk atelier', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'atelier', 'atelier edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-local',
    label: 'Cloud Accounting Desk — Local Growth Edition',
    category: 'Finance',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk local', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'local', 'local growth edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-commerce',
    label: 'Cloud Accounting Desk — Commerce Edition',
    category: 'Finance',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk commerce', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'commerce', 'commerce edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-booking',
    label: 'Cloud Accounting Desk — Booking Edition',
    category: 'Finance',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk booking', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'booking', 'booking edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-trust',
    label: 'Cloud Accounting Desk — Trust Edition',
    category: 'Finance',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk trust', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'trust', 'trust edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-magazine',
    label: 'Cloud Accounting Desk — Magazine Edition',
    category: 'Finance',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk magazine', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'magazine', 'magazine edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-cloud-accounting-desk-enterprise',
    label: 'Cloud Accounting Desk — Enterprise Edition',
    category: 'Finance',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['finance', 'cloud accounting desk', 'cloud accounting desk enterprise', 'bookkeeping', 'gst returns', 'cashflow reports', 'payroll runs'],
    keywords: ['finance', 'cloud accounting desk', 'enterprise', 'enterprise edition', 'services', 'reports', 'tax', 'payroll', 'consult', 'bookkeeping', 'GST returns', 'cashflow reports', 'payroll runs', 'audit prep'],
    description: 'Standalone unique Finance website template for Cloud Accounting Desk, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-signal',
    label: 'Architectural Lighting Studio — Signal Edition',
    category: 'Design',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio signal', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'signal', 'signal edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-atelier',
    label: 'Architectural Lighting Studio — Atelier Edition',
    category: 'Design',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio atelier', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'atelier', 'atelier edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-local',
    label: 'Architectural Lighting Studio — Local Growth Edition',
    category: 'Design',
    color: '#EF4444',
    bg: '#060606',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio local', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'local', 'local growth edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-commerce',
    label: 'Architectural Lighting Studio — Commerce Edition',
    category: 'Design',
    color: '#10B981',
    bg: '#111827',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio commerce', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'commerce', 'commerce edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-booking',
    label: 'Architectural Lighting Studio — Booking Edition',
    category: 'Design',
    color: '#F472B6',
    bg: '#101112',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio booking', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'booking', 'booking edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-trust',
    label: 'Architectural Lighting Studio — Trust Edition',
    category: 'Design',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio trust', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'trust', 'trust edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-magazine',
    label: 'Architectural Lighting Studio — Magazine Edition',
    category: 'Design',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio magazine', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'magazine', 'magazine edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-architectural-lighting-studio-enterprise',
    label: 'Architectural Lighting Studio — Enterprise Edition',
    category: 'Design',
    color: '#A3E635',
    bg: '#080501',
    industries: ['design', 'architectural lighting studio', 'architectural lighting studio enterprise', 'lighting plans', 'fixture library', 'smart controls', 'lux levels'],
    keywords: ['design', 'architectural lighting studio', 'enterprise', 'enterprise edition', 'concepts', 'fixtures', 'projects', 'controls', 'consult', 'lighting plans', 'fixture library', 'smart controls', 'lux levels', 'site commissioning'],
    description: 'Standalone unique Design website template for Architectural Lighting Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-signal',
    label: 'Corporate Wellness Platform — Signal Edition',
    category: 'HealthTech',
    color: '#A3E635',
    bg: '#080501',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform signal', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'signal', 'signal edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-atelier',
    label: 'Corporate Wellness Platform — Atelier Edition',
    category: 'HealthTech',
    color: '#FB7185',
    bg: '#031316',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform atelier', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'atelier', 'atelier edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-corporate-wellness-platform-local',
    label: 'Corporate Wellness Platform — Local Growth Edition',
    category: 'HealthTech',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['healthtech', 'corporate wellness platform', 'corporate wellness platform local', 'employee health', 'fitness challenges', 'mental wellness', 'hr dashboard'],
    keywords: ['healthtech', 'corporate wellness platform', 'local', 'local growth edition', 'programs', 'coaches', 'analytics', 'engagement', 'demo', 'employee health', 'fitness challenges', 'mental wellness', 'HR dashboard', 'participation reports'],
    description: 'Standalone unique HealthTech website template for Corporate Wellness Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
