// Auto-split chunk 10 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_10: WebsiteTemplate[] = [
  {
    id: "graphic-design-studio",
    label: "Graphic Design Studio",
    category: "Creative",
    color: "#F43F5E",
    bg: "#120306",
    industries: ["graphic design", "creative agency", "branding", "design"],
    keywords: ["graphic design", "branding", "creative", "logo", "poster"],
    description: "Bold creative website for graphic design studios and brand identity teams.",
  },
  {
    id: "video-production",
    label: "Video Production Studio",
    category: "Creative",
    color: "#EF4444",
    bg: "#100303",
    industries: ["video production", "film studio", "creative", "advertising"],
    keywords: ["video", "film", "production", "ad film", "reel", "camera"],
    description: "Cinematic website for video production houses, ad filmmakers and studios.",
  },
  {
    id: "animation-studio",
    label: "Animation Studio",
    category: "Creative",
    color: "#A855F7",
    bg: "#080411",
    industries: ["animation", "creative studio", "3d", "video"],
    keywords: ["animation", "3d", "motion", "cartoon", "studio"],
    description: "Vibrant animation studio website for motion, 3D and character content businesses.",
  },
  {
    id: "podcast-studio",
    label: "Podcast Studio",
    category: "Creative",
    color: "#F97316",
    bg: "#100604",
    industries: ["podcast", "studio", "media", "creative"],
    keywords: ["podcast", "recording", "studio", "audio", "mic"],
    description: "Modern podcast studio website for recording services, shows and audio brands.",
  },
  {
    id: "influencer-portfolio",
    label: "Influencer Portfolio",
    category: "Creative",
    color: "#EC4899",
    bg: "#120611",
    industries: ["influencer", "creator", "personal brand", "portfolio"],
    keywords: ["influencer", "creator", "instagram", "youtube", "personal brand"],
    description: "Personal brand website for influencers, creators and digital personalities.",
  },
  {
    id: "author-portfolio",
    label: "Author Portfolio",
    category: "Creative",
    color: "#D6C8A6",
    bg: "#0C0A07",
    industries: ["author", "writer", "portfolio", "creative"],
    keywords: ["author", "book", "writer", "novel", "publication"],
    description: "Elegant portfolio website for authors, writers and book launches.",
  },
  {
    id: "artist-gallery",
    label: "Artist Gallery",
    category: "Creative",
    color: "#FBBF24",
    bg: "#0E0B03",
    industries: ["artist", "art gallery", "creative", "portfolio"],
    keywords: ["artist", "gallery", "painting", "art", "portfolio"],
    description: "Gallery-style website for artists, painters and creative exhibitions.",
  },
  {
    id: "dance-academy",
    label: "Dance Academy",
    category: "Creative",
    color: "#F472B6",
    bg: "#100611",
    industries: ["dance academy", "education", "creative", "fitness"],
    keywords: ["dance", "academy", "classes", "choreography", "performance"],
    description: "Energetic dance academy website for classes, performances and training.",
  },
  {
    id: "theatre-group",
    label: "Theatre Group",
    category: "Creative",
    color: "#C084FC",
    bg: "#080410",
    industries: ["theatre", "creative", "performing arts", "events"],
    keywords: ["theatre", "stage", "drama", "performance", "artist"],
    description: "Dramatic website for theatre groups, stage productions and performing arts.",
  },
  {
    id: "makeup-artist",
    label: "Makeup Artist",
    category: "Beauty",
    color: "#F9A8D4",
    bg: "#12070D",
    industries: ["makeup artist", "beauty", "wedding", "salon"],
    keywords: ["makeup", "bridal makeup", "artist", "beauty", "glam"],
    description: "Portfolio website for makeup artists, bridal beauty and glam services.",
  },
  {
    id: "nail-studio",
    label: "Nail Studio",
    category: "Beauty",
    color: "#F0ABFC",
    bg: "#110612",
    industries: ["nails", "beauty", "salon", "spa"],
    keywords: ["nails", "nail art", "manicure", "salon", "beauty"],
    description: "Trendy nail studio website for manicures, nail art and beauty bookings.",
  },
  {
    id: "barber-shop",
    label: "Barber Shop",
    category: "Beauty",
    color: "#B08968",
    bg: "#0C0704",
    industries: ["barber", "salon", "grooming", "beauty"],
    keywords: ["barber", "haircut", "grooming", "men salon", "beard"],
    description: "Premium grooming website for barber shops and men’s salons.",
  },
  {
    id: "bridal-boutique",
    label: "Bridal Boutique",
    category: "Fashion",
    color: "#F7C7D9",
    bg: "#12060C",
    industries: ["bridal boutique", "fashion", "wedding", "retail"],
    keywords: ["bridal", "boutique", "lehenga", "wedding dress", "fashion"],
    description: "Luxury bridal boutique website for wedding fashion and couture brands.",
  },
  {
    id: "kidswear-brand",
    label: "Kidswear Brand",
    category: "Fashion",
    color: "#60A5FA",
    bg: "#06101A",
    industries: ["kidswear", "fashion", "clothing", "retail"],
    keywords: ["kidswear", "children clothing", "baby clothes", "fashion"],
    description: "Friendly fashion website for kidswear and children’s clothing brands.",
  },
  {
    id: "menswear-brand",
    label: "Menswear Brand",
    category: "Fashion",
    color: "#94A3B8",
    bg: "#05070A",
    industries: ["menswear", "fashion", "clothing", "retail"],
    keywords: ["menswear", "suits", "shirts", "fashion", "apparel"],
    description: "Clean menswear website for apparel, tailoring and premium clothing labels.",
  },
  {
    id: "saree-store",
    label: "Saree Store",
    category: "Fashion",
    color: "#D946EF",
    bg: "#120512",
    industries: ["saree", "fashion", "ethnic wear", "retail"],
    keywords: ["saree", "ethnic", "silk saree", "fashion", "boutique"],
    description: "Elegant ethnic wear website for saree stores and traditional fashion brands.",
  },
  {
    id: "streetwear-brand",
    label: "Streetwear Brand",
    category: "Fashion",
    color: "#E5E7EB",
    bg: "#050505",
    industries: ["streetwear", "fashion", "clothing", "apparel"],
    keywords: ["streetwear", "hoodie", "sneakers", "drop", "clothing"],
    description: "Dark streetwear website for fashion drops, apparel and youth brands.",
  },
  {
    id: "sneaker-store",
    label: "Sneaker Store",
    category: "Fashion",
    color: "#22D3EE",
    bg: "#041015",
    industries: ["sneakers", "fashion", "retail", "footwear"],
    keywords: ["sneaker", "shoes", "footwear", "streetwear", "drop"],
    description: "Modern sneaker store website for footwear, drops and lifestyle retail.",
  },
  {
    id: "jewellery-bridal",
    label: "Bridal Jewellery",
    category: "Luxury",
    color: "#F2DCA7",
    bg: "#10080B",
    industries: ["jewellery", "bridal", "wedding", "luxury retail"],
    keywords: ["bridal jewellery", "gold", "diamond", "wedding", "rings"],
    description: "Luxury bridal jewellery variation with wedding-first messaging and booking CTA.",
  },
  {
    id: "jewellery-minimal",
    label: "Minimal Jewellery",
    category: "Luxury",
    color: "#E5D7C1",
    bg: "#0C0B0A",
    industries: ["jewellery", "minimal fashion", "accessories", "retail"],
    keywords: ["minimal jewellery", "silver", "rings", "accessories", "modern"],
    description: "Minimal jewellery website for daily wear, silver and contemporary accessory brands.",
  },
  {
    id: "diamond-jewellery",
    label: "Diamond Jewellery",
    category: "Luxury",
    color: "#BFE7FF",
    bg: "#071018",
    industries: ["diamond jewellery", "luxury", "bridal", "retail"],
    keywords: ["diamond", "jewellery", "rings", "luxury", "bridal"],
    description: "Refined diamond jewellery website for luxury retail and high-value collections.",
  },
  {
    id: "watch-brand",
    label: "Watch Brand",
    category: "Luxury",
    color: "#D4AF37",
    bg: "#070707",
    industries: ["watch brand", "luxury retail", "fashion", "accessories"],
    keywords: ["watch", "watches", "timepiece", "luxury", "accessory"],
    description: "Premium watch brand website for luxury timepieces and accessories.",
  },
  {
    id: "perfume-brand",
    label: "Perfume Brand",
    category: "Luxury",
    color: "#D8B4FE",
    bg: "#0D0712",
    industries: ["perfume", "fragrance", "luxury retail", "beauty"],
    keywords: ["perfume", "fragrance", "scent", "luxury", "bottle"],
    description: "Sensory fragrance website for perfume brands and luxury scent collections.",
  },
  {
    id: "premium-gift-store",
    label: "Premium Gift Store",
    category: "Luxury",
    color: "#F59E0B",
    bg: "#0F0803",
    industries: ["gifting", "retail", "luxury", "ecommerce"],
    keywords: ["gift", "gifting", "hamper", "luxury gift", "corporate gifts"],
    description: "Premium gifting website for hampers, corporate gifts and curated presents.",
  },
  {
    id: "ca-firm",
    label: "CA Firm",
    category: "Finance",
    color: "#60A5FA",
    bg: "#030B14",
    industries: ["chartered accountant", "tax", "finance", "consulting"],
    keywords: ["ca", "chartered accountant", "tax", "gst", "audit", "returns"],
    description: "Professional CA firm website for taxation, GST, audit and compliance services.",
  },
  {
    id: "tax-consultant",
    label: "Tax Consultant",
    category: "Finance",
    color: "#4ADE80",
    bg: "#051008",
    industries: ["tax consultant", "finance", "consulting", "legal"],
    keywords: ["tax", "income tax", "gst", "consultant", "return"],
    description: "Trustworthy tax consultant website for individuals and business compliance.",
  },
  {
    id: "loan-consultant",
    label: "Loan Consultant",
    category: "Finance",
    color: "#FBBF24",
    bg: "#100B03",
    industries: ["loan consultant", "finance", "banking", "consulting"],
    keywords: ["loan", "home loan", "business loan", "finance", "emi"],
    description: "Conversion-focused loan consultant website for finance advisory and loan assistance.",
  },
  {
    id: "stock-trading-coach",
    label: "Stock Trading Coach",
    category: "Finance",
    color: "#22C55E",
    bg: "#041008",
    industries: ["stock market", "trading coach", "finance", "education"],
    keywords: ["stock market", "trading", "investing", "coach", "nifty"],
    description: "Modern trading coach website for stock market education and finance programs.",
  },
  {
    id: "insurance-agency",
    label: "Insurance Agency",
    category: "Finance",
    color: "#38BDF8",
    bg: "#030E14",
    industries: ["insurance", "finance", "advisor", "consulting"],
    keywords: ["insurance", "policy", "health insurance", "life insurance", "advisor"],
    description: "Reliable insurance agency website for policy advisors and financial protection brands.",
  },
  {
    id: "fintech-app",
    label: "Fintech App",
    category: "Finance",
    color: "#00C2FF",
    bg: "#020B12",
    industries: ["fintech", "finance app", "saas", "startup"],
    keywords: ["fintech", "payments", "wallet", "finance app", "upi"],
    description: "Modern fintech app landing page for payments, lending and money products.",
  },
  {
    id: "hr-consultancy",
    label: "HR Consultancy",
    category: "Corporate",
    color: "#A78BFA",
    bg: "#080615",
    industries: ["hr consultancy", "recruitment", "corporate", "consulting"],
    keywords: ["hr", "recruitment", "hiring", "talent", "staffing"],
    description: "Professional HR consultancy website for hiring, staffing and talent solutions.",
  },
  {
    id: "recruitment-agency",
    label: "Recruitment Agency",
    category: "Corporate",
    color: "#60A5FA",
    bg: "#05101A",
    industries: ["recruitment", "jobs", "hr", "corporate"],
    keywords: ["recruitment", "jobs", "hiring", "career", "placement"],
    description: "Conversion-led recruitment agency website for placements and employer services.",
  },
  {
    id: "business-consultant",
    label: "Business Consultant",
    category: "Corporate",
    color: "#D4AF37",
    bg: "#080706",
    industries: ["business consultant", "consulting", "corporate", "general business"],
    keywords: ["business consultant", "strategy", "growth", "consulting", "management"],
    description: "Premium consulting website for strategy, business growth and corporate advisory.",
  },
  {
    id: "b2b-manufacturer",
    label: "B2B Manufacturer",
    category: "Industry",
    color: "#F59E0B",
    bg: "#100903",
    industries: ["manufacturing", "b2b", "industry", "factory"],
    keywords: ["manufacturer", "factory", "industrial", "b2b", "production"],
    description: "Industrial website for manufacturers, factories and B2B suppliers.",
  },
  {
    id: "steel-supplier",
    label: "Steel Supplier",
    category: "Industry",
    color: "#A3A3A3",
    bg: "#070707",
    industries: ["steel", "manufacturing", "construction", "b2b"],
    keywords: ["steel", "iron", "supplier", "metal", "fabrication"],
    description: "Strong B2B website for steel suppliers, metal traders and fabrication brands.",
  },
  {
    id: "packaging-company",
    label: "Packaging Company",
    category: "Industry",
    color: "#F97316",
    bg: "#0F0603",
    industries: ["packaging", "manufacturing", "b2b", "industry"],
    keywords: ["packaging", "box", "carton", "printing", "manufacturer"],
    description: "Clean B2B website for packaging, cartons and industrial supply companies.",
  },
  {
    id: "printing-press",
    label: "Printing Press",
    category: "Industry",
    color: "#EC4899",
    bg: "#120611",
    industries: ["printing", "design", "b2b", "marketing"],
    keywords: ["printing", "press", "offset", "digital print", "brochure"],
    description: "Practical printing press website for print shops and commercial design services.",
  },
  {
    id: "chemical-supplier",
    label: "Chemical Supplier",
    category: "Industry",
    color: "#22D3EE",
    bg: "#041014",
    industries: ["chemical supplier", "industry", "b2b", "manufacturing"],
    keywords: ["chemical", "supplier", "industrial", "factory", "b2b"],
    description: "Technical B2B website for chemical suppliers and industrial materials.",
  },
  {
    id: "textile-manufacturer",
    label: "Textile Manufacturer",
    category: "Industry",
    color: "#C084FC",
    bg: "#0B0612",
    industries: ["textile", "manufacturing", "fashion", "b2b"],
    keywords: ["textile", "fabric", "garment", "manufacturer", "cloth"],
    description: "B2B textile manufacturing website for fabrics, garments and export units.",
  },
  {
    id: "electronics-store",
    label: "Electronics Store",
    category: "Retail",
    color: "#38BDF8",
    bg: "#030D14",
    industries: ["electronics", "retail", "gadgets", "ecommerce"],
    keywords: ["electronics", "mobile", "laptop", "gadgets", "store"],
    description: "Modern retail website for electronics, gadgets and mobile/laptop stores.",
  },
  {
    id: "mobile-store",
    label: "Mobile Store",
    category: "Retail",
    color: "#7C3AED",
    bg: "#070412",
    industries: ["mobile store", "electronics", "retail", "gadgets"],
    keywords: ["mobile", "smartphone", "phone", "accessories", "repair"],
    description: "High-conversion mobile store website for smartphones and accessories.",
  },
  {
    id: "bookstore",
    label: "Bookstore",
    category: "Retail",
    color: "#D6B982",
    bg: "#0C0804",
    industries: ["bookstore", "retail", "education", "ecommerce"],
    keywords: ["bookstore", "books", "stationery", "library", "reading"],
    description: "Warm bookstore website for books, stationery and education retail.",
  },
  {
    id: "toy-store",
    label: "Toy Store",
    category: "Retail",
    color: "#F472B6",
    bg: "#110612",
    industries: ["toys", "kids", "retail", "ecommerce"],
    keywords: ["toy", "toys", "kids", "games", "children"],
    description: "Playful toy store website for kids products, gifts and educational games.",
  },
  {
    id: "sports-store",
    label: "Sports Store",
    category: "Retail",
    color: "#22C55E",
    bg: "#041007",
    industries: ["sports store", "retail", "fitness", "ecommerce"],
    keywords: ["sports", "cricket", "football", "fitness gear", "store"],
    description: "Energetic sports store website for equipment, gear and fitness retail.",
  },
  {
    id: "optical-store",
    label: "Optical Store",
    category: "Retail",
    color: "#67E8F9",
    bg: "#061116",
    industries: ["optical", "eyewear", "retail", "healthcare"],
    keywords: ["optical", "glasses", "eyewear", "lens", "spectacles"],
    description: "Stylish optical store website for eyewear, lenses and vision products.",
  },
  {
    id: "flower-shop",
    label: "Flower Shop",
    category: "Retail",
    color: "#F472B6",
    bg: "#10060B",
    industries: ["flower shop", "gifting", "retail", "events"],
    keywords: ["flowers", "florist", "bouquet", "gifting", "wedding flowers"],
    description: "Elegant florist website for bouquets, gifting and event floral design.",
  },
  {
    id: "jewellery-ecommerce",
    label: "Jewellery Ecommerce",
    category: "Ecommerce",
    color: "#D4AF37",
    bg: "#090807",
    industries: ["jewellery", "ecommerce", "luxury retail", "fashion"],
    keywords: ["jewellery ecommerce", "online store", "gold", "rings", "collection"],
    description: "Shop-forward jewellery ecommerce template for product-led luxury retail.",
  },
  {
    id: "fashion-ecommerce",
    label: "Fashion Ecommerce",
    category: "Ecommerce",
    color: "#F43F5E",
    bg: "#110406",
    industries: ["fashion", "ecommerce", "retail", "clothing"],
    keywords: ["fashion ecommerce", "shop", "clothing", "collection", "cart"],
    description: "Modern fashion ecommerce website for clothing brands and online boutiques.",
  },
  {
    id: "beauty-ecommerce",
    label: "Beauty Ecommerce",
    category: "Ecommerce",
    color: "#F9A8D4",
    bg: "#12070D",
    industries: ["beauty", "ecommerce", "cosmetics", "skincare"],
    keywords: ["beauty ecommerce", "cosmetics", "skincare", "shop", "makeup"],
    description: "Polished beauty ecommerce website for skincare, makeup and personal care products.",
  },
  {
    id: "grocery-delivery",
    label: "Grocery Delivery",
    category: "Ecommerce",
    color: "#65A30D",
    bg: "#061004",
    industries: ["grocery", "delivery", "ecommerce", "food"],
    keywords: ["grocery", "delivery", "vegetables", "online store", "fresh"],
    description: "Fresh grocery delivery website for online food and household essentials.",
  },
  {
    id: "electronics-ecommerce",
    label: "Electronics Ecommerce",
    category: "Ecommerce",
    color: "#38BDF8",
    bg: "#031018",
    industries: ["electronics", "ecommerce", "gadgets", "retail"],
    keywords: ["electronics ecommerce", "gadgets", "mobile", "laptop", "shop"],
    description: "Modern ecommerce website for gadgets, electronics and tech accessories.",
  },
  {
    id: "furniture-ecommerce",
    label: "Furniture Ecommerce",
    category: "Ecommerce",
    color: "#C8956A",
    bg: "#0A0604",
    industries: ["furniture", "ecommerce", "home decor", "retail"],
    keywords: ["furniture ecommerce", "sofa", "bed", "home decor", "shop"],
    description: "Premium furniture ecommerce website for home and decor products.",
  },
  {
    id: "edtech-platform",
    label: "EdTech Platform",
    category: "Edu",
    color: "#4FC3F7",
    bg: "#020B14",
    industries: ["edtech", "education", "saas", "startup"],
    keywords: ["edtech", "online learning", "course", "student", "platform"],
    description: "Modern EdTech landing page for learning platforms and course apps.",
  },
  {
    id: "coaching-institute",
    label: "Coaching Institute",
    category: "Edu",
    color: "#6A9FD8",
    bg: "#02060F",
    industries: ["coaching", "education", "academy", "classes"],
    keywords: ["coaching", "institute", "neet", "jee", "upsc", "classes"],
    description: "Result-focused coaching institute website for exam prep and offline classes.",
  },
  {
    id: "preschool",
    label: "Preschool",
    category: "Edu",
    color: "#FBBF24",
    bg: "#100B03",
    industries: ["preschool", "school", "education", "kids"],
    keywords: ["preschool", "kids", "kindergarten", "school", "nursery"],
    description: "Friendly preschool website for early learning, admissions and parent trust.",
  },
  {
    id: "online-course-creator",
    label: "Online Course Creator",
    category: "Edu",
    color: "#A855F7",
    bg: "#080412",
    industries: ["online course", "creator", "education", "personal brand"],
    keywords: ["course", "creator", "online class", "workshop", "webinar"],
    description: "Personal course creator website for workshops, digital products and coaching.",
  },
  {
    id: "language-school",
    label: "Language School",
    category: "Edu",
    color: "#22D3EE",
    bg: "#031014",
    industries: ["language school", "education", "classes", "academy"],
    keywords: ["language", "english speaking", "ielts", "french", "classes"],
    description: "Clean language school website for communication classes and exam prep.",
  },
  {
    id: "music-school",
    label: "Music School",
    category: "Edu",
    color: "#F97316",
    bg: "#100604",
    industries: ["music school", "education", "creative", "academy"],
    keywords: ["music school", "guitar", "piano", "vocal", "classes"],
    description: "Creative music school website for instrument, vocal and performance classes.",
  },
  {
    id: "sports-academy",
    label: "Sports Academy",
    category: "Edu",
    color: "#22C55E",
    bg: "#041008",
    industries: ["sports academy", "education", "fitness", "training"],
    keywords: ["sports academy", "cricket", "football", "training", "coach"],
    description: "Energetic sports academy website for training, admissions and athlete programs.",
  },
  {
    id: "real-estate-premium",
    label: "Premium Real Estate",
    category: "Property",
    color: "#D4AF37",
    bg: "#080806",
    industries: ["real estate", "property", "luxury", "builder"],
    keywords: ["luxury property", "villa", "apartment", "real estate", "builder"],
    description: "Luxury real estate variation for premium villas, apartments and builder projects.",
  },
  {
    id: "real-estate-broker",
    label: "Real Estate Broker",
    category: "Property",
    color: "#87A878",
    bg: "#030804",
    industries: ["real estate broker", "property", "realty", "consulting"],
    keywords: ["broker", "property dealer", "real estate", "rent", "sale"],
    description: "Trust-building broker website for property dealers and real estate advisors.",
  },
  {
    id: "property-management",
    label: "Property Management",
    category: "Property",
    color: "#60A5FA",
    bg: "#05101A",
    industries: ["property management", "real estate", "rental", "facility"],
    keywords: ["property management", "rental", "facility", "maintenance"],
    description: "Professional property management website for rentals, facilities and maintenance services.",
  },
  {
    id: "architecture-minimal",
    label: "Minimal Architecture",
    category: "Design",
    color: "#E5E0D3",
    bg: "#0B0A08",
    industries: ["architecture", "design studio", "interior", "construction"],
    keywords: ["architecture", "minimal", "design", "villa", "project"],
    description: "Minimal architecture variation with clean editorial project presentation.",
  },
  {
    id: "construction-premium",
    label: "Premium Construction",
    category: "Industry",
    color: "#F4A000",
    bg: "#0A0600",
    industries: ["construction", "builder", "contractor", "infrastructure"],
    keywords: ["construction", "premium builder", "project", "contractor"],
    description: "Premium construction variation for builders, contractors and project developers.",
  },
  {
    id: "civil-contractor",
    label: "Civil Contractor",
    category: "Industry",
    color: "#F59E0B",
    bg: "#0F0802",
    industries: ["civil contractor", "construction", "industry", "b2b"],
    keywords: ["civil contractor", "road", "building", "infrastructure", "contractor"],
    description: "Robust website for civil contractors and infrastructure firms.",
  },
  {
    id: "roofing-company",
    label: "Roofing Company",
    category: "Industry",
    color: "#94A3B8",
    bg: "#07090B",
    industries: ["roofing", "construction", "contractor", "home improvement"],
    keywords: ["roofing", "roof repair", "contractor", "home improvement"],
    description: "Practical roofing contractor website for repairs, installation and inquiries.",
  },
  {
    id: "plumbing-service",
    label: "Plumbing Service",
    category: "Services",
    color: "#38BDF8",
    bg: "#031019",
    industries: ["plumbing", "home services", "repair", "contractor"],
    keywords: ["plumbing", "plumber", "repair", "pipe", "home service"],
    description: "Local service website for plumbing repairs, installations and emergency calls.",
  },
  {
    id: "electrician-service",
    label: "Electrician Service",
    category: "Services",
    color: "#FDE047",
    bg: "#100D03",
    industries: ["electrician", "home services", "repair", "contractor"],
    keywords: ["electrician", "electrical", "repair", "wiring", "home service"],
    description: "Fast local website for electricians, wiring and emergency service bookings.",
  },
  {
    id: "cleaning-service",
    label: "Cleaning Service",
    category: "Services",
    color: "#5EEAD4",
    bg: "#04100E",
    industries: ["cleaning", "home services", "facility", "b2b"],
    keywords: ["cleaning", "housekeeping", "deep clean", "office cleaning"],
    description: "Clean local service website for home, office and facility cleaning businesses.",
  },
  {
    id: "pest-control",
    label: "Pest Control",
    category: "Services",
    color: "#84CC16",
    bg: "#071004",
    industries: ["pest control", "home services", "facility", "health"],
    keywords: ["pest control", "termite", "cockroach", "home service"],
    description: "Trustworthy pest control website for home and commercial protection services.",
  },
  {
    id: "security-agency",
    label: "Security Agency",
    category: "Services",
    color: "#60A5FA",
    bg: "#030B14",
    industries: ["security agency", "facility", "corporate", "b2b"],
    keywords: ["security", "guards", "agency", "surveillance", "facility"],
    description: "Professional security agency website for guards, surveillance and facility services.",
  },
  {
    id: "laundry-service",
    label: "Laundry Service",
    category: "Services",
    color: "#7DD3FC",
    bg: "#041016",
    industries: ["laundry", "home services", "retail", "delivery"],
    keywords: ["laundry", "dry cleaning", "wash", "pickup", "delivery"],
    description: "Fresh laundry service website for dry cleaning, pickup and delivery businesses.",
  },
  {
    id: "moving-packers",
    label: "Packers & Movers",
    category: "Services",
    color: "#F97316",
    bg: "#100604",
    industries: ["packers movers", "logistics", "home services", "transport"],
    keywords: ["packers", "movers", "shifting", "transport", "relocation"],
    description: "Conversion-focused packers and movers website for relocation services.",
  },
  {
    id: "repair-service",
    label: "Appliance Repair",
    category: "Services",
    color: "#F59E0B",
    bg: "#0E0903",
    industries: ["repair service", "home services", "electronics", "local business"],
    keywords: ["repair", "appliance", "ac", "fridge", "washing machine"],
    description: "Local appliance repair website for AC, fridge, machine and electronics service.",
  },
  {
    id: "automobile-workshop",
    label: "Automobile Workshop",
    category: "Auto",
    color: "#EF4444",
    bg: "#100303",
    industries: ["automobile workshop", "garage", "auto care", "repair"],
    keywords: ["garage", "mechanic", "car repair", "workshop", "auto service"],
    description: "Practical automobile workshop website for mechanics, repair and servicing.",
  },
  {
    id: "bike-showroom",
    label: "Bike Showroom",
    category: "Auto",
    color: "#FF4E00",
    bg: "#100402",
    industries: ["bike showroom", "automobile", "retail", "auto"],
    keywords: ["bike", "motorcycle", "showroom", "scooter", "dealer"],
    description: "High-energy bike showroom website for dealerships and two-wheeler brands.",
  },
  {
    id: "ev-showroom",
    label: "EV Showroom",
    category: "Auto",
    color: "#22C55E",
    bg: "#031008",
    industries: ["ev showroom", "automobile", "electric vehicle", "retail"],
    keywords: ["ev", "electric vehicle", "scooter", "battery", "showroom"],
    description: "Modern EV showroom website for electric scooters, bikes and vehicle dealerships.",
  },
  {
    id: "driving-school",
    label: "Driving School",
    category: "Auto",
    color: "#FBBF24",
    bg: "#100B03",
    industries: ["driving school", "education", "auto", "training"],
    keywords: ["driving school", "license", "car driving", "training"],
    description: "Lead-generation website for driving schools and vehicle training institutes.",
  },
  {
    id: "car-rental",
    label: "Car Rental",
    category: "Auto",
    color: "#38BDF8",
    bg: "#031018",
    industries: ["car rental", "travel", "automobile", "transport"],
    keywords: ["car rental", "cab", "self drive", "taxi", "travel"],
    description: "Modern car rental website for self-drive, taxi and fleet services.",
  },
  {
    id: "taxi-service",
    label: "Taxi Service",
    category: "Transport",
    color: "#FDE047",
    bg: "#100D03",
    industries: ["taxi", "transport", "travel", "local service"],
    keywords: ["taxi", "cab", "ride", "airport transfer", "booking"],
    description: "Fast taxi service website for local rides, outstation trips and airport transfers.",
  },
  {
    id: "courier-service",
    label: "Courier Service",
    category: "Logistics",
    color: "#4A90D9",
    bg: "#01060D",
    industries: ["courier", "logistics", "delivery", "transport"],
    keywords: ["courier", "delivery", "parcel", "shipping", "logistics"],
    description: "Efficient courier service website for parcel delivery and logistics businesses.",
  },
  {
    id: "warehouse-logistics",
    label: "Warehouse Logistics",
    category: "Logistics",
    color: "#60A5FA",
    bg: "#030B14",
    industries: ["warehouse", "logistics", "supply chain", "b2b"],
    keywords: ["warehouse", "storage", "logistics", "supply chain", "fulfillment"],
    description: "B2B warehouse website for storage, fulfilment and supply chain operations.",
  },
  {
    id: "legal-consultant",
    label: "Legal Consultant",
    category: "Legal",
    color: "#8B7355",
    bg: "#06050A",
    industries: ["legal consultant", "law", "advocate", "consulting"],
    keywords: ["legal consultant", "lawyer", "agreement", "case", "advice"],
    description: "Professional website for legal consultants and advisory services.",
  },
  {
    id: "immigration-consultant",
    label: "Immigration Consultant",
    category: "Legal",
    color: "#60A5FA",
    bg: "#041018",
    industries: ["immigration", "visa consultant", "legal", "travel"],
    keywords: ["immigration", "visa", "study abroad", "pr", "consultant"],
    description: "Trust-focused website for immigration, visa and study abroad consultants.",
  },
  {
    id: "notary-service",
    label: "Notary Service",
    category: "Legal",
    color: "#D6B982",
    bg: "#0B0804",
    industries: ["notary", "legal", "documentation", "services"],
    keywords: ["notary", "document", "affidavit", "legal", "stamp"],
    description: "Simple professional website for notary and legal document services.",
  },
  {
    id: "wedding-planner-luxury",
    label: "Luxury Wedding Planner",
    category: "Events",
    color: "#F8BBD9",
    bg: "#0A0305",
    industries: ["wedding planner", "events", "luxury", "decor"],
    keywords: ["wedding planner", "luxury wedding", "decor", "venue"],
    description: "Luxury wedding planner variation for premium celebrations and destination weddings.",
  },
  {
    id: "corporate-events",
    label: "Corporate Events",
    category: "Events",
    color: "#60A5FA",
    bg: "#030B14",
    industries: ["corporate events", "events", "b2b", "agency"],
    keywords: ["corporate event", "conference", "seminar", "event management"],
    description: "Professional corporate event website for conferences, launches and brand activations.",
  },
  {
    id: "birthday-planner",
    label: "Birthday Planner",
    category: "Events",
    color: "#F472B6",
    bg: "#110612",
    industries: ["birthday planner", "events", "kids", "party"],
    keywords: ["birthday", "party", "planner", "decor", "celebration"],
    description: "Playful event website for birthday parties and celebration planning.",
  },
  {
    id: "photobooth-service",
    label: "Photo Booth Service",
    category: "Events",
    color: "#A855F7",
    bg: "#080412",
    industries: ["photo booth", "events", "photography", "rental"],
    keywords: ["photo booth", "event rental", "party", "wedding", "instant photo"],
    description: "Fun event service website for photo booths and celebration rentals.",
  },
  {
    id: "tent-house",
    label: "Tent House",
    category: "Events",
    color: "#F59E0B",
    bg: "#100804",
    industries: ["tent house", "events", "wedding", "rental"],
    keywords: ["tent house", "mandap", "event rental", "wedding decor"],
    description: "Practical website for tent houses, mandap, decor and event rentals.",
  },
  {
    id: "digital-marketing-agency",
    label: "Digital Marketing Agency",
    category: "Agency",
    color: "#FF4081",
    bg: "#0D0104",
    industries: ["digital marketing", "agency", "advertising", "branding"],
    keywords: ["digital marketing", "seo", "ads", "social media", "growth"],
    description: "Performance-focused agency website for ads, SEO and social media marketing.",
  },
  {
    id: "seo-agency",
    label: "SEO Agency",
    category: "Agency",
    color: "#22C55E",
    bg: "#041008",
    industries: ["seo agency", "marketing", "agency", "b2b"],
    keywords: ["seo", "google ranking", "search", "traffic", "agency"],
    description: "SEO-focused website for search marketing agencies and growth consultants.",
  },
  {
    id: "social-media-agency",
    label: "Social Media Agency",
    category: "Agency",
    color: "#EC4899",
    bg: "#120611",
    industries: ["social media", "agency", "marketing", "creator"],
    keywords: ["social media", "instagram", "content", "reels", "agency"],
    description: "Trendy social media agency website for content, reels and brand growth.",
  },
  {
    id: "branding-studio",
    label: "Branding Studio",
    category: "Agency",
    color: "#D4AF37",
    bg: "#080706",
    industries: ["branding", "agency", "design", "consulting"],
    keywords: ["branding", "logo", "identity", "strategy", "design"],
    description: "Premium branding studio website for identity, strategy and design systems.",
  },
  {
    id: "pr-agency",
    label: "PR Agency",
    category: "Agency",
    color: "#A78BFA",
    bg: "#080615",
    industries: ["pr agency", "public relations", "agency", "corporate"],
    keywords: ["pr", "public relations", "media", "reputation", "press"],
    description: "Professional PR agency website for media relations and reputation building.",
  },
  {
    id: "influencer-marketing",
    label: "Influencer Marketing",
    category: "Agency",
    color: "#F97316",
    bg: "#100604",
    industries: ["influencer marketing", "agency", "social media", "advertising"],
    keywords: ["influencer", "creator campaign", "brand collaboration", "agency"],
    description: "Modern influencer marketing website for creator campaigns and brand collaborations.",
  },
  {
    id: "ai-automation-agency",
    label: "AI Automation Agency",
    category: "Agency",
    color: "#00C2FF",
    bg: "#020B12",
    industries: ["ai automation", "agency", "saas", "consulting"],
    keywords: ["ai", "automation", "chatbot", "workflow", "agency"],
    description: "Futuristic agency website for AI automation, chatbots and workflow systems.",
  },
  {
    id: "website-design-agency",
    label: "Website Design Agency",
    category: "Agency",
    color: "#7C3AED",
    bg: "#060412",
    industries: ["website design", "agency", "development", "branding"],
    keywords: ["website design", "web development", "landing page", "agency"],
    description: "Premium web design agency website for websites, landing pages and digital products.",
  },
  {
    id: "software-company",
    label: "Software Company",
    category: "Tech",
    color: "#00C2FF",
    bg: "#020B12",
    industries: ["software company", "technology", "saas", "development"],
    keywords: ["software company", "development", "tech", "platform", "product"],
    description: "Modern software company website for development services and tech products.",
  },
  {
    id: "cloud-services",
    label: "Cloud Services",
    category: "Tech",
    color: "#38BDF8",
    bg: "#031018",
    industries: ["cloud services", "technology", "IT", "saas"],
    keywords: ["cloud", "aws", "server", "devops", "hosting"],
    description: "Technical cloud services website for hosting, DevOps and infrastructure businesses.",
  },
  {
    id: "it-support",
    label: "IT Support",
    category: "Tech",
    color: "#60A5FA",
    bg: "#030B14",
    industries: ["it support", "technology", "services", "b2b"],
    keywords: ["it support", "computer repair", "network", "managed IT"],
    description: "Professional IT support website for managed services and tech maintenance.",
  },
  {
    id: "data-analytics",
    label: "Data Analytics",
    category: "Tech",
    color: "#A855F7",
    bg: "#080412",
    industries: ["data analytics", "technology", "saas", "consulting"],
    keywords: ["data", "analytics", "dashboard", "business intelligence", "ai"],
    description: "Modern analytics website for BI, dashboards and data consulting brands.",
  },
  {
    id: "ai-saas",
    label: "AI SaaS",
    category: "Tech",
    color: "#7C3AED",
    bg: "#050313",
    industries: ["ai saas", "startup", "software", "technology"],
    keywords: ["ai", "saas", "automation", "model", "platform"],
    description: "Futuristic AI SaaS website for automation platforms and intelligent tools.",
  },
  {
    id: "crm-software",
    label: "CRM Software",
    category: "Tech",
    color: "#4FC3F7",
    bg: "#010A10",
    industries: ["crm", "saas", "software", "b2b"],
    keywords: ["crm", "sales", "pipeline", "customers", "software"],
    description: "B2B SaaS website for CRM, sales tools and customer platforms.",
  },
  {
    id: "cybersecurity-saas",
    label: "Cybersecurity SaaS",
    category: "Tech",
    color: "#00FF94",
    bg: "#010A05",
    industries: ["cybersecurity", "saas", "software", "technology"],
    keywords: ["cybersecurity", "saas", "security platform", "data protection"],
    description: "Product-style cybersecurity SaaS website for secure software platforms.",
  },
  {
    id: "hosting-company",
    label: "Hosting Company",
    category: "Tech",
    color: "#38BDF8",
    bg: "#031018",
    industries: ["hosting", "cloud", "technology", "IT"],
    keywords: ["hosting", "server", "domain", "cloud", "website hosting"],
    description: "Modern hosting company website for domains, servers and cloud plans.",
  },
  {
    id: "domain-provider",
    label: "Domain Provider",
    category: "Tech",
    color: "#F97316",
    bg: "#100604",
    industries: ["domain provider", "hosting", "technology", "IT"],
    keywords: ["domain", "hosting", "dns", "website", "provider"],
    description: "Clean domain provider website for domain registration and hosting add-ons.",
  },
  {
    id: "blockchain-startup",
    label: "Blockchain Startup",
    category: "Tech",
    color: "#A855F7",
    bg: "#060412",
    industries: ["blockchain", "web3", "startup", "technology"],
    keywords: ["blockchain", "web3", "crypto", "smart contract", "startup"],
    description: "Futuristic blockchain website for Web3 products and infrastructure startups.",
  },
  {
    id: "crypto-education",
    label: "Crypto Education",
    category: "Finance",
    color: "#FBBF24",
    bg: "#100B03",
    industries: ["crypto education", "finance", "education", "trading"],
    keywords: ["crypto", "blockchain", "education", "trading", "course"],
    description: "Educational finance website for crypto learning and blockchain awareness.",
  },
  {
    id: "gaming-esports-team",
    label: "Esports Team",
    category: "Tech",
    color: "#39FF14",
    bg: "#010801",
    industries: ["esports", "gaming", "team", "entertainment"],
    keywords: ["esports", "gaming team", "tournament", "stream", "pro player"],
    description: "Neon esports website for teams, tournaments and gaming communities.",
  },
  {
    id: "school-website",
    label: "School Website",
    category: "Edu",
    color: "#60A5FA",
    bg: "#06101A",
    industries: ["school", "education", "academy", "institution"],
    keywords: ["school", "admission", "students", "education", "campus"],
    description: "Trustworthy school website for admissions, academics and parent communication.",
  },
  {
    id: "college-website",
    label: "College Website",
    category: "Edu",
    color: "#A78BFA",
    bg: "#080615",
    industries: ["college", "education", "institution", "campus"],
    keywords: ["college", "university", "admission", "campus", "courses"],
    description: "Modern college website for higher education, admissions and campus life.",
  },
  {
    id: "upsc-coaching",
    label: "UPSC Coaching",
    category: "Edu",
    color: "#D4AF37",
    bg: "#080706",
    industries: ["upsc coaching", "education", "coaching", "academy"],
    keywords: ["upsc", "ias", "civil services", "coaching", "academy"],
    description: "Serious UPSC coaching website for civil services exam preparation.",
  },
  {
    id: "export-business",
    label: "Export Business",
    category: "Industry",
    color: "#38BDF8",
    bg: "#051018",
    industries: ["export", "import", "international trade", "B2B supply", "wholesale", "manufacturing"],
    keywords: ["export", "import", "trade", "international", "supply", "B2B", "wholesale", "manufacturer", "freight", "customs", "sourcing"],
    description: "Professional export business website for international trade, B2B supply and import-export brands.",
  },
  {
    id: "export-logistics",
    label: "Export Logistics",
    category: "Industry",
    color: "#22D3EE",
    bg: "#031014",
    industries: ["export logistics", "shipping", "freight", "cargo", "supply chain", "customs"],
    keywords: ["export", "logistics", "shipping", "freight", "cargo", "transport", "customs", "warehouse", "supply chain", "courier"],
    description: "Professional export logistics website for cargo, shipping, freight and international transport companies.",
  },
]
