// Auto-split chunk 7 of WEBSITE_TEMPLATE_LIBRARY (mechanical split, no logic changes).
// Source: src/lib/website/templates.ts
import type { WebsiteTemplate } from '../template-types'

export const TEMPLATES_CHUNK_07: WebsiteTemplate[] = [
  {
    id: 'bsx-pharma-cold-storage-booking',
    label: 'Pharma Cold Storage — Booking Edition',
    category: 'Logistics',
    color: '#FFD166',
    bg: '#031316',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage booking', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'booking', 'booking edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-trust',
    label: 'Pharma Cold Storage — Trust Edition',
    category: 'Logistics',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage trust', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'trust', 'trust edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-magazine',
    label: 'Pharma Cold Storage — Magazine Edition',
    category: 'Logistics',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage magazine', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'magazine', 'magazine edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-pharma-cold-storage-enterprise',
    label: 'Pharma Cold Storage — Enterprise Edition',
    category: 'Logistics',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['logistics', 'pharma cold storage', 'pharma cold storage enterprise', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance'],
    keywords: ['logistics', 'pharma cold storage', 'enterprise', 'enterprise edition', 'facilities', 'temperature', 'compliance', 'network', 'quote', 'temperature logs', 'validated storage', 'backup power', 'pharma compliance', 'dispatch records'],
    description: 'Standalone unique Logistics website template for Pharma Cold Storage, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-signal',
    label: 'Book Cafe Community — Signal Edition',
    category: 'Food',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['food', 'book cafe community', 'book cafe community signal', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'signal', 'signal edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-atelier',
    label: 'Book Cafe Community — Atelier Edition',
    category: 'Food',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['food', 'book cafe community', 'book cafe community atelier', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'atelier', 'atelier edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-local',
    label: 'Book Cafe Community — Local Growth Edition',
    category: 'Food',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['food', 'book cafe community', 'book cafe community local', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'local', 'local growth edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-commerce',
    label: 'Book Cafe Community — Commerce Edition',
    category: 'Food',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['food', 'book cafe community', 'book cafe community commerce', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'commerce', 'commerce edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-booking',
    label: 'Book Cafe Community — Booking Edition',
    category: 'Food',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['food', 'book cafe community', 'book cafe community booking', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'booking', 'booking edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-trust',
    label: 'Book Cafe Community — Trust Edition',
    category: 'Food',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['food', 'book cafe community', 'book cafe community trust', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'trust', 'trust edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-magazine',
    label: 'Book Cafe Community — Magazine Edition',
    category: 'Food',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['food', 'book cafe community', 'book cafe community magazine', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'magazine', 'magazine edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-book-cafe-community-enterprise',
    label: 'Book Cafe Community — Enterprise Edition',
    category: 'Food',
    color: '#EF4444',
    bg: '#060606',
    industries: ['food', 'book cafe community', 'book cafe community enterprise', 'reading corners', 'author nights', 'coffee menu', 'member shelves'],
    keywords: ['food', 'book cafe community', 'enterprise', 'enterprise edition', 'books', 'coffee', 'events', 'membership', 'visit', 'reading corners', 'author nights', 'coffee menu', 'member shelves', 'book clubs'],
    description: 'Standalone unique Food website template for Book Cafe Community, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-signal',
    label: 'Online Dance Conservatory — Signal Edition',
    category: 'Education Arts',
    color: '#EF4444',
    bg: '#060606',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory signal', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'signal', 'signal edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-atelier',
    label: 'Online Dance Conservatory — Atelier Edition',
    category: 'Education Arts',
    color: '#10B981',
    bg: '#111827',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory atelier', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'atelier', 'atelier edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-local',
    label: 'Online Dance Conservatory — Local Growth Edition',
    category: 'Education Arts',
    color: '#F472B6',
    bg: '#101112',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory local', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'local', 'local growth edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-commerce',
    label: 'Online Dance Conservatory — Commerce Edition',
    category: 'Education Arts',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory commerce', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'commerce', 'commerce edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-booking',
    label: 'Online Dance Conservatory — Booking Edition',
    category: 'Education Arts',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory booking', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'booking', 'booking edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-trust',
    label: 'Online Dance Conservatory — Trust Edition',
    category: 'Education Arts',
    color: '#A3E635',
    bg: '#080501',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory trust', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'trust', 'trust edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-magazine',
    label: 'Online Dance Conservatory — Magazine Edition',
    category: 'Education Arts',
    color: '#FB7185',
    bg: '#031316',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory magazine', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'magazine', 'magazine edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-online-dance-conservatory-enterprise',
    label: 'Online Dance Conservatory — Enterprise Edition',
    category: 'Education Arts',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['education arts', 'online dance conservatory', 'online dance conservatory enterprise', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows'],
    keywords: ['education arts', 'online dance conservatory', 'enterprise', 'enterprise edition', 'styles', 'faculty', 'classes', 'shows', 'enroll', 'live batches', 'recorded practice', 'faculty feedback', 'annual shows', 'level certificates'],
    description: 'Standalone unique Education Arts website template for Online Dance Conservatory, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-signal',
    label: 'Direct To Fan Music Platform — Signal Edition',
    category: 'CreatorTech',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform signal', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'signal', 'signal edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-atelier',
    label: 'Direct To Fan Music Platform — Atelier Edition',
    category: 'CreatorTech',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform atelier', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'atelier', 'atelier edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-local',
    label: 'Direct To Fan Music Platform — Local Growth Edition',
    category: 'CreatorTech',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform local', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'local', 'local growth edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-commerce',
    label: 'Direct To Fan Music Platform — Commerce Edition',
    category: 'CreatorTech',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform commerce', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'commerce', 'commerce edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-booking',
    label: 'Direct To Fan Music Platform — Booking Edition',
    category: 'CreatorTech',
    color: '#06D6A0',
    bg: '#0E0814',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform booking', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'booking', 'booking edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-trust',
    label: 'Direct To Fan Music Platform — Trust Edition',
    category: 'CreatorTech',
    color: '#118AB2',
    bg: '#120817',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform trust', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'trust', 'trust edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-magazine',
    label: 'Direct To Fan Music Platform — Magazine Edition',
    category: 'CreatorTech',
    color: '#E0E7FF',
    bg: '#050313',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform magazine', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'magazine', 'magazine edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-direct-to-fan-music-enterprise',
    label: 'Direct To Fan Music Platform — Enterprise Edition',
    category: 'CreatorTech',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['creatortech', 'direct to fan music platform', 'direct to fan music platform enterprise', 'music drops', 'fan memberships', 'merch links', 'artist dashboard'],
    keywords: ['creatortech', 'direct to fan music platform', 'enterprise', 'enterprise edition', 'artists', 'drops', 'memberships', 'analytics', 'start', 'music drops', 'fan memberships', 'merch links', 'artist dashboard', 'ticket launches'],
    description: 'Standalone unique CreatorTech website template for Direct To Fan Music Platform, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-signal',
    label: 'Security Guard Company — Signal Edition',
    category: 'Security',
    color: '#C4B5FD',
    bg: '#0D0302',
    industries: ['security', 'security guard company', 'security guard company signal', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'signal', 'signal edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-atelier',
    label: 'Security Guard Company — Atelier Edition',
    category: 'Security',
    color: '#F97316',
    bg: '#0A0700',
    industries: ['security', 'security guard company', 'security guard company atelier', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'atelier', 'atelier edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-local',
    label: 'Security Guard Company — Local Growth Edition',
    category: 'Security',
    color: '#14B8A6',
    bg: '#060606',
    industries: ['security', 'security guard company', 'security guard company local', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'local', 'local growth edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-commerce',
    label: 'Security Guard Company — Commerce Edition',
    category: 'Security',
    color: '#7C3AED',
    bg: '#111827',
    industries: ['security', 'security guard company', 'security guard company commerce', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'commerce', 'commerce edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-booking',
    label: 'Security Guard Company — Booking Edition',
    category: 'Security',
    color: '#00C2FF',
    bg: '#101112',
    industries: ['security', 'security guard company', 'security guard company booking', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'booking', 'booking edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-trust',
    label: 'Security Guard Company — Trust Edition',
    category: 'Security',
    color: '#F59E0B',
    bg: '#100A04',
    industries: ['security', 'security guard company', 'security guard company trust', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'trust', 'trust edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-magazine',
    label: 'Security Guard Company — Magazine Edition',
    category: 'Security',
    color: '#EF4444',
    bg: '#100808',
    industries: ['security', 'security guard company', 'security guard company magazine', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'magazine', 'magazine edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-security-guard-company-enterprise',
    label: 'Security Guard Company — Enterprise Edition',
    category: 'Security',
    color: '#10B981',
    bg: '#080501',
    industries: ['security', 'security guard company', 'security guard company enterprise', 'trained guards', 'site audits', 'night patrols', 'control room'],
    keywords: ['security', 'security guard company', 'enterprise', 'enterprise edition', 'services', 'training', 'clients', 'control room', 'enquire', 'trained guards', 'site audits', 'night patrols', 'incident reports'],
    description: 'Standalone unique Security website template for Security Guard Company, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-signal',
    label: '3D Product Rendering Studio — Signal Edition',
    category: 'Creative',
    color: '#10B981',
    bg: '#080501',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio signal', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'signal', 'signal edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-atelier',
    label: '3D Product Rendering Studio — Atelier Edition',
    category: 'Creative',
    color: '#F472B6',
    bg: '#031316',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio atelier', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'atelier', 'atelier edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-local',
    label: '3D Product Rendering Studio — Local Growth Edition',
    category: 'Creative',
    color: '#FDE68A',
    bg: '#09111f',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio local', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'local', 'local growth edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-commerce',
    label: '3D Product Rendering Studio — Commerce Edition',
    category: 'Creative',
    color: '#38BDF8',
    bg: '#020B12',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio commerce', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'commerce', 'commerce edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-booking',
    label: '3D Product Rendering Studio — Booking Edition',
    category: 'Creative',
    color: '#A3E635',
    bg: '#010A05',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio booking', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'booking', 'booking edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-trust',
    label: '3D Product Rendering Studio — Trust Edition',
    category: 'Creative',
    color: '#FB7185',
    bg: '#020C10',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio trust', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'trust', 'trust edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-magazine',
    label: '3D Product Rendering Studio — Magazine Edition',
    category: 'Creative',
    color: '#C084FC',
    bg: '#0E0814',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio magazine', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'magazine', 'magazine edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-3d-product-rendering-enterprise',
    label: '3D Product Rendering Studio — Enterprise Edition',
    category: 'Creative',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['creative', '3d product rendering studio', '3d product rendering studio enterprise', 'cgi renders', 'material setup', 'turntables', 'lifestyle scenes'],
    keywords: ['creative', '3d product rendering studio', 'enterprise', 'enterprise edition', 'work', 'process', 'materials', 'industries', 'book', 'CGI renders', 'material setup', 'turntables', 'lifestyle scenes', 'catalogue exports'],
    description: 'Standalone unique Creative website template for 3D Product Rendering Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-signal',
    label: 'Export Documentation Desk — Signal Edition',
    category: 'Trade',
    color: '#22D3EE',
    bg: '#120817',
    industries: ['trade', 'export documentation desk', 'export documentation desk signal', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'signal', 'signal edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-atelier',
    label: 'Export Documentation Desk — Atelier Edition',
    category: 'Trade',
    color: '#FF6B35',
    bg: '#050313',
    industries: ['trade', 'export documentation desk', 'export documentation desk atelier', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'atelier', 'atelier edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-local',
    label: 'Export Documentation Desk — Local Growth Edition',
    category: 'Trade',
    color: '#FFD166',
    bg: '#0D0302',
    industries: ['trade', 'export documentation desk', 'export documentation desk local', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'local', 'local growth edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-commerce',
    label: 'Export Documentation Desk — Commerce Edition',
    category: 'Trade',
    color: '#06D6A0',
    bg: '#0A0700',
    industries: ['trade', 'export documentation desk', 'export documentation desk commerce', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'commerce', 'commerce edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-booking',
    label: 'Export Documentation Desk — Booking Edition',
    category: 'Trade',
    color: '#118AB2',
    bg: '#060606',
    industries: ['trade', 'export documentation desk', 'export documentation desk booking', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'booking', 'booking edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-trust',
    label: 'Export Documentation Desk — Trust Edition',
    category: 'Trade',
    color: '#E0E7FF',
    bg: '#111827',
    industries: ['trade', 'export documentation desk', 'export documentation desk trust', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'trust', 'trust edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-magazine',
    label: 'Export Documentation Desk — Magazine Edition',
    category: 'Trade',
    color: '#C4B5FD',
    bg: '#101112',
    industries: ['trade', 'export documentation desk', 'export documentation desk magazine', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'magazine', 'magazine edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-export-documentation-desk-enterprise',
    label: 'Export Documentation Desk — Enterprise Edition',
    category: 'Trade',
    color: '#F97316',
    bg: '#100A04',
    industries: ['trade', 'export documentation desk', 'export documentation desk enterprise', 'invoice sets', 'packing lists', 'country rules', 'shipment status'],
    keywords: ['trade', 'export documentation desk', 'enterprise', 'enterprise edition', 'documents', 'compliance', 'shipments', 'partners', 'consult', 'invoice sets', 'packing lists', 'country rules', 'shipment status', 'bank documents'],
    description: 'Standalone unique Trade website template for Export Documentation Desk, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-signal',
    label: 'Modular Kitchen Studio — Signal Edition',
    category: 'Home',
    color: '#F97316',
    bg: '#100A04',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio signal', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'signal', 'signal edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-atelier',
    label: 'Modular Kitchen Studio — Atelier Edition',
    category: 'Home',
    color: '#14B8A6',
    bg: '#100808',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio atelier', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'atelier', 'atelier edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-local',
    label: 'Modular Kitchen Studio — Local Growth Edition',
    category: 'Home',
    color: '#7C3AED',
    bg: '#080501',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio local', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'local', 'local growth edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-commerce',
    label: 'Modular Kitchen Studio — Commerce Edition',
    category: 'Home',
    color: '#00C2FF',
    bg: '#031316',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio commerce', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'commerce', 'commerce edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-booking',
    label: 'Modular Kitchen Studio — Booking Edition',
    category: 'Home',
    color: '#F59E0B',
    bg: '#09111f',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio booking', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'booking', 'booking edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-trust',
    label: 'Modular Kitchen Studio — Trust Edition',
    category: 'Home',
    color: '#EF4444',
    bg: '#020B12',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio trust', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'trust', 'trust edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-magazine',
    label: 'Modular Kitchen Studio — Magazine Edition',
    category: 'Home',
    color: '#10B981',
    bg: '#010A05',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio magazine', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'magazine', 'magazine edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-modular-kitchen-studio-enterprise',
    label: 'Modular Kitchen Studio — Enterprise Edition',
    category: 'Home',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['home', 'modular kitchen studio', 'modular kitchen studio enterprise', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement'],
    keywords: ['home', 'modular kitchen studio', 'enterprise', 'enterprise edition', 'designs', 'materials', 'storage', 'projects', 'visit', 'space planning', 'cabinet finishes', 'storage zones', 'site measurement', 'installation crews'],
    description: 'Standalone unique Home website template for Modular Kitchen Studio, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-signal',
    label: 'Diagnostic Imaging Centre — Signal Edition',
    category: 'Healthcare',
    color: '#F472B6',
    bg: '#020C10',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre signal', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'signal', 'signal edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-atelier',
    label: 'Diagnostic Imaging Centre — Atelier Edition',
    category: 'Healthcare',
    color: '#FDE68A',
    bg: '#0E0814',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre atelier', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'atelier', 'atelier edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-local',
    label: 'Diagnostic Imaging Centre — Local Growth Edition',
    category: 'Healthcare',
    color: '#38BDF8',
    bg: '#120817',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre local', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'local', 'local growth edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-commerce',
    label: 'Diagnostic Imaging Centre — Commerce Edition',
    category: 'Healthcare',
    color: '#A3E635',
    bg: '#050313',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre commerce', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'commerce', 'commerce edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-booking',
    label: 'Diagnostic Imaging Centre — Booking Edition',
    category: 'Healthcare',
    color: '#FB7185',
    bg: '#0D0302',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre booking', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'booking', 'booking edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-trust',
    label: 'Diagnostic Imaging Centre — Trust Edition',
    category: 'Healthcare',
    color: '#C084FC',
    bg: '#0A0700',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre trust', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'trust', 'trust edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-magazine',
    label: 'Diagnostic Imaging Centre — Magazine Edition',
    category: 'Healthcare',
    color: '#22D3EE',
    bg: '#060606',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre magazine', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'magazine', 'magazine edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-diagnostic-imaging-centre-enterprise',
    label: 'Diagnostic Imaging Centre — Enterprise Edition',
    category: 'Healthcare',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['healthcare', 'diagnostic imaging centre', 'diagnostic imaging centre enterprise', 'mri scans', 'ct scans', 'radiologist reports', 'online results'],
    keywords: ['healthcare', 'diagnostic imaging centre', 'enterprise', 'enterprise edition', 'scans', 'doctors', 'reports', 'safety', 'book', 'MRI scans', 'CT scans', 'radiologist reports', 'online results', 'patient prep'],
    description: 'Standalone unique Healthcare website template for Diagnostic Imaging Centre, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-signal',
    label: 'Hyperlocal Job Board — Signal Edition',
    category: 'HRTech',
    color: '#FF6B35',
    bg: '#111827',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board signal', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'signal', 'signal edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-atelier',
    label: 'Hyperlocal Job Board — Atelier Edition',
    category: 'HRTech',
    color: '#FFD166',
    bg: '#101112',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board atelier', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'atelier', 'atelier edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-local',
    label: 'Hyperlocal Job Board — Local Growth Edition',
    category: 'HRTech',
    color: '#06D6A0',
    bg: '#100A04',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board local', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'local', 'local growth edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-commerce',
    label: 'Hyperlocal Job Board — Commerce Edition',
    category: 'HRTech',
    color: '#118AB2',
    bg: '#100808',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board commerce', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'commerce', 'commerce edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-booking',
    label: 'Hyperlocal Job Board — Booking Edition',
    category: 'HRTech',
    color: '#E0E7FF',
    bg: '#080501',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board booking', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'booking', 'booking edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-trust',
    label: 'Hyperlocal Job Board — Trust Edition',
    category: 'HRTech',
    color: '#C4B5FD',
    bg: '#031316',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board trust', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'trust', 'trust edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-magazine',
    label: 'Hyperlocal Job Board — Magazine Edition',
    category: 'HRTech',
    color: '#F97316',
    bg: '#09111f',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board magazine', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'magazine', 'magazine edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-hyperlocal-job-board-enterprise',
    label: 'Hyperlocal Job Board — Enterprise Edition',
    category: 'HRTech',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['hrtech', 'hyperlocal job board', 'hyperlocal job board enterprise', 'area filters', 'verified employers', 'skill tests', 'walk-in slots'],
    keywords: ['hrtech', 'hyperlocal job board', 'enterprise', 'enterprise edition', 'jobs', 'employers', 'areas', 'screening', 'post job', 'area filters', 'verified employers', 'skill tests', 'walk-in slots', 'candidate alerts'],
    description: 'Standalone unique HRTech website template for Hyperlocal Job Board, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-signal',
    label: 'Farm To Table Restaurant — Signal Edition',
    category: 'Food',
    color: '#14B8A6',
    bg: '#020B12',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant signal', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'signal', 'signal edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-atelier',
    label: 'Farm To Table Restaurant — Atelier Edition',
    category: 'Food',
    color: '#7C3AED',
    bg: '#010A05',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant atelier', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'atelier', 'atelier edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-local',
    label: 'Farm To Table Restaurant — Local Growth Edition',
    category: 'Food',
    color: '#00C2FF',
    bg: '#020C10',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant local', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'local', 'local growth edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-commerce',
    label: 'Farm To Table Restaurant — Commerce Edition',
    category: 'Food',
    color: '#F59E0B',
    bg: '#0E0814',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant commerce', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'commerce', 'commerce edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-booking',
    label: 'Farm To Table Restaurant — Booking Edition',
    category: 'Food',
    color: '#EF4444',
    bg: '#120817',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant booking', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'booking', 'booking edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-trust',
    label: 'Farm To Table Restaurant — Trust Edition',
    category: 'Food',
    color: '#10B981',
    bg: '#050313',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant trust', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'trust', 'trust edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-magazine',
    label: 'Farm To Table Restaurant — Magazine Edition',
    category: 'Food',
    color: '#F472B6',
    bg: '#0D0302',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant magazine', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'magazine', 'magazine edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-farm-to-table-restaurant-enterprise',
    label: 'Farm To Table Restaurant — Enterprise Edition',
    category: 'Food',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['food', 'farm to table restaurant', 'farm to table restaurant enterprise', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners'],
    keywords: ['food', 'farm to table restaurant', 'enterprise', 'enterprise edition', 'menu', 'farms', 'chef', 'events', 'reserve', 'seasonal menu', 'farm partners', 'chef table', 'harvest dinners', 'local sourcing'],
    description: 'Standalone unique Food website template for Farm To Table Restaurant, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-signal',
    label: 'Electrician Service Network — Signal Edition',
    category: 'Home Services',
    color: '#FDE68A',
    bg: '#0A0700',
    industries: ['home services', 'electrician service network', 'electrician service network signal', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'signal', 'signal edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-atelier',
    label: 'Electrician Service Network — Atelier Edition',
    category: 'Home Services',
    color: '#38BDF8',
    bg: '#060606',
    industries: ['home services', 'electrician service network', 'electrician service network atelier', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'atelier', 'atelier edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-local',
    label: 'Electrician Service Network — Local Growth Edition',
    category: 'Home Services',
    color: '#A3E635',
    bg: '#111827',
    industries: ['home services', 'electrician service network', 'electrician service network local', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'local', 'local growth edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-commerce',
    label: 'Electrician Service Network — Commerce Edition',
    category: 'Home Services',
    color: '#FB7185',
    bg: '#101112',
    industries: ['home services', 'electrician service network', 'electrician service network commerce', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'commerce', 'commerce edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-booking',
    label: 'Electrician Service Network — Booking Edition',
    category: 'Home Services',
    color: '#C084FC',
    bg: '#100A04',
    industries: ['home services', 'electrician service network', 'electrician service network booking', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'booking', 'booking edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-trust',
    label: 'Electrician Service Network — Trust Edition',
    category: 'Home Services',
    color: '#22D3EE',
    bg: '#100808',
    industries: ['home services', 'electrician service network', 'electrician service network trust', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'trust', 'trust edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-magazine',
    label: 'Electrician Service Network — Magazine Edition',
    category: 'Home Services',
    color: '#FF6B35',
    bg: '#080501',
    industries: ['home services', 'electrician service network', 'electrician service network magazine', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'magazine', 'magazine edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-electrician-service-network-enterprise',
    label: 'Electrician Service Network — Enterprise Edition',
    category: 'Home Services',
    color: '#FFD166',
    bg: '#031316',
    industries: ['home services', 'electrician service network', 'electrician service network enterprise', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards'],
    keywords: ['home services', 'electrician service network', 'enterprise', 'enterprise edition', 'services', 'technicians', 'pricing', 'safety', 'book', 'verified electricians', 'emergency calls', 'transparent pricing', 'warranty cards', 'work photos'],
    description: 'Standalone unique Home Services website template for Electrician Service Network, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-signal',
    label: 'VFX Compositing House — Signal Edition',
    category: 'Media',
    color: '#FFD166',
    bg: '#031316',
    industries: ['media', 'vfx compositing house', 'vfx compositing house signal', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'signal', 'signal edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-atelier',
    label: 'VFX Compositing House — Atelier Edition',
    category: 'Media',
    color: '#06D6A0',
    bg: '#09111f',
    industries: ['media', 'vfx compositing house', 'vfx compositing house atelier', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'atelier', 'atelier edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-local',
    label: 'VFX Compositing House — Local Growth Edition',
    category: 'Media',
    color: '#118AB2',
    bg: '#020B12',
    industries: ['media', 'vfx compositing house', 'vfx compositing house local', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'local', 'local growth edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-commerce',
    label: 'VFX Compositing House — Commerce Edition',
    category: 'Media',
    color: '#E0E7FF',
    bg: '#010A05',
    industries: ['media', 'vfx compositing house', 'vfx compositing house commerce', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'commerce', 'commerce edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-booking',
    label: 'VFX Compositing House — Booking Edition',
    category: 'Media',
    color: '#C4B5FD',
    bg: '#020C10',
    industries: ['media', 'vfx compositing house', 'vfx compositing house booking', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'booking', 'booking edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-trust',
    label: 'VFX Compositing House — Trust Edition',
    category: 'Media',
    color: '#F97316',
    bg: '#0E0814',
    industries: ['media', 'vfx compositing house', 'vfx compositing house trust', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'trust', 'trust edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-magazine',
    label: 'VFX Compositing House — Magazine Edition',
    category: 'Media',
    color: '#14B8A6',
    bg: '#120817',
    industries: ['media', 'vfx compositing house', 'vfx compositing house magazine', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'magazine', 'magazine edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-vfx-compositing-house-enterprise',
    label: 'VFX Compositing House — Enterprise Edition',
    category: 'Media',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['media', 'vfx compositing house', 'vfx compositing house enterprise', 'green screen', 'roto prep', 'shot tracking', 'review links'],
    keywords: ['media', 'vfx compositing house', 'enterprise', 'enterprise edition', 'reels', 'pipeline', 'shots', 'artists', 'book', 'green screen', 'roto prep', 'shot tracking', 'review links', 'delivery masters'],
    description: 'Standalone unique Media website template for VFX Compositing House, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-signal',
    label: 'Artisan Chocolate Brand — Signal Edition',
    category: 'Food Retail',
    color: '#7C3AED',
    bg: '#050313',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand signal', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'signal', 'signal edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-atelier',
    label: 'Artisan Chocolate Brand — Atelier Edition',
    category: 'Food Retail',
    color: '#00C2FF',
    bg: '#0D0302',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand atelier', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'atelier', 'atelier edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-local',
    label: 'Artisan Chocolate Brand — Local Growth Edition',
    category: 'Food Retail',
    color: '#F59E0B',
    bg: '#0A0700',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand local', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'local', 'local growth edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-commerce',
    label: 'Artisan Chocolate Brand — Commerce Edition',
    category: 'Food Retail',
    color: '#EF4444',
    bg: '#060606',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand commerce', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'commerce', 'commerce edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-booking',
    label: 'Artisan Chocolate Brand — Booking Edition',
    category: 'Food Retail',
    color: '#10B981',
    bg: '#111827',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand booking', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'booking', 'booking edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-trust',
    label: 'Artisan Chocolate Brand — Trust Edition',
    category: 'Food Retail',
    color: '#F472B6',
    bg: '#101112',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand trust', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'trust', 'trust edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-magazine',
    label: 'Artisan Chocolate Brand — Magazine Edition',
    category: 'Food Retail',
    color: '#FDE68A',
    bg: '#100A04',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand magazine', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'magazine', 'magazine edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-artisan-chocolate-brand-enterprise',
    label: 'Artisan Chocolate Brand — Enterprise Edition',
    category: 'Food Retail',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['food retail', 'artisan chocolate brand', 'artisan chocolate brand enterprise', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories'],
    keywords: ['food retail', 'artisan chocolate brand', 'enterprise', 'enterprise edition', 'bars', 'origins', 'pairings', 'gifts', 'shop', 'single origin cacao', 'tasting notes', 'gift boxes', 'factory stories', 'subscription bars'],
    description: 'Standalone unique Food Retail website template for Artisan Chocolate Brand, Enterprise Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-signal',
    label: 'RERA Real Estate Advisory — Signal Edition',
    category: 'Real Estate',
    color: '#38BDF8',
    bg: '#100808',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory signal', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'signal', 'signal edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Signal Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-atelier',
    label: 'RERA Real Estate Advisory — Atelier Edition',
    category: 'Real Estate',
    color: '#A3E635',
    bg: '#080501',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory atelier', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'atelier', 'atelier edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Atelier Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-local',
    label: 'RERA Real Estate Advisory — Local Growth Edition',
    category: 'Real Estate',
    color: '#FB7185',
    bg: '#031316',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory local', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'local', 'local growth edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Local Growth Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-commerce',
    label: 'RERA Real Estate Advisory — Commerce Edition',
    category: 'Real Estate',
    color: '#C084FC',
    bg: '#09111f',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory commerce', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'commerce', 'commerce edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Commerce Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-booking',
    label: 'RERA Real Estate Advisory — Booking Edition',
    category: 'Real Estate',
    color: '#22D3EE',
    bg: '#020B12',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory booking', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'booking', 'booking edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Booking Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-trust',
    label: 'RERA Real Estate Advisory — Trust Edition',
    category: 'Real Estate',
    color: '#FF6B35',
    bg: '#010A05',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory trust', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'trust', 'trust edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Trust Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
  {
    id: 'bsx-rera-real-estate-advisory-magazine',
    label: 'RERA Real Estate Advisory — Magazine Edition',
    category: 'Real Estate',
    color: '#FFD166',
    bg: '#020C10',
    industries: ['real estate', 'rera real estate advisory', 'rera real estate advisory magazine', 'rera checks', 'site visits', 'loan desks', 'legal review'],
    keywords: ['real estate', 'rera real estate advisory', 'magazine', 'magazine edition', 'projects', 'legal', 'loans', 'visits', 'consult', 'RERA checks', 'site visits', 'loan desks', 'legal review', 'builder history'],
    description: 'Standalone unique Real Estate website template for RERA Real Estate Advisory, Magazine Edition, with industry-specific menu sections, images, proof, FAQ and lead capture.',
  },
]
