// src/lib/website/renderTemplateHtml.ts
// SERVER-ONLY — reads public/samples/*.html and applies plan personalisation.
// Uses only string operations. No heavy DOM parser dependency required.
// Do NOT import this into client components.

import { readTemplateHtml } from './templateFiles'
import { getFallbackTemplate } from './templates'
import type { WebsiteTemplatePlan, SectionItem, PlanSection } from './generateTemplatePlan'

// ── Minimal HTML fallback when template file is missing ───────────────────────

function buildMinimalHtml(plan: WebsiteTemplatePlan): string {
  const { business_name, hero, seo, colors, sections } = plan

  const servicesSection = sections.find(
    (s): s is Extract<PlanSection, { type: 'services' }> => s.type === 'services'
  )
  const whyUsSection = sections.find(
    (s): s is Extract<PlanSection, { type: 'why_us' }> => s.type === 'why_us'
  )
  const contactSection = sections.find(
    (s): s is Extract<PlanSection, { type: 'contact' }> => s.type === 'contact'
  )

  const serviceItems = servicesSection?.items
    ?.map(
      (item: SectionItem) =>
        `<div style="background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:24px 20px;margin-bottom:16px;">
          <h3 style="font-size:18px;font-weight:600;margin:0 0 10px;color:${colors.primary}">${item.title}</h3>
          <p style="font-size:14px;color:rgba(255,255,255,0.7);margin:0;line-height:1.6;">${item.description}</p>
        </div>`
    )
    .join('') ?? ''

  const whyItems = whyUsSection?.items
    ?.map(
      (item: SectionItem) =>
        `<div style="margin-bottom:20px;">
          <div style="font-size:16px;font-weight:600;color:${colors.primary};margin-bottom:6px;">${item.title}</div>
          <div style="font-size:14px;color:rgba(255,255,255,0.65);line-height:1.6;">${item.description}</div>
        </div>`
    )
    .join('') ?? ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${seo.title}</title>
  <meta name="description" content="${seo.description}">
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{background:${colors.background};color:#fff;font-family:'Inter','DM Sans',system-ui,sans-serif;line-height:1.6}
    .hero{min-height:90vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:80px 24px;background:linear-gradient(135deg,${colors.background} 0%,#1a1a2e 100%)}
    .hero h1{font-size:clamp(36px,6vw,80px);font-weight:700;line-height:1.1;margin-bottom:20px;letter-spacing:-0.02em}
    .hero p{font-size:18px;color:rgba(255,255,255,0.7);max-width:560px;margin:0 auto 32px;line-height:1.7}
    .btn{display:inline-flex;align-items:center;gap:8px;padding:14px 28px;border-radius:6px;font-size:14px;font-weight:600;text-decoration:none;letter-spacing:0.04em;cursor:pointer;border:none}
    .btn-primary{background:${colors.primary};color:#000}
    .btn-secondary{background:transparent;color:${colors.primary};border:1px solid ${colors.primary}40;margin-left:12px}
    section{padding:80px 24px;max-width:1100px;margin:0 auto}
    .section-label{font-size:10px;letter-spacing:0.22em;text-transform:uppercase;color:${colors.primary};margin-bottom:16px}
    h2{font-size:clamp(28px,4vw,48px);font-weight:700;line-height:1.2;margin-bottom:32px}
    footer{text-align:center;padding:48px 24px;color:rgba(255,255,255,0.35);font-size:12px;border-top:1px solid rgba(255,255,255,0.08)}
  </style>
</head>
<body>
  <!-- Generated by Brand Syndicate website mode: ${plan.template_id} (minimal fallback) -->
  <nav style="position:fixed;top:0;left:0;right:0;z-index:100;padding:18px 32px;display:flex;justify-content:space-between;align-items:center;background:rgba(${hexToRgb(colors.background)},0.9);backdrop-filter:blur(20px);border-bottom:1px solid rgba(255,255,255,0.08)">
    <div style="font-size:18px;font-weight:700;letter-spacing:-0.01em;color:${colors.primary}">${business_name}</div>
    <a href="#contact" class="btn btn-primary" style="padding:8px 20px;font-size:12px">${hero.cta_primary}</a>
  </nav>

  <div class="hero">
    <div>
      <div class="section-label">${plan.industry}</div>
      <h1 style="color:#fff">${hero.headline}</h1>
      <p>${hero.subheadline}</p>
      <a href="#services" class="btn btn-primary">${hero.cta_primary}</a>
      <a href="#contact" class="btn btn-secondary">${hero.cta_secondary}</a>
    </div>
  </div>

  ${servicesSection ? `
  <section id="services" style="padding:80px 24px;max-width:1100px;margin:0 auto">
    <div class="section-label">Services</div>
    <h2>${servicesSection.title}</h2>
    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px">
      ${serviceItems}
    </div>
  </section>` : ''}

  ${whyUsSection ? `
  <section style="padding:80px 24px;max-width:900px;margin:0 auto">
    <div class="section-label">Why Us</div>
    <h2>${whyUsSection.title}</h2>
    ${whyItems}
  </section>` : ''}

  ${contactSection ? `
  <section id="contact" style="padding:80px 24px;max-width:700px;margin:0 auto;text-align:center">
    <div class="section-label">Contact</div>
    <h2>${contactSection.title}</h2>
    <p style="font-size:16px;color:rgba(255,255,255,0.65);margin-bottom:32px;line-height:1.7">${contactSection.description}</p>
    <a href="mailto:hello@${business_name.toLowerCase().replace(/\s+/g,'')+'.com'}" class="btn btn-primary">${hero.cta_primary}</a>
  </section>` : ''}

  <footer>&copy; ${new Date().getFullYear()} ${business_name}. Website powered by <a href="https://www.thebrandsyndicate.in" style="color:${colors.primary};text-decoration:none">Brand Syndicate</a></footer>
</body>
</html>`
}

// Convert #rrggbb to "r,g,b" for rgba()
function hexToRgb(hex: string): string {
  const clean = hex.replace('#', '')
  const r = parseInt(clean.slice(0, 2), 16)
  const g = parseInt(clean.slice(2, 4), 16)
  const b = parseInt(clean.slice(4, 6), 16)
  if (isNaN(r) || isNaN(g) || isNaN(b)) return '0,0,0'
  return `${r},${g},${b}`
}

// ── HTML completeness repair ──────────────────────────────────────────────────

export function ensureTemplateHtmlComplete(html: string): string {
  let fixed = html.trim()
  if (!fixed) return fixed

  if (!fixed.toLowerCase().startsWith('<!doctype')) {
    fixed = `<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>\n<body>\n${fixed}\n</body>\n</html>`
    return fixed
  }
  if (!/<html/i.test(fixed))  fixed = `<!DOCTYPE html>\n<html lang="en">\n${fixed}\n</html>`
  if (!/<head/i.test(fixed))  fixed = fixed.replace(/<html[^>]*>/i, m => `${m}\n<head></head>`)
  if (!/<body/i.test(fixed))  fixed = fixed.replace(/<\/head>/i, '</head>\n<body>') + '\n</body>'
  if (!/<\/html>/i.test(fixed)) fixed += '\n</html>'

  return fixed
}

// ── Safe string replacement helpers ──────────────────────────────────────────

function replaceFirst(html: string, pattern: RegExp, replacement: string): string {
  return html.replace(pattern, replacement)
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function safeText(str: string): string {
  // Allow normal HTML in the template, but escape values coming from user input
  return str.replace(/[<>"]/g, c => ({ '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] ?? c))
}


function buildRealContentSections(plan: WebsiteTemplatePlan): string {
  const servicesSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'services' }> => s.type === 'services'
  )
  const whyUsSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'why_us' }> => s.type === 'why_us'
  )
  const contactSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'contact' }> => s.type === 'contact'
  )

  const serviceItems = (servicesSection?.items?.length ? servicesSection.items : [
    { title: 'Premium Service', description: `High-quality ${plan.industry.toLowerCase()} solutions designed around real customer needs.` },
    { title: 'Fast Delivery', description: 'Clear process, quick turnaround, and reliable execution from enquiry to completion.' },
    { title: 'Customer Support', description: 'Helpful assistance before, during, and after the service so customers always know the next step.' },
  ]).slice(0, 6)

  const whyItems = (whyUsSection?.items?.length ? whyUsSection.items : [
    { title: 'Trusted Team', description: 'Experienced professionals focused on quality, clarity, and dependable delivery.' },
    { title: 'Business Ready', description: 'Built with the sections customers expect: services, proof, process, FAQs, and contact actions.' },
    { title: 'Local Understanding', description: 'Messaging and structure suitable for Indian buyers, enquiries, bookings, and sales calls.' },
  ]).slice(0, 4)

  const card = (item: SectionItem, index: number) => `
    <article class="bs-real-card">
      <span>${String(index + 1).padStart(2, '0')}</span>
      <h3>${safeText(item.title)}</h3>
      <p>${safeText(item.description)}</p>
    </article>`

  return `
<section id="bs-ready-content" class="bs-real-site-section" aria-label="${safeText(plan.business_name)} services and details">
  <div class="bs-real-wrap">
    <p class="bs-real-label">${safeText(plan.industry)}</p>
    <h2>${safeText(servicesSection?.title || `${plan.business_name} Services`)}</h2>
    <p class="bs-real-intro">${safeText(plan.hero.subheadline)}</p>
    <div class="bs-real-grid">${serviceItems.map(card).join('')}</div>
  </div>
</section>
<section class="bs-real-site-section bs-real-site-section-alt" aria-label="Why choose ${safeText(plan.business_name)}">
  <div class="bs-real-wrap">
    <p class="bs-real-label">Why Choose Us</p>
    <h2>${safeText(whyUsSection?.title || `Why ${plan.business_name}`)}</h2>
    <div class="bs-real-proof-grid">${whyItems.map(card).join('')}</div>
  </div>
</section>
<section id="contact" class="bs-real-contact" aria-label="Contact ${safeText(plan.business_name)}">
  <div class="bs-real-wrap bs-real-contact-box">
    <p class="bs-real-label">Contact</p>
    <h2>${safeText(contactSection?.title || `Start with ${plan.business_name}`)}</h2>
    <p>${safeText(contactSection?.description || 'Share your requirement and our team will contact you shortly.')}</p>
    <a class="bs-real-cta" href="mailto:hello@${safeText(plan.business_name.toLowerCase().replace(/[^a-z0-9]+/g, '') || 'business')}.com">${safeText(plan.hero.cta_primary || 'Enquire Now')}</a>
  </div>
</section>`
}

function hasThinTemplateContent(html: string): boolean {
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  const body = bodyMatch ? bodyMatch[1] : html
  const text = body
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()

  const placeholderHits = [
    'service one', 'service two', 'service three', 'template is intentionally',
    'structure is intentionally predictable', 'your backend can safely replace',
    'lorem ipsum', 'feature one', 'feature two', 'placeholder'
  ].filter(token => text.includes(token)).length

  const sectionCount = (html.match(/<section\b/gi) || []).length
  return placeholderHits > 0 || text.length < 1200 || sectionCount < 3
}

function injectBeforeFooterOrBody(html: string, block: string): string {
  if (html.includes('id="bs-ready-content"') || html.includes("id='bs-ready-content'")) return html
  if (/<footer\b/i.test(html)) return html.replace(/<footer\b/i, `${block}\n<footer`)
  if (/<\/body>/i.test(html)) return html.replace(/<\/body>/i, `${block}\n</body>`)
  return html + block
}

function stripTemplateLanguage(html: string): string {
  const replacements: Array<[RegExp, string]> = [
    [/\btemplate\b/gi, 'website'],
    [/\btemplates\b/gi, 'websites'],
    [/\bplaceholder\b/gi, 'content'],
    [/\bdemo content\b/gi, 'business content'],
    [/\bClaude JSON personalisation\b/gi, 'business personalisation'],
    [/\bClaude JSON\b/gi, 'business content'],
    [/\bAI personalisation\b/gi, 'business personalisation'],
    [/\bBrand Syndicate AI personalisation\b/gi, 'business personalisation'],
    [/\bprompt-based industry matching\b/gi, 'industry-focused messaging'],
    [/\bfree AI preview\b/gi, 'business website'],
    [/\bAI preview\b/gi, 'business website'],
    [/this website is intentionally different from your current \d+ files:?/gi, ''],
    [/the structure is intentionally predictable:?/gi, ''],
    [/your backend can safely replace text while keeping the design intact\.?/gi, ''],
    [/new ID, new label, new section order, industry menu, copy pattern and layout treatment\.?/gi, ''],
    [/inside Brand Syndicate\.?/gi, ''],
    [/\bpreview\b/gi, 'website'],
    [/\bpreviews\b/gi, 'websites'],
    [/\bAI generator\b/gi, 'business system'],
    [/\byour backend\b/gi, 'the team'],
    [/\bBrand Syndicate AI renderer\b/gi, 'service team'],
    [/Every section is structured so your AI generator can replace copy, colours and business details without breaking the design\.?/gi, 'Every section explains the offer clearly, builds trust and guides visitors toward enquiry.'],
    [/The structure is intentionally predictable:\s*hero, proof, services, process, testimonials, FAQ and contact\.\s*Your backend can safely replace text while keeping the design intact\.?/gi, 'This page combines hero positioning, proof, services, process, testimonials, FAQ and contact to create a complete customer journey.'],
    [/Responsive,\s*premium\s*and\s*ready\s*for\s*Brand Syndicate\s*AI personalisation\.?/gi, 'Responsive, premium and built for serious enquiries.'],
    [/Yes\. The text, colours, images, service cards and contact details are designed to be replaced by the Brand Syndicate AI renderer\.?/gi, 'Yes. The offering can be tailored based on customer needs, quantity, timeline and location.'],
    [/Yes\. It is built to work as a low-cost website while still looking polished and conversion-focused\.?/gi, 'Yes. Visitors can use the enquiry form or contact action to request more information.'],
    [/Images, final copy, SEO, domain setup, analytics, forms and brand-specific sections should be refined during paid delivery\.?/gi, 'Customers should share their requirement, quantity, timeline, budget and preferred contact details.'],
    [/What should be refined for paid clients\?/gi, 'What details should customers share before starting?'],
    [/Can this be used for a free business website\?/gi, 'Can visitors enquire from this page?'],
    [/Can this be used for a business website\?/gi, 'Can visitors enquire from this page?'],
    [/low-cost website/gi, 'lean business website'],
    [/generated website/gi, 'customer page'],
    [/regenerate repeatedly/gi, 'repeat rework'],
    [/copy replacement/gi, 'content clarity'],
    [/Trust blocks already/gi, 'Customer trust'],
    [/built into the page/gi, 'built into every section'],
    [/Claude JSON personalisation/gi, 'service and content clarity'],
    [/Claude JSON/gi, 'business content'],
    [/prompt-based industry matching/gi, 'category-specific messaging'],
    [/AI personalisation/gi, 'clear customer journey'],
    [/business personalisation/gi, 'customer-ready presentation'],
    [/enough structure for AI personalisation/gi, 'a clear customer journey'],
    [/responsive copy wrapping and clear conversion context/gi, 'clear mobile layout and customer-focused detail'],
    [/copy wrapping/gi, 'mobile readability'],
    [/conversion context/gi, 'customer context'],
    [/Hero image and CTA area sized for desktop, tablet and mobile preview cards\.?/gi, 'Hero section keeps imagery, messaging and CTA readable across desktop, tablet and mobile.'],
    [/Hero image and CTA area sized for desktop, tablet and mobile website cards\.?/gi, 'Hero section keeps imagery, messaging and CTA readable across desktop, tablet and mobile.'],
    [/Work designed for ([^.]+)\.?/gi, 'Work created for $1 customers.'],
    [/Work designed for/gi, 'Work created for'],
    [/This website is built around/gi, 'This page presents'],
    [/includes a dedicated section for/gi, 'highlights'],
    [/Necessary website elements are included so Claude can add these as complete websites, not empty design shells\.?/gi, 'Essential customer journey elements are included so the page feels complete, credible and ready for enquiries.'],
    [/Claude can add these as complete websites, not empty design shells\.?/gi, 'the page feels complete, credible and ready for enquiries.'],
    [/not empty design shells/gi, 'not empty layouts'],
    [/empty design shells/gi, 'thin layouts'],
    [/This website keeps/gi, 'This section keeps'],
    [/Lead capture ready for Brand Syndicate\.?/gi, 'Lead capture ready.'],
    [/Use this page to collect enquiries and present the offer clearly\.\s*inside Brand Syndicate\.?/gi, 'Use this page to collect enquiries and present the offer clearly.'],
    [/inside Brand Syndicate\.?/gi, ''],
    [/Connect this form to your existing generation history, admin panel, WhatsApp follow-up or CRM\. The layout stays readable even when Claude inserts longer AI content\.?/gi, 'Connect this form to WhatsApp, CRM or direct follow-up. The layout stays readable even with longer customer requirements.'],
    [/generation history, admin panel, WhatsApp follow-up or CRM/gi, 'WhatsApp, CRM or direct follow-up'],
    [/even when Claude inserts longer AI content/gi, 'even with longer customer requirements'],
    [/AI content/gi, 'customer requirements'],
  ]

  return html
    .split(/(<[^>]+>)/g)
    .map(part => {
      if (part.startsWith('<')) return part
      let clean = part
      for (const [pattern, replacement] of replacements) clean = clean.replace(pattern, replacement)
      return clean.replace(/\s{2,}/g, ' ')
    })
    .join('')
}


function stableTemplateImageForQuery(query: string): string {
  const hay = decodeURIComponent(String(query || '')).replace(/[,+]/g, ' ')
  const options: Array<[RegExp, string]> = [
    [/furniture|sofa|interior|decor|wood|carpenter|kitchen/i, 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=75&auto=format&fit=crop'],
    [/school|college|academy|coaching|learning|education|training|student|course/i, 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=75&auto=format&fit=crop'],
    [/clinic|hospital|doctor|medical|dental|ayurveda|wellness|spa|health/i, 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&q=75&auto=format&fit=crop'],
    [/restaurant|cafe|bakery|food|cloud-kitchen|bar|lounge|chef|chocolate/i, 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=75&auto=format&fit=crop'],
    [/fashion|boutique|clothing|apparel|beauty|cosmetic|salon/i, 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1200&q=75&auto=format&fit=crop'],
    [/jewel|diamond|luxury|adore/i, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&q=75&auto=format&fit=crop'],
    [/real-estate|property|villa|architect|architecture|construction/i, 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=75&auto=format&fit=crop'],
    [/auto|car|bike|vehicle|automobile|mobility|showroom/i, 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=75&auto=format&fit=crop'],
    [/sports|fitness|gym|marathon|bat|cricket|club/i, 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&q=75&auto=format&fit=crop'],
    [/farm|agri|crop|organic|dairy|rural/i, 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=75&auto=format&fit=crop'],
    [/finance|accounting|fintech|bank|tax|loan|wealth/i, 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=75&auto=format&fit=crop'],
    [/logistics|warehouse|courier|shipping|transport/i, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=75&auto=format&fit=crop'],
    [/solar|energy|power/i, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=75&auto=format&fit=crop'],
    [/travel|tour|hotel|resort|stay/i, 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=75&auto=format&fit=crop'],
    [/law|legal|advocate/i, 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=75&auto=format&fit=crop'],
    [/tech|saas|software|ai|automation|cyber|blockchain|app|cloud/i, 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=75&auto=format&fit=crop'],
  ]
  for (const [pattern, url] of options) if (pattern.test(hay)) return url
  return 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=75&auto=format&fit=crop'
}

function replaceDeprecatedTemplateImages(html: string): string {
  return html.replace(/https:\/\/source\.unsplash\.com\/featured\/(?:\d+x\d+\/)?\?([^"'\s<)]+)/gi, (_match, query: string) => stableTemplateImageForQuery(query))
}

function repairCommonTemplateHtmlIssues(html: string): string {
  return replaceDeprecatedTemplateImages(html)
    // Some imported sample templates had <img ... /> loading="lazy" which can break parsing in browsers.
    .replace(/<img([^>]*?)\/\s+(loading|decoding|style|class|alt|src)=/gi, '<img$1 $2=')
    .replace(/<img([^>]*?)\/\s*>/gi, '<img$1>')
    // Prevent accidental 100vw + scrollbar overflow on generated sites.
    .replace(/width:\s*100vw/gi, 'width:100%')
    .replace(/min-width:\s*100vw/gi, 'min-width:100%')
}

function replaceTextOutsideTags(html: string, replacements: Array<[RegExp, string]>): string {
  return html
    .split(/(<[^>]+>)/g)
    .map(part => {
      if (part.startsWith('<')) return part
      let clean = part
      for (const [pattern, replacement] of replacements) clean = clean.replace(pattern, replacement)
      return clean.replace(/\s{2,}/g, ' ')
    })
    .join('')
}

function replaceFirstTextInTag(html: string, tag: string, value: string): string {
  const pattern = new RegExp(`(<${tag}\\b[^>]*>)[\\s\\S]*?(<\\/${tag}>)`, 'i')
  return html.replace(pattern, `$1${safeText(value)}$2`)
}

function replaceNthTextInTags(html: string, tag: string, values: string[], offset = 0): string {
  let index = 0
  return html.replace(new RegExp(`(<${tag}\\b[^>]*>)[\\s\\S]*?(<\\/${tag}>)`, 'gi'), (match, open, close) => {
    const value = values[index - offset]
    index += 1
    if (index <= offset || value === undefined) return match
    return `${open}${safeText(value)}${close}`
  })
}

function getPlanCopy(plan: WebsiteTemplatePlan) {
  const servicesSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'services' }> => s.type === 'services'
  )
  const whyUsSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'why_us' }> => s.type === 'why_us'
  )
  const contactSection = plan.sections.find(
    (s): s is Extract<PlanSection, { type: 'contact' }> => s.type === 'contact'
  )

  const serviceItems = (servicesSection?.items?.length ? servicesSection.items : [
    { title: `${plan.business_name} Services`, description: plan.hero.subheadline },
    { title: 'Reliable Delivery', description: 'Clear process, dependable execution and support from enquiry to completion.' },
    { title: 'Customer-Focused Support', description: 'Helpful guidance and quick responses for serious buyers and enquiries.' },
    { title: 'Custom Requirements', description: 'Flexible solutions built around business needs, budgets and timelines.' },
  ]).slice(0, 8)

  const whyItems = (whyUsSection?.items?.length ? whyUsSection.items : [
    { title: 'Trusted Quality', description: `${plan.business_name} focuses on dependable quality, clear communication and practical results.` },
    { title: 'Built for Buyers', description: 'The website journey is designed to help visitors understand the offer and take action.' },
    { title: 'Fast Enquiry Flow', description: 'Repeated contact actions and clear sections guide visitors toward calls, quotes and bookings.' },
    { title: 'Premium Presentation', description: 'A refined structure helps the brand look credible across mobile and desktop.' },
  ]).slice(0, 6)

  return { servicesSection, whyUsSection, contactSection, serviceItems, whyItems }
}

function personaliseTemplateSections(html: string, plan: WebsiteTemplatePlan): string {
  const { serviceItems, whyItems, servicesSection, whyUsSection, contactSection } = getPlanCopy(plan)
  const business = safeText(plan.business_name)
  const industry = safeText(plan.industry)
  const heroSub = safeText(plan.hero.subheadline)
  const serviceTitle = safeText(servicesSection?.title || `${plan.business_name} Services`)
  const whyTitle = safeText(whyUsSection?.title || `Why Choose ${plan.business_name}`)
  const contactTitle = safeText(contactSection?.title || `Start with ${plan.business_name}`)
  const contactDesc = safeText(contactSection?.description || 'Share your requirement and our team will contact you shortly.')

  // Replace template labels / internal preview copy without touching tags, classes or layout.
  html = replaceTextOutsideTags(html, [
    [/Live Preview/gi, 'Project Snapshot'],
    [/Business Preview/gi, 'Project Snapshot'],
    [/Preview Quality/gi, 'Website Quality'],
    [/Fast Preview ready/gi, 'Fast enquiry ready'],
    [/Responsive,\s*premium\s*and\s*ready\s*for\s*Brand Syndicate\s*AI personalisation\.?/gi, `Responsive, premium and built for serious enquiries.`],
    [/Every section is structured so your AI generator can replace copy, colours and business details without breaking the design\.?/gi, `Every section explains the offer clearly, builds trust and guides visitors toward enquiry.`],
    [/The structure is intentionally predictable:\s*hero, proof, services, process, testimonials, FAQ and contact\.\s*Your backend can safely replace text while keeping the design intact\.?/gi, `This page combines hero positioning, proof, services, process, testimonials, FAQ and contact to create a complete customer journey.`],
    [/This website is intentionally different from your current \d+ files:?\s*new ID, new label, new section order, industry menu, copy pattern and layout treatment\.?/gi, `A focused section built around clear services, proof and enquiry flow.`],
    [/generated preview/gi, 'customer page'],
    [/the need for users to regenerate repeatedly/gi, 'the need for repeated rework'],
    [/regenerate repeatedly/gi, 'repeat rework'],
    [new RegExp(plan.template_label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), business],
    [/Industry website/gi, `${industry} Website`],
    [/Creative website/gi, `${industry} Website`],
    [/Live Preview/gi, 'Business Preview'],
    [/Responsive,\s*premium\s*and\s*ready\s*for\s*Brand Syndicate\s*AI personalisation\.?/gi, `Responsive, premium and ready for ${business} customers.`],
    [/Responsive,\s*premium\s*and\s*ready\s*for\s*business personalisation\.?/gi, `Responsive, premium and ready for ${business} customers.`],
    [/Built for serious\s*business growth\./gi, `Built for ${business}'s growth.`],
    [/Industrial website for manufacturers, factories and B2B suppliers\./gi, heroSub],
    [/Every section is structured so your AI generator can replace copy, colours and business details without breaking the design\./gi, `Every section is structured to explain ${business} clearly and guide visitors toward enquiry.`],
    [/Why This Works/gi, whyTitle],
    [/A complete credibility-first business journey for[^.]*\./gi, `${whyTitle}.`],
    [/This website is built around[^.]*\./gi, `${business} is presented with clear services, proof points, enquiry flow and premium business positioning.`],
    [/Website sections with\s*real business depth\./gi, `${business} services with real business depth.`],
    [/Instead of a thin landing page,[^.]*\./gi, `This layout gives visitors clear reasons to trust ${business} and enquire.`],
    [/Preview Quality/gi, 'Website Quality'],
    [/Made for business personalisation without breaking the layout\./gi, `Made to present ${business} clearly without breaking the layout.`],
    [/Works for industry-focused messaging/gi, 'Built around customer search intent'],
    [/Clear sections for business content personalisation/gi, 'Clear sections for services, proof and enquiry'],
    [/Clear sections for services, proof and enquiries/gi, 'Clear sections for services, proof and enquiry'],
    [/Responsive composition for phone, tablet and desktop/gi, 'Responsive composition for phone, tablet and desktop'],
    [/Can this website be customised for a real[^?]*\?/gi, `Can ${business} handle custom requirements?`],
    [/Will it work on mobile devices\?/gi, 'Is the website mobile friendly?'],
    [/Can this be used for a business website\?/gi, `Can I contact ${business} from this page?`],
    [/Can this be used for a free business website\?/gi, `Can I contact ${business} from this page?`],
    [/What should be refined for paid clients\?/gi, `What details should customers share with ${business}?`],
    [/Yes\. The text, colours, images, service cards and contact details are designed to be replaced by the Brand Syndicate AI renderer\./gi, `${business} can tailor the offering based on customer needs, quantity, timeline and location.`],
    [/Yes\. It is built to work as a low-cost preview website while still looking polished and conversion-focused\./gi, 'Yes. Visitors can use the enquiry form or contact action to request more information.'],
    [/Images, final copy, SEO, domain setup, analytics, forms and brand-specific sections should be refined during paid delivery\./gi, 'Customers should share their requirement, quantity, timeline, budget and preferred contact details.'],
    [/Use this website as a fast,\s*premium base for AI-personalised website previews\s*/gi, contactDesc],
    [/Ready to build your [^?]+ brand\?/gi, contactTitle],
    [/Turn the preview into a real enquiry page\./gi, 'Turn interest into a real enquiry.'],
    [/Connect this section to your Brand Syndicate lead form, WhatsApp CTA or booking flow when the website is used for a client\./gi, contactDesc],
    [/Lead Ready/gi, 'Enquiry Ready'],
  ])

  // Replace common stock service/process card copy with plan-specific content.
  const serviceReplacements = [
    { title: serviceItems[0]?.title || 'Main Service', desc: serviceItems[0]?.description || plan.hero.subheadline },
    { title: serviceItems[1]?.title || 'Premium Quality', desc: serviceItems[1]?.description || 'Quality-focused service built around customer needs.' },
    { title: serviceItems[2]?.title || 'Fast Enquiry Flow', desc: serviceItems[2]?.description || 'Clear contact actions help visitors enquire quickly.' },
  ]
  html = replaceTextOutsideTags(html, [
    [/Premium\s+(?:Industry|Tech|Creative|Local|Health|Retail|Service)\s+Strategy/gi, serviceReplacements[0].title],
    [/Conversion Ready Design/gi, serviceReplacements[1].title],
    [/Fast Inquiry Flow/gi, serviceReplacements[2].title],
    [/A polished digital presence made for[^.]*\./gi, serviceReplacements[0].desc],
    [/Clear sections, responsive spacing and strong CTAs designed for mobile-first visitors\./gi, serviceReplacements[1].desc],
    [/Inquiry buttons, contact section and trust blocks built to convert interest into leads\./gi, serviceReplacements[2].desc],
    [/Position the offer/gi, serviceItems[0]?.title || 'Present the Offer'],
    [/Hero section explains who the business helps and why it matters\./gi, serviceItems[0]?.description || plan.hero.subheadline],
    [/Build trust quickly/gi, whyItems[0]?.title || 'Build Trust'],
    [/Service cards, process and visual hierarchy make the brand look credible\./gi, whyItems[0]?.description || 'Clear proof points help visitors trust the business quickly.'],
    [/Convert visitors/gi, contactTitle],
    [/Clear CTA and contact anchor guide visitors toward enquiry\./gi, contactDesc],
    [/Launch Ready Capabilities/gi, serviceItems[0]?.title || 'Core Capabilities'],
    [/Present the main offer with clear value, refined hierarchy and a CTA that matches high-intent visitors\./gi, serviceItems[0]?.description || plan.hero.subheadline],
    [/Conversion System/gi, serviceItems[1]?.title || 'Conversion System'],
    [/Showcase the most important benefits using structured cards that work across mobile and desktop\./gi, serviceItems[1]?.description || 'Clear sections help visitors scan the offer and enquire.'],
    [/Premium Proof/gi, whyItems[0]?.title || 'Premium Proof'],
    [/Build confidence through proof points, process clarity and testimonial-ready content blocks\./gi, whyItems[0]?.description || 'Trust-building sections answer customer objections.'],
    [/Growth CTA|Lead Engine/gi, contactTitle],
    [/Guide users from curiosity to enquiry using repeated CTAs and a conversion-focused contact section\./gi, contactDesc],
  ])

  // Replace repeated h2/h3/p text positions with plan content when common templates are detected.
  if (/bs-ready-content|section-head|offer-card|check-list|showcase-card/.test(html)) {
    html = html.replace(/(<div[^>]*class=["'][^"']*section-head[^"']*["'][^>]*>\s*<h2[^>]*>)[\s\S]*?(<\/h2>)/i, `$1${serviceTitle}$2`)
    html = html.replace(/(<section[^>]*id=["']process["'][\s\S]*?<h2[^>]*>)[\s\S]*?(<\/h2>)/i, `$1${whyTitle}$2`)
    html = html.replace(/(<section[^>]*id=["']faq["'][\s\S]*?<h2[^>]*>)[\s\S]*?(<\/h2>)/i, `$1Answers that help customers enquire.$2`)
  }

  // Replace gallery alt text so broken image alt text never exposes the template id.
  html = html
    .replace(/\salt=["'][^"']*\bgallery["']/gi, ` alt="${business} gallery"`)
    .replace(/>\s*[\w-]+\s+gallery\s*</gi, `>${business} gallery<`)

  // Contact buttons should use the planned CTA text where possible.
  html = replaceTextOutsideTags(html, [
    [/Request Callback/gi, plan.hero.cta_primary || 'Request Callback'],
    [/Start Project/gi, plan.hero.cta_primary || 'Start Project'],
    [/Explore/gi, plan.hero.cta_secondary || 'Explore'],
    [/Contact Now/gi, plan.hero.cta_primary || 'Contact Now'],
  ])

  return html
}


function ensureEmailFieldInForms(html: string): string {
  const emailInput = '<input type="email" name="email" aria-label="Email" placeholder="Email" autocomplete="email" data-bs-injected-email="true" />'
  return html.replace(/<form\b([^>]*)>([\s\S]*?)<\/form>/gi, (match, attrs, inner) => {
    if (/type=["']email["']|name=["']email["']|aria-label=["']email["']|placeholder=["']email["']/i.test(inner)) return match
    let nextInner = inner
    if (/<textarea\b/i.test(nextInner)) {
      nextInner = nextInner.replace(/<textarea\b/i, `${emailInput}<textarea`)
    } else if (/<button\b/i.test(nextInner)) {
      nextInner = nextInner.replace(/<button\b/i, `${emailInput}<button`)
    } else if (/<input\b/i.test(nextInner)) {
      nextInner = `${nextInner}${emailInput}`
    } else {
      nextInner = `${emailInput}${nextInner}`
    }
    return `<form${attrs}>${nextInner}</form>`
  })
}

function removeDisabledFormHandlers(html: string): string {
  return ensureEmailFieldInForms(html)
    .replace(/\s+onsubmit=["']return\s+false;?["']/gi, '')
    .replace(/\s+onsubmit=["']event\.preventDefault\(\);?["']/gi, '')
}


const BS_MOBILE_ROOT_HERO_FIX = `
<style id="bs-mobile-root-hero-fix-v7">
/* Final mobile correction: broad hero selectors used to catch body/header/hero-grid on phones. */
@media(max-width:980px){
  body[class*="bs-hero-v"]{display:block!important;position:static!important;padding:0!important;margin:0!important;min-height:100%!important;height:auto!important;overflow-x:hidden!important;}
  body[class*="bs-hero-v"]>nav,body[class*="bs-hero-v"]>.nav,body[class*="bs-hero-v"]>header{position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:10000!important;transform:none!important;}
  body[class*="bs-hero-v"] .hero,body[class*="bs-layout-"] .hero,body[class*="bs-seed-"] .hero,main.hero,section.hero{position:relative!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;justify-content:center!important;min-height:0!important;height:auto!important;}
  body[class*="bs-hero-v"] .hero-grid,body[class*="bs-layout-"] .hero-grid,body[class*="bs-seed-"] .hero-grid,body[class*="bs-hero-v"] .wrap.hero-grid,body[class*="bs-layout-"] .wrap.hero-grid,body[class*="bs-seed-"] .wrap.hero-grid,[class*="hero-grid"]{min-height:0!important;height:auto!important;padding-top:0!important;padding-bottom:0!important;display:grid!important;grid-template-columns:1fr!important;gap:24px!important;align-items:start!important;justify-content:initial!important;overflow:visible!important;width:min(100% - 28px,1180px)!important;margin-inline:auto!important;}
  .hero-bg,[class*="hero-bg"],.bs-hero-image-bg,[class*="hero-image"],[class*="hero-visual"],[class*="hero-media"]{padding:0!important;margin:0!important;min-height:0!important;}
  body[class*="bs-hero-v"] .hero-bg,body[class*="bs-layout-"] .hero-bg,body[class*="bs-seed-"] .hero-bg,body[class*="bs-hero-v"] .bs-hero-image-bg,body[class*="bs-layout-"] .bs-hero-image-bg,body[class*="bs-seed-"] .bs-hero-image-bg,.hero>.hero-bg,.hero>.bs-hero-image-bg,main.hero>.bs-hero-image-bg{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;z-index:0!important;pointer-events:none!important;overflow:hidden!important;}
  body[class*="bs-hero-v"] .hero-bg img,body[class*="bs-layout-"] .hero-bg img,body[class*="bs-seed-"] .hero-bg img,body[class*="bs-hero-v"] .bs-hero-image-bg img,body[class*="bs-layout-"] .bs-hero-image-bg img,body[class*="bs-seed-"] .bs-hero-image-bg img,.hero>.hero-bg img,.hero>.bs-hero-image-bg img,main.hero>.bs-hero-image-bg img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;display:block!important;}
  body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .hero-bg.hero-bg,body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .bs-hero-image-bg.bs-hero-image-bg{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;padding:0!important;margin:0!important;z-index:0!important;overflow:hidden!important;}
  body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .hero-bg.hero-bg img,body[class*="bs-hero-v"][class*="bs-layout-"][class*="bs-seed-"] .hero.hero .bs-hero-image-bg.bs-hero-image-bg img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:cover!important;object-position:center center!important;display:block!important;}
  .hero>div:not(.hero-bg):not(.bs-hero-image-bg),main.hero>div:not(.hero-bg):not(.bs-hero-image-bg),section.hero>div:not(.hero-bg):not(.bs-hero-image-bg),.hero>.wrap,main.hero>.wrap,section.hero>.wrap{position:relative!important;z-index:2!important;}
  .hero-actions,[class*="hero-actions"],.actions{min-height:0!important;padding-top:0!important;padding-bottom:0!important;display:flex!important;flex-wrap:wrap!important;gap:12px!important;}
  body[class*="bs-hero-v"] .showcase,body[class*="bs-layout-"] .showcase,body[class*="bs-seed-"] .showcase,.hero-card,[class*="hero-card"]{width:100%!important;max-width:100%!important;padding:0!important;display:block!important;overflow:hidden!important;}
}
@media(max-width:560px){
  .hero,.hero-section,main.hero,section.hero{padding-top:clamp(86px,20vw,112px)!important;padding-bottom:clamp(38px,10vw,64px)!important;min-height:0!important;height:auto!important;}
  body[class*="bs-hero-v"] .showcase{min-height:260px!important;}
  .hero-card,[class*="hero-card"]{min-height:220px!important;max-height:320px!important;}
  .hero-card>img,[class*="hero-card"]>img{min-height:220px!important;max-height:320px!important;}
}
</style>
`

const MOBILE_NAV_SCRIPT = `
<script id="bs-mobile-nav-script">
(function(){
  try{
    function ready(fn){ if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',fn); else fn(); }
    ready(function(){
      (document.querySelectorAll('nav').length ? document.querySelectorAll('nav') : document.querySelectorAll('header')).forEach(function(nav, idx){
        if(nav.querySelector('.bs-mobile-menu-toggle')) return;
        // Skip if template already has its own hamburger/toggle button
        var existingToggle = Array.prototype.slice.call(nav.querySelectorAll('button,div[role="button"]')).filter(function(el){
          var cls = (el.className||'').toLowerCase();
          var hasHamburgerClass = /toggle|burger|hamburger|menu-btn|mob|drawer|open/.test(cls);
          var hasOnlySpans = el.children.length >= 2 && Array.prototype.every.call(el.children, function(c){ return c.tagName === 'SPAN'; });
          return hasHamburgerClass || hasOnlySpans;
        });
        if(existingToggle.length > 0) {
          nav.classList.add('bs-mobile-nav-ready');
          Array.prototype.slice.call(nav.querySelectorAll('a,button')).forEach(function(el){
            if(existingToggle.indexOf(el) !== -1) return;
            var txt=(el.textContent||'').trim().toLowerCase();
            var cls=((el.className||'')+'').toLowerCase();
            var looksLikeBrand=/brand|logo|company/.test(cls) && txt.length < 34;
            var looksLikeNavAction=/schedule|consult|collection|service|about|contact|shop|book|pricing|generate|get started|start|portfolio/.test(txt) || /links|actions|cta|btn|menu/.test(cls);
            if(!looksLikeBrand && looksLikeNavAction) el.classList.add('bs-mobile-nav-original');
          });
          return;
        }
        var links = Array.prototype.slice.call(nav.querySelectorAll('a,button')).filter(function(el, i){
          var txt=(el.textContent||'').trim();
          if(!txt) return false;
          if(i===0 && txt.length < 34) return false;
          if(el.classList && (el.classList.contains('bs-mobile-menu-toggle') || el.classList.contains('bs-mobile-drawer-link'))) return false;
          return true;
        });
        if(links.length < 2) return;
        links.forEach(function(el){
          var parent = el.parentElement;
          if(parent && parent !== nav && parent.children.length <= Math.max(links.length + 1, 3)) parent.classList.add('bs-mobile-nav-original');
          else el.classList.add('bs-mobile-nav-original');
        });
        var btn=document.createElement('button');
        btn.type='button';
        btn.className='bs-mobile-menu-toggle';
        btn.setAttribute('aria-label','Open menu');
        btn.setAttribute('aria-expanded','false');
        btn.innerHTML='<span></span><span></span><span></span>';
        // Drawer appended to body so nav overflow:hidden never clips it
        var drawer=document.createElement('div');
        drawer.className='bs-mobile-drawer';
        links.forEach(function(el){
          var clone=el.cloneNode(true);
          clone.classList.add('bs-mobile-drawer-link');
          clone.removeAttribute('style');
          clone.addEventListener('click',function(){
            drawer.classList.remove('open');
            btn.setAttribute('aria-expanded','false');
          });
          drawer.appendChild(clone);
        });
        // Position drawer below the nav bar
        function positionDrawer(){
          var navRect=nav.getBoundingClientRect();
          var top=navRect.bottom+6;
          drawer.style.top=top+'px';
        }
        btn.addEventListener('click',function(){
          positionDrawer();
          var isOpen=drawer.classList.toggle('open');
          btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        });
        // Close drawer when clicking outside
        document.addEventListener('click',function(e){
          if(!nav.contains(e.target) && !drawer.contains(e.target)){
            drawer.classList.remove('open');
            btn.setAttribute('aria-expanded','false');
          }
        });
        nav.appendChild(btn);
        document.body.appendChild(drawer);
        nav.classList.add('bs-mobile-nav-ready');
      });
    });
  }catch(e){}
})();
</script>`

const IMAGE_FALLBACK_SCRIPT = `
<script id="bs-image-fallback-script">
(function(){try{function fb(i){if(!i||i.dataset.bsFallbackApplied==='true')return;i.dataset.bsFallbackApplied='true';i.onerror=null;i.alt=i.alt||'Image unavailable';i.style.background='linear-gradient(135deg,#16110B,#3A2A16)';i.style.minHeight=i.style.minHeight||'180px';i.style.objectFit=i.style.objectFit||'cover';var label=(i.alt||'Image unavailable').replace(/[<>&"]/g,' ').slice(0,80);var svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#16110B"/><stop offset="1" stop-color="#6A4A25"/></linearGradient></defs><rect width="1200" height="800" fill="url(#g)"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#F5E8D0" font-family="Georgia,serif" font-size="44" letter-spacing="4">'+label+'</text></svg>';i.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);}function f(){document.querySelectorAll('img').forEach(function(i){i.loading='eager';i.decoding='async';if(!i.getAttribute('referrerpolicy'))i.setAttribute('referrerpolicy','no-referrer');i.onerror=function(){fb(this)};if(i.complete&&i.naturalWidth===0)fb(i);});}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',f);else f();window.addEventListener('load',f);}catch(e){}})();
</script>`


// ── Core renderer ─────────────────────────────────────────────────────────────

export async function renderTemplateHtml(plan: WebsiteTemplatePlan): Promise<string> {
  const { template_id, business_name, hero, seo, colors, sections } = plan

  // Read template HTML
  let html = await readTemplateHtml(template_id)

  // Fallback to fallback template
  if (!html) {
    console.warn(`[renderTemplateHtml] Template file missing: ${template_id}, trying fallback`)
    const fallbackId = getFallbackTemplate().id
    html = await readTemplateHtml(fallbackId)
  }

  // If even fallback is missing, build minimal HTML
  if (!html) {
    console.warn('[renderTemplateHtml] Fallback template also missing, using minimal HTML')
    return buildMinimalHtml(plan)
  }

  // ── 1. Replace <title> ────────────────────────────────────────────────────
  if (/<title>[^<]*<\/title>/i.test(html)) {
    html = html.replace(/<title>[^<]*<\/title>/i, `<title>${escapeHtml(seo.title)}</title>`)
  } else {
    html = html.replace(/<\/head>/i, `<title>${escapeHtml(seo.title)}</title>\n</head>`)
  }

  // ── 2. Replace / add meta description ────────────────────────────────────
  const metaDescPattern = /<meta\s+name=["']description["'][^>]*>/i
  const metaDescTag = `<meta name="description" content="${escapeHtml(seo.description)}">`
  if (metaDescPattern.test(html)) {
    html = html.replace(metaDescPattern, metaDescTag)
  } else {
    html = html.replace(/<\/head>/i, `${metaDescTag}\n</head>`)
  }

  // ── 3. Inject CSS variables ───────────────────────────────────────────────
  const cssVars = `\n<style id="bs-brand-vars">
/* Brand Syndicate — injected brand variables */
:root {
  --accent: ${colors.primary};
  --gold: ${colors.primary};
  --primary: ${colors.primary};
  --brand-primary: ${colors.primary};
  --brand-bg: ${colors.background};
  --brand-secondary: ${colors.secondary};
}
</style>`
  html = html.replace(/<\/head>/i, `${cssVars}\n</head>`)

  // ── 4. Inject visibility fix (same as full-code mode) ────────────────────
  const visibilityOverride = `\n<style id="bs-visibility-fix">
[class*="reveal"],[class*="hidden"],[class*="fade"],[class*="slide"],[data-reveal],[data-animate] {
  opacity: 1 !important; transform: none !important; visibility: visible !important;
}
</style>`
  html = html.replace(/<\/head>/i, `${visibilityOverride}\n</head>`)

  // ── 4b. Inject mobile/image/content safety layer for all new generated websites ─
  const mobileReadyOverride = `
<style id="bs-mobile-ready-fix">
/* Brand Syndicate mobile safety layer: keeps generated sites usable on phones */
*,*::before,*::after{box-sizing:border-box;}
html,body{width:100%;max-width:100%;overflow-x:hidden;-webkit-text-size-adjust:100%;}
body{min-width:0;}
/* Only constrain non-positioned images — never touch hero-bg / cover images */
img:not(:not(body)[class*="hero"]):not([class*="bg"]):not([class*="cover"]):not([class*="fill"]),
picture,video,canvas,svg,iframe{max-width:100%;}
img{display:block;object-position:center center;}
section,header,main,footer,nav,.container,.wrap,.wrapper,[class*="container"],[class*="wrap"]{max-width:100%;min-width:0;}
a,button{max-width:100%;}
.bs-real-site-section,.bs-real-contact{background:var(--brand-bg,#0b0b0b);color:#fff;padding:clamp(56px,8vw,96px) clamp(18px,5vw,56px);}
.bs-real-site-section-alt{background:color-mix(in srgb,var(--brand-bg,#0b0b0b) 88%,#ffffff 12%);}
.bs-real-wrap{width:min(1120px,100%);margin:0 auto;}
.bs-real-label{margin:0 0 14px;color:var(--brand-primary,#C9A84C);font-size:11px;letter-spacing:.22em;text-transform:uppercase;font-weight:700;}
.bs-real-site-section h2,.bs-real-contact h2{margin:0 0 18px;font-size:clamp(30px,5vw,58px);line-height:1.05;letter-spacing:-.04em;color:#fff;}
.bs-real-intro,.bs-real-contact p{max-width:760px;color:rgba(255,255,255,.72);font-size:clamp(15px,2vw,18px);line-height:1.75;margin:0 0 32px;}
.bs-real-grid,.bs-real-proof-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;}
.bs-real-proof-grid{grid-template-columns:repeat(2,minmax(0,1fr));}
.bs-real-card{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055);border-radius:20px;padding:24px;min-width:0;}
.bs-real-card span{display:block;color:var(--brand-primary,#C9A84C);font-size:12px;letter-spacing:.18em;margin-bottom:18px;}
.bs-real-card h3{margin:0 0 10px;color:#fff;font-size:20px;line-height:1.25;}
.bs-real-card p{margin:0;color:rgba(255,255,255,.68);font-size:14px;line-height:1.65;}
.bs-real-contact-box{border:1px solid rgba(255,255,255,.14);border-radius:28px;padding:clamp(28px,5vw,56px);background:rgba(255,255,255,.06);}
.bs-real-cta{display:inline-flex;align-items:center;justify-content:center;margin-top:8px;padding:14px 24px;border-radius:999px;background:var(--brand-primary,#C9A84C);color:#070707;text-decoration:none;font-weight:800;letter-spacing:.04em;}

/* ── Mobile hamburger drawer (injected by MOBILE_NAV_SCRIPT) ── */
.bs-mobile-menu-toggle{display:none;align-items:center;justify-content:center;flex-direction:column;gap:4px;width:42px;height:42px;border:1px solid rgba(255,255,255,.18);border-radius:999px;background:rgba(255,255,255,.08);color:inherit;cursor:pointer;z-index:10001;flex-shrink:0;}
.bs-mobile-menu-toggle span{display:block;width:18px;height:2px;background:currentColor;border-radius:2px;transition:transform .2s,opacity .2s;}
/* Drawer: fixed so it's never clipped by nav overflow */
.bs-mobile-drawer{display:none;position:fixed;left:12px;right:12px;top:72px;z-index:10000;padding:14px;border:1px solid rgba(255,255,255,.16);border-radius:18px;background:rgba(10,10,10,.97);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);box-shadow:0 24px 60px rgba(0,0,0,.5);}
.bs-mobile-drawer.open{display:grid;gap:8px;}
.bs-mobile-drawer-link{display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;min-height:44px!important;padding:11px 14px!important;border-radius:12px!important;text-decoration:none!important;color:#fff!important;background:rgba(255,255,255,.07)!important;border:1px solid rgba(255,255,255,.08)!important;font-size:13px!important;letter-spacing:.08em!important;text-transform:uppercase!important;}
@media(max-width:768px){
  .bs-mobile-nav-ready{position:relative!important;}
  .bs-mobile-nav-ready .bs-mobile-menu-toggle{display:flex!important;margin-left:auto!important;flex:0 0 auto!important;}
  .bs-mobile-nav-ready .bs-mobile-nav-original{display:none!important;}
  nav [class*="actions"],header [class*="actions"],nav [class*="desktop"],header [class*="desktop"],nav ul,header nav ul{display:none!important;}
  nav button[aria-label*="menu" i],header button[aria-label*="menu" i],nav [class*="hamb" i],header [class*="hamb" i],nav [class*="toggle" i],header [class*="toggle" i]{display:flex!important;flex:0 0 auto!important;}
}

@media(max-width:768px){
  body{font-size:16px;}
  /* Nav: flex layout, never clip children (drawer is fixed, not absolute) */
  nav,header{overflow:visible!important;position:relative;}
  nav,header nav,[class*="navbar"],[class*="nav-inner"],[class*="navInner"],[class*="nav"]{
    display:flex!important;flex-wrap:nowrap!important;align-items:center!important;
    gap:8px!important;overflow:visible!important;height:auto!important;min-height:0!important;
    padding-left:16px!important;padding-right:16px!important;
  }
  /* Hide original nav links only when the Brand Syndicate mobile drawer is active.
     This prevents restaurant menus/service menus from disappearing on phones. */
  .bs-mobile-nav-ready [class*="links"],
  .bs-mobile-nav-ready [class*="nav-links"],
  .bs-mobile-nav-ready [class*="navLinks"],
  .bs-mobile-nav-ready [class*="menu"]:not(.bs-mobile-menu-toggle){
    display:none!important;
  }
  nav a,header a,nav button,header button{flex-shrink:1;}
  nav > a[class*="cta"],nav > a[class*="btn"],nav > button[class*="cta"],nav > button[class*="btn"],nav [class*="nav-cta"],header [class*="nav-cta"]{display:none!important;}
  nav [class*="actions"],header [class*="actions"],nav [class*="desktop"],header [class*="desktop"],nav ul,header nav ul{display:none!important;}

  /* ── Hero section: proper full-bleed on mobile ── */
  :not(body)[class*="hero"], .hero {
	    min-height: 85vw !important; height: auto !important;
	    padding-top: clamp(80px, 20vw, 120px) !important;
	    padding-bottom: clamp(60px, 15vw, 100px) !important;
	  }
  section:first-of-type:not(:not(body)[class*="hero"]):not(.hero){
    min-height:auto!important;height:auto!important;
    padding-top:clamp(56px,14vw,96px)!important;
    padding-bottom:clamp(56px,14vw,96px)!important;
  }

  /* ── Hero background images: MUST stay cover, never contain ── */
	  .hero-bg, .hero-bg img,
	  [class*="hero-bg"], [class*="hero-bg"] img,
	  [class*="hero-image"], [class*="hero-image"] img,
	  [class*="heroBg"], [class*="heroBg"] img,
	  [class*="hero-visual"], [class*="hero-visual"] img,
	  [class*="hero-media"], [class*="hero-media"] img {
	    position: absolute !important; inset: 0 !important;
	    width: 100% !important; height: 100% !important;
	    max-width: none !important; max-height: none !important;
	    object-fit: cover !important; object-position: center center !important;
	    z-index: -1;
	  }
	  /* If hero-bg is just a div container, ensure it doesn't collapse */
	  .hero-bg, [class*="hero-bg"], [class*="hero-image"], [class*="heroBg"] {
	    display: block !important;
	  }
  /* Ensure the hero section itself is positioned so absolute children anchor correctly */
	  :not(body)[class*="hero"], .hero {
	    position: relative !important;
	    overflow: hidden !important;
	    min-height: clamp(400px, 90vw, 700px) !important;
	    display: flex !important;
	    flex-direction: column !important;
	    justify-content: center !important;
	  }
	  /* Content inside hero must be above background */
	  :not(body)[class*="hero"] > div, .hero > div, :not(body)[class*="hero"] > .wrap, .hero > .wrap {
	    position: relative !important;
	    z-index: 2 !important;
	  }

  /* ── Regular content images (not bg/cover) ── */
  img:not(:not(body)[class*="hero"]):not([class*="bg"]):not([class*="cover"]):not([class*="fill"]):not([style*="position:absolute"]):not([style*="position: absolute"]){
    max-width:100%!important;height:auto!important;
  }

  h1{font-size:clamp(2rem,10vw,3.4rem)!important;line-height:1.05!important;max-width:100%!important;overflow-wrap:anywhere!important;}
  h2{font-size:clamp(1.55rem,7vw,2.4rem)!important;line-height:1.15!important;}
  p{max-width:100%!important;overflow-wrap:anywhere!important;}
  .grid,[class*="grid"],[style*="grid-template-columns"],.features,.services,.pricing,.testimonials,.gallery,.metric-grid,.proof-wall,.contact,.split,.hero-grid{grid-template-columns:1fr!important;}
  [style*="display: flex"],[style*="display:flex"],.row,[class*="row"]{flex-wrap:wrap!important;}
  .bs-real-grid,.bs-real-proof-grid{grid-template-columns:1fr!important;}
  .bs-real-card{padding:20px;}
  .bs-real-contact-box{border-radius:20px;}
}
@media(max-width:430px){
  nav,header nav,[class*="navbar"],[class*="nav-inner"],[class*="nav"]{justify-content:flex-start!important;}
  a[class*="btn"],button[class*="btn"],a[class*="button"],button[class*="button"],a[class*="cta"],button[class*="cta"]{width:auto!important;min-width:min(160px,100%)!important;}
  .bs-real-site-section,.bs-real-contact{padding-left:16px!important;padding-right:16px!important;}
}

/* Final anti-overlap safety pass: brand/logo text must never stack vertically or clip */
nav,header,header nav,[class*="navbar"],[class*="nav-inner"],[class*="navInner"]{
  min-width:0!important;
}
nav > *,header > *,header nav > *{min-width:0!important;}
nav [class*="logo"],nav [class*="brand"],nav [class*="company"],
header [class*="logo"],header [class*="brand"],header [class*="company"],
nav a:first-child,header a:first-child{
  white-space:nowrap!important;
  word-break:keep-all!important;
  overflow-wrap:normal!important;
  writing-mode:horizontal-tb!important;
  text-orientation:mixed!important;
  line-height:1.12!important;
  display:inline-flex!important;
  align-items:center!important;
  gap:.35rem!important;
  max-width:calc(100% - 92px)!important;
  letter-spacing:.04em!important;
  overflow:hidden!important;
  text-overflow:ellipsis!important;
}
nav [class*="logo"] *,nav [class*="brand"] *,header [class*="logo"] *,header [class*="brand"] *{
  white-space:nowrap!important;
  word-break:keep-all!important;
  overflow-wrap:normal!important;
}
section,main,footer,[class*="section"],[class*="container"],[class*="wrap"]{
  min-width:0!important;
}
form,input,textarea,select,button{max-width:100%!important;}
input,textarea,select{min-height:44px!important;}
@media(max-width:768px){
  nav,header nav,[class*="navbar"],[class*="nav-inner"],[class*="navInner"]{
    width:100%!important;
    justify-content:space-between!important;
  }
  nav [class*="logo"],nav [class*="brand"],header [class*="logo"],header [class*="brand"],nav a:first-child,header a:first-child{
    flex:1 1 auto!important;
    max-width:calc(100% - 96px)!important;
    font-size:clamp(14px,4.8vw,22px)!important;
  }
  nav > a[class*="cta"],nav > a[class*="btn"],nav > button[class*="cta"],nav > button[class*="btn"],nav [class*="nav-cta"],header [class*="nav-cta"]{display:none!important;}

  .bs-mobile-nav-ready > a[class*="cta"],
  .bs-mobile-nav-ready > a[class*="btn"],
  .bs-mobile-nav-ready > button[class*="cta"],
  .bs-mobile-nav-ready > button[class*="btn"]{
    display:none!important;
  }
  [class*="hero-content"],[class*="hero-left"],[class*="hero-inner"],[class*="hero-copy"],[class*="hero-text"],
  [class*="showcase"],[class*="card"],[class*="content"],[class*="copy"]{
    min-width:0!important;
    max-width:100%!important;
  }
  section,.section,[class*="section"]{
    padding-left:clamp(16px,5vw,28px)!important;
    padding-right:clamp(16px,5vw,28px)!important;
  }
  [class*="metric"],[class*="stat"],[class*="service"],[class*="feature"],[class*="price"],[class*="testimonial"]{
    min-width:0!important;
    overflow-wrap:break-word!important;
  }
  [style*="min-width"]{min-width:0!important;}
  table{display:block!important;width:100%!important;overflow-x:auto!important;}
  h1,h2,h3,p,li,a,button,span{word-break:normal!important;overflow-wrap:break-word!important;}
}
</style>`
  html = html.replace(/<\/head>/i, `${mobileReadyOverride}
${BS_MOBILE_ROOT_HERO_FIX}
</head>`)


  // ── 5. Replace brand name occurrences (safe: only common template patterns) ─
  // Templates typically have the brand name in nav, footer, and page title.
  // We avoid global replace to not break CSS class names that might include "noir", "arka", etc.
  // Strategy: only replace standalone words in specific tag positions.

  // Nav brand name (first element with class containing "brand", "logo", "company", or first <a> in nav)
  html = replaceFirst(
    html,
    /(<(?:nav|header)[^>]*>[\s\S]*?<(?:a|div|span)[^>]*(?:class="[^"]*(?:brand|logo|company)[^"]*")[^>]*>)[^<]{2,60}(<\/(?:a|div|span)>)/i,
    `$1${safeText(business_name)}$2`
  )

  // Logo anchors often contain nested <span> elements (for example "B2B<span>.</span>").
  // Replace the full logo text/content without touching the surrounding nav layout.
  html = html.replace(
    /(<a[^>]*class=["'][^"']*(?:logo|brand|company)[^"']*["'][^>]*>)[\s\S]*?(<\/a>)/i,
    `$1${safeText(business_name)}$2`
  )

  // ── 6. Replace first H1 with hero headline ────────────────────────────────
  html = replaceFirst(
    html,
    /(<h1[^>]*>)[\s\S]*?(<\/h1>)/i,
    `$1${safeText(hero.headline)}$2`
  )

  // ── 7. Replace first paragraph near hero area with subheadline ───────────
  // Look for <p> right after first h1 block (within ~500 chars)
  const h1Match = html.match(/<h1[^>]*>[\s\S]*?<\/h1>/i)
  if (h1Match) {
    const h1End = html.indexOf(h1Match[0]) + h1Match[0].length
    const near = html.slice(h1End, h1End + 600)
    const pMatch = near.match(/<p[^>]*>([^<]{10,})<\/p>/i)
    if (pMatch) {
      const fullPTag = pMatch[0]
      const firstOccurrence = html.indexOf(fullPTag, h1End)
      if (firstOccurrence !== -1) {
        const openTag  = fullPTag.match(/^(<p[^>]*>)/i)?.[1] ?? '<p>'
        const closeTag = '</p>'
        const replacement = `${openTag}${safeText(hero.subheadline)}${closeTag}`
        html = html.slice(0, firstOccurrence) + replacement + html.slice(firstOccurrence + fullPTag.length)
      }
    }
  }

  // ── 8. Replace first CTA button/link text ────────────────────────────────
  // Target first <a> or <button> with class containing "cta", "btn", "button" in hero area
  const heroEnd = html.indexOf('</section>') > 0 ? html.indexOf('</section>') : 1500
  const heroHtml = html.slice(0, heroEnd + 20)
  const ctaPattern = /(<(?:a|button)[^>]*(?:class="[^"]*(?:cta|btn|button)[^"]*")[^>]*>)[^<]{2,40}(<\/(?:a|button)>)/i
  if (ctaPattern.test(heroHtml)) {
    const replaced = heroHtml.replace(ctaPattern, `$1${safeText(hero.cta_primary)}$2`)
    html = replaced + html.slice(heroEnd + 20)
  }



  // ── 9. Replace obvious placeholder/template copy and ensure thin templates become real websites ─
  const servicesSectionForCopy = sections.find(
    (s): s is Extract<PlanSection, { type: 'services' }> => s.type === 'services'
  )
  const copyItems = servicesSectionForCopy?.items ?? []
  for (let i = 0; i < Math.min(copyItems.length, 3); i++) {
    const label = ['Service One', 'Service Two', 'Service Three'][i]
    html = html.replace(new RegExp(label, 'g'), safeText(copyItems[i].title))
  }
  html = html
    .replace(/The structure is intentionally predictable: hero, proof, services, process, testimonials, FAQ and contact\. Your backend can safely replace text while keeping the design intact\./gi, safeText(hero.subheadline))
    .replace(/This template is intentionally different from your current 192 files: new ID, new label, new section order, industry menu, copy pattern and layout treatment\./gi, safeText(hero.subheadline))
    .replace(/This website is intentionally different from your current \d+ files:?\s*new ID, new label, new section order, industry menu, copy pattern and layout treatment\.?/gi, safeText(hero.subheadline))
    .replace(/Every section is structured so your AI generator can replace copy, colours and business details without breaking the design\.?/gi, `Every section explains ${safeText(business_name)} clearly and guides visitors toward enquiry.`)
    .replace(/Yes\. The text, colours, images, service cards and contact details are designed to be replaced by the Brand Syndicate AI renderer\.?/gi, `${safeText(business_name)} can tailor the offering based on customer needs, quantity, timeline and location.`)
    .replace(/Lorem ipsum[^<]*/gi, safeText(hero.subheadline))

  html = personaliseTemplateSections(html, plan)
  html = removeDisabledFormHandlers(html)

  if (hasThinTemplateContent(html)) {
    html = injectBeforeFooterOrBody(html, buildRealContentSections(plan))
  }

  if (/<\/body>/i.test(html)) {
    html = html.replace(/<\/body>/i, `${MOBILE_NAV_SCRIPT}\n${IMAGE_FALLBACK_SCRIPT}\n</body>`)
  }

  html = stripTemplateLanguage(html)

  // ── 10. Add generation comment ─────────────────────────────────────────────
  html = html.replace(
    /<body[^>]*>/i,
    m => `${m}\n<!-- Generated by Brand Syndicate website mode: ${template_id} -->`
  )

  // ── 11. Ensure document completeness and repair common imported-template HTML issues ─
  html = ensureTemplateHtmlComplete(removeDisabledFormHandlers(stripTemplateLanguage(personaliseTemplateSections(html, plan))))
  html = repairCommonTemplateHtmlIssues(html)

  return html
}
