// src/lib/image-engine/industries.ts
// Industry definitions with Pexels/Unsplash keyword sets and archetype/template hints.

export interface IndustryDef {
  id: string
  label: string
  category: string
  recommendedArchetypes: string[]
  pexelsKeywords: string[]
  unsplashKeywords: string[]
  avoidKeywords: string[]
  suggestedTemplates: string[]
  defaultTone: string
  preferredSizes: string[]
  visualNotes: string
}

export const INDUSTRIES: Record<string, IndustryDef> = {
  jewellery: {
    id: 'jewellery', label: 'Jewellery', category: 'Fashion & Luxury',
    recommendedArchetypes: ['premium_luxury', 'legacy_story', 'craftsmanship'],
    pexelsKeywords: ['gold jewellery close up', 'bridal jewelry warm light', 'luxury jewelry table', 'wedding jewelry details', 'gold necklace close up', 'diamond ring close up'],
    unsplashKeywords: ['jewelry gold', 'bridal jewellery', 'luxury accessories gold'],
    avoidKeywords: ['celebrity', 'famous', 'bollywood'],
    suggestedTemplates: ['luxury_editorial', 'legacy_story_poster', 'product_hero'],
    defaultTone: 'premium', preferredSizes: ['instagram_post_4x5', 'whatsapp_portfolio_3x4'],
    visualNotes: 'Prefer close-up product shots with warm light and bokeh. Cream/gold palette.',
  },
  jewellery_wholesaler: {
    id: 'jewellery_wholesaler', label: 'Jewellery Wholesaler', category: 'Fashion & Luxury',
    recommendedArchetypes: ['craftsmanship', 'legacy_story', 'authority_power'],
    pexelsKeywords: ['bulk jewelry collection', 'jewelry workshop craft', 'gold manufacturing', 'gemstones collection', 'wholesale jewelry display'],
    unsplashKeywords: ['jewelry collection', 'gemstones', 'gold workshop'],
    avoidKeywords: ['retail single'],
    suggestedTemplates: ['craftsmanship_detail', 'legacy_story_poster', 'service_grid_premium'],
    defaultTone: 'bold', preferredSizes: ['linkedin_post_1_91x1', 'instagram_post_4x5'],
    visualNotes: 'Show craft, collection scale, material richness.',
  },
  restaurant: {
    id: 'restaurant', label: 'Restaurant', category: 'Food & Beverage',
    recommendedArchetypes: ['legacy_story', 'local_pride', 'celebration'],
    pexelsKeywords: ['restaurant food photography plated dish', 'atmospheric restaurant table candle light', 'chef cooking kitchen', 'gourmet food close up', 'indian restaurant thali'],
    unsplashKeywords: ['restaurant food', 'gourmet dish', 'restaurant interior warm'],
    avoidKeywords: ['fast food', 'junk'],
    suggestedTemplates: ['legacy_story_poster', 'product_hero', 'local_market_story'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Warm atmospheric shots. Food hero or dining scene.',
  },
  cafe: {
    id: 'cafe', label: 'Café', category: 'Food & Beverage',
    recommendedArchetypes: ['local_pride', 'minimal_editorial', 'care_ritual'],
    pexelsKeywords: ['cafe coffee latte art', 'coffee shop interior cozy', 'barista espresso', 'cafe table window light', 'coffee cup close up'],
    unsplashKeywords: ['cafe coffee', 'latte art', 'coffee shop minimal'],
    avoidKeywords: ['fast food chain'],
    suggestedTemplates: ['minimal_proof_card', 'product_hero', 'local_market_story'],
    defaultTone: 'clean', preferredSizes: ['instagram_square_1x1', 'instagram_story_9x16'],
    visualNotes: 'Cozy, minimal, warm-toned photography.',
  },
  bakery: {
    id: 'bakery', label: 'Bakery', category: 'Food & Beverage',
    recommendedArchetypes: ['craftsmanship', 'legacy_story', 'celebration'],
    pexelsKeywords: ['bakery fresh bread oven', 'pastry close up warm', 'croissant bake morning', 'artisan bread loaf', 'bakery display case'],
    unsplashKeywords: ['bakery pastry', 'fresh bread', 'artisan baking'],
    avoidKeywords: ['industrial factory bread'],
    suggestedTemplates: ['craftsmanship_detail', 'product_hero', 'legacy_story_poster'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Rustic warmth, handmade craft, golden bread tones.',
  },
  sweets_shop: {
    id: 'sweets_shop', label: 'Sweets Shop', category: 'Food & Beverage',
    recommendedArchetypes: ['celebration', 'legacy_story', 'local_pride'],
    pexelsKeywords: ['indian sweets mithai close up', 'ladoo barfi dessert', 'festive sweets colourful', 'traditional indian sweet shop', 'gulab jamun syrup'],
    unsplashKeywords: ['indian sweets', 'mithai dessert', 'festival sweets'],
    avoidKeywords: ['western cake', 'cupcake'],
    suggestedTemplates: ['festival_celebration', 'legacy_story_poster', 'product_hero'],
    defaultTone: 'festive', preferredSizes: ['instagram_post_4x5', 'whatsapp_status_9x16'],
    visualNotes: 'Festival colours, warm golden tones, traditional presentation.',
  },
  cloud_kitchen: {
    id: 'cloud_kitchen', label: 'Cloud Kitchen', category: 'Food & Beverage',
    recommendedArchetypes: ['bold_offer', 'transformation', 'founder_ambition'],
    pexelsKeywords: ['food delivery packaging box', 'takeaway food modern', 'food packaging clean', 'delivery box meal', 'food container minimal'],
    unsplashKeywords: ['food delivery', 'takeaway packaging', 'food container modern'],
    avoidKeywords: ['dine in restaurant sit'],
    suggestedTemplates: ['bold_offer_card', 'founder_ambition', 'product_hero'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Modern packaging, digital-first, delivery-centric.',
  },
  tiffin_service: {
    id: 'tiffin_service', label: 'Tiffin Service', category: 'Food & Beverage',
    recommendedArchetypes: ['care_ritual', 'local_pride', 'trust_proof'],
    pexelsKeywords: ['tiffin box home food indian', 'meal prep food container lunch', 'home cooked thali', 'indian lunch box stainless'],
    unsplashKeywords: ['tiffin box', 'home meal', 'indian food lunch'],
    avoidKeywords: ['restaurant fine dining'],
    suggestedTemplates: ['care_wellness', 'local_market_story', 'testimonial_proof'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'whatsapp_portfolio_3x4'],
    visualNotes: 'Home warmth, local trust, everyday reliability.',
  },
  hotel: {
    id: 'hotel', label: 'Hotel', category: 'Travel & Hospitality',
    recommendedArchetypes: ['premium_luxury', 'celebration', 'trust_proof'],
    pexelsKeywords: ['luxury hotel room interior', 'hotel lobby premium', 'hotel pool view', 'hotel suite bedroom grand', 'hotel exterior architecture'],
    unsplashKeywords: ['luxury hotel', 'hotel interior', 'hotel pool resort'],
    avoidKeywords: ['budget hostel'],
    suggestedTemplates: ['luxury_editorial', 'website_hero_campaign', 'product_hero'],
    defaultTone: 'luxury', preferredSizes: ['website_hero_16x9', 'instagram_post_4x5'],
    visualNotes: 'Grand, aspirational, premium experience imagery.',
  },
  resort: {
    id: 'resort', label: 'Resort', category: 'Travel & Hospitality',
    recommendedArchetypes: ['premium_luxury', 'celebration', 'care_ritual'],
    pexelsKeywords: ['resort pool tropical', 'beach resort luxury', 'resort villa infinity pool', 'resort sunset view', 'tropical resort cabana'],
    unsplashKeywords: ['resort tropical', 'beach villa luxury', 'infinity pool resort'],
    avoidKeywords: ['urban city'],
    suggestedTemplates: ['luxury_editorial', 'website_hero_campaign', 'festival_celebration'],
    defaultTone: 'luxury', preferredSizes: ['website_hero_16x9', 'instagram_story_9x16'],
    visualNotes: 'Lush outdoor, water, warm daylight.',
  },
  travel_agency: {
    id: 'travel_agency', label: 'Travel Agency', category: 'Travel & Hospitality',
    recommendedArchetypes: ['celebration', 'transformation', 'community_first'],
    pexelsKeywords: ['travel destination landscape', 'couple travel adventure mountains', 'travel suitcase airport', 'scenic destination landmark', 'group travel tour'],
    unsplashKeywords: ['travel adventure', 'travel destination', 'tourism landscape'],
    avoidKeywords: ['business corporate only'],
    suggestedTemplates: ['festival_celebration', 'website_hero_campaign', 'bold_offer_card'],
    defaultTone: 'festive', preferredSizes: ['instagram_post_4x5', 'website_hero_16x9'],
    visualNotes: 'Adventure, aspiration, destination beauty.',
  },
  event_planner: {
    id: 'event_planner', label: 'Event Planner', category: 'Events & Weddings',
    recommendedArchetypes: ['celebration', 'craftsmanship', 'premium_luxury'],
    pexelsKeywords: ['event decoration elegant', 'wedding hall decoration', 'event stage setup', 'party decor flowers', 'corporate event setup'],
    unsplashKeywords: ['event decor', 'wedding decoration', 'celebration setup'],
    avoidKeywords: [],
    suggestedTemplates: ['festival_celebration', 'luxury_editorial', 'product_hero'],
    defaultTone: 'festive', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Colour, decor detail, celebratory mood.',
  },
  wedding_planner: {
    id: 'wedding_planner', label: 'Wedding Planner', category: 'Events & Weddings',
    recommendedArchetypes: ['premium_luxury', 'celebration', 'craftsmanship'],
    pexelsKeywords: ['indian wedding decor flowers', 'wedding mandap beautiful', 'bride groom wedding portrait', 'wedding table floral arrangement', 'wedding venue grand'],
    unsplashKeywords: ['wedding decor', 'wedding flowers', 'indian wedding'],
    avoidKeywords: [],
    suggestedTemplates: ['luxury_editorial', 'festival_celebration', 'legacy_story_poster'],
    defaultTone: 'luxury', preferredSizes: ['instagram_post_4x5', 'whatsapp_portfolio_3x4'],
    visualNotes: 'Floral luxury, grand mandap, warm bridal tones.',
  },
  photographer: {
    id: 'photographer', label: 'Photographer / Studio', category: 'Creative & Media',
    recommendedArchetypes: ['minimal_editorial', 'craftsmanship', 'premium_luxury'],
    pexelsKeywords: ['photographer camera portrait studio', 'photography camera equipment', 'photo studio setup', 'behind camera shooting', 'photography composition'],
    unsplashKeywords: ['photography camera', 'photo studio', 'photographer at work'],
    avoidKeywords: ['amateur selfie'],
    suggestedTemplates: ['minimal_proof_card', 'luxury_editorial', 'dark_agency_noir'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Artistic, minimal, camera/craft-focused.',
  },
  fashion: {
    id: 'fashion', label: 'Fashion Brand', category: 'Fashion & Luxury',
    recommendedArchetypes: ['premium_luxury', 'minimal_editorial', 'transformation'],
    pexelsKeywords: ['fashion editorial model studio', 'luxury clothing detail', 'fashion shoot minimal background', 'designer outfit lookbook', 'fashion model pose dramatic'],
    unsplashKeywords: ['fashion editorial', 'clothing lookbook', 'fashion model minimal'],
    avoidKeywords: ['casual street random'],
    suggestedTemplates: ['luxury_editorial', 'dark_power_campaign', 'minimal_proof_card'],
    defaultTone: 'luxury', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'High fashion, editorial, model or product-centric.',
  },
  boutique: {
    id: 'boutique', label: 'Boutique / Designer Store', category: 'Fashion & Luxury',
    recommendedArchetypes: ['premium_luxury', 'craftsmanship', 'local_pride'],
    pexelsKeywords: ['boutique store interior elegant', 'fashion boutique display', 'designer clothing store', 'premium retail interior', 'clothing rack boutique'],
    unsplashKeywords: ['boutique store', 'fashion retail', 'clothing display'],
    avoidKeywords: ['discount sale'],
    suggestedTemplates: ['luxury_editorial', 'product_hero', 'local_market_story'],
    defaultTone: 'premium', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Curated, premium store feel. Warm indoor lighting.',
  },
  cosmetics: {
    id: 'cosmetics', label: 'Cosmetics / Makeup', category: 'Beauty & Wellness',
    recommendedArchetypes: ['premium_luxury', 'transformation', 'minimal_editorial'],
    pexelsKeywords: ['cosmetics makeup product flat lay', 'lipstick makeup luxury', 'beauty product minimal background', 'makeup brush collection', 'cosmetics bottle close up'],
    unsplashKeywords: ['cosmetics product', 'makeup luxury', 'beauty flat lay'],
    avoidKeywords: [],
    suggestedTemplates: ['product_hero', 'luxury_editorial', 'transformation_offer'],
    defaultTone: 'premium', preferredSizes: ['instagram_square_1x1', 'instagram_post_4x5'],
    visualNotes: 'Clean product focus, luxury palette, soft editorial light.',
  },
  skincare: {
    id: 'skincare', label: 'Skincare', category: 'Beauty & Wellness',
    recommendedArchetypes: ['care_ritual', 'premium_luxury', 'minimal_editorial'],
    pexelsKeywords: ['skincare product cream bottle', 'skincare routine serum', 'natural skincare ingredients', 'face cream luxury white background', 'skincare product flat lay'],
    unsplashKeywords: ['skincare product', 'face cream natural', 'skincare routine'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'product_hero', 'luxury_editorial'],
    defaultTone: 'clean', preferredSizes: ['instagram_square_1x1', 'instagram_post_4x5'],
    visualNotes: 'Clean whites, soft light, natural ingredients.',
  },
  salon: {
    id: 'salon', label: 'Salon / Hair Studio', category: 'Beauty & Wellness',
    recommendedArchetypes: ['transformation', 'premium_luxury', 'care_ritual'],
    pexelsKeywords: ['hair salon professional', 'hair styling tools scissors', 'luxury salon interior', 'hair colour treatment', 'salon chair mirror'],
    unsplashKeywords: ['hair salon', 'hair styling', 'salon interior'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'product_hero', 'care_wellness'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Before/after energy or luxury salon equipment.',
  },
  spa: {
    id: 'spa', label: 'Spa & Wellness', category: 'Beauty & Wellness',
    recommendedArchetypes: ['care_ritual', 'premium_luxury', 'minimal_editorial'],
    pexelsKeywords: ['spa wellness massage stones', 'spa treatment room candle', 'luxury spa pool interior', 'wellness calm meditation', 'spa bath flower petals'],
    unsplashKeywords: ['spa wellness', 'massage relaxation', 'luxury spa interior'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'luxury_editorial', 'minimal_proof_card'],
    defaultTone: 'premium', preferredSizes: ['instagram_post_4x5', 'whatsapp_portfolio_3x4'],
    visualNotes: 'Serenity, warm candle tones, luxury calm.',
  },
  gym: {
    id: 'gym', label: 'Gym / Fitness Center', category: 'Health & Fitness',
    recommendedArchetypes: ['transformation', 'youth_energy', 'authority_power'],
    pexelsKeywords: ['gym equipment weights barbell', 'fitness workout athlete', 'gym interior modern equipment', 'athlete lifting weights', 'gym training session'],
    unsplashKeywords: ['gym fitness', 'athlete workout', 'gym interior'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'dark_power_campaign', 'bold_offer_card'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'High energy, dark/dramatic, iron and sweat aesthetic.',
  },
  fitness_coach: {
    id: 'fitness_coach', label: 'Fitness Coach / Personal Trainer', category: 'Health & Fitness',
    recommendedArchetypes: ['transformation', 'founder_ambition', 'growth_proof'],
    pexelsKeywords: ['personal trainer coach athlete', 'fitness training outdoors', 'coach workout session', 'athletic coach running', 'fitness motivation training'],
    unsplashKeywords: ['fitness coach', 'personal trainer', 'workout training'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'founder_ambition', 'testimonial_proof'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Athlete in action, strong lighting, motivational energy.',
  },
  yoga_studio: {
    id: 'yoga_studio', label: 'Yoga Studio', category: 'Health & Fitness',
    recommendedArchetypes: ['care_ritual', 'minimal_editorial', 'community_first'],
    pexelsKeywords: ['yoga studio serene', 'yoga pose morning light', 'meditation yoga mat calm', 'yoga class group studio', 'yoga sunrise nature'],
    unsplashKeywords: ['yoga studio', 'yoga pose', 'meditation serene'],
    avoidKeywords: ['gym heavy weights'],
    suggestedTemplates: ['care_wellness', 'minimal_proof_card', 'community_first'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Soft light, minimal, serene calm.',
  },
  doctor: {
    id: 'doctor', label: 'Doctor / Specialist', category: 'Healthcare',
    recommendedArchetypes: ['care_ritual', 'authority_power', 'trust_proof'],
    pexelsKeywords: ['doctor stethoscope professional', 'medical consultation clinic', 'doctor white coat confident', 'healthcare professional portrait', 'medical examination calm'],
    unsplashKeywords: ['doctor medical', 'healthcare professional', 'clinic consultation'],
    avoidKeywords: ['hospital emergency graphic'],
    suggestedTemplates: ['care_wellness', 'professional_trust', 'testimonial_proof'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Clean clinical whites, calm confidence, trust signals.',
  },
  clinic: {
    id: 'clinic', label: 'Clinic / Medical Center', category: 'Healthcare',
    recommendedArchetypes: ['care_ritual', 'trust_proof', 'community_first'],
    pexelsKeywords: ['clinic interior clean modern', 'medical reception area', 'healthcare clinic interior', 'medical office professional', 'clinic consultation room'],
    unsplashKeywords: ['clinic interior', 'medical center', 'healthcare space'],
    avoidKeywords: ['emergency graphic blood'],
    suggestedTemplates: ['care_wellness', 'clean_brand_audit', 'testimonial_proof'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'google_display_banner'],
    visualNotes: 'Bright whites, trust, clean modern healthcare.',
  },
  hospital: {
    id: 'hospital', label: 'Hospital', category: 'Healthcare',
    recommendedArchetypes: ['trust_proof', 'care_ritual', 'authority_power'],
    pexelsKeywords: ['hospital corridor modern clean', 'hospital exterior building', 'medical team professional hospital', 'hospital interior bright', 'healthcare facility modern'],
    unsplashKeywords: ['hospital modern', 'healthcare facility', 'medical building'],
    avoidKeywords: ['emergency graphic', 'blood injury'],
    suggestedTemplates: ['care_wellness', 'professional_trust', 'website_hero_campaign'],
    defaultTone: 'clean', preferredSizes: ['website_hero_16x9', 'linkedin_post_1_91x1'],
    visualNotes: 'Institutional trust, clean modern facility.',
  },
  dentist: {
    id: 'dentist', label: 'Dentist / Dental Clinic', category: 'Healthcare',
    recommendedArchetypes: ['care_ritual', 'trust_proof', 'transformation'],
    pexelsKeywords: ['dental clinic chair modern', 'dentist professional teeth', 'dental equipment clean', 'smile teeth white close up', 'dental office interior'],
    unsplashKeywords: ['dental clinic', 'dentist teeth', 'dental office'],
    avoidKeywords: ['pain graphic'],
    suggestedTemplates: ['care_wellness', 'transformation_offer', 'testimonial_proof'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Smile and clean white aesthetic.',
  },
  pharmacy: {
    id: 'pharmacy', label: 'Pharmacy / Medical Store', category: 'Healthcare',
    recommendedArchetypes: ['trust_proof', 'care_ritual', 'community_first'],
    pexelsKeywords: ['pharmacy medicine shelves', 'pharmacist professional', 'medical store interior', 'medicine capsule pill close up', 'pharmacy clean interior'],
    unsplashKeywords: ['pharmacy medical', 'medicine store', 'pharmacist'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'clean_brand_audit', 'testimonial_proof'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Clean, organized, trustworthy medical aesthetic.',
  },
  physiotherapy: {
    id: 'physiotherapy', label: 'Physiotherapy / Rehabilitation', category: 'Healthcare',
    recommendedArchetypes: ['transformation', 'care_ritual', 'trust_proof'],
    pexelsKeywords: ['physiotherapy treatment session', 'physical therapy exercise', 'rehabilitation clinic', 'physiotherapist patient treatment', 'sports injury recovery'],
    unsplashKeywords: ['physiotherapy', 'physical therapy', 'rehabilitation exercise'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'care_wellness', 'testimonial_proof'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Recovery, movement, professional care.',
  },
  diagnostic_centre: {
    id: 'diagnostic_centre', label: 'Diagnostic Centre / Lab', category: 'Healthcare',
    recommendedArchetypes: ['authority_power', 'trust_proof', 'care_ritual'],
    pexelsKeywords: ['diagnostic lab equipment', 'blood test laboratory', 'medical laboratory modern', 'lab technician microscope', 'diagnostic centre clean'],
    unsplashKeywords: ['laboratory medical', 'diagnostic lab', 'lab equipment'],
    avoidKeywords: ['graphic medical'],
    suggestedTemplates: ['professional_trust', 'care_wellness', 'clean_brand_audit'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Scientific precision, clean sterile whites.',
  },
  dermatologist: {
    id: 'dermatologist', label: 'Dermatologist / Skin Clinic', category: 'Healthcare',
    recommendedArchetypes: ['care_ritual', 'transformation', 'premium_luxury'],
    pexelsKeywords: ['skin clinic aesthetic treatment', 'dermatology clinic clean', 'skin care treatment facial', 'dermatologist professional', 'skincare clinic interior'],
    unsplashKeywords: ['dermatology skin clinic', 'skin treatment aesthetic', 'skincare professional'],
    avoidKeywords: ['graphic skin disease'],
    suggestedTemplates: ['care_wellness', 'transformation_offer', 'luxury_editorial'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Soft clinical-luxury blend, transformation promise.',
  },
  real_estate: {
    id: 'real_estate', label: 'Real Estate / Property', category: 'Real Estate',
    recommendedArchetypes: ['premium_luxury', 'trust_proof', 'authority_power'],
    pexelsKeywords: ['luxury modern house exterior', 'real estate interior living room', 'apartment building exterior', 'property for sale beautiful home', 'luxury villa architecture'],
    unsplashKeywords: ['real estate luxury home', 'property architecture', 'house interior modern'],
    avoidKeywords: ['slum run down'],
    suggestedTemplates: ['luxury_editorial', 'website_hero_campaign', 'website_hero_campaign'],
    defaultTone: 'premium', preferredSizes: ['website_hero_16x9', 'instagram_post_4x5'],
    visualNotes: 'Grand architecture, luxurious interiors.',
  },
  builder: {
    id: 'builder', label: 'Builder / Developer', category: 'Real Estate',
    recommendedArchetypes: ['authority_power', 'craftsmanship', 'trust_proof'],
    pexelsKeywords: ['construction building under construction', 'modern architecture building design', 'developer construction site', 'building blueprint architecture', 'real estate development site'],
    unsplashKeywords: ['construction building', 'real estate developer', 'architecture modern'],
    avoidKeywords: [],
    suggestedTemplates: ['authority_power', 'website_hero_campaign', 'service_grid_premium'],
    defaultTone: 'bold', preferredSizes: ['website_hero_16x9', 'linkedin_post_1_91x1'],
    visualNotes: 'Scale, progress, authority and strength.',
  },
  architecture: {
    id: 'architecture', label: 'Architecture Firm', category: 'Design & Interiors',
    recommendedArchetypes: ['minimal_editorial', 'craftsmanship', 'authority_power'],
    pexelsKeywords: ['modern architecture building exterior', 'architectural design concept', 'building facade geometry', 'interior architecture space', 'contemporary architecture detail'],
    unsplashKeywords: ['architecture modern building', 'architectural design', 'building geometry'],
    avoidKeywords: [],
    suggestedTemplates: ['minimal_proof_card', 'website_hero_campaign', 'website_hero_campaign'],
    defaultTone: 'clean', preferredSizes: ['website_hero_16x9', 'linkedin_post_1_91x1'],
    visualNotes: 'Geometric, bold, architectural lines and space.',
  },
  interior_design: {
    id: 'interior_design', label: 'Interior Designer', category: 'Design & Interiors',
    recommendedArchetypes: ['premium_luxury', 'craftsmanship', 'minimal_editorial'],
    pexelsKeywords: ['interior design luxury living room', 'modern interior design space', 'home decor elegant interior', 'designer bedroom living space', 'interior design concept minimal'],
    unsplashKeywords: ['interior design luxury', 'home decor modern', 'living room elegant'],
    avoidKeywords: [],
    suggestedTemplates: ['luxury_editorial', 'product_hero', 'minimal_proof_card'],
    defaultTone: 'premium', preferredSizes: ['instagram_post_4x5', 'website_hero_16x9'],
    visualNotes: 'Curated beautiful spaces, texture and light.',
  },
  furniture: {
    id: 'furniture', label: 'Furniture / Home Furniture', category: 'Design & Interiors',
    recommendedArchetypes: ['craftsmanship', 'premium_luxury', 'minimal_editorial'],
    pexelsKeywords: ['luxury furniture sofa interior', 'wooden furniture detail craft', 'modern furniture minimal', 'home furniture showroom', 'furniture design close up'],
    unsplashKeywords: ['furniture design', 'luxury sofa', 'wooden furniture detail'],
    avoidKeywords: [],
    suggestedTemplates: ['craftsmanship_detail', 'product_hero', 'luxury_editorial'],
    defaultTone: 'premium', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Craft, material, and space-in-use shots.',
  },
  home_decor: {
    id: 'home_decor', label: 'Home Decor', category: 'Design & Interiors',
    recommendedArchetypes: ['premium_luxury', 'craftsmanship', 'minimal_editorial'],
    pexelsKeywords: ['home decor interior objects', 'decorative items candle vase', 'interior accessories minimal', 'home styling decoration', 'decor product flat lay'],
    unsplashKeywords: ['home decor', 'interior accessories', 'decorative objects minimal'],
    avoidKeywords: [],
    suggestedTemplates: ['product_hero', 'minimal_proof_card', 'luxury_editorial'],
    defaultTone: 'clean', preferredSizes: ['instagram_square_1x1', 'instagram_post_4x5'],
    visualNotes: 'Flat lay or styled scene, warm editorial tones.',
  },
  solar_company: {
    id: 'solar_company', label: 'Solar Energy Company', category: 'Green Energy',
    recommendedArchetypes: ['authority_power', 'transformation', 'growth_proof'],
    pexelsKeywords: ['solar panels rooftop installation', 'solar energy sun panels', 'green energy solar farm', 'solar panel technology', 'renewable energy solar home'],
    unsplashKeywords: ['solar panels', 'renewable energy', 'solar installation'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'bold_offer_card', 'website_hero_campaign'],
    defaultTone: 'bold', preferredSizes: ['website_hero_16x9', 'instagram_post_4x5'],
    visualNotes: 'Future-forward, clean energy, bright daylight.',
  },
  startup: {
    id: 'startup', label: 'Startup', category: 'Technology',
    recommendedArchetypes: ['founder_ambition', 'youth_energy', 'growth_proof'],
    pexelsKeywords: ['startup workspace team modern office', 'entrepreneur founder laptop working', 'startup team meeting', 'modern office coworking startup', 'tech startup workspace'],
    unsplashKeywords: ['startup workspace', 'entrepreneur working', 'startup team'],
    avoidKeywords: [],
    suggestedTemplates: ['founder_ambition', 'dark_agency_noir', 'growth_proof'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Ambitious, dark-workspace or open-office energy.',
  },
  saas: {
    id: 'saas', label: 'SaaS / Software Product', category: 'Technology',
    recommendedArchetypes: ['founder_ambition', 'authority_power', 'growth_proof'],
    pexelsKeywords: ['software developer coding laptop', 'tech dashboard screen UI', 'developer workspace dark', 'SaaS product interface screen', 'tech team modern office'],
    unsplashKeywords: ['software coding', 'SaaS dashboard', 'developer workspace'],
    avoidKeywords: [],
    suggestedTemplates: ['founder_ambition', 'dark_agency_noir', 'startup_pitch_visual'],
    defaultTone: 'bold', preferredSizes: ['linkedin_post_1_91x1', 'instagram_post_4x5'],
    visualNotes: 'Dark workspace, screen glow, precision code.',
  },
  app_development: {
    id: 'app_development', label: 'App Development Agency', category: 'Technology',
    recommendedArchetypes: ['founder_ambition', 'authority_power', 'youth_energy'],
    pexelsKeywords: ['mobile app development team', 'smartphone app screen UI', 'developer coding mobile', 'app design workspace', 'tech development team'],
    unsplashKeywords: ['app development', 'mobile app UI', 'developer team'],
    avoidKeywords: [],
    suggestedTemplates: ['dark_agency_noir', 'startup_pitch_visual', 'service_grid_premium'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Mobile screens, code, dark tech energy.',
  },
  software_company: {
    id: 'software_company', label: 'Software Company', category: 'Technology',
    recommendedArchetypes: ['authority_power', 'professional_trust', 'growth_proof'],
    pexelsKeywords: ['software company office modern', 'tech company team professional', 'software development workspace', 'corporate tech office building', 'developer team meeting'],
    unsplashKeywords: ['software company', 'tech office', 'developer professional'],
    avoidKeywords: [],
    suggestedTemplates: ['dark_power_campaign', 'service_grid_premium', 'website_hero_campaign'],
    defaultTone: 'bold', preferredSizes: ['website_hero_16x9', 'linkedin_post_1_91x1'],
    visualNotes: 'Authority, scale, professional tech.',
  },
  marketing_agency: {
    id: 'marketing_agency', label: 'Marketing Agency', category: 'Services',
    recommendedArchetypes: ['authority_power', 'dark_noir', 'growth_proof'],
    pexelsKeywords: ['marketing team creative agency', 'advertising creative workspace', 'agency team brainstorm', 'marketing strategy meeting', 'creative office modern'],
    unsplashKeywords: ['marketing agency', 'creative team', 'advertising workspace'],
    avoidKeywords: [],
    suggestedTemplates: ['dark_power_campaign', 'dark_agency_noir', 'service_grid_premium'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Authority and creative power. Dark premium aesthetic.',
  },
  branding_agency: {
    id: 'branding_agency', label: 'Branding Agency', category: 'Services',
    recommendedArchetypes: ['dark_noir', 'authority_power', 'minimal_editorial'],
    pexelsKeywords: ['branding design creative studio', 'designer workspace moodboard', 'brand identity creation', 'creative studio minimal desk', 'branding strategy meeting'],
    unsplashKeywords: ['branding creative', 'design studio', 'brand identity workspace'],
    avoidKeywords: [],
    suggestedTemplates: ['dark_agency_noir', 'dark_power_campaign', 'website_hero_campaign'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Creative authority, dark minimal desk shots.',
  },
  consultant: {
    id: 'consultant', label: 'Consultant / Business Advisor', category: 'Professional Services',
    recommendedArchetypes: ['authority_power', 'professional_trust', 'founder_ambition'],
    pexelsKeywords: ['business consultant professional meeting', 'advisor boardroom confident', 'consultant strategy whiteboard', 'professional advisor portrait', 'business meeting corporate'],
    unsplashKeywords: ['business consultant', 'professional advisor', 'corporate meeting'],
    avoidKeywords: [],
    suggestedTemplates: ['dark_power_campaign', 'professional_trust', 'service_grid_premium'],
    defaultTone: 'bold', preferredSizes: ['linkedin_post_1_91x1', 'instagram_post_4x5'],
    visualNotes: 'Authority, confidence, professional gravity.',
  },
  coaching_institute: {
    id: 'coaching_institute', label: 'Coaching Institute / Tuition', category: 'Education',
    recommendedArchetypes: ['authority_power', 'transformation', 'community_first'],
    pexelsKeywords: ['classroom students learning study', 'coaching institute students', 'teacher student board', 'exam preparation study group', 'education learning chalk board'],
    unsplashKeywords: ['coaching students', 'classroom learning', 'education institute'],
    avoidKeywords: [],
    suggestedTemplates: ['transformation_offer', 'bold_offer_card', 'community_first'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'instagram_story_9x16'],
    visualNotes: 'Students, results, aspiration and discipline.',
  },
  school: {
    id: 'school', label: 'School', category: 'Education',
    recommendedArchetypes: ['community_first', 'care_ritual', 'trust_proof'],
    pexelsKeywords: ['school building exterior', 'children classroom learning', 'school playground children happy', 'teacher classroom education', 'school uniform students'],
    unsplashKeywords: ['school education children', 'classroom learning', 'school building'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'community_first', 'website_hero_campaign'],
    defaultTone: 'clean', preferredSizes: ['website_hero_16x9', 'instagram_post_4x5'],
    visualNotes: 'Warm, caring, children-focused, community trust.',
  },
  ca_accountant: {
    id: 'ca_accountant', label: 'CA / Chartered Accountant', category: 'Professional Services',
    recommendedArchetypes: ['authority_power', 'professional_trust', 'trust_proof'],
    pexelsKeywords: ['accountant professional office desk', 'financial advisor meeting', 'tax consultant documents', 'chartered accountant professional', 'business finance calculation'],
    unsplashKeywords: ['accountant professional', 'finance office', 'tax advisor'],
    avoidKeywords: [],
    suggestedTemplates: ['professional_trust', 'clean_typography_offer', 'service_grid_premium'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Professional trust, number authority, clean corporate.',
  },
  local_retail_store: {
    id: 'local_retail_store', label: 'Local Retail Store', category: 'Retail',
    recommendedArchetypes: ['local_pride', 'community_first', 'legacy_story'],
    pexelsKeywords: ['retail shop store interior', 'small business shopfront', 'local market store products', 'retail display shop', 'shopkeeper retail business'],
    unsplashKeywords: ['retail store local', 'small business shop', 'store interior'],
    avoidKeywords: [],
    suggestedTemplates: ['local_market_story', 'heritage_city_campaign', 'bold_offer_card'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'whatsapp_status_9x16'],
    visualNotes: 'Local pride, authentic, neighbourhood warmth.',
  },
  grocery: {
    id: 'grocery', label: 'Grocery / Kirana Store', category: 'Retail',
    recommendedArchetypes: ['local_pride', 'trust_proof', 'bold_offer'],
    pexelsKeywords: ['grocery store fresh vegetables', 'supermarket produce aisle', 'fresh food market vegetables', 'grocery shop shelves', 'local market fresh produce'],
    unsplashKeywords: ['grocery store', 'fresh vegetables market', 'kirana store'],
    avoidKeywords: [],
    suggestedTemplates: ['local_market_story', 'bold_offer_card', 'community_first'],
    defaultTone: 'bold', preferredSizes: ['instagram_post_4x5', 'whatsapp_status_9x16'],
    visualNotes: 'Fresh, local, everyday value.',
  },
  agriculture: {
    id: 'agriculture', label: 'Agriculture / Farm', category: 'Agriculture',
    recommendedArchetypes: ['heritage_india', 'craftsmanship', 'local_pride'],
    pexelsKeywords: ['farm field green crops aerial', 'farmer harvesting crops india', 'agriculture wheat field golden', 'farm produce vegetables fresh', 'tractor farming field'],
    unsplashKeywords: ['agriculture farm', 'farmer crops', 'wheat field golden'],
    avoidKeywords: [],
    suggestedTemplates: ['heritage_city_campaign', 'local_market_story', 'legacy_story_poster'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'website_hero_16x9'],
    visualNotes: 'Golden fields, harvest, earthy authenticity.',
  },
  organic_store: {
    id: 'organic_store', label: 'Organic Store / Health Store', category: 'Retail',
    recommendedArchetypes: ['care_ritual', 'craftsmanship', 'minimal_editorial'],
    pexelsKeywords: ['organic products natural store', 'organic vegetables fruits', 'health store natural products', 'organic food minimal', 'natural ingredients herbs'],
    unsplashKeywords: ['organic natural products', 'healthy store', 'natural ingredients'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'product_hero', 'minimal_proof_card'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Earth tones, natural materials, clean organic.',
  },
  flower_shop: {
    id: 'flower_shop', label: 'Flower Shop / Florist', category: 'Retail',
    recommendedArchetypes: ['celebration', 'craftsmanship', 'premium_luxury'],
    pexelsKeywords: ['flower bouquet close up beautiful', 'florist shop flowers arrangement', 'fresh flowers roses display', 'floral arrangement wedding', 'flower shop interior colorful'],
    unsplashKeywords: ['flower bouquet', 'florist shop', 'floral arrangement'],
    avoidKeywords: [],
    suggestedTemplates: ['festival_celebration', 'product_hero', 'luxury_editorial'],
    defaultTone: 'festive', preferredSizes: ['instagram_square_1x1', 'instagram_post_4x5'],
    visualNotes: 'Vibrant flower colours, natural beauty.',
  },
  pet_care: {
    id: 'pet_care', label: 'Pet Care / Vet Clinic', category: 'Services',
    recommendedArchetypes: ['care_ritual', 'community_first', 'trust_proof'],
    pexelsKeywords: ['pet dog cat cute', 'veterinary clinic animal', 'pet grooming care', 'happy pet dog owner', 'animal care veterinarian'],
    unsplashKeywords: ['pet dog cat cute', 'veterinary care', 'pet grooming'],
    avoidKeywords: [],
    suggestedTemplates: ['care_wellness', 'community_first', 'testimonial_proof'],
    defaultTone: 'warm', preferredSizes: ['instagram_post_4x5', 'instagram_square_1x1'],
    visualNotes: 'Warm and caring, cute animals, trust-building.',
  },
  coworking_space: {
    id: 'coworking_space', label: 'Co-working Space', category: 'Services',
    recommendedArchetypes: ['community_first', 'founder_ambition', 'minimal_editorial'],
    pexelsKeywords: ['coworking space modern office', 'shared workspace open office', 'coworking interior minimal', 'startup coworking community', 'collaborative workspace desk'],
    unsplashKeywords: ['coworking space', 'shared office modern', 'startup workspace community'],
    avoidKeywords: [],
    suggestedTemplates: ['service_grid_premium', 'community_first', 'founder_ambition'],
    defaultTone: 'clean', preferredSizes: ['instagram_post_4x5', 'linkedin_post_1_91x1'],
    visualNotes: 'Open, community, modern collaborative space.',
  },
}

export function getIndustryById(id: string): IndustryDef | null {
  return INDUSTRIES[id] ?? null
}

export function matchIndustryFromText(text: string): string {
  const lower = text.toLowerCase()
  const mappings: [string, string[]][] = [
    ['jewellery', ['jewel', 'jewellery', 'jewelry', 'gold', 'ornament', 'diamond', 'necklace']],
    ['restaurant', ['restaurant', 'dhaba', 'thali', 'food place', 'eatery', 'dining']],
    ['cafe', ['cafe', 'coffee', 'cappuccino', 'barista', 'coffee shop']],
    ['bakery', ['baker', 'bread', 'croissant', 'pastry', 'bake']],
    ['sweets_shop', ['mithai', 'sweet', 'ladoo', 'barfi', 'halwa', 'confection']],
    ['gym', ['gym', 'fitness center', 'weight', 'bodybuilding', 'workout center']],
    ['fitness_coach', ['fitness coach', 'personal trainer', 'trainer']],
    ['yoga_studio', ['yoga', 'meditation', 'yogi']],
    ['doctor', ['doctor', 'physician', 'specialist', 'surgeon', 'dr.']],
    ['clinic', ['clinic', 'medical center', 'health center']],
    ['hospital', ['hospital', 'nursing home', 'multispeciality']],
    ['dentist', ['dent', 'dental', 'teeth', 'orthodontist']],
    ['skincare', ['skincare', 'skin care', 'skin cream', 'face serum']],
    ['dermatologist', ['dermat', 'skin doctor', 'skin clinic', 'acne clinic']],
    ['salon', ['salon', 'hair studio', 'barbershop', 'beauty parlour']],
    ['spa', ['spa', 'massage', 'wellness centre']],
    ['real_estate', ['real estate', 'property', 'housing', 'realty', 'flat', 'apartment for sale']],
    ['builder', ['builder', 'developer', 'construction company', 'contractor']],
    ['interior_design', ['interior design', 'interior decorator', 'interior consultant']],
    ['startup', ['startup', 'start-up', 'early stage', 'seed funded']],
    ['saas', ['saas', 'software as a service', 'cloud product', 'b2b software']],
    ['marketing_agency', ['marketing agency', 'digital marketing', 'performance marketing']],
    ['branding_agency', ['branding agency', 'brand studio', 'brand identity', 'brand syndicate']],
    ['coaching_institute', ['coaching', 'tuition', 'institute', 'academy', 'classes']],
    ['school', ['school', 'primary school', 'convent', 'vidyalaya']],
    ['ca_accountant', ['ca ', 'chartered accountant', 'accountant', 'tax consultant', 'gst consultant']],
    ['local_retail_store', ['shop', 'store', 'retail', 'kirana', 'dukan']],
    ['agriculture', ['farm', 'agriculture', 'kisan', 'crop', 'harvest']],
    ['flower_shop', ['flower', 'florist', 'bouquet', 'floral']],
    ['pet_care', ['pet', 'veterinar', 'vet clinic', 'dog cat care']],
    ['coworking_space', ['coworking', 'co-working', 'shared office', 'workspace']],
    ['organic_store', ['organic', 'natural store', 'health store', 'herbal']],
  ]
  for (const [id, keywords] of mappings) {
    if (keywords.some(k => lower.includes(k))) return id
  }
  return 'local_retail_store'
}
